### ISSUE TITLE
ESP glitches and black blobs

### ISSUE THREAD

**Issue by SpamSPez** [ImpactDevelopment/ImpactIssues#1014]
### What happens?

Weird blobs of black everywhere.... I got no clue how/why. It seems all heads are removed.

![ss](https://i.imgur.com/q8f2BpG.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.12.2
- Using Optifine?  No
- Using LiteLoader? No
- Enabled mods: Auto cheat,light,nametags,tracer,anti van, anti desync,traject,anti bot,chest steal, criticals(packet)
- Operating System: win 10 64bit

</details>

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
