### ISSUE TITLE
.clone

### ISSUE THREAD

**Issue by SpicyBigGithub** [ImpactDevelopment/ImpactIssues#1022]
add a .clone command for cloning items in vanilla multiplayer

**Comment by LeafHacker** [comment]
What?

**Comment by leijurv** [comment]
this is a thing you can do

**Comment by leijurv** [comment]
future has `.dupe`

**Comment by usereewrjrjeejr** [comment]
Is there a free client that does it?

**Comment by 0-x-2-2** [comment]
🦍

**Comment by usereewrjrjeejr** [comment]
Shut fuck

**Comment by LeafHacker** [comment]
is this just 11/11 dupe, chunk info cap dupe, or some other dupe and how does the proposed command behave?

**Comment by SuperOP535** [comment]
is 11/11 the date the dupe was found or does it mean 1.11.1

**Comment by LeafHacker** [comment]
it was published on 11/11 (2016?) it was 1.11 though iirc

**Comment by dominikaaaa** [comment]
I'm closing this as won't fix because it only works on vanilla servers, which literally nobody with more then 10 players uses, so it doesn't work on any servers with a significant player count.
