### ISSUE TITLE
Random tracers on cracked servers.

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactIssues#1032]
### What happens?
Random tracer(s) show up whenever a player joins a server (usually happens on cracked servers for some reason) and point in a direction you can't look at. It's weird and impossible to look in their direction. It's like they're always to the side.
https://youtu.be/LbxJlnYfFhQ

### Exact steps to reproduce?
-Turn tracers on (cracked servers should always work).
-Let a player join that's outside of your render distance.

### Yeesss.
- Impact Version: Was a thing back in 4.4 and still is in 4.6
- Using Optifine? Yes.
- Using LiteLoader? No.
- Enabled mods: Tracers.

**Comment by Nikita11790** [comment]
Could this be anti-cheat?

**Comment by MastaNub** [comment]
Highly doubt.

**Comment by dominikaaaa** [comment]
Sounds like a duplicate of the antibots false positive bug.
