### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by tbjerry07** [ImpactDevelopment/ImpactIssues#1042]
### What is your suggestion? 

Adding a minimap that's similar to the forge mod journey map. It would include features such as waypoints and terrainmap. And also maybe some intergration with other modules such as log position being shown on the map.

### Why is it useful?

- To keep track of the map.
- Have waypoints so users won't have to keep on taking so many screenshots of coords.
- Just an overall quality of life addition.

**Comment by MastaNub** [comment]
Donate and wait for forge.

**Comment by ScanmanTM** [comment]
F😂RGE

**Comment by sapioit** [comment]
More details in #1247

**Comment by MightyKnight** [comment]
Closing because more details in the other issue
