### ISSUE TITLE
Log Position not working correctly

### ISSUE THREAD

**Issue by Ceiridge** [ImpactDevelopment/ImpactIssues#1048]
### What happens?

The logged name and time does appear after a logout, but after some milliseconds it just disappears. It should still log that to a file.

### Exact steps to reproduce?

- Enable Log Position
- Make another player log out
- Look on your screen

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  3.5 for 1.12.2
- Using Optifine?  Yes
- Using LiteLoader?  Yes
- Enabled mods:  A lot, but it shouldn't matter. If you can't reproduce the bug, you can ask for the list again.
- Operating System:  Windows 8.1 x64

</details>

**Comment by MightyKnight** [comment]
Forward resolving your issue as #1621 contains all information.
Also wondering why this is marked as a Suggestion
