### ISSUE TITLE
Add true durability to .peek

### ISSUE THREAD

**Issue by mastatrue** [ImpactDevelopment/ImpactIssues#1071]
I don't know if its a bug or if it's not implemented but the true durability (unbreakables) doens't show when you do .peek, it only show the maximum durability

**Comment by SylveonBottle** [comment]
That's how unbreakable works.
https://minecraft.gamepedia.com/Enchanting#Unbreaking

Items/armour has a chance to loose a durability point based on the level of unbreaking.
This is a random chance and can cause a diamond pickaxe with 1561 durability to have a "true durability" (as you called it) of either 5000 or 7500 - and that's completely random between the two.

![image](https://user-images.githubusercontent.com/17802843/55451872-77846280-559a-11e9-9b1c-15aa05ae36ed.png)

If you know of a way to get the seed for when unbreaking enchant removes a point of durability (if a seed for such a thing even exists), THEN we can talk about predicting the "true durability".

**Comment by mastatrue** [comment]
Ok, either I'm stupid or I have expressed myself wrong, I'm not talking about enchanting, i'm talking about viewing that item in a shulkers with .peek. So I got a pickaxe that is 32k durability if I do.peek and hover over it it should the max durability of 1,5k. If I place the shulkers down and open it, then it shows the true durability

**Comment by LeafHacker** [comment]
@SylveonBottle he's talking about negative damage items that have a durability higher than maxDamage. In 1.12.2 and below it is possible for the server to store negative damage although you can't /give it, the only way to obtain such an item in survival is through buggy spigot plugins that allowed overflowing the damage past maxDamage, past the highest possible short and into the negative range.

In 4.6 1.12 we added an option to correctly view these items in item tooltips, but this report is saying that it doesn't work in .peak

That said, 4.7 won't have 1.12 support so I'm not sure this is going to happen.

**Comment by mastatrue** [comment]
Yes @leafhacker, you are right, that's what I mean, .peek doesn't show the real durability. For a second there I thought I'm to dumb to understand his answer. Thank you for clarifying

**Comment by SylveonBottle** [comment]
My fault, for some reason I thought `.peek` was used to see another user's items based on recording what they've held. 

True enough, this won't be necessary if this isn't possible in 1.13 - although if there's still some servers running >1.12 and a demand for this then I'd still recommending patching an earlier version for this. Then again, in what situation would one require .peek and not be able to check it with the fixed/working method?

**Comment by leijurv** [comment]
tempted to hit this with a wontfix not gonna lie

**Comment by SylveonBottle** [comment]
Go for it. If someone wants you to add they can comment on this thread next year, otherwise there's no reason to work on this.

**Comment by LeafHacker** [comment]
TBH we didn't even include the "true" side of true durability in 1.13 because it doesn't look like any servers support it (although we do have a test branch ready in case that changes), so that's need to change in addition to this.

We could interpret this as wanting "always show" durability in .peek, as that did make it into 1.13

**Comment by l1ving** [comment]
> If someone wants you to fix it then they can comment on this thread next year

I'm assuming there's no interest for this now
