### ISSUE TITLE
Make betas commit-ly

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactIssues#1082]
Users are the best kinds of app testers, having commitly betas will ensure that you didn't screw up a feature. (think having freecam issues patched without having to have hotfixes)

Maybe this will be a good first badge to add to this repo, a CI with automatic beta builds.

**Comment by leijurv** [comment]
:heart_eyes_cat:

**Comment by EvilSourcerer** [comment]
this place needs more badges...

Mom Made Pizza Roles

**Comment by SuperOP535** [comment]
vanilla impact integration (soon????)tm

**Comment by ScanmanTM** [comment]
Wasn't like automatic builds like scraped due to brady's obfuscation?

**Comment by EvilSourcerer** [comment]
cat man already took care of that 😻

**Comment by LeafHacker** [comment]
Commitly may be a bit much, but once i sort out automatic maven stuff planning to do nightly, weekly or something like that

**Comment by SuperOP535** [comment]
Are you going to automate the ![image](https://user-images.githubusercontent.com/27556391/55674281-f6d3a800-58b2-11e9-9abb-0f5a3dedeb22.png) too?

**Comment by EvilSourcerer** [comment]
cat man already took care of that 😍

**Comment by LeafHacker** [comment]
Yeah @leijurv's already automated the obfuscation tasks - although we still need to renew our ZKM trial every two weeks lol

**Comment by EvilSourcerer** [comment]
~~inb4 impcat gets sued for purchase evasion~~

**Comment by LeafHacker** [comment]
ikr


Standard Price: | US$479.
-- | --
  | Applies if your organization (i.e. your company) consists of three or more people or has employed or contracted three or more people at any one time in the twelve months prior to the order date.
Small Developer Price: | US$239.
  | Applies if your organization (i.e. your company) consists of no more than two people and has employed or contracted no more than two people at any one time in the twelve months prior to the order date.

**Comment by leijurv** [comment]
> instead of having any particular version number it should just be "live"

**Comment by LeafHacker** [comment]
Was thinking of using mcversion-yyyy-MM-dd

**Comment by leijurv** [comment]
My only concern would be the amount of storage space that'd use on packagecloud (or wherever).

**Comment by LeafHacker** [comment]
As an alternative we could include the jar within the installer instead of hosting it on maven. Just extract the jar into `.minecraft/libraries`

**Comment by LeafHacker** [comment]
This has been fixed for a while, in the form of nightlies that can be installed by the installer.
