### ISSUE TITLE
Cant deploy elytra or ride entities on realms

### ISSUE THREAD

**Issue by Jake-Moss** [ImpactDevelopment/ImpactIssues#1093]
Cant ride mine carts, boats, horses, pigs, or deploy elytra even with fresh install, no modules enabled

**Comment by LeafHacker** [comment]
What happens when you try to?

**Comment by RoguePortal** [comment]
Nothing, right clicking does, I can just continue on my way

**Comment by usereewrjrjeejr** [comment]
What modules do you have on?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
