### ISSUE TITLE
Deploy to packagecloud instead of github-maven

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactIssues#1100]
Blocking #1082 

Use gradle's `maven` or `maven-publish` plugin to deploy the obfuscated jar to maven. CI can then run this task on tagged commits.

**Comment by leijurv** [comment]
The publicly viewable history of hotfixes is a benefit of having the maven on a git repo however....

**Comment by LeafHacker** [comment]
a) in theory there's no reason why packagecloud can't announce uploads
b) really this would be better served by either a post in #releases or an actual point release (4.6.1)
