### ISSUE TITLE
NoFall not working properly

### ISSUE THREAD

**Issue by Frappyy** [ImpactDevelopment/ImpactIssues#1113]
**Describe the bug**
NoFall simply doesn't work half of the time and when flying, you just die of fall damage. This has happened more times than I can count on a vanilla server with no anticheat.

**To Reproduce**
1. Turn on NoFall
2. Set it to 'Packet' mode
3. Change Flight mode to 'glide'
4. Start flying and you will die of fall damage or when you fall on the ground, you also die of fall damage

**Expected behavior**
Falling from a high distance and surviving. Also, flying and not dying of fall damage.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: NoFall, NoPush, NoRotate, Inventory, Auto Fish, Anti Vanish, ESP, Auto Reconnect
- Operating System: Windows 10 Pro 64-bit

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
