### ISSUE TITLE
Alt Manager Help!

### ISSUE THREAD

**Issue by TheGamingTitan11** [ImpactDevelopment/ImpactIssues#1134]
Hello, the alt manager isn't working. It used to work fine on older versions of Impact, now whenever I redeem an alt from MCLeaks and login with it it says "Not authenticated with minecraft.net". If anyone could instruct me on how to fix this I would appreciate it, thanks.

**Comment by usereewrjrjeejr** [comment]
Mc leaks is broken

**Comment by TheGamingTitan11** [comment]
Then what can I use?

**Comment by usereewrjrjeejr** [comment]
You'll have to ask around

**Comment by ZeroMemes** [comment]
Outdated, create a new issue if it still happens on the most recent version.
