### ISSUE TITLE
Impact - Riding hack doesn't affect speed on pig, but it affects speed on horse

### ISSUE THREAD

**Issue by SweHun** [ImpactDevelopment/ImpactIssues#1149]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by usereewrjrjeejr** [comment]
Thanks for all the info will be fixed soon!!!

**Comment by dominikaaaa** [comment]
Closed as can't reproduce. Reopen if you can still reproduce this.
