### ISSUE TITLE
[4.6][1.12.2] When disconnecting in one dimension and reconnecting in another, a NullPointerException is thrown and the client crashes

### ISSUE THREAD

**Issue by 0tii** [ImpactDevelopment/ImpactIssues#1153]
**Describe the bug**
This has now occured multiple times with me. I will use two examples to describe this issue.

1. The server I played on crashed while entering the nether (I was already at the "Downloading Terrain" stage). I tried reconnecting and every single time I tried that the client crashes and throws me back to the launcher. (The error was NUllPointerException while targeting(?) an entity" or smth) and I had to reconnect using vanilla client, go to overworld and then reconnect with Impact.

2. I disconnected in the nether on one server, tried connecting to a server where I was playing on the overworld and couldn't connect to that server with the same error as above. Fixing this took connecting to the first server, going to the overworld and then connecting to the second server.

**To Reproduce**
1. Go to a server
2. Go to the nether
3. Go to another server where your character is in the overworld

**Expected behavior**
The client will crash and throw an exception

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2
- Using Optifine? Nope
- Using LiteLoader? Nope
- Enabled mods: Antihunger, Tracers, ChestESP, Chams, Search, AntiHUnger, Portals
- Operating System: Win10

</details>

**Additional context**

**Comment by leijurv** [comment]
Need the crash report itself, it doesn't help to say "there was a crash report".

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
