### ISSUE TITLE
Why is steve a pig? module

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactIssues#1177]
Replaces pig's texture with steve.
Make it under misc or render.
![image](https://user-images.githubusercontent.com/35407179/56864679-4b070f00-69bd-11e9-81e3-5cf93be3e81c.png)
I know texture packs exist. Make it a module instead.

**Comment by ThatGrzegorzB** [comment]
![unknown](https://user-images.githubusercontent.com/6506529/56864800-1b5d0480-69c7-11e9-92bf-a2e52bc62897.png)
something like this xD

**Comment by usereewrjrjeejr** [comment]
Please this is very good

**Comment by EvilSourcerer** [comment]
yes!

**Comment by leijurv** [comment]
absolutely yes










this should be an option under franky

**Comment by usereewrjrjeejr** [comment]
I would pay my shekels for this

**Comment by leijurv** [comment]
IMPACT PREMIUM FEATURE

**Comment by EvilSourcerer** [comment]
this tbh ^

**Comment by ThatGrzegorzB** [comment]
I made that screenshot with my mate fucking ages ago, memed so fucking hard from it

**Comment by EvilSourcerer** [comment]
Now all we need is some developer to confirm this to be an Impact 4.7 feature.

**Comment by leijurv** [comment]
![download](https://user-images.githubusercontent.com/3837873/56870034-ce286500-69bd-11e9-9d4c-fb94781f1e7f.jpeg)

**Comment by ZeroMemes** [comment]
a mf really a joke when he ain't adding it to the milestone

**Comment by leijurv** [comment]
oh god oh fuck you jsut pwned me so hard im crying and shaking

**Comment by zPeanut** [comment]
mfw

**Comment by fawwaz1234** [comment]
mfw necropost
