### ISSUE TITLE
Alt Key

### ISSUE THREAD

**Issue by PNPengy** [ImpactDevelopment/ImpactIssues#1183]
**Describe the bug**
I think this is a function from Impact but you should make an option to disable it

**To Reproduce**
1. Go to 'A world'
2. Click on 'Alt key on your keyboard'
3. Try moving around

**Expected behavior**
You can't change direction

**Screenshots**
Can't described by screenshot try it yourself

**Additional context**
Thank you

**Comment by SuperFurias** [comment]
You can disable it with this command:
.perspective disable
