### ISSUE TITLE
Skyblock Cactus Farm

### ISSUE THREAD

**Issue by XxRedHunterxX** [ImpactDevelopment/ImpactIssues#1221]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to spend hours on a cactus farm when a simple mod can make it way easier.

**Describe the solution you'd like**
I'd like it so you can choose if you want to move or it automatically moves for you or if you want to stay still so it will make the cactus farm for you so it's way less work this the bot mine but, not exactly we should be able to set an exact path like we choose a button the start the path maker and it automatically makes it for you in that path

**Describe alternatives you've considered**
I haven't considered any alternative yet but it's just so stressful to make a cactus farm 

**Additional context**
Please Make it so we can use string or fences or anything and make it so we can use this like auto soup it pulls what it needs out of your inventory

**Comment by leijurv** [comment]
`.b farm`?

**Comment by XxRedHunterxX** [comment]
that doesn't work it doesn't make the type of farm I want I have been trying it today
it doesn't make the cacti farm I can show you how you can do it just message me my discord is One#7108

**Comment by l1ving** [comment]
Baritone has a path / patrol type thing planned
