### ISSUE TITLE
Chest stealer causing server to crash.

### ISSUE THREAD

**Issue by XShadowzxc** [ImpactDevelopment/ImpactIssues#1231]
**Describe the bug**
When using chest stealer while inventory is too will cause the server to crash.

**To Reproduce**
1. Join a server.
2. Make your inventory full.
3. Click the steal button while opening a chest.
4. Later, the server crashes.
 
- Impact Version: 4.6
- Using Optifine? No 
- Using LiteLoader?  No 
- Enabled mods: Only light and Auto tools.
- Operating System: Windows 10 64bit

**Comment by ZeroMemes** [comment]
...It crashed the server? Can you provide the hostname/ip address to the server?

**Comment by XShadowzxc** [comment]
Server IP : 139.99.16.114

**Comment by ScanmanTM** [comment]
I failed to reproduce this bug. I went on that server (factions) filled my inventory and used the steal button with a empty/full chest and the only bug happened to me which was my player's views were locked until I press escape.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
