### ISSUE TITLE
NameTags blurring out when in different f5 modes

### ISSUE THREAD

**Issue by Infernopickaxe** [ImpactDevelopment/ImpactIssues#1234]
Occasional blurring of nametags in different f5 modes

**Comment by ZeroMemes** [comment]
Can you provide screenshots to demonstrate the issue?

**Comment by leijurv** [comment]
it doesnt do this for me at all

**Comment by Cerbiac** [comment]
Can't reproduce it, could you answer these questions:
- Impact Version: e.g. "4.1 for 1.12.1"
- Using Optifine? Yes or No
- Using LiteLoader? Yes or No
- Enabled mods: e.g. "Killaura, Elytra+, Ridable with speed set to 3, etc"
- Operating System: "Windows 10 64bit" or "Fedora 24"

**Comment by T0ED** [comment]
[https://cdn.discordapp.com/attachments/583453983427788830/678344798503043074/Screenshot_11.png](url)

Here's a screeenshot of what he's talking about.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
