### ISSUE TITLE
Tracers and nametags going up instead of down

### ISSUE THREAD

**Issue by Infernopickaxe** [ImpactDevelopment/ImpactIssues#1235]
Players that are far below you will have the tracers and nametags go up off the screen instead of showing where the player is

**Comment by leijurv** [comment]
Does the nametag itself render at the top of the screen? Or is it just the tracer doing the wrong direction?

**Comment by Cerbiac** [comment]
If you look up and they (testing tracers on pigs, b/c I don't have friends. ;-;) walk behind you while you are looking straight up, it happens, but that's normal. Can't reproduce name tags at all, I'll play with it later.

**Comment by leijurv** [comment]
Can confirm, when you're at y=256 drawing a tracer to an entity at y=0 (or any different in Y level above 220 or so), there is a certain angle below which the tracer gets reversed. Looking at level or above, the tracer draws downwards, but as you start to go closer to looking straight down towards them, the tracer goes in the opposite direction from your crosshair.

**Comment by leijurv** [comment]
very easy to reproduce: enter freecam, and fly about 230 blocks straight up, the tracer to your player will invert and draw upwards instead of downwards

**Comment by LeafHacker** [comment]
This had been hackfixed so that now instead of happening at around y230 it happens at around y320.

**Comment by leijurv** [comment]
u really gotta do me like that?
