### ISSUE TITLE
Inline shulker peek / preview

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactIssues#1237]
I literally do not believe there isn't already an issue for this, but for some reason I can't find it?

shulker preview lol

**Comment by User-developer** [comment]
.peek -wait does impact have it?

**Comment by usereewrjrjeejr** [comment]
Yes

**Comment by leijurv** [comment]
By inline I meant a GUI like peek on mouse over, like shulker preview lol

**Comment by slinkayy** [comment]
Here's an example: https://i.imgur.com/n1M5GvB.png

**Comment by GreenMan36** [comment]
**Bump.** I need this.
