### ISSUE TITLE
Game crashes while joining a server

### ISSUE THREAD

**Issue by plisky** [ImpactDevelopment/ImpactIssues#1239]
When I use Impact 4.6 on version 1.12.2. My game crashes when trying to join a server due to a render error. It says, "The game crashed whilst rendering entity in world". I don't know how to fix it but I tried to remove the impact files from versions and the impact file from .minecraft.

[crash-2019-05-31_09.02.53-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3241524/crash-2019-05-31_09.02.53-client.txt)

The only server that works is 2b2t not any other else.

**Comment by ZeroMemes** [comment]
Very interesting, it appears to be caused by chams, disable that until a fix is available.

**Comment by leijurv** [comment]
What server crashes?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
