### ISSUE TITLE
ESP Shader Mode crashes the game

### ISSUE THREAD

**Issue by jkr174** [ImpactDevelopment/ImpactIssues#1255]
I'm not sure if this just don't work with AMD based computers or what but whenever i try to use that mode it instantly crashes the game.

**Comment by EmeraldSnorlax** [comment]
AMD cpu and gpu here on Manjaro lincucks. No issues here.

**Comment by ZeroMemes** [comment]
Please provide a crash log, it's difficult to diagnose an issue without one and without the specific hardware that it was produced on.

**Comment by boasbakker** [comment]
Hey, I have the same problem, but the game doesn't crash completely.
I use Forge Impact 4.8.3
The game freezes and you cant do anything.
It is in a strange state, I will send a video.
https://www.youtube.com/watch?v=CNWlt-yZXj4&feature=youtu.be

**Comment by 0-x-2-2** [comment]
Legacy GPU and CPU issue
