### ISSUE TITLE
How to add liteloader to Impact on Multimc ?

### ISSUE THREAD

**Issue by Adarcer** [ImpactDevelopment/ImpactIssues#1286]
Have a clear way to add Optifine to MultiMC Impact.json even tho it took a little trial and error because I am on Linux instead of windows, but I am having problems adding liteloader on multiMC and the only guide is for vanilla launcher. Have removed org folder from the liteloader.jar (even renamed and put in local library area for instance) even tried to do the "local" trick I did with Optifine here, but it does not see the location unlike Optifine.

Here is the  error I am getting the file is in location stated.

Instance update failed because: Some artifacts marked as 'local' are missing their files:
/home/REDACTED/.local/share/multimc/instances/Impact 4.6/libraries/INVALID

liteloader.json lint'd and says valid 
{
    "+tweakers": [
        "com.mumfrey.liteloader.launch.LiteLoaderTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "org.ow2.asm:asm-all:5.2",
            "url": "http://repo.liteloader.com/"
        },
        {
            "name": "liteloader-1.12.2-Impact",
            "MMC-hint": "local",
            "MMC-filename": "liteloader-1.12.2-Impact.jar"
        }
    ],
    "uid": "com.mumfrey.liteloader"
}

**Comment by AstragoYT** [comment]
not a suggestion. Use discord

**Comment by Adarcer** [comment]
The suggestion is that wiki needs some multimc instructions and some of the current instructions needs linux instuctions

**Comment by 0-x-2-2** [comment]
I don't see anything that is really platform dependent except for how to get to the .minecraft folder but if you are already using linux you should already know the location.

**Comment by swiftlysstuff** [comment]
Question for Adarcer, how did you get Optifine, MultiMC, and Impact working together?

**Comment by S-B99** [comment]
Closed due to inactivity. To get them working together make a custom json.
