### ISSUE TITLE
No Fall Bucket Not Working

### ISSUE THREAD

**Issue by pullup** [ImpactDevelopment/ImpactIssues#1315]
Version: Latest

Doesn't even try to use the bucket lmao

**Comment by Cerbiac** [comment]
I've been so busy playing Kirby and Minecraft with my buds that I forgot to make this issue aaaaa...
Anyways. I got it to break on Impact **4.6 on 1.13.2**. There was also a secondary issue that I'll post in a bit.

**Comment by VirxEC** [comment]
The no fall bucket only deploys if it's fatal to the player. To fix this, please support my issue: https://github.com/ImpactDevelopment/ImpactClient/issues/1292 This does make this issue a duplicate, however.

**Comment by Cerbiac** [comment]
> The no fall bucket only deploys if it's fatal to the player.
I've tried it. Doesn't work even then. With lethal on or off.

**Comment by Cerbiac** [comment]
Actually, I'm getting different results in 1.12.2 now that I'm testing it. Now it works perfectly. ;-;
I'm having issues with the launcher, so I can't double-check 1.13.2.

**Comment by pullup** [comment]
> The no fall bucket only deploys if it's fatal to the player. To fix this, please support my issue #1292 This does make this issue a duplicate, however.

Never have gotten it to deploy a single time :p
https://youtu.be/_RmHiQaEhL0

**Comment by a6d6061ed1** [comment]
> > The no fall bucket only deploys if it's fatal to the player. To fix this, please support my issue #1292 This does make this issue a duplicate, however.
> 
> Never have gotten it to deploy a single time :p
> https://youtu.be/_RmHiQaEhL0

it works for me but it seems glitchy both in singleplayer and low-lag vanilla multiplayer. it either deploys onto wrong block or not at all. also there's this bug where it creates 'ghost' water source that doesn't flow and it's only visible on client side

**Comment by dominikaaaa** [comment]
Closed in favor of previously linked issue
