### ISSUE TITLE
RainbowMode/Clear RainbowArraylist

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactIssues#132]
Same like old but more clear the Rainbow Effect should be Visible in one String
Like this here
![rainbowarray](https://user-images.githubusercontent.com/29576723/29489620-b5e47fca-8525-11e7-86e4-dd099b4fbc1e.PNG)

**Comment by zPeanut** [comment]
german intensifies

**Comment by ZeroMemes** [comment]
This would probably require the use of a shader program. With the smoothness of the existing rainbow mode, is this really needed?

**Comment by LeafHacker** [comment]
My mum told me not to use shady programs
