### ISSUE TITLE
Macro don't work

### ISSUE THREAD

**Issue by ulysserevient** [ImpactDevelopment/ImpactIssues#1321]
Hi,
Macro does nothing
I set some macros, but it does nothing !
Is there a solution ?
Here is my macro conf :

` [
  {
    "key": "w",
    "macro": "/spawn"
  },
  {
    "key": "1",
    "macro": "/home h"
  },
  {
    "key": "5",
    "macro": [
      "Top",
      ".top",
      "/top"
    ]
  }
]'

Minecraft 1.13.2
Impact 4.6

**Comment by usereewrjrjeejr** [comment]
This is a known issue

**Comment by dominikaaaa** [comment]
Fixed already
