### ISSUE TITLE
Autofish doesn't reel in the fish

### ISSUE THREAD

**Issue by Thepiotug** [ImpactDevelopment/ImpactIssues#1324]
AutoFish doesn't reel in the fish (doesnt do anything at all)
I tried to do it on quackity.up.lol
nearby only disabled

**Expected behavior**
Fish should be reeled in

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.6 for 1.13.2
- Using Optifine? yes
- Using LiteLoader? nope
- Enabled mods: only AutoFish
- Operating System: W10, may update
</details>

**Comment by Aaron2550** [comment]
This may be a Anti-Cheat thingy, i noticed the same thing on servers using matrix anti cheat

**Comment by VincentCCandela** [comment]
Same problem here. The fish bite sound is played but it  doesn't reel in no matter what I set the catch delay to. I also have turned nearby only off as well.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
