### ISSUE TITLE
Minecraft Launcher Won't Start 1.12.2 v4.6

### ISSUE THREAD

**Issue by Clownyn** [ImpactDevelopment/ImpactIssues#1331]
I downloaded Impact a while ago and had it working fine but had to re-download it recently for version 1.12.2 and followed all the steps to the letter and even watched multiple videos but it still doesn't work. every time I press Play it just says "Error! Unable To Start Game" I've uninstalled and reinstalled multiple times but nothing was working. Not sure if there is related to the new format on the website or what but if anyone can provide any help that's be appreciated.

**Comment by ZeroMemes** [comment]
There will be a crash log that is provided if the game is unable to start. Please link it.

**Comment by EastArctica** [comment]
I am also running into a similar issue. I am trying to run Impact 1.12.2 v4.6 with latest baritone on forge. I am running this within a mod pack, this mod pack runs on the Technic Launcher and is called Quality Of Life 2. Link below. I also have a mod list below. Thanks in advance!
https://www.technicpack.net/modpack/quality-of-life-2.1451271
https://www.technicpack.net/modpack/quality-of-life-2.1451271/mods

**Comment by usereewrjrjeejr** [comment]
Forge version broke

**Comment by EastArctica** [comment]
Any update being worked on? I looked into mine more and it seems that for me it is the death screen being over written

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

**Comment by EastArctica** [comment]
Sickkkkkk and I can’t edit the impact jar to remove the death screen because it’s obfusucated

**Comment by leijurv** [comment]
well actually the mixins aren't obfuscated 😈

you could delete mixinguirespawn or whatever 😈

**Comment by EastArctica** [comment]
org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[Impact-4.6-1.12.2.jar:?] Seems to not be there? I’m definitely wrong

**Comment by leijurv** [comment]
no you dont want to remove mixin entirely just that one mixin

edit mixins.impact.json and remove that line its ez :wink:

**Comment by EastArctica** [comment]
What program do you recommend for editing it

**Comment by usereewrjrjeejr** [comment]
Notepad++

**Comment by EastArctica** [comment]
True

**Comment by mrphax0r** [comment]
@EastArctica spongepowered??? Is that shiginima launcher

**Comment by mrphax0r** [comment]
Also atom.io
