### ISSUE TITLE
Baritone doesn't automine 2-block plants properly

### ISSUE THREAD

**Issue by daneeko** [ImpactDevelopment/ImpactIssues#1335]
**Describe the bug**
When doing `.b mine` with flowers/plants that are 2 blocks tall, baritone gets stuck when getting to a target block.
However, when I jump, baritone breaks the block and continues, getting stuck on the next block.

**To Reproduce**
1. `.b mine` with any 2block plant (rose bush, lilac, etc.)
2. see the bug

**Expected behavior**
baritone doesn't get stuck

<details> 
  <summary><strong>Game output</strong></summary>
 

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.13.2
- Using Optifine? no
- Using LiteLoader? nope
- Enabled mods: ESP Shader, New Chunks, Auto Eat, Portals, Light
- Operating System: Windows 7 64bit

</details>

**Additional context**
none

**Comment by dominikaaaa** [comment]
Can't reproduce, also this is a [Baritone](https://github.com/cabaletta/baritone) issue, not an impact one.
