### ISSUE TITLE
Auto Gapple

### ISSUE THREAD

**Issue by AlphaMaBeta** [ImpactDevelopment/ImpactIssues#1336]
Auto Gapple, when a player is losing health, the client would automatically switch to a golden apple and eat it then switch back to the item that it switched from.

**Comment by taxitank** [comment]
Sounds cool! 1.9 pvpers would approve :)

**Comment by mrphax0r** [comment]
yes

**Comment by Cerbiac** [comment]
Possibly we could combine pot, soup, and this module into one modifiable module, possibly with separate keybinds.

**Comment by Cadaver1337** [comment]
agreed, this should be added

**Comment by mrphax0r** [comment]
+10

**Comment by l1ving** [comment]
AutoEat should be able to do this, if not, one customizable module such as #1424 should
