### ISSUE TITLE
ItemSaver would crash the game if an item with 0 durability is moved into the hotbar through inventory.

### ISSUE THREAD

**Issue by theheartbenvn** [ImpactDevelopment/ImpactIssues#1351]
If i attempt to put an item with zero durability into the hotbar when ItemSaver is on, it would crash my game.

Using Optifine HD E2 + Impact 4.6 on Minecraft 1.12.2, Windows 10.

**Comment by ZeroMemes** [comment]
Unable to reproduce, please provide a crashlog.
