### ISSUE TITLE
ClickGUI hacks won't show up

### ISSUE THREAD

**Issue by 13yearoldADULT** [ImpactDevelopment/ImpactIssues#1357]
Okay, so I just installed Impact for FORGE 1.12.2, everything was fine during the installation, no crashes, no errors. Everything went completely fine.

Alright, so right after messing with Baritone (basically trying it out), I was curious what mods were in this client. I'm no new to hacked clients, I have been using them since 1.3.1. After pressing R-Shift which is the default for most hacked clients, and right-clicking on one of the tabs, I noticed that the hacks/mods didn't show up. Their description showed only showed up.

Here's a screenshot of my issue:
![image](https://user-images.githubusercontent.com/32934452/61242440-5eb94a80-a74e-11e9-911e-22ef6681d2ab.png)

It may be interfering with one of the mods installed but I'm 100% sure that I haven't installed a mod that would interfere with a hack's GUI. Also, when writing .toggle clickgui the Impact client only says that its on
Image;
![image](https://user-images.githubusercontent.com/32934452/61242614-d6877500-a74e-11e9-952f-842e12bfd48b.png)

Other: Before writing this, I looked for possible threads that have my issue, none were found. If a thread exists with my exact issue please reply to this thread with the other thread's "id" and mark this as a duplicate. btw sorry for my shitty english

**Comment by ZeroMemes** [comment]
Please provide the Forge version that you are using, and confirm whether or not having other mods affects the functionality of the Click GUI.

**Comment by 13yearoldADULT** [comment]
@ZeroMemes The mods shouldn't have any interference with the client. They shouldn't affect the Click GUI, I have scanned my mods before posting this. Forge version: 14.23.5.2836

**Comment by ZeroMemes** [comment]
*I'm asking for you to launch with the other mods removed to 100% eliminate this factor*

**Comment by 13yearoldADULT** [comment]
Removed every mod except optifine and JEI (Just Enough Items). The problem continues to occur.

Tested with every mod removed, same story

**Comment by 0-x-2-2** [comment]
remove jei lol

**Comment by 13yearoldADULT** [comment]
jei doesnt do anything lmao

**Comment by LeafHacker** [comment]
Literally just rename your `mods` directory to `mods.bk`, make a new `mods` directory and copy impact there, then report back to say if it affected anything.

**Comment by 0-x-2-2** [comment]
It does not matter what you think it does.

**Comment by dominikaaaa** [comment]
Closed due to inactivity.
