### ISSUE TITLE
Automine Bot bug

### ISSUE THREAD

**Issue by Toxic2Venom** [ImpactDevelopment/ImpactIssues#1358]
Automine Bot doesn't scan nearby things coal etc. What it wants to do is go to the farthest thing even if you are next to a coal block etc it takes you like halfway across the map so please fix this major issue.

ps. You should add an attack mob feature if it interferes the automine bot process.

        With regards,
        Gavin.

**Comment by StijnSimons** [comment]
Do you have legit mine on?
Also, you can enable 'combat halting' using Impact, or make the bot dodge mobs using [avoidance](https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/utils/pathing/Avoidance.java)
```java
/**
     * Toggle the following 4 settings
     * <p>
     * They have a noticeable performance impact, so they default off
     * <p>
     * Specifically, building up the avoidance map on the main thread before pathing starts actually takes a noticeable
     * amount of time, especially when there are a lot of mobs around, and your game jitters for like 200ms while doing so
     */
    public final Setting<Boolean> avoidance = new Setting<>(false);

    /**
     * Set to 1.0 to effectively disable this feature
     * <p>
     * Set below 1.0 to go out of your way to walk near mob spawners
     */
    public final Setting<Double> mobSpawnerAvoidanceCoefficient = new Setting<>(2.0);

    public final Setting<Integer> mobSpawnerAvoidanceRadius = new Setting<>(16);
```

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
