### ISSUE TITLE
LAuncher is black

### ISSUE THREAD

**Issue by simplyskyro** [ImpactDevelopment/ImpactIssues#1369]
**Describe the bug**
when i try to start the launcher, it just stays black and never crashed or loads.
**To Reproduce**

[2019-07-17-7.log](https://github.com/ImpactDevelopment/ImpactClient/files/3404662/2019-07-17-7.log)

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
User error
