### ISSUE TITLE
[AutoWalk] Reduce amount of debug output to chat

### ISSUE THREAD

**Issue by 0xx06** [ImpactDevelopment/ImpactIssues#1370]
Currently when baritone fails to find a path in Impact AutoWalk it will spam the chat with a message along the lines of 

"Failed to find a path, try looking into another direction and turn autowalk off and back on"
.

Instead of printing the message to chat on every loop run, please reduce it to once per second or less.

**Comment by Cerbiac** [comment]
This is a baritone issue, and it is working as intended, so it is also a suggestion.

**Comment by dominikaaaa** [comment]
This is an option in Baritone now, and next time make an issue in the Baritone repo.
