### ISSUE TITLE
Plugin List - Plugin name cut off

### ISSUE THREAD

**Issue by Rindula** [ImpactDevelopment/ImpactIssues#1375]
**Describe the bug**
When using the `.plugins` command (also on `.server`) the Pluginnames missing the first Character.

**To Reproduce**
1. Join a Server (I have tried it on mine)
2. Type `.plugins` or `.server`

**Expected behavior**
The Plugin name schould appear without missing characters

**Screenshots**
![Screenshot_4](https://user-images.githubusercontent.com/20195655/61470391-47ae6e80-a981-11e9-99d2-7b34642443fe.png)

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None (plugins)
- Operating System: Windows 10 64bit

</details>

**Additional context**

**Comment by ZeroMemes** [comment]
My own testing has revealed that the plugin finder is working as expected, this has to be a server-specific issue.

**Comment by Rindula** [comment]
Maybe try to use it on a BungeeCord Network, thats how the Server is setup ...

**Comment by 0-x-2-2** [comment]
I don't see how this can be a thing unless the server is just stripping the first char.

**Comment by Rindula** [comment]
Is it possible that you can give me a bit of insight knowledge of this part of the code so I can investigate on my side where the problem might be?

**Comment by ZeroMemes** [comment]
Closed this issue on a duplicate, #2015.
