### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by olilord123** [ImpactDevelopment/ImpactIssues#1382]
**Describe the bug**

**To Reproduce**
1. Go to 'the dowload page for impact'
2. Click on 'download (wondows)'
3. See error

**Expected behavior**
when i try to download impact 4.6 it says "This site can’t be reached The webpage at http://evassmat.com/K4AN might be temporarily down or it may have moved permanently to a new web address."
**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
You probably have some firewall or some browser plugin blocking the website since its a adfly url

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
