### ISSUE TITLE
Keybind gets reset on death

### ISSUE THREAD

**Issue by Aaron2550** [ImpactDevelopment/ImpactIssues#1390]
_(IDK why the template isn't showing up, I'm on mobile maybe that's why)_

When using the **0** key as a bind for killaura you have to rebind it every time you die. The GUI still says it's bound to 0 but pressing 0 doesn't do anything.

**Comment by ZeroMemes** [comment]
Please provide the Impact version and Minecraft version that this occurs on.

**Comment by Aaron2550** [comment]
1.13.2 with OF, Impact 4.6 _(Im currently on vacation and cannot give y'all the versions I selected in the Installer but I'm 100% sure it was all the newest)_

**Comment by Aaron2550** [comment]
Doesnt seem to happen anymore, sorry for having this open for this long, i just found this when going thru all my open issues
