### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Trixelit** [ImpactDevelopment/ImpactIssues#1392]
While using Impact 1.12.2, I cannot break, use, or place blocks.
Does anyone know how to fix this?

**Comment by ZeroMemes** [comment]
Please provide more context, i.e:

What modules are you using?
What Impact version are you using?
Have you tried disabling certain modules to diagnose what specifically is causing it?
etc.

We can't help you if we don't know any information. My immediate guess is that this is the same issue that is occurring in #1273.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
