### ISSUE TITLE
Plz add legitaura

### ISSUE THREAD

**Issue by LukasDoesDev** [ImpactDevelopment/ImpactIssues#1393]
Plz

**Comment by ZeroMemes** [comment]
What would the functionality of such a thing entail? There is already a smooth aimbot and autoclicker in Impact.

**Comment by Lukas562Dev** [comment]
oh ok i did not know lol

**Comment by Lukas562Dev** [comment]
but i would want also better panic feature. so i would show vanilla menus in case of a screenshare but you could show impact menus/reset it to default by pressing something like Ctrl+R or something
