### ISSUE TITLE
Alts Login Failed

### ISSUE THREAD

**Issue by Georgel72** [ImpactDevelopment/ImpactIssues#1405]
Hi, 
I recently downloaded Impact 4.6 for 1.13.2
It works just fine. I gathered my accounts (8 Premium MC Accounts) and tried the Alts Feature. When i added all of my accounts I noticed that when i tried to login into any of them I would get the message ,,Premium - Failed Authentication''. Those are not Fake MC Accounts. All 8 are Bought from Minecraft.net
Can someone help me with my Problem?
Thanks

**Comment by HannexYT** [comment]
I have the same problem look 
![Annotation 2020-04-10 135516](https://user-images.githubusercontent.com/63297505/78989111-f196e200-7b32-11ea-8087-b1656d35a63b.png) those are real alts from minecraft

**Comment by dominikaaaa** [comment]
Your password is wrong or mojang is rate limiting you, try again later. Not an impact issue.
