### ISSUE TITLE
FastBreak and XRay

### ISSUE THREAD

**Issue by lolw0tm8** [ImpactDevelopment/ImpactIssues#1423]
**Describe the bug**
FastBreak - If i enable fastbreak, fastinteract and set any speed of it it just mines on normal speed
Xray - Most ores doesn't render and some are half transparent (Screenshot below)

**To Reproduce**
Steps to reproduce the behavior (XRAY):
1. Enable xray
2. See error
Steps to reproduce the behavior (FastBreak):
1. Enable FastInteract
2. Enable FastBreak
3. Set any FastBreak speed
4. Try to mine
5. See error

**Expected behavior**
Xray - All ores seen in rendered chunks, full ores
FastBreak - Break blocks alot faster, same speed with disabling 

**Screenshots**
Below

**No crashes**

  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.6 for 1.13.2 (happens in 1.12.2 too) - No forge
- Using Optifine? Yes
- Using LiteLoader? No
- Operating System: Windows 10 64bit

</details>

**Comment by lolw0tm8** [comment]
Sorry, bad screenshot lol
![2019-07-24_13 38 11](https://user-images.githubusercontent.com/53062952/61791300-e6234f80-ae19-11e9-9635-d614eb290ef1.png)

**Comment by StijnSimons** [comment]
Use without optifine.

**Comment by Bayleaf154** [comment]
I second this fastbreak issue, however it seems like the block just refuses to break if I have fastbreak set to anything except 1. Tried on latest nightly build (Impact 4.8.0-20190821-nightly) and Impact 4.7.3. Both in singleplayer and on Minecraft versions 1.14.4 and 1.12.2.

**Comment by dominikaaaa** [comment]
Can't reproduce
