### ISSUE TITLE
Hard lag when i turn on the auto mine

### ISSUE THREAD

**Issue by Gizmo1256** [ImpactDevelopment/ImpactIssues#1425]
**Describe the bug**
When i turn the auto mine on it lags my pc VERY hard to the point where nothing responds

open the menu 
turn on the auto mine
HARD lag

**Expected behavior**
I though it should auto mine and find things and not almost crash my computer im not sure what it was from

**Screenshots**
No

**Comment by StijnSimons** [comment]
Which specification does your PC have?

**Comment by iTechieGamer** [comment]
To be more specific, the frames drop.

It is caused by the "Legit Mine" feature. Turning it off removes the lag

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
