### ISSUE TITLE
Auto-disconnect isn't working

### ISSUE THREAD

**Issue by zSnowyV** [ImpactDevelopment/ImpactIssues#1436]
Auto-disconnect isn't disconnecting even with the right settings.

Literally just enable it for whatever point of life you want and get down the certain life u specified for the bot to use.

it should disconnect, it isn't disconnecting.

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.7.1
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Auto Cheat, Auto Reconnect, Velocity, Anti Desync, Anti Vanish, Item Saver, AutoEject, Nametags, Auto Eat, Sprint.
- Operating System: W10

</details>

**Comment by S-B99** [comment]
Please provide more information, such as the settings and a video if this issue is still happening
