### ISSUE TITLE
Game Crashed upon disconnecting while falling through void in an unloaded chunk

### ISSUE THREAD

**Issue by 0xx06** [ImpactDevelopment/ImpactIssues#1442]
So I was autorunning and ran into an unloaded chunk causing me to fall down (pretty standard until the chunk loads). Usually it takes a second or two  and i'll be running again.

When i was around -4000 Y though i though i disconnect and reconnect. upon clicking disconnect the game crashed. minecraft didnt let me see the crash report sadly, this happens to me sometimes.

To reproduce (?):

1. autorun until falling into an unloaded chunk
2. when the chunk doesnt load until you have fallen to -4000 y try disconnecting
3. game should crash

Used impact: 4.7.2
Used baritone with timer.

**Comment by 0xx06** [comment]
it happened again while disconnecting during autowalking with timer with "screen tick error" ( i think)

**Comment by 0-x-2-2** [comment]
game version?

**Comment by 0xx06** [comment]
1.12.2 impact 4.7.2

**Comment by dominikaaaa** [comment]
No log, can't reproduce. Make a new issue if this is still happening
