### ISSUE TITLE
Feature for Baritone.

### ISSUE THREAD

**Issue by gupah** [ImpactDevelopment/ImpactIssues#1443]
A baritone option in creative mode, which automatically collects the blocks needed to build the schematics. In survival mode, show a list with the amount of materials needed (and put how many items are missing) or the bot, collect the necessary materials on its own.

**Comment by dominikaaaa** [comment]
Duplicate of https://github.com/cabaletta/baritone/issues/1675

In the future, please make issues in the proper repository
