### ISSUE TITLE
Undetectable Murderer weapon on Murder Mystery [Hypixel]

### ISSUE THREAD

**Issue by Sinily** [ImpactDevelopment/ImpactIssues#1446]
**Description:**
Murder for Hypixel doesn't detect the Feather item as a murderer weapon. Therefore the Murderer's highlighted box isn't red as it should be, it is white as if they are an Innocent.

**Steps to reproduce the behavior:** N/A

**Expected behavior:** 
The murderer's highlighted box should be colored red.

**Comment by viluzi** [comment]
i found this very annoying.

**Comment by MightyKnight** [comment]
Closing as a duplicate, #1894 is the same but has been getting more activity.
