### ISSUE TITLE
1.12 / 1.12.2 Some mods (hacks) not displaying

### ISSUE THREAD

**Issue by Lavodan** [ImpactDevelopment/ImpactIssues#1453]
NOTE: By mods, I mean features, utilities, things like xray, flight, timer, whatever, NOT forge mods.

**Description**
Some of the mods fail to display on the mod menu on the right side of the screen. Which mods dont show up seems to be random, but consistent within versions (4.6, 4,7.1 , 4.7.2, optifine, non-optifine) and restarts (e.g. nametags will never show up, not matter how many times I restart the game). This bug does not occur on the 1.13 version. This bug is not tested on the forge versions. I am running Win7, 64 bit, newest Java, 4GB RAM

**To Reproduce**
1. Open Impact 1.12 or 1.12.2 (with or without optifine)
2. Join a game (SP or MP)
3. Enable a few mods
4. Check HUD display of active mods, there should be some blank spacec

**Expected behavior**
The mods should show up as normal (e.g like killaura)

**Screenshots**
![](https://media.discordapp.net/attachments/222120655594848256/603985800958312462/unknown.png?width=930&height=500)
Blank spaces should have mod names.

  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version:  4.6/4.7.1/4.7.2 for 1.12/1.12.2
- Using Optifine?: Yes/No 
- Using LiteLoader?: No
- Enabled mods: N/A
- Operating System: Win7 32bit

</details>

**Comment by ZeroMemes** [comment]
Can you provide your config file? (Located under `.minecraft/Impact/profiles/default.json`)

**Comment by Lavodan** [comment]
@ZeroMemes 

My Impact folder does not have a `profiles` folder
![image](https://user-images.githubusercontent.com/21205085/62057700-6f72c180-b220-11e9-8e3a-d5832e688982.png)

I am going to assume that you mean the `default.json` file in the `config` folder, so here it is:
https://drive.google.com/open?id=1XvuigclgTRwyT2g4Yl_V_D3Kly_gG48U

**Comment by Lavodan** [comment]
@ZeroMemes 
Hey, could I get some kinda response? 
Thanks

**Comment by dominikaaaa** [comment]
Can't reproduce this issue.
