### ISSUE TITLE
Baritone feature

### ISSUE THREAD

**Issue by Lua51** [ImpactDevelopment/ImpactIssues#1462]
I would like to see more legit movement for baritone, as legitmine still doesn't look that legit, as your character keeps moving weird, and their head snapping to different places.

**Comment by mrphax0r** [comment]
So basically smooth rots?

**Comment by Lua51** [comment]
> So basically smooth rots?

Yes.

**Comment by KevTN5656** [comment]
I support this 100%

**Comment by dominikaaaa** [comment]
Iirc this is now an option, or at least suggested in the proper Baritone repo.
