### ISSUE TITLE
Auto Obby

### ISSUE THREAD

**Issue by Infernopickaxe** [ImpactDevelopment/ImpactIssues#1463]
Auto places obsidian around your legs to prevent endcrystals from damaging you
Should do constant checks to replace obby or just replace a broken obsidian immediately

**Comment by StijnSimons** [comment]
A crystal explodes within a tick... You can't place many blocks in one tick.

**Comment by Infernopickaxe** [comment]
I have seen auto obbys react faster than auto crystals can

**Comment by MightyKnight** [comment]
Resolving your issue as a duplicate, even though it's the oldest. Other issue has more information.
Duplicate of #1922
