### ISSUE TITLE
KillAura not attaks Bats in 4.7

### ISSUE THREAD

**Issue by DARKESTSOULER** [ImpactDevelopment/ImpactIssues#1465]
**Bat are difficult to kill couse they have so small hitbox and flying around your head. They are just anoying. In Impact v. 4.6 i can kill them with the KillAura so easy, but in v 4.7.2 the Aura not attaks them**

![lmao](https://user-images.githubusercontent.com/53310113/61992325-fc6d1d80-b05c-11e9-90b7-3ab68082758f.jpg)

 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System:

**Comment by StijnSimons** [comment]
Do you have Passive enabled?

**Comment by DARKESTSOULER** [comment]
Yh passive is enabled

**Comment by DARKESTSOULER** [comment]
I tested it with the Impact v. 4.6 and there it workst but not in v. 4.7.2

**Comment by DARKESTSOULER** [comment]
And i found out that ESP is ignoring Bats to :c

**Comment by LeafHacker** [comment]
Iirc bats are ambient not passive, so maybe we don't have a filter for them!

**Comment by StijnSimons** [comment]
> Iirc bats are ambient not passive, so maybe we don't have a filter for them!

Yeah but i tought it would've been in there cause it worked in 4.6

**Comment by dominikaaaa** [comment]
KA should have a neutral setting now?
