### ISSUE TITLE
Impact 4.7.2 shows only loading screen when entering a survival world

### ISSUE THREAD

**Issue by GionRubitschung** [ImpactDevelopment/ImpactIssues#1469]
So I just upgraded to the newest Impact version. I wanted now to see what changed in a singleplayer world but when I try to enter it I just see the loading screen (dirt). The strange thing is that I hear the sounds of the world, but can't see the world. I run Impact on 1.12.2. I also tried to make a new world, but there is the same problem...

![unknown](https://user-images.githubusercontent.com/43574999/62000026-227ed600-b0ce-11e9-9365-82d1ca970bbd.png)

Thats how it looks...

How can I fix this?

**Comment by Carbonixx** [comment]
Do you happen to be using optifine with it?

**Comment by GionRubitschung** [comment]
I used optifine in the old version too and there it worked.

**Comment by GionRubitschung** [comment]
So I reinstalled it but this time without optifine and this works now. So the problem is with optifine

**Comment by ScanmanTM** [comment]
Its cause by shaders and esp. if you want to use shaders + esp set esp to 2d mode.

**Comment by sirtomato999** [comment]
can i use chams instead? will that work?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
