### ISSUE TITLE
KillAura Tick automatically crits

### ISSUE THREAD

**Issue by Shyrogan** [ImpactDevelopment/ImpactIssues#1474]
**Describe the bug**
I mean, I think it's a bug because this is a little bit dumb but when using tick aura, it seems like it has it's own criticals and it can't be untoggled.

**To Reproduce**
Turn "Tick" mode in KillAura and use it on any entity.

**Expected behavior**
Expected to not crit if I don't want it to.

**Comment by sirtomato999** [comment]
do you have criticals on?

**Comment by Shyrogan** [comment]
> do you have criticals on?

Nope, Criticals is disabled.

**Comment by sirtomato999** [comment]
huh

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
