### ISSUE TITLE
all menu text disappear when i set the language to chinese

### ISSUE THREAD

**Issue by lupohan44** [ImpactDevelopment/ImpactIssues#1478]
**Describe the bug**
all menu text disappear when i set the language to chinese

**To Reproduce**
1. Go to 'language'
2. Click on '简体中文(中国)'
3. Click on '完成'

**Expected behavior**
I should be able to see the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/23133361/62124676-61df3980-b2fd-11e9-9217-0653c79f4ce1.png)

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: all version
- Using Optifine? both situation
- Using LiteLoader? No
- Enabled mods: non-relevant
- Operating System: Windows 10 64bit

</details>

**Additional context**
is there any way that i can translate the client to other language by ourselves?

**Comment by ngt1133** [comment]
this font doesnt support this language

**Comment by lupohan44** [comment]
> this font doesnt support this language

wolfram has the option to use Minecraft's default font,perhaps can add the same option to Impact?

**Comment by dominikaaaa** [comment]
Duplicate
