### ISSUE TITLE
More quality of life improvements (mainly for esp)

### ISSUE THREAD

**Issue by DanCuber** [ImpactDevelopment/ImpactIssues#1495]
Ok so now that colored tracers are a thing, why not also customizeable color-coded esp?
Hostile mobs: red
Passive: green
Players: custom
Other: blue

Again on esp (very petty thing ik) but the ability to add custom colors to specified items (dropped items) and/or exclude specific items (dropped items) from being picked up on esp all together (the second part would also be nice with chams)

**Comment by MightyKnight** [comment]
Duplicate of #1041
