### ISSUE TITLE
Mining while autoeject is ejecting an item results in a crash

### ISSUE THREAD

**Issue by DanCuber** [ImpactDevelopment/ImpactIssues#1500]
**Describe the bug**
While autoeject is enabled, you'll crash if it ejects the item at the same time as you're mining.

**To Reproduce**
Steps to reproduce the bug
:
Launch impact 4.7 for minecraft 1.13.2 (no optifine, vanilla launcher)

Go on a 1.13.2 vanilla server (not lan world)(have only tried this in multiplayer)

Enable autoeject and type .autoeject add dirt

Enable autotool (idk had it enabled at the time)

Find some dirt and dig a couple blocks straight down (standing on the block you mine)

Crash

**Expected behavior**
Should drop the items without issues, like in 4.6 for 1.12.2

(Will add the crash log as soon as I can)

**Comment by MightyKnight** [comment]
Please re-test this issue on the latest Impact version (make sure to only have the relevant modules enabled). Then, provide a **crash report**.
