### ISSUE TITLE
Redstone contraption compatibility

### ISSUE THREAD

**Issue by TheOPtimal** [ImpactDevelopment/ImpactIssues#1501]
So basically - Allow interactions with redstone.

This should be done with AI/Neural Network

Have baritone automatically detect redstone traps, and avoid the things that trigger the following trap.
If the block activated by the certain thing is a command block and thus unreadable, simply avoid as there is no knowledge on whether it's safe or not

Interact with redstone doors - Instead of mining through the redstone door, simply press the button/walk over the pressure plate and activate the door.

Manual addition of redstone contraptions - Allow the player to add certain redstone contraptions for example - Armor equipping stations. This is a useless example, but so much can be done with this. Maybe while going to a certain place - use a TNT launcher and the list goes on.

And also - ability to mark command blocks as safe so if the command block is simply to apply like a speed effect, allow the player to mark it as safe so baritone knows it's safe. If the player is in creative, simply check the command block for - debuffs, teleportation (to an unloaded chunk/if loaded, check for unsafe place. Like maybe teleportation to void, etc), a /kill command leading to @a, @e (if it's an @e[type:!minecraft:player] ignore), @r, @p or the player name.

**Comment by sirtomato999** [comment]
that would be a baritone thing, not an impact thing

**Comment by dominikaaaa** [comment]
This is out of scope of impact, and realistically, who the hell is building redstone traps in 2020?

**Comment by dominikaaaa** [comment]
Next time, make Baritone suggestions in the Baritone repo
