### ISSUE TITLE
Minecraft crashing when opening world or server

### ISSUE THREAD

**Issue by testedmatthew** [ImpactDevelopment/ImpactIssues#1503]
Upon opening, a server/world, after terrain has loaded, I crash seconds after terrain has finished loading. I have attempted ways to fix this but have failed

1. Create/Open a world or join a server
2. Let Terrain load
3. Wait a few seconds
4. Minecraft ends up crashing

Expectation was to see a new world load up as I was testing some features

Screenshot: 
![image](https://user-images.githubusercontent.com/53839565/62579027-48dc0880-b868-11e9-8e6c-f6c0d4a0fdb3.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.7 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 1903 64bit

</details>

**Comment by ScanmanTM** [comment]
Thought about including the crash log you moron.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
