### ISSUE TITLE
Impact 4.7 1.12.2 crashing when attempting to load any server or world

### ISSUE THREAD

**Issue by CrookDragoon** [ImpactDevelopment/ImpactIssues#1508]
The game boots as usual, but upon attempting to join a world or server, it will do the whole "not responding" thing, and continue to freeze until I close it. For whatever reason, the game detects a crash, but doesn't send a crash report as seen below, so I can't really help you there as much as I would like to. Any tips? 
![Screenshot (18)](https://user-images.githubusercontent.com/53883903/62667521-34217280-b945-11e9-9d92-28ef2a793ab7.png)

**Comment by spookydascary24** [comment]
Same issue here, also posted it - No help at all, just switch to other clients.

**Comment by leijurv** [comment]
Find the logs in `.minecraft/logs/latest.log`, there should be a stacktrace at the bottom

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
