### ISSUE TITLE
Kicked when sending messages

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#1522]
**Describe the bug**
Getting kicked for spam after sending message with /ac /msg and sometimes on /login when password is wrong

**To Reproduce**
I shoulnt have to explain this right?

**Expected behavior**
To dont get kicked?

**Screenshots**
Not necesary?

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.7.2 for 1.13.2
- Using Optifine? Yes
- Using LiteLoader? No
- Operating System: Windows 10 1903
- Enabled mods:  Autoarmor autoweapon criticals aimbot killaura lag anti hunger animations anti desync anti sound lag middle click friend no srp jesus no slow riding sprint step velocity autoeject autotool chest stealer inventory no fall no rotater respawn timer weather
Render mods not added

</details>

**Additional context**
?

**Comment by lolw0tm8** [comment]
this is issue with 1.13 since 1.13 has new chat system i think

**Comment by S-B99** [comment]
This is a server issue.
