### ISSUE TITLE
Better scaffold

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#1523]
**Is your feature request related to a problem? Please describe.**
More customizable scaffold that atleast can be used on some servers

**Describe the solution you'd like**
Legit mode of scaffold like having the blocks on hand and not too fast building
A option for block placement delay
Option to look where you are placing the block for better bypass (if not already done)
 
Also option to disable speed and timer when using scaffold and when disabling scaffold reenable them (I really need this one so it doesnt do stairs)

**Comment by thegamerx1** [comment]
please it doesnt bypass any anticheat still waiting after months

**Comment by S-B99** [comment]
> disable speed and timer when using scaffold and reenable them
use a macro or bind them to the same key

**Comment by thegamerx1** [comment]
...

**Comment by S-B99** [comment]
fixed my formatting.

**Comment by S-B99** [comment]
Because macros are built into Impact lmao

It's such a super specific thing that nobody else would use. 

Or just bind all of those to the same key.

**Comment by thegamerx1** [comment]
Why closed?
