### ISSUE TITLE
Custom hotbar module

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#1524]
A module to select which items to have on the hotbar like
1st slot sword 
2nd slot second gapple and if there isnt gapple food 
3rd slot food
4th slot pickaxe
5th slot shovel
and so on

**Comment by lolw0tm8** [comment]
useless just use the num keys on your keyboard while in invetory sorting items

**Comment by thegamerx1** [comment]
useless? then why autoeject just do shift + q why cheats just use skillz

**Comment by Thunder33345** [comment]
basically a auto grab item with hotkey
