### ISSUE TITLE
Build(World Tab)

### ISSUE THREAD

**Issue by VladSKTZ** [ImpactDevelopment/ImpactIssues#1531]
i am playing on a server, on SeaBlock, like skyblock but with water that kills you, anyway, the build option does not work on water, if there is water, the hack wil not place the blocks
https://www.youtube.com/watch?v=tahZa3PzTMo

**Comment by thegamerx1** [comment]
you're using the blocks or the water bucket?

**Comment by NotRealPaz** [comment]
impact's build module cannot place block in water. I try to create sand wall so that i can remove water in the ocean but that's doesnt work.

**Comment by dominikaaaa** [comment]
`#okIfWater` or remove the water 

also this isn't an impact issue

**Comment by dominikaaaa** [comment]
Locking this as it's off topic and super old anyways.
