### ISSUE TITLE
Only AutoEat when not targeting killaura

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#1533]
Autoeat only when not targeting with killaura or aimbot

**Comment by ZWORX52** [comment]
I experience this, and when Killaura activates while Autoeat is eating, I can't do anything until I turn off Killaura or Autoeat - Killaura tries to hit with whatever Autoeat is eating with, and it doesn't let me eat or hit until I turn off either Killaura (and it's done eating) or I turn off Autoeat (and wait for Killaura to kill or stop)

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by ZWORX52** [comment]
I believe it got fixed, possibly by accident.
