### ISSUE TITLE
Impact resetting

### ISSUE THREAD

**Issue by conf1rmed** [ImpactDevelopment/ImpactIssues#1535]
Sometimes when I load minecraft all the options in the clickGUI that I chose gets reset

**Comment by thegamerx1** [comment]
Anything that you do sometimes that may make that to reset? Any console log that may help?

**Comment by DaGameGamer** [comment]
I don’t know

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
