### ISSUE TITLE
No Rotate allow rotate at world loading

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#1539]
Allow first rotate packet or allow rotate packets for x time after spawning in the world

Its annoying having to move the camera to the right direction every time that i enter any server but i need norotate because server anticheats sometimes move my camera when using killaura but they dont kick or ban me at all

**Comment by mrphax0r** [comment]
This would render norotset useless

**Comment by thegamerx1** [comment]
another one?
