### ISSUE TITLE
cant play

### ISSUE THREAD

**Issue by Kelkios** [ImpactDevelopment/ImpactIssues#1548]
**Describe the bug**
I cant play
**To Reproduce**
dont

**Expected behavior**
Me to be able to play

**Screenshots**
https://gofile.io/?c=uggP4b
<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
Maybe because you got portals(god mode) enabled??

**Comment by eatmedaddy** [comment]
> Maybe because you got portals(god mode) enabled??

No, It was disabled, but after 5 minutes or so of running impact portals it just keeps me stuck

**Comment by VirxEC** [comment]
try typing #freelook or .b freelook into chat - it looks like baritone was trying to walk backwards bc freelook was enabled and the anticheat kept getting triggered. Also try turning off anti-hunger, maybe that's a part of it, too.

**Comment by sirtomato999** [comment]
portals god ok

**Comment by MightyKnight** [comment]
Link doesn't work anymore, issue is unclear anyway

**Comment by S-B99** [comment]
lmaooooo
```
Describe the bug
I cant play
To Reproduce
dont
```

**Comment by MightyKnight** [comment]
Pin issue immediately - Best report xD
