### ISSUE TITLE
Enderchest automine bug

### ISSUE THREAD

**Issue by dermono** [ImpactDevelopment/ImpactIssues#1551]
Upon placing down enderchests and running the command .b mine ender_chest, baritone sends me hundreds of blocks away instead of mining the chests directly in front of me. 
**To Reproduce**

1. Place down Ender Chests in front of you or around you
2. Type .b mine ender_chest
3. Instead of mining the chests, baritone sends me to chests hundreds of blocks away in search of more chests.

I attempted to use .b repack to fix the issue, but it did not fix it, and instead only queued chunks.

**Comment by leijurv** [comment]
What version of Minecraft, impact, baritone, etc?

**Comment by dominikaaaa** [comment]
Can't reproduce, next time make the issue in the baritone repo.
