### ISSUE TITLE
Annoying thing with .b mine

### ISSUE THREAD

**Issue by hitleriscool** [ImpactDevelopment/ImpactIssues#1553]
Ok so i need to get a shulker of seeds for a friend and i did .b mine tallgrass to mine grass and i have a shovel with fortune in my hotbar and it wont let me hold it its really annoying

**Comment by hitleriscool** [comment]
Also sorry about my name i made this account a while ago

**Comment by 0-x-2-2** [comment]
`.b` just runs baritone commands afaik so maybe this should be on the baritone repo???
