### ISSUE TITLE
ESP Skeleton mode not working on 32-bit Win 7 system

### ISSUE THREAD

**Issue by TrulyYoko99** [ImpactDevelopment/ImpactIssues#1556]
ESP will not display anything when used in "Skeleton" mode

![Box mode](https://user-images.githubusercontent.com/54221312/63217981-81c18a80-c150-11e9-86aa-cf568b53d2e9.png)
![2D mode](https://user-images.githubusercontent.com/54221312/63217982-81c18a80-c150-11e9-80e5-39ebb9945d98.png)
![Skeleton mode](https://user-images.githubusercontent.com/54221312/63217983-81c18a80-c150-11e9-93f4-6d9dd1dcb6f8.png)

The system this was verified on is a 32-bit Windows 7 install with a dual GeForce 8800 GT GFX setup

![OS](https://user-images.githubusercontent.com/54221312/63218014-39569c80-c151-11e9-8875-074f6b8ca238.png)

![GFX p1](https://user-images.githubusercontent.com/54221312/63218031-889ccd00-c151-11e9-93c5-9ba90fe01324.png)
![GFX p2](https://user-images.githubusercontent.com/54221312/63218033-8cc8ea80-c151-11e9-96ec-dc550e8206d8.png)

**Comment by 0-x-2-2** [comment]
Skeleton mode only works with with players currently as it is hardcoded for the player model afaik.

**Comment by TrulyYoko99** [comment]
> Skeleton mode only works with with players currently as it is hardcoded for the player model afaik.

That is incorrect. Here it is working as intended on another machine. Please reopen

![2019-08-18_23 45 08](https://user-images.githubusercontent.com/54221312/63230870-9155d780-c213-11e9-906b-f999e4230be3.png)

**Comment by leijurv** [comment]
Sorry accidentally reopened. Your screenshot of it "working as intended" is esp mode shader, not esp mode skeleton.

**Comment by TrulyYoko99** [comment]
> Sorry accidentally reopened. Your screenshot of it "working as intended" is esp mode shader, not esp mode skeleton.

Thank you for your clarification. In that case title needs editing. Please reopen.

**Comment by TrulyYoko99** [comment]
> > Sorry accidentally reopened. Your screenshot of it "working as intended" is esp mode shader, not esp mode skeleton.
> 
> Thank you for your clarification. Title edited. Please reopen.

Please disregard previous comment. After verification, the issue apears to be an altogether different one i.e whereas on one system the 4.7.3 version of Impact offers a choice in its ClickGUI between the 4 options (Box, 2D, Shader, Skeleton), it only offers 3 options on the other system (Box, 2D and Skeleton)

Thank you for closing the issue.
