### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Johnsilverknight** [ImpactDevelopment/ImpactIssues#1557]
**Is your feature request related to a problem? Please describe.**
Not really
**Describe the solution you'd like**
When an alt gets banned or trying out an alt that is already banned on a server give us a random alt button that will use a random alt from the alt list
**Describe alternatives you've considered**
Doing it manually
**Additional context**
Liquid bounce has it and is a free client and seeing how this client is better than it in every singble way except this, I think this should be in the client. Its also a QOL thing

**Comment by LeafHacker** [comment]
Please add a brief but descriptive title

**Comment by wholesomeduck** [comment]
Please add a brief but descriptive title

**Comment by enderman2s** [comment]
Please add a brief but descriptive title

**Comment by S-B99** [comment]
This is now a thing.
