### ISSUE TITLE
[1.14] freecam camera spawns thousands of blocks away

### ISSUE THREAD

**Issue by Fish815420** [ImpactDevelopment/ImpactIssues#1560]
**Describe the bug**
Free cam doesn't show the area you're in and won't let you move and puts you thousands of blocks away
**To Reproduce**
1. Go to 'free'
2. Click on 'activate'
3. watch cords before and after

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54226531/63220017-a7489700-c144-11e9-9959-4c6fc4afb376.png)
![image](https://user-images.githubusercontent.com/54226531/63220024-b6c7e000-c144-11e9-8da3-4c4306f0dc7f.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4 
- Using Optifine? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by leijurv** [comment]
Fixed for today's nightly
