### ISSUE TITLE
Formatting codes to be added in Anvil UI

### ISSUE THREAD

**Issue by SaltyMelons** [ImpactDevelopment/ImpactIssues#1561]
- Currently, the "signs" option exists in impact that allows formatting codes to be typed out on signs with '&' instead of '§'

- The anvil UI does not allow for '§' to be typed or pasted into the renaming section

- It would be cool to have a function similar to "signs" when renaming things in an anvil, which could allow for some cool name tags or weapon names

**Comment by 0-x-2-2** [comment]
This is not possible the server strips the anvil correctly and this is how the fix for signs works.
