### ISSUE TITLE
[1.12.2] Log Position Not Working

### ISSUE THREAD

**Issue by Nightinq** [ImpactDevelopment/ImpactIssues#1566]
Log Position does not work, upon enabling nothing occurs.

1. Go to Misc
2. Click on Log Position
3. Enable Show Names and Save Positions
4. Nothing occurs nor is anything saved

The toggle should tell the user the positions of players that have logged in his/her render distance, this does not occur and is therefore broken.

**Comment by LordVertice** [comment]
Same problem for me, 4.8.2

**Comment by MightyKnight** [comment]
#1621
