### ISSUE TITLE
It won't let me turn on antiafk using the bind command.

### ISSUE THREAD

**Issue by TeamDoodz** [ImpactDevelopment/ImpactIssues#1570]
What will it not let me bind a key to antiafk?

I have used the command: .bind antiafk g
And: .bind g antiafk

Why won't it work? I am not getting any error message, nothing appears in chat after using the command.

**Comment by VirxEC** [comment]
after you ran the command, did you try the keybind?

**Comment by berrely** [comment]
Have you actually pressed the button "G"?

**Comment by l1ving** [comment]
Closed as stale. Reopen if you can still reproduce this.
