### ISSUE TITLE
.chestpeek

### ISSUE THREAD

**Issue by VirxEC** [ImpactDevelopment/ImpactIssues#1572]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to see the contents of a chest that you're looking at without opening the chest.

**Describe the solution you'd like**
Add a command called .chestpeek that would let you look into the contents of a chest without opening the chest.

**Describe alternatives you've considered**
Make it a module instead of a command, but a command would be much better.

**Additional context**
No additional context.

**Comment by StijnSimons** [comment]
Iirc not possible :thinking:
