### ISSUE TITLE
[1.14] Nametags Tamed shows UUID, not name

### ISSUE THREAD

**Issue by HappyManCZ** [ImpactDevelopment/ImpactIssues#1573]
In Render, Nametags there is a thing called Tamed, it shows on tamed animals who owns it but by the release of 1.14.4 version of impact, it just says: Owned by : iefifijfejifejifeijfe(something like that)

![image](https://user-images.githubusercontent.com/54249959/63230556-7a60b680-c20e-11e9-8d6d-e9489b567087.png)

**Comment by Fuhsahd** [comment]
It looks like your UID, or the UID of whoever owns it.

**Comment by leijurv** [comment]
Yes. We only get the UUID of the owner, we ask mojang for their real username but sometimes that fails, in which case we just display the UUID.

**Comment by LeafHacker** [comment]
Does it always show the UUID in 1.14? If not does it happen any more often than it did in 1.12/1.13?

If this is unchanged from the previous version then it isn't a bug.

**Comment by HappyManCZ** [comment]
It happened few times in 1.13.2 but in 1.14.4 it happens way more

**Comment by LeafHacker** [comment]
Assuming that it does still show the player name sometimes I'm gonna assume this is either due to random variation, a change in your isp's network or some serverside changes. Closing for now.
