### ISSUE TITLE
alt manager not working send help

### ISSUE THREAD

**Issue by notzopac** [ImpactDevelopment/ImpactIssues#1582]
yes hi gamers the alt manager doesn't work even for premium accounts it doesn't work (might just be me idfk) but if someone can help pls do

- Impact Version:  1.12.2
- Using Optifine?  yes
- Using LiteLoader?  no
- Enabled mods:  none
- Operating System:  Mac OS high Sierra

**Comment by LeafHacker** [comment]
Steps to reproduce? Nightly version tested on? There's zero info here...

**Comment by x2xt-timeforacrusade** [comment]
oh sorry i am on the latest version of impact premium 4.8 nightly (on phone rn idk but its just the latest of every update it doesnt work) Some people say its just for show, the direct login doesnt work, putting an account in it doesnt work (it always says it has the wrong username or password)

**Comment by x2xt-timeforacrusade** [comment]
It might just be a bug for me I have no idea I also have tested it on forge, with optifine, without optifine and it still doesnt work

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
