### ISSUE TITLE
[1.14]

### ISSUE THREAD

**Issue by 11gea** [ImpactDevelopment/ImpactIssues#1583]
Schematics not working
Currently i can get everything ready for building but when using the .b build <build>, it says loading build or something like that and never starts.

Used obsidian Jesus statue from vid and followed steps from https://www.youtube.com/watch?v=r-E2f-IdPmc&t=187s, links of file in desc.
Then go create flat world and run .b build <name or build>

**Comment by ScanmanTM** [comment]
This isn't a bug, schematics can only be built in 1.12. You may close this.

**Comment by StijnSimons** [comment]
A copy of literally 3 issues.
