### ISSUE TITLE
Baritone Lines don't render with Optifine

### ISSUE THREAD

**Issue by wozniak** [ImpactDevelopment/ImpactIssues#1585]
**Describe the bug**
look at the title

**To Reproduce**
1. load up optifine impact
2. turn on a shader
3. use baritone

**Expected behavior**
lines render

**Screenshots**

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: 
- Operating System: Windows 10 64bit

</details>

**Comment by usereewrjrjeejr** [comment]
Turn off the shaderpack

**Comment by dominikaaaa** [comment]
Can't reproduce. Next time make an issue in the baritone repo for baritone related stuff.
