### ISSUE TITLE
IDK, but I'm pretty sure this isn't supposed to happen. (First time)

### ISSUE THREAD

**Issue by UsernameEXE** [ImpactDevelopment/ImpactIssues#1586]
I'm pretty sure it's better to just post the pic. here:
![Screenshot (7)](https://user-images.githubusercontent.com/54405145/63518368-e10bfb80-c4be-11e9-8e05-c0e34e754ac4.png)
Please notify me @trinity666 on discord

**Comment by StijnSimons** [comment]
1) update impact jesus
2) run the vanilla version first
