### ISSUE TITLE
Antihunger Bug

### ISSUE THREAD

**Issue by coolpvpv1** [ImpactDevelopment/ImpactIssues#1587]
Describe the bug
If you have nofall on packet mode and have antihunger mode on effective jump from a high distance then turn off antihunger and it damages you even if nofall is still on and i find this annoying on some anarchy servers

To Reproduce
1. Go to 'go to antihunger go on effective mode'
2. Click on 'go to nofall turn on packet mode jump from a high distance then turn off antihunger and it damages you even if nofalls still on '
3. Scroll down to ''

Expected behavior
i  expected it to do nothing and not damage me

- Impact Version:  4.7.3 for 1.12.2
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods: 
- Operating System:  windows 10 64 bit

**Comment by dominikaaaa** [comment]
that's a feature.
