### ISSUE TITLE
hypixel skyblock automine

### ISSUE THREAD

**Issue by Zak3334** [ImpactDevelopment/ImpactIssues#1588]
**Describe the bug**
yo guys i wrote the #blockstoavoidbreaking minecraft:cobblestone,minecraft:bedrock command so i dont mine cobblestone and bedrock in hypixel skyblock but it still mines it 

**To Reproduce**
1. Go to 'automine'
2. Click on 'enable it'
3. See error

**Expected behavior**
I expected it to only mine diamonds

 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Comment by Orinion** [comment]
try setting blockBreakAdditionalPenalty high, but it will still try to break blocks [below or above the goalblock in some conditions](https://github.com/cabaletta/baritone/issues/854)

**Comment by dominikaaaa** [comment]
Known bug in baritone
