### ISSUE TITLE
Impact premium not given on Forge edition

### ISSUE THREAD

**Issue by Exaflar** [ImpactDevelopment/ImpactIssues#1592]
I have Impact Premium and when i load up Impact donor edition (the nightly builds) i don't have Impact premium, and premium functions also don't work. But i am able to use the nightly builds. Help?

**Comment by LeafHacker** [comment]
Do you have optifine loaded as a forge mod too? Any other forge mods?

**Comment by leijurv** [comment]
Fixed in 4.8
