### ISSUE TITLE
Black screen when around elytras

### ISSUE THREAD

**Issue by N7NobodyCats** [ImpactDevelopment/ImpactIssues#1595]
**Describe the bug**
Black screen when people wearing elytras are nearby? i think its elytras at least, its the one thing that was constant in each instance that it occurred.

**To Reproduce**
go to a server with people wearing elytras and i guess the screen will go black. 

**Expected behavior**
to be able to see like normal i guess?

**Screenshots**

![2019-08-24_10 21 44](https://user-images.githubusercontent.com/54138400/63642650-53274080-c677-11e9-991a-4dbbe1cbcd97.png)

- Impact Version: 4.8 nightly for 1.14.4 <4.8.0-20190823-nightly>
- Using Optifine? No
- Enabled mods:  Anti Overlay, ESP(Shader), Nametags, Radar(Static), Storage ESP, Tracers, Anti Vanish, Auto Cheat, Inventory, No Fall(Packet), No Push, Auto Clicker, Criticals(Packet), Hitbox
- Operating System: Windows 10 64bit

details

started happening on this version(image below), when a staff/moderator on a server i was playing on was nearby wearing elytra,
![ss+(2019-08-24+at+11 54 30)](https://user-images.githubusercontent.com/54138400/63642613-a2b93c80-c676-11e9-9469-4ee604eb969e.jpg)

**Comment by TheCompieter** [comment]
yeah also have the same issue very anoying

**Comment by LeafHacker** [comment]
Can you test if this still occurs with a different ESP mode? ESP:Shader has been known to cause issues on some GPUs.

**Comment by OfficialThing** [comment]
This happens when you have no items in your hand.

**Comment by ZeroMemes** [comment]
Can we have additional system information? i.e.
- Pre-built PC? Laptop? If so, please provide model.
- CPU
- GPU (If applicable)

**Comment by ZeroMemes** [comment]
1 more thing, can you determine which module is causing the issue, you have multiple render-related modules enabled yet didn't specify which one could be disabled to prevent the issue, if any.

**Comment by OfficialThing** [comment]
A Lenovo Laptop, think it’s about 3 years old.
Don’t know the cpu
The gpu is an intel graphics 4000 (I feel like it might be that)
I think it might be an ESP module

**Comment by leijurv** [comment]
when you turn off esp, does the issue stop? lol

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
