### ISSUE TITLE
1.12.2 xray bug

### ISSUE THREAD

**Issue by NotAnEgirl** [ImpactDevelopment/ImpactIssues#1596]
So the bug is I press "X" and in the chat box it states
[Impact] Toggled XRAY [OFF]
[Impact] Invalid syntax provided! Use "help toggle" for syntax definitions. (Not enough arguments provided)
[Impact] Toggled XRAY [On]
And every time I press "X" it turns it off then back on again.

**To Reproduce**
So what I did was first went to macros and bound "X" to do .t xray and that worked besides the part it would but "xray" in chat. And I dont want it to say "xray" every time I press x. So i joined the discord and got somebody to help me (xpielordx#9848) and I was told to do stuff with the .bind xray x and thats when the "[Impact] Invalid syntax provided! Use "help toggle" for syntax definitions. (Not enough arguments provided)" started. At this point I tried changing the keybind from X to another key, which worked perfectly fine, but still after changing the bind when I press X it still has the same issue.

**Expected behavior**
Should toggle xray and say [Impact] Toggled XRAY [ON] or [Impact] Toggled XRAY [OFF]

**Screenshots**
![png](https://user-images.githubusercontent.com/54512940/63655784-960e1480-c75a-11e9-8485-5a78ad97c176.png)

- Impact Version: 4.7.3 For 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Crosshair+, Xray
- Operating System:Windows 10 64-bit

**Comment by leijurv** [comment]
Delete your macro and just bind xray in clickgui like a normal human being lmao

**Comment by WaffleTraits** [comment]
> Delete your macro and just bind xray in clickgui like a normal human being lmao

macros.json was empty on this user's system and the macro GUI showed no macros

**Comment by dominikaaaa** [comment]
Can't reproduce.
