### ISSUE TITLE
[1.14] Timestamp doesn't account for different timezones

### ISSUE THREAD

**Issue by AutismGaming228** [ImpactDevelopment/ImpactIssues#1598]
**Describe the bug**
Timestamp doesn't account for different timezones, for example I have GMT+4 yet the time in HUD is GMT+0.

**To Reproduce**
1. Enable "time" in HUD while having a different timezone

**Expected behavior**
Accurate time that accounts for timezones.

**Screenshots**
![Fy2TnNCs6d](https://user-images.githubusercontent.com/38699033/63806968-d40f6200-c92d-11e9-8c24-6417b20b2c39.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 20190826 nightly for 1.14.4 
- Using Optifine? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
whatever

**Comment by StijnSimons** [comment]
Works correct for me. Blocking timezone?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
