### ISSUE TITLE
[1.14] Scaffold is very loud for some reason

### ISSUE THREAD

**Issue by AutismGaming228** [ImpactDevelopment/ImpactIssues#1599]
**Describe the bug**
When you enable scaffold it creates very loud sounds for some reason.

**To Reproduce**
1. Enable scaffold.

**Expected behavior**
Working scaffold without earrape.

**Screenshots**
https://youtu.be/Nu9lN7qGIz4

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 20190826 nightly for 1.14.4 
- Using Optifine? No
- Enabled mods: Too much, please see in the video 
- Operating System: Windows 10 1903 build 64bit 

</details>

**Additional context**

**Comment by enderman2s** [comment]
This happens with scaffold because you have safe on. So until it can be fixed, you have to have safe off so you don't get earraped.

**Comment by ZeroMemes** [comment]
Will be fixed in 4.8.2.
