### ISSUE TITLE
Add search to ClickGUI

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactIssues#160]

**Comment by daggerdig** [comment]
this is a good idea!

**Comment by LeafHacker** [comment]
> The current click gui framework that we have in place [is] mega **aids** ~~to do anything more than mod searching on~~

**Comment by ZeroMemes** [comment]
> The current click gui framework that we have in place [is] mega **aids** to ~~do anything more than mod searching on~~

Very true

**Comment by ZeroMemes** [comment]
You hate to see it

**Comment by leijurv** [comment]
pasting what i wrote

Just an idea, not sure if this will actually happen.

The idea is when you open ClickGUI it functions as normal, but when you type normally (i.e. not in chat or in the process of setting a keybind) it will filter out modules that don't match what's typed so far. This could be in the form of removing them, or just darkening their text color. Perhaps it could also search for options? Or maybe it could even auto scroll each pane down to the first match?


imma maybe do this lol

**Comment by Zane4077** [comment]
Along side the search function, maybe the ability to make a quick menu of modules to use? To prevent the cgui from become to crowded, instead of a button to do so, maybe middle click on the mod?

**Comment by leijurv** [comment]
heres a prototype i whipped up https://youtu.be/HDjLLiAQay4

**Comment by SuperOP535** [comment]
ok now this is epic

**Comment by EvilSourcerer** [comment]
you should add aliases for search, for example, add an alias to Riding called EntitySpeed, or Scaffold as Bridge

**Comment by LeafHacker** [comment]
I'd rather track an aliase system as a separate issue

**Comment by LeafHacker** [comment]
> maybe the ability to make a quick menu of modules to use

@Zane4077 that's a suggestion in its own right, rather than hijacking this issue would you open it as a separate one? Thanks
