### ISSUE TITLE
Inventory Sort & Dump

### ISSUE THREAD

**Issue by hexxone** [ImpactDevelopment/ImpactIssues#1602]
**Is your feature request related to a problem? Please describe.**
When using Chest-Stealer or Moving Chests my Inventory is always a mess and hard to keep track of.

**Describe the solution you'd like**
I'd really appreciate a feature where I could Sort an Inventory (my Own & Chests) using a "makro" click (e.g. middle mouse button) or a small button like the "Steal" one.

Also a function where you could "Dump" your own whole inventory (or just useless items) into another open inventory would be really amazing. So you can pick up and store items faster.

**Describe alternatives you've considered**
In theory there are already Mods (forge) for this but these are mostly outdated and you would also have to wait for a new Impact forge release...

**Additional context**
My Idea is inspired by this mod: https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks
Which had the best sorting imo.

**Comment by Aaron2550** [comment]
9minecraft.net lol

**Comment by usereewrjrjeejr** [comment]
>9minecraft

 🤢

**Comment by 0-x-2-2** [comment]
9minecraft == bad
