### ISSUE TITLE
Put automatically death sethome

### ISSUE THREAD

**Issue by PixelHack13** [ImpactDevelopment/ImpactIssues#1603]
Hello
I died in server faction and I had an idea at that moment the
His will be good if he can sethome
automatically when we die (a death sethome)

**Comment by enderman2s** [comment]
If your using impact you can turn death coords on so you know the coords to path to. If not it would be a good idea.

**Comment by Thunder33345** [comment]
baritone should auto set death homes right?

**Comment by ScanmanTM** [comment]
.b goto death
