### ISSUE TITLE
Impact with liteloader on MultiMC

### ISSUE THREAD

**Issue by XPHonza** [ImpactDevelopment/ImpactIssues#1605]
I cannot find any json in it or tell liteloader to use the mixin version 0.7.11
help pls

**Comment by LeafHacker** [comment]
This isn't a support forum. This is an issue tracker. For tracking bugs that need fixing and features that need adding.

**Comment by XPHonza** [comment]
so there is a support forum?
like Brady himself?

**Comment by enderman2s** [comment]
It's called discord mboy

**Comment by XPHonza** [comment]
nope they didnt help

**Comment by enderman2s** [comment]
Then wait and don't be impatient. Discord is the only place where you can get support for this.

**Comment by XPHonza** [comment]
ok ill wait and try to repost my question so it can be seen
