### ISSUE TITLE
auto farm

### ISSUE THREAD

**Issue by youri123456** [ImpactDevelopment/ImpactIssues#1606]
hey if i want to autofarm just afk in my own wheet farm it will automaticly walk to other things like sugar cane, is there already a way to only farm wheet or otherways this is a suggestoin

**Comment by enderman2s** [comment]
You could've asked this on the discord server

**Comment by youri123456** [comment]
well is there already a way or not?

**Comment by enderman2s** [comment]
ask in #help in the server

**Comment by usereewrjrjeejr** [comment]
`.b mine wheat` might work

**Comment by enderman2s** [comment]
You would continually have to run that command because after all the all the wheat is mined it will stop so you would have to run the command when there is wheat.

**Comment by VirxEC** [comment]
same with farm. once there's nothing to farm it just stops.
