### ISSUE TITLE
.plugins doesn't work

### ISSUE THREAD

**Issue by SilencedFrost** [ImpactDevelopment/ImpactIssues#1607]
.Plugins doesnt work and it is LITERALLY MY SERVER HELP

1. Go to play.mumbojumbo.xyz
2. use .plugins

Expected it to say the plugins

- Impact Version: Latest
- Using Optifine? Yes
- Using LiteLoader? No
- Operating System: Windows 10 Pro 64bit

**Comment by VirxEC** [comment]
If it's ur server then just op urself and do /pl

**Comment by VirxEC** [comment]
actually u don't even have to op urself

**Comment by ScanmanTM** [comment]
What does the error say?

**Comment by Aaron2550** [comment]
I bet this is something absolutely normal and it doesn't work because the way impact checks for  plugins  is disabled on his server
