### ISSUE TITLE
 I cant get in boats or horses and my outer layer of my skin doesent work on servers but everything is fine on singleplayer its 1.12.2 

### ISSUE THREAD

**Issue by DemonicSchwalbe** [ImpactDevelopment/ImpactIssues#1608]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by enderman2s** [comment]
There is literally no info apart from the title.

**Comment by 0-x-2-2** [comment]
The skin layers can be toggled via skin customization settings.
