### ISSUE TITLE
Being able to put blocks on your head

### ISSUE THREAD

**Issue by ControllerData** [ImpactDevelopment/ImpactIssues#1610]
**Is your feature request related to a problem? Please describe.**
Putting blocks on your head is pretty cool, good for a utility mod like Impact

**Describe the solution you'd like**
Putting blocks on your head is possible in Vanilla Minecraft with a command, and Impact has Auto Armor so this has a possibility of working.

**Describe alternatives you've considered**
Items on your head might be hard so that might not be a feature.

**Additional context**
![image](https://user-images.githubusercontent.com/29762615/64078019-f7c30700-cca3-11e9-90b1-dcc884194fbe.png)

**Comment by usereewrjrjeejr** [comment]
No

**Comment by 0-x-2-2** [comment]
Not possible.
