### ISSUE TITLE
Add IRC to impact

### ISSUE THREAD

**Issue by enderman2s** [ImpactDevelopment/ImpactIssues#1611]
**Is your feature request related to a problem? Please describe.**
Adding IRC to impact would be great as other clients already have it.

**Describe the solution you'd like to see**
When implemented, force it upon everyone and put ads in it and the only people that can turn the ads and/or IRC are premium users.
**Describe alternatives you've considered**
Another thing is to make it a premium feature only.

**Additional context**
![Screenshot_20190902-112631_Discord](https://user-images.githubusercontent.com/54308774/64085214-b2223f00-cd74-11e9-9f52-f7c99210a0f8.jpg)

**Comment by SirEdwardthe4th** [comment]
I think IRC should have a mirrored feed on Discord that just allows you to talk in IRC from either in game or from the discord chat
edit: That might be a bad idea actually, given what happened last night in #help

**Comment by ScanmanTM** [comment]
Already suggested.
