### ISSUE TITLE
Speed Mode Boost Bug

### ISSUE THREAD

**Issue by coolpvpv1** [ImpactDevelopment/ImpactIssues#1612]
Describe the bug
if you have speed on boost mode then go on ice it will like launch you super fast forward idk why and this bug does happen on packed ice to
To Reproduce
1. Go to 'speed'
2. Click on 'modes until you go to boost'
3. Scroll down to ''

Expected behavior
i just expected it to move a little faster not make you go like 100 blocks per second

Screenshots
heres a video of the bug https://streamable.com/425xt

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.7.3 for 1.12.2
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods:  https://imgur.com/uRwZxNJ
- Operating System:  windows 10 64bit

</details>

Additional context
heres a video of the bug https://streamable.com/425xt this bug does happen on packed ice to

**Comment by usereewrjrjeejr** [comment]
High key OP

**Comment by coolpvpv1** [comment]
> High key OP

it flags you back on ncp so you cant go fast on ice at all and it makes you go like 200 blocks per second so you flag back by vanilla anticheat literally so its pretty bad and its not op lmao

**Comment by dominikaaaa** [comment]
not a bug
