### ISSUE TITLE
Baritone Bridging

### ISSUE THREAD

**Issue by PollastreGH** [ImpactDevelopment/ImpactIssues#1613]
I notice when Baritone goes across water it takes a while, so this is an improvement
I thought Baritone could use blocks to bridge across water if it had blocks
This would make baritone go across terrain much faster if it knew how to bridge.

**Comment by VirxEC** [comment]
This isn't something Impact can handle. This is a suggestion for Baritone, so please transfer this post to the Baritone github: https://github.com/cabaletta/baritone/issues
