### ISSUE TITLE
[1.14] No villager ESP

### ISSUE THREAD

**Issue by Quizitive** [ImpactDevelopment/ImpactIssues#1615]
**Describe the bug**
Villager doesn't gain ESP outline

**To Reproduce**
1. Spawn villager

**Expected behavior**
The villager does not gain a ESP outline

**Screenshots**
https://user-images.githubusercontent.com/54865168/64205409-e3c70300-ce65-11e9-999d-52c27f546eb9.png

 

- Impact Version: 4.8 nightly for 1.14.4 
- Using Optifine?  No
- Enabled mods: ESP
- Operating System: Win 10

**Comment by LeafHacker** [comment]
Villagers weren't being handled by our entity filters due to 1.14 changes, keep an eye out for any other un-target-able entities!
