### ISSUE TITLE
 A chat tag

### ISSUE THREAD

**Issue by hitleriscool** [ImpactDevelopment/ImpactIssues#1616]
A good feature would be a chat tag. Like adding a tag at the end of every message in chat that you send. Like in rusherhack and kami. Example: "Hey everyone | ᴵᵐᵖᵃᶜᵗ"

Another cool feature would be adding other chat things. Like adding > at the start of every message for greentext in some servers, or ` for bluetext.

And maybe chatspam with an interval?

**Comment by enderman2s** [comment]
Chatspam would be good, idk how first 2 suggestions would work.

**Comment by 0-x-2-2** [comment]
spam is cringe
