### ISSUE TITLE
Esp tweaks

### ISSUE THREAD

**Issue by DanCuber** [ImpactDevelopment/ImpactIssues#1630]
Tweak #1: make it so you can have custom esp color for different entity categories, e.g. red for hostile mobsx green for passive, idk blue for misc stuff like boats and so on (like in future and how it already works with tracers). 

Tweak #2: the ability to change the opacity and line thickness of the "box" mode esp.

**Comment by 0-x-2-2** [comment]
One suggestion per issue.
