### ISSUE TITLE
Optifine not working.

### ISSUE THREAD

**Issue by sapioit** [ImpactDevelopment/ImpactIssues#1632]
**Describe the bug**
Optifine not working. (By the way, the github wiki page on installing optifine is outdated, not working on 4.7.3.)

**To Reproduce**
1. Install 1.13.2-Impact_4.7.3-OptiFine_HD_U_E7 using the installer.
2. Launch Impact.
3. MC + Impact loads, Optifine does not.
4. Check the wiki page on how to add Optifine to Impact, and see it doesn't work.

**Expected behavior**
Optifine loading, or a working tutorial to manually install it.

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.7.3
- Using Optifine? OptiFine_HD_U_E7
- Using LiteLoader? Negative
- Enabled mods: Irelevant
- Operating System: Windows 7 Ultimate

</details>

**Additional context**
Please also fix the github wiki page.

**Comment by FayneAldan** [comment]
I tried the same version of Minecraft, Optifine, and Impact and it worked fine. What makes you believe Optifine isn't working? Do you not see the additional Optifine options in video settings?

**Comment by sapioit** [comment]
Not only do I not see the Optifine options, but also cannot zoom (using the C key).

**Comment by S-B99** [comment]
Hi, please provide a log and more information about when this issue is caused if it's still happening.
