### ISSUE TITLE
SFW (Safe for work) mod

### ISSUE THREAD

**Issue by smacpats** [ImpactDevelopment/ImpactIssues#1633]
**Is your feature request related to a problem? Please describe.**
Not a problem with Impact specifically, but when playing on Anarchy servers in a professional environment (school/work), it can be hard to hide profane language and offensive content. Many of these servers include Withers and server descriptions, and I would like to censor these. 

**Describe the solution you'd like**
"Safe for Work/SFW" render mod, would disable wither nametags and server descriptions/pictures. It could also censor chat while still allowing you to type and use commands, but this can already be accomplished by lowering Chat opacity in vanilla chat settings. 

**Describe alternatives you've considered**
Using direct connect and staying away from spawn.

**Additional context**
Possible before and after for server description being censored (I intentionally chose a less offensive example for this):
![What censoring the Server description could look like](https://user-images.githubusercontent.com/37053049/64642594-b7b6ff00-d3dc-11e9-8747-8ed62dfefe88.png)
What censoring wither nametags could look like:
![What censoring nametags could look like](https://user-images.githubusercontent.com/37053049/64642634-cdc4bf80-d3dc-11e9-8477-bafab5d0e5df.png)

**Comment by enderman2s** [comment]
Or you can just not play on anarchy servers during school/work.

**Comment by leijurv** [comment]
you can use anti overlay to remove the wither boss bars

just use direct connect for the motd censorship lmao
