### ISSUE TITLE
[1.14] Search ESP Shaking.

### ISSUE THREAD

**Issue by Gitc0s** [ImpactDevelopment/ImpactIssues#1634]
**Search module ESP shaking.** 

**To Reproduce**

1. Enable Search Function
2. Select any block
3. Teleport to 1,000,000 x, z cords. **(high cords causes this)**

**Expected behavior**
Search ESP should function just like Chest ESP. Where it stays still on the exact block location.

**Screenshots**
Video. 
https://cdn.discordapp.com/attachments/208753003996512258/621054342341853194/Desktop_2019.09.10_-_19.40.46.01.webm

<details> 
  <summary><strong>Additional Client Info</strong></summary>

- Impact Version: Latest (1.14.4)
- Using Optifine? : No
- Enabled mods: Name Tags, ESP, Search, Chest ESP.
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
@leijurv was able to reproduce this to a lesser extent at ~10k, assigning him for now

**Comment by leijurv** [comment]
Fixed
