### ISSUE TITLE
[1.14_04092019] Default Backgrounds in Impact Tabs not drawed properly

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactIssues#1645]
![image](https://user-images.githubusercontent.com/25800857/64805740-0b1e7e00-d592-11e9-81ac-1f134dd98f13.png)
![image](https://user-images.githubusercontent.com/25800857/64805756-1376b900-d592-11e9-8026-291a4209e250.png)
![image](https://user-images.githubusercontent.com/25800857/64805775-1e314e00-d592-11e9-9125-0ff4a4bb9856.png)
these 3 have cutoff default backgrounds
![image](https://user-images.githubusercontent.com/25800857/64805805-2ee1c400-d592-11e9-9fbe-d46b065e4fa0.png)
however the macro tab doesnt.

**Comment by LeafHacker** [comment]
For some reason minecraft's list gui element draws the background texture, not the default-background (which is sometimes transparent). AFAIK it shouldn't need to draw the background but mojang are hacky so :shrug:

Will probably just force the opaque background on those GUIs :-(

**Comment by LeafHacker** [comment]
Turns out the mappings had changed a little, the method to draw the opaque dirt background has a new name. Fixed
