### ISSUE TITLE
automine 

### ISSUE THREAD

**Issue by Marathonman123** [ImpactDevelopment/ImpactIssues#1648]
i try automining  it keeps getting stuck i have to keep interviening i dint understand whats causing it to stop i thought it was other blocks but ill try and mine a block when it gets stuck and it just places it back and stays where it is. ill change the ores and that doesnt affect the AI it still gets stuck with its minepath in the red outline set

**Comment by StijnSimons** [comment]
can anyone make a translated version of this

**Comment by enderman2s** [comment]
Let's see. something something something im a idiot who cant fill in the form and instead posts this cancer of a issue something something something include more info and make it more clear next time by maybe actually filling out the template

**Comment by sapioit** [comment]
Translation: automine breaks block, but it gets stuck and places it back where it was, and stays there. Irrelevant of the target of the automine. The path is still shown in red.
@StijnSimons

**Comment by berrely** [comment]
Possibly related to [Baritone 161](https://github.com/cabaletta/baritone/issues/161).

**Comment by l1ving** [comment]
There isn't enough information here to reproduce it anyways
