### ISSUE TITLE
Feature Request: Mobspawn ESP

### ISSUE THREAD

**Issue by Verifirs** [ImpactDevelopment/ImpactIssues#1649]
A simple implementation of Mobspawn ESP highlights blocks that are below light level 7, letting the player know that the block is vulnerable to mobs spawning on top of it. This makes base building easier, especially with larger rooms in which gaps in lighting can be easily overlooked.

**Comment by 0-x-2-2** [comment]
"This code is licensed under the GNU General Public License v3. You can only use this code in open-source clients that you release under the same license! Using it in closed-source/proprietary clients is not allowed!"

**Comment by S-B99** [comment]
Duplicate of #1597
