### ISSUE TITLE
Biome Name option under HUD

### ISSUE THREAD

**Issue by sapioit** [ImpactDevelopment/ImpactIssues#1650]
**Is your feature request related to a problem? Please describe.**
Not really, but it would be easier to not have to press F3 and deal with lots of visual clutter to see the biome you're in.

**Describe the solution you'd like**
A checkable option under HUD (next to TPS, Ping and FPS, prefferably before/above the list of mobs nearby) which to show us the name of the biome we're in. Very useful for squid farms and building (due to the color/hue changes of the biomes)

**Describe alternatives you've considered**
Walking with F3 menu on, dealing with all that visual clutter, and livestreamers and youtubers having to cover even more of their screen, because the coords are shown in 2 different positions (once in the F3 menu, and once by Impact).

**Comment by ZeroMemes** [comment]
Added in 4.8

**Comment by sapioit** [comment]
Thanks!

**Comment by sapioit** [comment]
Estimated Time Of Arival for MC 1.13.2 Impact 4.8?

**Comment by 0-x-2-2** [comment]
no
