### ISSUE TITLE
Speed boost not working on 2b2t

### ISSUE THREAD

**Issue by Teddydog11** [ImpactDevelopment/ImpactIssues#1653]
**Describe the bug**
Speed boost isn't working for some reason

**To Reproduce**
1. Go to https://www.youtube.com/watch?v=KQvi-1NIyU4&feature=youtu.be
2. Click on play
3. See error

**Expected behavior**
It not to rubber band me back every 2 seconds

**Comment by Coldram3n** [comment]
@Teddydog11 This isn't a bug, Hause disabled speedhacks recently.
