### ISSUE TITLE
safewalk step down

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactIssues#1657]
**Is your feature request related to a problem? Please describe.**
safe walk keeps me from falling off edges but i have to jump to get down one block

**Describe the solution you'd like**
a setting that will allow you to descend one or two blocks with safewalk on, makes stair travel with safewalk easier. preferably you can toggle the distance you can descend

**Describe alternatives you've considered**
turning it off And falling off cuz i have the hand eye coordination of stephen hawkings

**Additional context**
buy rusher hacks

**Comment by dominikaaaa** [comment]
#836
