### ISSUE TITLE
schematica integration

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactIssues#1658]
**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
a full integration of schematica into impact.

**Describe alternatives you've considered**
installing it manually and failing lol

**Additional context**
add it or i cry

**Comment by leijurv** [comment]
https://discordapp.com/channels/208753003996512258/378646935302701070/614274322596364298
