### ISSUE TITLE
Rename Search module to BlockESP or something

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactIssues#1663]
**Is your feature request related to a problem? Please describe.**
Search is a misleading name for a Block ESP/Block tracer module. Especially when out of context in the Impact menu or the `.search` command.

**Describe the solution you'd like**
A better name; perhaps BlockESP

**Describe alternatives you've considered**
- BlockSearch
- BlockHighlighter
- Highlighter
- BlockFilter

**Comment by leijurv** [comment]
lmao yeah

**Comment by EvilSourcerer** [comment]
BlockFinder

**Comment by enderman2s** [comment]
Change it from Search to Search

**Comment by StijnSimons** [comment]
BlockRadar for cool guys

**Comment by LordMZTE** [comment]
> 
> 
> Change it from Search to Search

yeah you are right, search doesnt really explain what it does, so i think search would be better

**Comment by JustAnOkapi** [comment]
Originally I was lost and thought that there was no BlockESP until I realized that it was named search.

**Comment by LeafHacker** [comment]
> BlockRadar for cool guys

What about the un-cool guys?

**Comment by enderman2s** [comment]
> > BlockRadar for cool guys
> 
> What about the un-cool guys?

Call it search

**Comment by 0-x-2-2** [comment]
Search 😎

**Comment by mrphax0r** [comment]
BlockESP

**Comment by rebane2001** [comment]
Better change that name from w*rst to best

**Comment by dominikaaaa** [comment]
i'm closing this as won't fix, due to inactivity and it being a dumb idea. everybody knows what search is these days, all clients call it search, and I even kept getting asked to add "search like impact does" until I added it to blue.
