### ISSUE TITLE
[1.14] 0.8 Mixin - file contents differ from what was expected.

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactIssues#1666]
**Version - 20190916**

>Failed to download file, the file contents differ from what was expected.
Name: mixin-0.8-SNAPSHOT.jar
URL: https://jitpack.io/com/github/spongepowered/mixin/0.8-SNAPSHOT/mixin-0.8-SNAPSHOT.jar
Filename on disk: 896c-d535-1664-04cc
Path: C:\Users\S\AppData\Local\Temp\896c-d535-1664-04cc
Exists: File

Additional information: When combining it with optifine, only optifine loads.

**Comment by LeafHacker** [comment]
My bad, I used a "moving target" version, so the mixin 0.8 you're downloading is different to the mixin 0.8 the installer expects. Should be able to fix this by changing to a specific build reference.

**Comment by LeafHacker** [comment]
@leijurv has fixed this for future nighties by targeting a [specific](https://github.com/SpongePowered/Mixin/commit/d28607b86a3241d4314ef8cfa96880fce68da764) mixin commit, so closing. We could probably fix the current nigtly but it isn't worth the effort when it'll be replaced in 7hrs
