### ISSUE TITLE
[1.14] Crash when join a specific server

### ISSUE THREAD

**Issue by ArtoxFR** [ImpactDevelopment/ImpactIssues#1667]
**Describe the bug**
On only one server, i crash when trying to join

**To Reproduce**
Join the server

**Expected behavior**
Acces to the server lol

**Screenshots**
http://prntscr.com/p7g6df

<details> 
  <summary><strong>Game output</strong></summary>
 

```
ERREUR
Le jeu a cessé de fonctionner
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://pastebin.com/D1GeMX4c

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4 20190915 
- Using Optifine? No 
- Enabled mods: No one 
- Operating System: Windows 10 Pro 64bit 

</details>

**Additional context**

**Comment by leijurv** [comment]
What server?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
