### ISSUE TITLE
Headless client mode - Easily use multiple accounts

### ISSUE THREAD

**Issue by Fryke** [ImpactDevelopment/ImpactIssues#1670]
**Is your feature request related to a problem? Please describe.**
As of recent I've tried to use multiple accounts to send around a server, this works for only it takes a lot of resources of the PC and is quite cluttered. 

**Describe the solution you'd like**
I would like to see a headless client so the game does not use as many resources with multiple accounts. But leave the command line to use the commands and or talk.

**Describe alternatives you've considered**
A tool to send multiple commands to all currently running accounts would be a great help too, kind of linking up accounts with the same commands

**Additional context**
This would be great to gather resources on multiple accounts and speed up the process of gearing.

**Comment by 0-x-2-2** [comment]
https://github.com/ORelio/Minecraft-Console-Client
