### ISSUE TITLE
[1.14]

### ISSUE THREAD

**Issue by LilSizzurp** [ImpactDevelopment/ImpactIssues#1672]
**Describe the bug**
Every plugin name has the first letter remove (eg. Essentials -> ssentials, Bukkit -> ukkit)

**To Reproduce**
1. Go on a server
2. Open chat
3. Type ".plugins"

**Expected behavior**
Should show a list of plugins and their full name

**Screenshots**
<img src="https://i.imgur.com/bWsqa6s.png">

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4 20190918
- Using Optifine? Yes
- Enabled mods: Irrelevant (happens no matter what mods are on)
- Operating System: Ubuntu 19.04

</details>

**Comment by 0-x-2-2** [comment]
#1375
