### ISSUE TITLE
Having a .invsee command like wurst.

### ISSUE THREAD

**Issue by pizzahaat** [ImpactDevelopment/ImpactIssues#1674]
Im always frustrated when I have to go to wurst (its gay as hell) and i have to steal some poor guys armor.

I suggest that the player could see another players inv with a .invsee command.

I normally go to wurst and do it, but its just shameful using a _shitclient_.

**Comment by usereewrjrjeejr** [comment]
No

**Comment by pizzahaat** [comment]
y

**Comment by mrphax0r** [comment]
Dupe of #1408 .

**Comment by pizzahaat** [comment]
k
