### ISSUE TITLE
Make SelfDestruct copy the Impact folder to the first Hard drive it finds.

### ISSUE THREAD

**Issue by mrphax0r** [ImpactDevelopment/ImpactIssues#1675]
**Is your feature request related to a problem? Please describe.**
If you were to use SelfDestruct in a critical situation/by accident, you would have to reconfigure Impact.
**Describe the solution you'd like**
Copying the Impact folder to any hard drive to prevent data loss.

**Additional context**
Please

**Comment by StijnSimons** [comment]
I don't see the point in this as it can still be found in various ways.

**Comment by LeafHacker** [comment]
SelfDestruct isn't intended to modify the filesystem in an way. All it does is _turn off_ Impact.

> you would have to reconfigure Impact

If this is true then it is a bug (self destruct isn't intended to _change_ anything persistently). Please report that separately.
