### ISSUE TITLE
Waypoint ESP (Not sure what to call this)

### ISSUE THREAD

**Issue by BourbonCrow** [ImpactDevelopment/ImpactIssues#1676]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
able to track to your last death or custom location set by command ofc with a toggle module. image example below. to help you navigate "solo" without the help of baritone, cause it might be more efficient to run there alone like flying with Elytra for example 

![waypointESP](https://user-images.githubusercontent.com/6895650/65348412-6a5b3e80-dbe1-11e9-94ab-3f4ea766461d.png)

**Comment by BourbonCrow** [comment]
dont mind my scuffed ms paint job :D

**Comment by Hexxonite** [comment]
+ this way you had a way to show "saved" waypoints

**Comment by VolantTheFox** [comment]
+1 please add, would make it a step closer to not needing forge/a minimap

**Comment by ScanmanTM** [comment]
Already suggested.
