### ISSUE TITLE
Auto walk keeps toggling while in freecam (its not on the same keybind)

### ISSUE THREAD

**Issue by some1ongithub** [ImpactDevelopment/ImpactIssues#1679]
When you activate auto walk while in freecam it is always on when you enable freecam whether you disabled auto walk before or not.

- Impact Version: 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Freecam, (Auto walk)
- Operating System: Windows 10 64 bit

**Comment by ThebesAndSound** [comment]
i get this too

**Comment by jebthedev** [comment]
Yes! I also have this problem. Does anyone have a temporary fix? I can't find one.

**Comment by leijurv** [comment]
Fixed by https://github.com/ImpactDevelopment/Impact/commit/4ceea38769f724e801a10e771000bbd006862a2b for 4.9
