### ISSUE TITLE
[1.14.4] Game crash

### ISSUE THREAD

**Issue by N7NobodyCats** [ImpactDevelopment/ImpactIssues#1681]
**Describe the bug**
game crashes when im trying to get in a game, it seems to happen only after ive re-setup my preferred settings/keybinds. idk what the bug is, but it only started happening in the nightly-20190920 (that was the one i used) i went to the latest and got same results nightly-20190923 

**To Reproduce**
1. Go to a server from your server list
2. Click on join
3. wait for "joining world..."
4. See "saving world" and then crash

**Expected behavior**
no crash without having to remove impact folder and re-setup settings.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[crash-2019-09-24_00.28.20-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/3645836/crash-2019-09-24_00.28.20-client.txt)

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 nightly for 1.14.4 impact-20190923
- Using Optifine? no
- Enabled mods: tracers, radar, esp, no push, auto cheat, 
- Operating System: Windows 10 64bit

</details>

**Additional context**

**Comment by leijurv** [comment]
`Launched Version: 1.14.4-Impact_4.8.0-20190823-nightly`

update.

**Comment by leijurv** [comment]
that's 20190823 not 20190923

**Comment by leijurv** [comment]
stack traces that old can't be reversed xD
