### ISSUE TITLE
random fun modules

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactIssues#1687]
**Is your feature request related to a problem?**

**Describe the solution you'd like**
some random modules for fun, like a spinner that makes you spin around fast while still being able to walk, no head, would render your head in your body, a bedaura cuz why not. just some little things that would add a bit of flair. 

**Describe alternatives you've considered**
other clients

**Additional context**
ik it's Multiple features in one post, but each one is so minor and small i might as well throw em together

**Comment by ScanmanTM** [comment]
bedaura - Minigame -> breaker
spinner - Maybe anti-aim [makes your head move]
