### ISSUE TITLE
peek+

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactIssues#1688]
**Is your feature request related to a problem? Please describe.**
some things you can't peek into without wiping illegal items

**Describe the solution you'd like**
The ability to use peek on chests, item frames and anything used for storage that you wouldn't normally be able to use peek on

**Describe alternatives you've considered**
inventory+ with secret close

**Additional context**
 add it pls

**Comment by 0-x-2-2** [comment]
You don't get sent data from chests till you open it.
