### ISSUE TITLE
Squids not detected by ESP or Tracers

### ISSUE THREAD

**Issue by DyonR** [ImpactDevelopment/ImpactIssues#1689]
**Describe the bug**
Squids are not outlined by ESP when ESP is enabled.
Squids do not have a tracer going towards them when tracers are enabled.

**To Reproduce**
1. Enable ESP and Tracers with passive mobs on.
2. Find Squid.
3. No outline or tracer.

**Expected behavior**
A squid should have an outline around his model and should have a tracer going towards him.

**Screenshots**
https://i.imgur.com/E8KsQ0O.png

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 1.1.4.4-Impact-nightly-20190925
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: ESP (shader), Tracers

</details>

**Comment by DyonR** [comment]
Alright, I just checked in on 1.12.2 (Impact 4.7.3) and the issues does not exist in there.
I am not gonna test each version to see in version this bug impacts, but in 1.14.4 it exists for sure.

**Comment by LeafHacker** [comment]
Affects squid and dolphins in 1.13+
