### ISSUE TITLE
Build option in baritone "loads" endlessly

### ISSUE THREAD

**Issue by Mefiu-de** [ImpactDevelopment/ImpactIssues#1691]
**Describe the bug**
When i type in game .b build (something)
it loads endlessly yes i have the required blocks

**Screenshots**
https://ibb.co/SnGfXwY

Loading 'redeemer.schematic' to build from origin BlockPos(x,y,z)

 

  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.13.2 4.7.3(latest)
- Using Optifine?:  No 
- Using LiteLoader?:  No 
- Enabled mods: None
- Operating System: Windows 10 64bit

**Comment by ThebesAndSound** [comment]
you don't have any throwaway blocks in your hotbar

**Comment by Mefiu-de** [comment]
> you don't have any throwaway blocks in your hotbar

i have

**Comment by ThebesAndSound** [comment]
not in the screenshot you dont

**Comment by Mefiu-de** [comment]
> not in the screenshot you dont, also i dont think building works in 1.13 so it could be that

on discord they said it works on every version

**Comment by ThebesAndSound** [comment]
try building something different that a giant statue when you are obviously new to this

**Comment by Mefiu-de** [comment]
> try building something different that a giant statue when you are obviously new to this

but when this doesnt work anything else wont too right?

**Comment by ThebesAndSound** [comment]
depends on the schematic and your settings, some schematics if they are not optimised won't work, if you are trying to build that jesus statue without changing any settings i can promise you baritone will not be able to build it on any version

**Comment by Mefiu-de** [comment]
> depends on the schematic and your settings, some schematics if they are not optimised won't work, if you are trying to build that jesus statue without changing any settings i can promise you baritone will not be able to build it on any version

so what do i have to do

**Comment by ThebesAndSound** [comment]
make a schematic of a single block, and try to #build that

**Comment by Mefiu-de** [comment]
> make a schematic of a single block, and try to #build that

alright and how do  i make schematics

**Comment by LeafHacker** [comment]
building schematics only works on 1.12.2. This is a [baritone](/cabaletta/baritone/issues) issue not an impact issue.
