### ISSUE TITLE
versions below 1.12.2 doesnt work for me

### ISSUE THREAD

**Issue by Mefiu-de** [ImpactDevelopment/ImpactIssues#1693]
https://ibb.co/SV1tnpv
https://ibb.co/5YcwPpr
https://ibb.co/G9dKZVd
all what happens is on screenshoots 
so i click play it loads  minecraft doesnt open up and im still at launcher
version 1.13.2 works

**Comment by ScanmanTM** [comment]
Impact doesn't really support cracked launchers, go buy the game.
