### ISSUE TITLE
Minestrike Ignore smoke broken

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactIssues#1701]
**Describe the bug**
As the title says: Minestrike Ignore Smoke option doesn't work in 4.7 build

**To Reproduce**
1. Minestrike lobby
2 . Throw smoke
3. Have enemy on opposite side or in smoke
4. Toggle ignore smoke on
5. Toggle Minestrike on

**Expected behavior**
Should hit targets through smoke like in previous versions.
 

- Impact Version: 4.7 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Minestrike
- Operating System: Windows 10 64bit

</details>

**Comment by dominikaaaa** [comment]
Closed in favor of #1900
