### ISSUE TITLE
Minestrike bone scan broken

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactIssues#1702]
**Describe the bug**
Bone scan not targeting players when bone it only partially shown onto of a slab or similiar hiding

**To Reproduce**
1. Enemy player have only partially showing head or feet or arms from behind blocks
2. Turn Minestrike on
3. Won't target them

**Expected behavior**
Should target players even when only partial body parts are showing especially when head scan is not working with a head partially blocked by a slab because the enemy player would still be bale to hit you.
 

- Impact Version: 4.7 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Minestrike
- Operating System: Windows 10 64bit

**Comment by dominikaaaa** [comment]
Closed in favor of #1990
