### ISSUE TITLE
Item Durability HUD Widget

### ISSUE THREAD

**Issue by Raulsack69** [ImpactDevelopment/ImpactIssues#1711]
**Is your feature request related to a problem? Please describe.**
Feature is not related to any problem.

**Describe the solution you'd like**
Similar to Future Client's "TrueDurability" module, it would show the durability value of the selected tool in the corner of the screen (or perhaps the tooltip) when enabled.

**Describe alternatives you've considered**
Pressing F3 + H to show advanced tooltips, ignoring all the redundant data and only being able to see the durability of a tool when below the default maximum and only after the tool is damaged. Live with the fact that you can never see the true value of "unbreakable" tools who have a durability value much larger than normal.

**Additional context**
None.

**Comment by SentinelMKX** [comment]
![image](https://user-images.githubusercontent.com/22961592/66259976-96b5b400-e7b8-11e9-8050-fc4606896ae5.png)

**Comment by enderman2s** [comment]
That's for the mouse over tooltip, he wants it on the HUD.

**Comment by SentinelMKX** [comment]
> (or perhaps the tooltip)

**Comment by LeafHacker** [comment]
> That's for the mouse over tooltip, he wants it on the HUD.

The issue specifically states `(or perhaps the tooltip)` so closing this as already added.

**Comment by Raulsack69** [comment]
Yes, I didn't realize this feature already existed. My bad, keep up the good work!
