### ISSUE TITLE
Barritone Bucket Falls Issue: Waterloggable Blocks

### ISSUE THREAD

**Issue by mrmysterious33** [ImpactDevelopment/ImpactIssues#1712]
Baritone bucket falls on waterloggable blocks doesn't work. Rather than the water being placed where baritone intends (on top of the waterloggable block), the water ends up being placed **inside** the block, usually resulting in the death of the player, if the fall was far enough. Hopefully you guys can fix this so that either a: baritone avoids waterloggable blocks for bucket falls, or b: baritone glitches the system and places the water _on top_ of the block no matter what type of block it may be.

- Impact Version: 4.8 nightly for 1.14.4  20191005
- Using Optifine?  Not sure
- Enabled mods:  None; I just used the '.goto y' command
- Operating System:  Windows 10 64bit

**Comment by leijurv** [comment]
Thank you for the report. Can you file this at https://github.com/cabaletta/baritone/issues/ please?

Thanks!
