### ISSUE TITLE
1.13.2 xray only showing some xray blocks, and only some faces of them

### ISSUE THREAD

**Issue by chapsu** [ImpactDevelopment/ImpactIssues#1714]
![image](https://user-images.githubusercontent.com/46359113/66356949-b4516c00-e9b8-11e9-9096-b8425a16b81f.png)

example image of the issue^^

To reproduce:
enable xray

Expected Behaviour:
should work how xrays normally do, in showing all the blocks that are currently rendered and selected in the xray menu

Screenshots:
see above

impact version 4.7.3 for 1.13.2
using optifine
not using liteloader
enabled mods:
criticals, enchant color, anti overlay, storage esp, inventorywalk, no slow, entityspeed, sprint, light, and xray
operating system: windows 10 x64

**Comment by enderman2s** [comment]
dont use optifine
