### ISSUE TITLE
ERROR: Game Crash all versions (with and without Optifine)

### ISSUE THREAD

**Issue by dinkzzzz** [ImpactDevelopment/ImpactIssues#1718]
It has made playing the game with Impact nearly unusable with multiple crashes happening while loading into a server.

![image](https://user-images.githubusercontent.com/56366697/66514269-c7dcff80-eaaa-11e9-8d3a-77d658287841.png)

**Comment by leijurv** [comment]
Need crash log including stack trace and specific version of impact

**Comment by dinkzzzz** [comment]
`---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 10/9/19 3:44 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at dsa.handler$zzg000$preRenderEntity(EntityRendererManager.java:650)
	at dsa.a(EntityRendererManager.java:422)
	at dsa.a(EntityRendererManager.java:402)
	at dng.a(WorldRenderer.java:798)
	at dnc.b(GameRenderer.java:1207)
	at dnc.a(GameRenderer.java:1032)
	at dnc.a(GameRenderer.java:792)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dsa.handler$zzg000$preRenderEntity(EntityRendererManager.java:650)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (dmq)
	Entity ID: 13326151
	Entity Name: Paularomga
	Entity's Exact location: 0.50, 65.50, -3.50
	Entity's Block location: World: (0,65,-4), Chunk: (at 0,4,12 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: dwn@307f6602
	Location: 0.00,-1.62,0.00 - World: (0,-2,0), Chunk: (at 0,-1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -180.0
	Delta: 0.37995785
Stacktrace:
	at dsa.a(EntityRendererManager.java:422)
	at dsa.a(EntityRendererManager.java:402)
	at dng.a(WorldRenderer.java:798)
	at dnc.b(GameRenderer.java:1207)
	at dnc.a(GameRenderer.java:1032)

-- Affected level --
Details:
	All players: 8 total; [dmp['jojorobert1'/5817, l='MpServer', x=0.50, y=65.50, z=-3.50], dmq['Paularomga'/13326151, l='MpServer', x=0.50, y=65.50, z=-3.50], dmq['socialisinq'/13214581, l='MpServer', x=0.97, y=65.88, z=-10.91], dmq['FullSendBro'/12374568, l='MpServer', x=-10.69, y=66.16, z=-7.44], dmq['Fanashiess'/13293662, l='MpServer', x=-0.94, y=65.00, z=-13.53], dmq['chrislaban'/5535499, l='MpServer', x=-9.47, y=65.00, z=-10.91], dmq['Laabum'/12818625, l='MpServer', x=-1.91, y=65.00, z=-21.97], dmq['Biri_Biri'/13288779, l='MpServer', x=7.53, y=66.88, z=-25.47]]
	Chunk stats: Client Chunk Cache: 18225, 14
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,65,-4), Chunk: (at 0,4,12 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 313771565 game time, 315605839 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: TacoSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(ClientWorld.java:574)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:425)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 670237952 bytes (639 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_nightly-20191008-OptiFine_HD_U_F3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor `

Versions it happens on both of them tested with and without Optifine: "Vanilla; 1.14.4; nightly-20191008" as well as "Vanilla; 1.12.2; 4.7.3"

**Comment by leijurv** [comment]
What's the server (if public)?

**Comment by leijurv** [comment]
also can you send a screenshot of what modules are enabled?

**Comment by leijurv** [comment]
Is this instant on join, every time?

**Comment by dinkzzzz** [comment]
It happens on multiple servers on that is notable would be mc-central, but it happens on many others as well, it could be working fine one second then as soon as I render a new world like going back to hub or going to nether it'll crash again.

**Comment by dinkzzzz** [comment]
![image](https://user-images.githubusercontent.com/56366697/66519314-155e6a00-eab5-11e9-8cc5-36a310a1d209.png)

typically this is all i have on unless playing on singleplayer or 2b2t

**Comment by leijurv** [comment]
try turning off chams, or setting it to a mode that is neither Texture nor Solid. does that make it stop crashing?

**Comment by dinkzzzz** [comment]
~5mins of testing and it seems like that did the trick :) (usually crashes within a minute.) will update if it occurs again

**Comment by leijurv** [comment]
Hm. I'm on mccentral.org with chams texture on, but no crashes. Thanks for narrowing that down though...

**Comment by dinkzzzz** [comment]
Maybe something to do with my setup that I am unaware of.. did fix it though, thanks man

**Comment by leijurv** [comment]
Are you sure that it crashes specifically on 1.14, with chams, but without optifine?

**Comment by dinkzzzz** [comment]
it was crashing on 1.12.2 and 1.14.4 with and without optifine, for 1.12.2 i was using the 4.7.3 build and for 1.14.4 i was using the nightly build of october8

**Comment by leijurv** [comment]
hm.

if you're willing, could you load it up on 1.14.4 without optifine, with the modules in the settings that made it crash (i.e. chams enabled), then do `.preset save debugging` then send on here the file `minecraft/Impact/presets/debugging.json` (so i can run with your ExAcT settings)

**Comment by dinkzzzz** [comment]
https://mega.nz/#!xCwHwKJB!5X8Khtbspz2fSQz0COsKU9WPqXayhl5SPmyZRB3_Nkg
-
-
-
Just tested once again with and without, and it was definitely due to the chams being textured. Seemed when I joined me and my buddies multiplayer survival server with no one on it doesn't crash but as soon as I join a server and it renders the player models it does. Sorry for the late reply

**Comment by dominikaaaa** [comment]
Can't reproduce this in latest. Closing as stale.
