### ISSUE TITLE
Cannot move cursor while crouching

### ISSUE THREAD

**Issue by tylerr147** [ImpactDevelopment/ImpactIssues#1719]
**Describe the bug**
When crouching, I can't look around.

**To Reproduce**
1. Open game
2. Load world
3. Crouch
4. Attempt to look around

**Expected behavior**
Should be able to look around while crouching

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.7.3-1.13.2
- Using Optifine? I don't know, whatever the default is
- Using LiteLoader? I don't know what that is, so I'm assuming no?
- Enabled mods: {
    "Criticals"
    "Anti Desync"
    "Anti Cheat"
    "Anti Hunger"
    "Sprint"
    "Breadcrumbs"
    "Chams"
    "ClickGUI"
    "Crosshair+"
    "ESP"
    "HUD"
    "Light"
    "Main Menu"
    "Nametags"
    "Radar"
    "Storage ESP"
    "Trajectories"
}
- Operating System: Windows 10 64-bit

</details>

**Comment by dominikaaaa** [comment]
don't bind it to left alt, or disable freelook
