### ISSUE TITLE
[1.14] Alt manager (menus like friends manager) not clickable, freecam choppy, X-ray broken with optifine

### ISSUE THREAD

**Issue by Yertled** [ImpactDevelopment/ImpactIssues#1720]
**Describe the bug**
When I open the Alt manager, the top login is selected, and I can't change it no matter which one I click on or where I click.
Import / Export button doesnt do anything either when clicked.
Opening Alt Manager from In-Game bugs out the UI, will attach picture.

When freecamming, it's no longer smooth like earlier versions. It's super choppy and kinda feels like fps lag (but its not)

When activating xray with optifine on, it just acts like fullbright and all water are no longer rendered.

**To Reproduce**
I explained it with enough detail IMO. Should be self explanatory to reproduce.

**Expected behavior**
Irrelevant, it's self explanatory.

**Screenshots**
https://i.imgur.com/LoB3CY0.png Alt manager opened from in-game

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
nightly-20191009-1.14.4 version of impact.
 

- Impact Version: nightly-20191009-1.14.4
- Using Optifine? No (Yes with the xray bug)
- Enabled mods: 
- Operating System: Windows 10 64 bit build 1903

</details>

**Additional context**

**Comment by 0-x-2-2** [comment]
Don't put more than one issue in the same bug report. Both of these are also duplicates.
