### ISSUE TITLE
Item Frame and paintings hitboxes are to big

### ISSUE THREAD

**Issue by PachimariOWL** [ImpactDevelopment/ImpactIssues#1724]
say I have an item frame showcasing the item in the chest if you go to open the chest it will just rotate the item in the item frame

Edit: Just to be clear I don't have hitboxes enabled and when I switch to vanilla the hitboxes are normal

**Comment by leijurv** [comment]
do you perchance have `Hitbox` enabled? 😹

**Comment by PachimariOWL** [comment]
> do you perchance have `Hitbox` enabled? 😹

I do not!

**Comment by dominikaaaa** [comment]
can't reproduce this issue
