### ISSUE TITLE
Xray not working in latest version.

### ISSUE THREAD

**Issue by CokeCola943** [ImpactDevelopment/ImpactIssues#1726]
With xray on the latest version of impact with optifine this didn't happen before though.

**To Reproduce**
1. Go to minecraft impact with optifine latest version (4.8)
2. Click on xray
3. and it just doesn't work.

**Expected behavior**
Xray should work and see the ores and stuff you added.

**Screenshots**
https://cdn.discordapp.com/attachments/254510901837824000/632433380872683543/unknown.png

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 for 1.14.4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Xray (some others that don't matter)
- Operating System: Windows 10 64bit.

</details>

**Additional context**
I made a video but it's too big of a file.

**Comment by leijurv** [comment]
optifine breaks xray on 1.13 and 1.14, reinstall without it

**Comment by leijurv** [comment]
(closed since duplicate, theres a million issues all saying the same thing going back till march lmao)
