### ISSUE TITLE
[1.14] Baritone Farming doesn't work

### ISSUE THREAD

**Issue by Yertled** [ImpactDevelopment/ImpactIssues#1730]
**Describe the bug**
When I activate #farm, it says it started it but it does nothing. Same if I activate "Auto Farm" in impact, doesn't do anything.

**To Reproduce**
Type #farm in chat and see nothing will happen.

**Expected behavior**
It should start farming all nearby crops...

**Screenshots**
https://i.imgur.com/GI5mAJS.png
https://i.imgur.com/y7oFQPR.png

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.1 public version
- Using Optifine? Yes
- Enabled mods: Nothing relevant https://i.imgur.com/fdjcvEV.png
- Operating System: Windows 10 64 bit Build 1903

</details>

**Additional context**

**Comment by 0-x-2-2** [comment]
🤔 Baritone bug?

**Comment by leijurv** [comment]
Yes, this was fixed by https://github.com/cabaletta/baritone/commit/05b5894348a1329a8e58a49f81543e507616343f and is in baritone 1.4.3

**Comment by leijurv** [comment]
Will be in 4.8.2
