### ISSUE TITLE
Assigning Click GUI to a letter searches it in 4.8.1

### ISSUE THREAD

**Issue by strongboy54** [ImpactDevelopment/ImpactIssues#1732]
I use the letter "Y" to open the Click GUI. Upon installing Impact 4.8.1 where searchable click GUI is a feature, pressing Y to open the Click GUI also begins a search for Y in the click GUI.

**To Reproduce**
1. Assign Click GUI keybind to any letter on the keyboard
2. Press said keybind.
3. Notice how it will search for that letter pressed to open the Click GUI

**Expected behavior**
Opens the Click GUI without searching

**Screenshots**
https://prnt.sc/pibmqk

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.8.1
- Using Optifine?  No
- Using LiteLoader? No, Normal vanilla
- Enabled mods:  N/A
- Operating System: Win 10 Enterprise

</details>

**Additional context**

**Comment by strongboy54** [comment]
Temporary workaround is disabling click GUI search, or by assigning keybind to something other than a letter.

**Comment by leijurv** [comment]
Fixed for next hotfix (4.8.2?)
