### ISSUE TITLE
Build? Why not mine?

### ISSUE THREAD

**Issue by theluigiduck** [ImpactDevelopment/ImpactIssues#1739]
We already have build. It's a good utility that allows for quick construction and comes in handy very often. However, what would be stopping us from doing the same thing with mining?

I think that we should have a mine utility, where left click selects a position and right click selects another position, and everything in between those points will automatically be mined by Baritone. This way, clearing out large spaces would be considerably easier.

Now, there are a couple instances where this could still be done as it is right now.
For instance, the Nuker. The nuker clears out a large space, yes, and is very efficient in doing so, but is difficult to control. It's unpredictable, and has its limits.
What about if we just used ".b mine stone" instead? While, yes, this gets the Baritone program to mine out a lot of stone for you, it just travels in a direction instead of mining in a concise area. It also avoids anything that isn't any of the 5 selected blocks to mine, so there's already a bump in the road there.

If we were to get a proper mining tool, I would be very happy. It would provide a proper way to clear out a large area, and we might even consider making it target specific blocks, but ultimately, it will be the ultimate way to mine while you sit back and watch. Thanks for reading!

(Note: If this suggestion already exists somewhere else, or has already been implemented in some way, I apologize, for I do not know of its existence, and letting me know would be appreciated.)

🍪

**Comment by leijurv** [comment]
Yep, we have cleararea. 

You can select the area with `#click` or by doing `#sel pos1 <x> <y> <z>` `#sel pos2 <x> <y> <z>`

Then `#sel cleararea`

**Comment by theluigiduck** [comment]
i figured baritone would have something like that. thanks for telling me
