### ISSUE TITLE
Put cleararea in the ClickGui

### ISSUE THREAD

**Issue by theluigiduck** [ImpactDevelopment/ImpactIssues#1740]
This is really short and doesn't really warrant the typical format.
Basically, I'd like the #sel cleararea thing to be accessible via the ClickGui.
What do you think?

**Comment by 0-x-2-2** [comment]
🦍

**Comment by 0-x-2-2** [comment]
#click

**Comment by LeafHacker** [comment]
The  clickgui is used for managing mods, anything else (like activating a baritone command) is currently out of scope.
