### ISSUE TITLE
Impact doesn't open

### ISSUE THREAD

**Issue by ThePlayerChinChilia** [ImpactDevelopment/ImpactIssues#1742]
**Describe the bug**
When I open the installer and I clicked run anyways and after that nothing happens

**To Reproduce**
Steps to reproduce the behaviour:
1. Open "ImpactInstaller.exe"
2. Click on 'Run anyways'
3. See error

- Impact Version: "4.1 for 1.14.4"
- Using Optifine? "No"
- Using LiteLoader? "No"
- Operating System:  "Windows 10 64bit"

**Comment by MightyKnight** [comment]
This seems like a system issue.
Join the [official impact discord](https://impactclient.net/discord.html) and ask for help there(assuming you read this).
