### ISSUE TITLE
Schematic (1.12.2) Cactus farm, puts the sand and cancel at cactus!!

### ISSUE THREAD

**Issue by spaik66** [ImpactDevelopment/ImpactIssues#1744]
Hello !!
**Describe the bug**
Schematic (1.12.2) Cactus farms, puts the sand and cancel at cactus!! Try to make the 5x5 round 
cactus farm column. (i am experienced in schematics-printer works cannons and so.."
**To Reproduce**
I used both 2 ways "#schematica with loaded schem" and "#build 5x5cactus.schematic" ... At both
ways, it stops when it cannot place any more sand, because the rest of the sand its over the cactus and over the strings .... 
**I believe the problem is THAT it cannot recognize cactus as blocks or as crops that can be Plant-placed !!!!** Maybe it dont recognize cactus as crops, because i put sand down in room and try the #farm or .b farm and it start beeing in farming mode but place nothing on the sand !!!!!!!
**Expected behavior**
( in my schem the center column is a sand column to help going up with no-fly) As i stand in the middle of column. To put the first layer of sand, then (second layer) put cactus on the sand and the strings attached to the cactus at internal space (not out of schem).
Then put 2 sand under me to go up to 3rd block (layer) . At 3rd layer start again 1 layer sand on strings, then cactus with strings (as schem) and then sand under me 2 blocks, repeat until schem finish. 
Thank you, your job is great, hope you fix it soon cause some server are setting off the the printer mode of schematica.
**PC**
Windows 8.1 x64
Java1.8.0_221 x64 JDK
Multi Mc 5 0.6.7 - ver 1.12.2 - Forge 14.23.5.2768
**Mods**
Impact-4.8.1-1.12.2 (copied after instaled in the .minecraft/mods/1.12.2 of the Premium MC)
LunatriusCore-1.12.2-1.2.0.42
Schematica-1.12.2-1.8.0.git-universal or Schematica-1.12.2-1.8.0.169-universal
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT
and small java experience :)

**Recomendation** 
At farming put the #store <item> (to look closer chest to store farmed items) and the inside search "onfullinventory store".. sry havent look all the farming moves yet!!
Spaik

**Comment by dominikaaaa** [comment]
known bug in baritone

**Comment by autoclient118** [comment]
bru my friend build a cactus farm by 100 by 100......
