### ISSUE TITLE
Keybinds activate while using GUI Search feature

### ISSUE THREAD

**Issue by RyanA3** [ImpactDevelopment/ImpactIssues#1745]
**Describe the bug**
Your keybinds still activate / deactivate certain modules while using the new search feature in the click gui.

**To Reproduce**
1. Open ClickGUI
2. Set a keybind for killaura to (for example) k
3. Type k in the gui to search for modules with k in it
4. Kill aura will be activated and you will become very annoyed

**Expected behavior**
Keybinds should not work while using the search feature / while in the clickgui

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Comment by LeafHacker** [comment]
This is a feature not a bug

**Comment by LeafHacker** [comment]
(((only joking lol)))

**Comment by leijurv** [comment]
wtf bigoted leafhacker using antisemitic symbol wtf

**Comment by leijurv** [comment]
Fixed for next hotfix (4.8.2?)

**Comment by xCustomWorld** [comment]
This is very annoying for me, there should be option to turn this behaviour off, it is really anniying and I can't search anything without messing with the mods.

**Comment by leijurv** [comment]
Update to 4.8.2
