### ISSUE TITLE
Collect dropped items

### ISSUE THREAD

**Issue by theluigiduck** [ImpactDevelopment/ImpactIssues#1746]
I think we should have a feature that collects items for us. Baritone will scan the area and if it finds the specified drop you're looking for (or just any drop at all) it will go over to it and pick it up.

I know this is sort of already possible with the .b mine function, and if say, you were to type .b mine bone_block it would also pick up nearby dropped bone blocks, but this does not work with items such as eggs, rotten flesh, arrows, etc.

🍪

**Comment by ZeroMemes** [comment]
https://github.com/cabaletta/baritone
