### ISSUE TITLE
I can't use 'Build' option on crafting table

### ISSUE THREAD

**Issue by rgmine** [ImpactDevelopment/ImpactIssues#1750]
### **Describe the bug**
When I put any blocks on crafting table with 'Build', I can't escape from crafting menu.

### **To Reproduce**
1. I put these blocks:
![Screenshot at 2019-10-14 12-02-57](https://user-images.githubusercontent.com/56525233/66727648-8d44df80-ee7b-11e9-8965-5eefc8990873.png)
2. Enabled 'Build'
3. Click stone block
![Screenshot at 2019-10-14 12-03-52](https://user-images.githubusercontent.com/56525233/66727677-b1082580-ee7b-11e9-824d-ac15a3d9605c.png)
4. Right click grass block and,
![Screenshot at 2019-10-14 12-04-22](https://user-images.githubusercontent.com/56525233/66727684-c1b89b80-ee7b-11e9-8f14-b3a17ba8fecb.png)
5. I can't leave from crafting menu...
![Screenshot at 2019-10-14 12-05-06](https://user-images.githubusercontent.com/56525233/66727695-d137e480-ee7b-11e9-9f07-4276fa97cea1.png)

**Comment by dominikaaaa** [comment]
Open a bug report in baritone's repo if this still happens.
