### ISSUE TITLE
Broken Nametags

### ISSUE THREAD

**Issue by Darko1green1LOrd** [ImpactDevelopment/ImpactIssues#1753]
**Describe the bug**
Name tags are blured , you cant see them

**To Reproduce**
1. Go in gamemode spectator
2. Enable Nametags
3. Look on players in different angles

**Expected behavior**
Show text gamemode and these things

**Screenshots**
![2019-10-14_15 25 25](https://user-images.githubusercontent.com/48098927/66755383-284bb280-ee98-11e9-8012-9ab667cc0227.png)
![2019-10-14_15 25 45](https://user-images.githubusercontent.com/48098927/66755385-284bb280-ee98-11e9-9dfe-305fcb405a10.png)
![2019-10-14_15 25 49](https://user-images.githubusercontent.com/48098927/66755386-28e44900-ee98-11e9-9345-fd97bb6d10d7.png)
![2019-10-14_15 25 56](https://user-images.githubusercontent.com/48098927/66755387-28e44900-ee98-11e9-8291-e4658670cac3.png)

 

- Impact Version: 4.8.1 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
Could you describe the issue a bit more please? AFAICT the screenshots show nametags working normally, but one user's team colour happens to be similar to the nametags background colour?

**Comment by Darko1green1LOrd** [comment]
when i will go in gamemode spectator and go around people with nametags on they sometimes get blured , as on some screenshots can be seen how its just gray background of it and nothing can be seen on it

**Comment by Darko1green1LOrd** [comment]
Hello , i uploaded a video about the bug it might help 
https://youtu.be/lXhhOaGzBAc

**Comment by DanCuber** [comment]
A similar issue occurs with nametags and tacers when going in third person view: they all become a solid gray color regardless of settings

**Comment by dominikaaaa** [comment]
Can't reproduce. Reopen with steps to reproduce if you can.

**Comment by MP3Martin** [comment]
Same happens when pressing F1
