### ISSUE TITLE
Gui improve

### ISSUE THREAD

**Issue by Darko1green1LOrd** [ImpactDevelopment/ImpactIssues#1754]
**Is your feature request related to a problem? Please describe.**
I Really like the navigator of Wurst

**Soultion**
Add gui that will be full box like wurst has the navigator or how remix has its gui

**Additional context**
https://i.ytimg.com/vi/pSesAfPozh0/maxresdefault.jpg

https://user-images.githubusercontent.com/10100202/31046377-aaf941fc-a5f7-11e7-9a21-d4610641580d.jpg

https://user-images.githubusercontent.com/10100202/31046377-aaf941fc-a5f7-11e7-9a21-d4610641580d.jpg

https://user-images.githubusercontent.com/10100202/31046440-cf4399e4-a5f8-11e7-827e-948c73d4800f.jpg

**Comment by LeafHacker** [comment]
mfw this suggestion is literally "copy wurst".
