### ISSUE TITLE
Mouse invert while holding ALT

### ISSUE THREAD

**Issue by 0xAB51NTH** [ImpactDevelopment/ImpactIssues#1757]
**Describe the bug**
While pressing alt, your controls are inverted (up = down, and soo on.

**To Reproduce**
1. Go to server or world
2. Press alt on keyboard
3. Move mouse up or press walking key
5. Unpress alt
6. Your angle snaps to angle before alt was pressed
7. Use client mod self destruct.
8. Glitch is gone
**Expected behavior**
Nothing should happen

**Screenshots**
Not applicable.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 1.14.4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods : none
- Operating  system : win 10

</details>

**Comment by 0-x-2-2** [comment]
very sure this is a feature,

**Comment by SentinelMKX** [comment]
`.perspective disable` to don't allow ALT looking around in first view
