### ISSUE TITLE
auto drop unwanted items

### ISSUE THREAD

**Issue by Trixydust** [ImpactDevelopment/ImpactIssues#1758]
i noticed that the auto mine sometimes drops the tool when the toolsaver is turned on and the invetory is full. i have used the wurst client before this one and they provided a feature that makes you drop blocks you dont want or you rather not like to have in ur inventory. this has a gui somwhat similar to the  x-ray gui to add and remove blocks it needs to drop.  maybe this is an idea that can be played around with. this client is amazing. wouldnt want to use another one a big congratz on pulling this of!!!!

**Comment by chris7479** [comment]
This already exists as the auto eject feature. 
To use it:
.autoeject add itemnamehere
.t autoeject
