### ISSUE TITLE
Watermark keeps reappearing

### ISSUE THREAD

**Issue by Raulsack69** [ImpactDevelopment/ImpactIssues#1760]
**Describe the bug**
Ever since Impact 4.8.1, when "Visible" is unchecked under "Watermark", it disabled the watermark as expected but does not persist. Every time you reload Minecraft the watermark is back.

**To Reproduce**
1. Go to Render > HUD > Watermark > Visible and make sure Visible is not checked
2. Exit Minecraft
3. Reopen Minecraft
4. Notice the watermark has magically become visible again

**Expected behavior**
The watermark should stay off when "Visible" is unchecked, even if you relaunch the game.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.1
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 (64-Bit)

</details>

**Comment by SentinelMKX** [comment]
![image](https://user-images.githubusercontent.com/22961592/66867697-21a66380-ef9c-11e9-927d-5bb3173e2e52.png)
