### ISSUE TITLE
autofarm doesnt work

### ISSUE THREAD

**Issue by Trixydust** [ImpactDevelopment/ImpactIssues#1761]
so a brief thanks for the quick awnser for my latest post here.
now i have been messing around with the client some more and i feel like i have plenty of features on at any time in my playsession i tried the autofarm feature for the first time and it seemed that it didnt do anything. if this is a bug then i am glad i could help but if this may be some interfearance with my other hax active please lemme know which one i have to turn of to make it work.
![Screenshot (81)](https://user-images.githubusercontent.com/56592783/66868973-b14d1180-ef9e-11e9-9845-8d53415023de.png)

**Comment by 0-x-2-2** [comment]
This is fixed in the next hotfix afaik.
