### ISSUE TITLE
Fake Minecon Capes

### ISSUE THREAD

**Issue by Dvance0784** [ImpactDevelopment/ImpactIssues#1762]
This request is not related to a problem.

Is there any way you can publicly let users choose any one of the current Minecon capes and fake 'show off' to everyone publicly?

If there isn't a way to publicly show it off, there should be a way to customize your own cape via Click GUI and show off your amazing art skills to other Impact users.

It would be so cool to mess with friends or make your own capes in-game. I would have so much fun with this feature, and I think others will too.

**Comment by 0tii** [comment]
customizable capes would be sick

**Comment by ScanmanTM** [comment]
> Is there any way you can publicly let users choose any one of the current Minecon capes and fake 'show off' to everyone publicly?

No.

**Comment by Dvance0784** [comment]
Well, that is such a disappointment.
