### ISSUE TITLE
Macros don't get removed

### ISSUE THREAD

**Issue by ooodlllars** [ImpactDevelopment/ImpactIssues#1763]
**Describe the bug**
After I delete macros they still do stuff

**To Reproduce**
1. Go to Impact > Macros > Add > Set a key > add message
2. Remove it
3. Try pressing the key you set

**Expected behavior**
The macro should stop doing stuff

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8
- Using Optifine? Yes 
- Using LiteLoader? No 
- Enabled mods: Velocity, Weather, Nametags, Tracers, ESP, and Light
- Operating System: Windows 10 64bit 

</details>

**Comment by 5GameMaker** [comment]
Same

**Comment by TheNeverEndingEcksDee** [comment]
Same, please fix :I

**Comment by S-B99** [comment]
You have to restart your game to fix this.

**Comment by S-B99** [comment]
Or manually save the config.
