### ISSUE TITLE
Can't install Impact to MultiMC

### ISSUE THREAD

**Issue by YurtCurcle** [ImpactDevelopment/ImpactIssues#1766]
I can't seem to get Impact to install into MultiMC. I followed all the steps on the wiki page, but Minecraft was just normal Minecraft when I attempted to launch it. Do I need to have the files somewhere else in the MultiMC files?

**Comment by spaik66** [comment]
Look how i did it!!.. Follow the instractions on how to auto install Impact, the version you want on the usual minecraft game. (This is another way to create the mod, cause no other is working)  Be sure you have the right Forge installed for the version. Run the game with no other mods to make sure the Impact minecraft working. Then simply go at your mod folder and find the folder Impact. There you will see the installed working mod as you test it. Copy it at the MultiMc instance folder mod you play with the other mods and that’s it man :)

**Comment by dominikaaaa** [comment]
works fine for me
