### ISSUE TITLE
The installer isn't placing a jar file in the folder.

### ISSUE THREAD

**Issue by eggsarecool** [ImpactDevelopment/ImpactIssues#1769]
The installer isn't placing a jar file in the folder.

**To Reproduce**
1. Install Impact, I've tried with 1.13.2 and 1.14.4
2. Tried to use the newly installed client but wasn't in versions list
3. Went to check the folder, there is a json but no jar

**Expected behavior**
I expected a json and a jar so I could run the client.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.1 for 1.13.2 and 1.14.4" -->
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: N/A
- Operating System: Windows 7 Ultimate

</details>

**Additional context**

**Comment by SentinelMKX** [comment]
There is no need to be a JAR file in versions folder, in JSON are libraries path and download links that  launcher downloads,
Try to reinstall it with the installer. Also if you need help go on Impact Discord Server

**Comment by leijurv** [comment]
lmao have you tried launching the profile to see if it works before complaining that it doesn't?

**Comment by leijurv** [comment]
lack of a jar is not the issue, it's downloaded to `minecraft/libraries/com/github/impactdevelopment/something`
