### ISSUE TITLE
No option to set aps to cooldown for 1.12.2

### ISSUE THREAD

**Issue by DrStephan** [ImpactDevelopment/ImpactIssues#1787]
![helpthing1](https://user-images.githubusercontent.com/54516905/67516914-78343180-f66f-11e9-829f-1a8b624fe3db.PNG)
![helpthing2](https://user-images.githubusercontent.com/54516905/67516926-7e2a1280-f66f-11e9-96cf-5c655c742d0e.PNG)
As you can see there is no option for setting APS to tool cooldown, I think its a bug, I use the latest version of Impact from the website.

**Comment by 0-x-2-2** [comment]
![image](https://user-images.githubusercontent.com/9968651/67544019-d853c380-f6c1-11e9-90f6-01e70046fd37.png)
???????
