### ISSUE TITLE
Player-Skeleton ESP

### ISSUE THREAD

**Issue by Kami147** [ImpactDevelopment/ImpactIssues#1790]
I think esp that shows the players "Skeleton" would be a cool feature. For context of what i mean 
https://prnt.sc/pnzzrz is something like what i'd imagine, sorry for the low quality screenshot, i couldn't find a better pic

**Comment by 0-x-2-2** [comment]
already exists

**Comment by jewbob** [comment]
![Screen Shot 2020-07-14 at 19 34 18](https://user-images.githubusercontent.com/63724032/87463463-54ec5080-c609-11ea-8660-fb2b7f55738e.png)

**Comment by jewbob** [comment]
im going to cum in your spagetti
