### ISSUE TITLE
Can't select alts in alt menu, have to use random button instead

### ISSUE THREAD

**Issue by CovahYT** [ImpactDevelopment/ImpactIssues#1796]
**Describe the bug**
In the alt menu on the main screen you can't click on your added alts and you have to instead use the random button to get the one you want. This also means you can't delete alts because you can't highlight them.

**To Reproduce**
1. Click on "alts" in main menu
2. Add 1 or more alts
3. Attempt to click on them

**Expected behavior**
I expected the selected alt to be highlighted. This is impossible as it simply doesn't allow you to.

**Screenshots**
Doesn't need screenshots.

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.2 for 1.14.4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: A lot, however I'm certain they don't affect this issue.
- Operating System: Windows 7 64bit

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
duplicate
