### ISSUE TITLE
Schematics module for impact

### ISSUE THREAD

**Issue by devatator** [ImpactDevelopment/ImpactIssues#1804]
As far as i remember, i always use schematica with impact forge to use my schematics but this can't work with impact 1.14.4 since it don't have a forge or fabric version so it would be cool if you added a schematic tool/viewer inside impact

**Comment by Dad3** [comment]
schematica is an outdated mod and isn't compatible with 1.14.4. It would be extremely cool if impact team made a built in schematica mod but it's a lot of work and very unlikely

**Comment by enescaglayan** [comment]
Theres a schematic tool in baritone, but it needs more work, we cant see where to place the building etc.

**Comment by j5155** [comment]
Litematica is basically schematica for 1.12+
I can't really try using litematica with baritone as there's no fabric version of impact, but I would think they would work pretty decently together

**Comment by dominikaaaa** [comment]
I have no idea why this stayed open. You can use schematica for 1.12.2 and Litematica for newer versions.
