### ISSUE TITLE
Ability to mine when window is out of focus (without baritone)

### ISSUE THREAD

**Issue by sh3zb0t** [ImpactDevelopment/ImpactIssues#1813]
like in title, basically thats all
so you will be able to afk mine for example cobble gens so if admin will "debug" you by placing blocks around you and so you wouldnt spin silly

**Comment by dominikaaaa** [comment]
This would be an issue for Baritone's repo, no?

**Comment by LeafHacker** [comment]
> This would be an issue for Baritone's repo, no?

The title says "without baritone" so I'm guessing they just mean mining with an afk click of some kind?

Anyway, there's a vanilla feature that does this: F3+P
