### ISSUE TITLE
Auto XP Farm (Or Auto Mine Improvement)

### ISSUE THREAD

**Issue by DarkiBoi** [ImpactDevelopment/ImpactIssues#1815]
Hey, I've been farming quartz for xp with baritone for a time now, and its not exactly the most efficient way, because once your inventory is full, you wont pick up the quartz anymore, so it lays on the floor, and baritone wants to pick it up, but I dont, since i'm not farming quartz for quartz but instead for the huge amount of XP you get from them.
My Improvement Suggestions:
An Auto XP Farm Module, that ignores stuff lying on the ground, so you can XP farm more efficiently.
Or an option for Auto Mine to not pick up stuff of the ground, or to not get stuck on stuff lying on the ground, but instead just moving on.

I would highly appreciate if I could look forward to a comparable feature in the future.

~Darki

**Comment by leijurv** [comment]
turn off the setting like so `#minescandroppeditems` and baritone will keep going ignoring dropos
