### ISSUE TITLE
random baritone pathfinding

### ISSUE THREAD

**Issue by FLOWRIDER0** [ImpactDevelopment/ImpactIssues#1818]
on the 1.14 version of impact, baritone will randomly pathfind to a random player or location without input. there is no way to clear the goal. this only happens on multiplayer servers

(OS: x86 win-10)

**Comment by leijurv** [comment]
1. turn off modules that activate baritone: auto walk, auto mine, hunt
2. check what is causing it to path by enabling Baritone under HUD or running `#proc` in chat
3. cancel whatever that is, probably with `#cancel`
