### ISSUE TITLE
Can't open Impact installer jar on MacOS

### ISSUE THREAD

**Issue by jebthedev** [ImpactDevelopment/ImpactIssues#1819]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Opening-the-installer-on-Mac
