### ISSUE TITLE
Can't launch Impact installer on macOS

### ISSUE THREAD

**Issue by jebthedev** [ImpactDevelopment/ImpactIssues#1820]
**Describe the bug**
I have downloaded the latest impact installer. When I double click on it, to run it, I get an error message: The Java JAR file “ImpactInstaller-0.7.5.jar” could not be launched.

When I run it via the terminal, I get this error: no main manifest attribute

I have installed the latest version of Java.

I am running the latest version of macOS Catalina.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download latest impact installer (“ImpactInstaller-0.7.5.jar”)
2. Double click the .jar file to run it.

**Comment by leijurv** [comment]
Can you upload the exact file that you downloaded somewhere so I can take a look? Perhaps the server is broken, since "no main manifest attribute" means it must be corrupted somehow... Also the download works for me, also on mac

**Comment by jebthedev** [comment]
Running the .jar file from the downloads folder appears to be the issue. Running it from my desktop works as expected.

The jar file I was running was the latest "universal installer" from the impact website. I tried downloading multiple jars, so I don't think it was corrupted.
