### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Okka676767** [ImpactDevelopment/ImpactIssues#1822]
**Describe the bug**
When using Baritone, beacons will either not be detected or it will mine it with a cheat
**To Reproduce**
1. Go to 'mcprison.com’
2. Go to ‘/robot and visit beacon mine’
3. Type .b mine beacon

**Expected behaviour**
Should just mine beacons with the pickaxe given.
**Screenshots**
 

It detects no error

```
- Impact Version: <!-- e.g. "4.8.2” -->
- Using Optifine? <!-- No -->
- Using LiteLoader? <!-- No -->
- Enabled mods: <!-- “baritone auto mine " -->
- Operating System: <!-- e.g. "Windows 10 64bit" -->

</details>

**Additional context**
Add any other context about the problem here.

**Comment by S-B99** [comment]
This is a baritone issue.

**Comment by S-B99** [comment]
Also you probably have the wrong ID for them.
