### ISSUE TITLE
Freecam Stutters 100% of the Time

### ISSUE THREAD

**Issue by Zexim** [ImpactDevelopment/ImpactIssues#1824]
Freecam always stutters while moving even at high FPS.

**To Reproduce**
1. Enable freecam
2. Move around and watch the stuttering motion

**Expected behavior**
Freecam moves smoothly (like flight)

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Freecam
- Operating System: Windows 10 64bit

</details>

**Comment by dominikaaaa** [comment]
can't reproduce
