### ISSUE TITLE
Trajectories Ignores Crossbows

### ISSUE THREAD

**Issue by Zexim** [ImpactDevelopment/ImpactIssues#1825]
The Trajectories mod ignores crossbows.

**To Reproduce**
1. Enable trajectories
2. Select a crossbow and load it

**Expected behavior**
Trajectories are shown for crossbows

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Trajectories
- Operating System: Windows 10 64bit

</details>

**Comment by devatator** [comment]
i already reported it : https://github.com/ImpactDevelopment/ImpactIssues/issues/1770 but more posts will make this more visible
