### ISSUE TITLE
Inventory module not working properly on impact 1.12.2 forge

### ISSUE THREAD

**Issue by devatator** [ImpactDevelopment/ImpactIssues#1829]
**Describe the bug**
the move around and look around submodules of inventory does not work with impact for forge 

**To Reproduce**
1. Activate Inventory module
2. Activate "look around" and "move around"
3. Open inventory
4. Try to walk with WASD and look around with arrow keys

**Expected behavior**
WASD should make my player move and arrow keys should move the camera

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.2 forge
- Using Optifine?: does the same with or without optifine
- Using LiteLoader?: no
- Enabled mods: Radar dynamic, Trajectories, Light and inventory
- Operating System: Mac OS 10.11.6

</details>

**Comment by RedCarlos26** [comment]
Yeah I experienced this also with forge and Impact Client

**Comment by 0-x-2-2** [comment]
#1150
