### ISSUE TITLE
The Altening Support

### ISSUE THREAD

**Issue by ForyxCraft** [ImpactDevelopment/ImpactIssues#1832]
Please add The Altening Support so I can use my The Altening tokens in Impact

**Comment by Thunder33345** [comment]
> Do you have an API that i can use?
> We offer a free API key to every customer, they're free to implement TheAltening into their own applications! Integration - Integration is key here, that's why we've already implemented TheAltening functionality into popular tools like OQMineBot, a minecraft botting application that uses alts to work. The tools go hand in hand and you'll be able to use them both seamlessly!

but dont seem to find the docs, or publicly available at least
i think the owner is on our discord right? we should ask them to hit the devs up with docs access at least or else this is impossible

**Comment by ForyxCraft** [comment]
@Thunder33345 https://github.com/TheAltening/TheAlteningAuth4j

**Comment by LeafHacker** [comment]
Looks doable. Not sure if/when I'd have time but I imagine it would work ok.

**Comment by Xevier1** [comment]
> Looks doable. Not sure if/when I'd have time but I imagine it would work ok.

I am the owner of TheAltening, the API he linked is correct. If you'd like an HTTP API we have one available on the dashboard, for java you should reference that github linked previously.
If you decide to implement my API i can provide you with benefits that partnered clients are eligible to receive, as well as things like discounts for your client users among a lot of other things. Feel free to join my discord linked on my site's dashboard for more info @LeafHacker

**Comment by LeafHacker** [comment]
Tonight's nightly will include a basic implementation. Currently it allows you to paste a token generated by the [free generator](https://thealtening.com/free/free-minecraft-alt) or the premium [web generator](https://panel.thealtening.com/#generator) into the client. This saves the alt to the Alt List where you can then select and log into it.

I plan to look into supporting more advanced features such as generating the alt within the client too, but figured it was better to get a simple solution done first.

![image](https://user-images.githubusercontent.com/23565638/69094617-a0ce0200-0a48-11ea-9ba7-f4941b009d35.png)
![image](https://user-images.githubusercontent.com/23565638/69095199-bdb70500-0a49-11ea-845d-ab7ea7b4e05a.png)

**Comment by NightlyKnights** [comment]
Its not letting me make and alt and it keeps saying that a limit has been reached

**Comment by qTOLer05** [comment]
bruh why i have to pay for a simple free minecraft account just make 1 month free bruh

**Comment by CatGames22817** [comment]
Лавочку Прикрили :(
