### ISSUE TITLE
Anti Blind does not work

### ISSUE THREAD

**Issue by Dad3** [ImpactDevelopment/ImpactIssues#1842]
**Describe the bug**
Anti blind doesn't turn off blindness effect 

**To Reproduce**
1. Turn on anti blind
2. give yourself blindness or nausea

- Impact Version: Impact 4.8.2-Optifine_HD_U_F3 [1.14.4]
- Using Optifine? yes
- Using LiteLoader? no
- Enabled mods: esp
- Operating System: Windows 10 64 bit

**Comment by S-B99** [comment]
Please provide a video of it not working. Seems to work for me.
