### ISSUE TITLE
Animations mod to customize animations for sword, shifting, etc.

### ISSUE THREAD

**Issue by Dad3** [ImpactDevelopment/ImpactIssues#1843]
This mod would let you change the sword animation when hitting to either 1.7 animation or 1.8 etc. and other things
http://prntscr.com/pufdgq

Also would be nice if there is a way to disable shield animation AND make shift animation instant instead of slow in 1.14 

here is an example of this mod https://www.oldanimationsmod.net/

**Comment by Gitty891** [comment]
I would do love to see this, I know there's an animations option already, but that's only swords and it's not in 3rd person

**Comment by S-B99** [comment]
Use the animations mod itself.
