### ISSUE TITLE
Cubecraft not working

### ISSUE THREAD

**Issue by vZain** [ImpactDevelopment/ImpactIssues#1847]
**Describe the bug**
I can't log onto cube craft, when i try to it tells me: Internal Exception: java.lang.NullPointerException

**To Reproduce**
1. Go to 'Multiplayer'
2. Click on 'Cubecraft server'
3. Scroll down to '/'

**Expected behavior**
To get into the server

**Screenshots**
<img width="850" alt="Schermata 2019-11-10 alle 14 33 04" src="https://user-images.githubusercontent.com/57592190/68544785-0bd36500-03c7-11ea-91a9-10d5f825ca1d.png">

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by devatator** [comment]
Strangely it works fine for me since impact 4.7.3
Are you using an mcleaks account or a premium account.

**Comment by devatator** [comment]
try it with any version of impact 1.12.2

**Comment by S-B99** [comment]
Make sure you're using the official launcher and fill out the rest of the issue template.
