### ISSUE TITLE
Won't Bring Me To Download Site

### ISSUE THREAD

**Issue by Wally523** [ImpactDevelopment/ImpactIssues#1849]
1. Click On Any of the downloads (Java or Windows)
2. After Clicking on Java or Windows it brings me to the download link.  (Usually, It would) 
3. Instead the website says "This site can’t be reached The webpage at http://evassmat.com/K44b might be temporarily down or it may have moved permanently to a new web address.
ERR_CONNECTION_ABORTED
Please Fix
Thank You

**Comment by SentinelMKX** [comment]
This is happening because your AdBlocker or Antivirus blocked the site, evassmat is page that is providing ads.
