### ISSUE TITLE
Forge 1.12.2 download failed, unable to download

### ISSUE THREAD

**Issue by DreamMiu** [ImpactDevelopment/ImpactIssues#1852]
I hope that Google Translate will let you know! I am unable to download and install using Forge 1.12.2, is there any other download method?

**Comment by S-B99** [comment]
https://impactclient.net/ImpactInstaller.jar

**Comment by leijurv** [comment]
<img width="555" alt="Screen Shot 2020-02-04 at 11 19 55 AM" src="https://user-images.githubusercontent.com/3837873/73778564-49365d00-4740-11ea-91f0-d987a821f54d.png">
@S-B99 we disallow hotlinking, can u instead link to just the site. (e.g. link to /?brady-money... etc)

https://github.com/ImpactDevelopment/ImpactServer/blob/master/src/web/installer.go#L235

**Comment by S-B99** [comment]
That's a bruh moment
