### ISSUE TITLE
weierd camera mode when using alt to sprint

### ISSUE THREAD

**Issue by 5fc** [ImpactDevelopment/ImpactIssues#1854]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by EmeraldSnorlax** [comment]
i just lost so many fuckin braincells reading this
