### ISSUE TITLE
It shows impact in %appdata% > .minecraft > Versions but when i open up the launcher it isnt there. 

### ISSUE THREAD

**Issue by jaeceeee** [ImpactDevelopment/ImpactIssues#1856]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by SentinelMKX** [comment]
It's a fault of Official Minecraft Launcher, restart your computer, it should appear there after the restart.

**Comment by jaeceeee** [comment]
> It's a fault of Official Minecraft Launcher, restart your computer, it should appear there after the restart.

I already have but i'll try again

**Comment by jaeceeee** [comment]
> It's a fault of Official Minecraft Launcher, restart your computer, it should appear there after the restart.

Ok it worked this time thanks :)
