### ISSUE TITLE
why am I banned from the discord?

### ISSUE THREAD

**Issue by Nikita11790** [ImpactDevelopment/ImpactIssues#1857]
I was gonna go ask in the discord becuz my friend count get multimc to run it even after following tutorial and count find it so I tried to use invite on website but im banned. why am I banned?
im Arctic#5824 please help

**Comment by EmeraldSnorlax** [comment]
:clown_face:

**Comment by Nikita11790** [comment]
????

**Comment by EmeraldSnorlax** [comment]
🤡

**Comment by S-B99** [comment]
> suggestion

**Comment by Nikita11790** [comment]
I suggest that I be unbanned

**Comment by SpicyBigDaddy-alt** [comment]
🤡

**Comment by SentinelMKX** [comment]
You were banned for posting .exe's, unban is very likely not happening.

**Comment by Nikita11790** [comment]
Oh, I don’t recall that sorry

**Comment by SirAlmighty-Shibe** [comment]
🤡

**Comment by EmeraldSnorlax** [comment]
clown_face
