### ISSUE TITLE
Installer not working.

### ISSUE THREAD

**Issue by Saalty** [ImpactDevelopment/ImpactIssues#1859]
So basically I was in help chat and I saw this kid saying his impact wouldn't install. I said try reopening your launcher and it didn't fix it. I went into dms and he screenshared me and he did all the correct steps. The minecraft directory was correct. He had ran the 1.14.4 at least once. So in the end I just had to send him all the impact files and manually install it. Idk how I can reproduce it though. I've tried. It said success on the installer so idk. Thanks and goodbye.

**Comment by SentinelMKX** [comment]
Very likely this is fault of users.

**Comment by Saalty** [comment]
He sent me a picture on discord of his .Minecraft folder and there was no impact folder there. Nor was there a json in the versions.

**Comment by S-B99** [comment]
If you can still reproduce this please provide a video and reopen this.
