### ISSUE TITLE
Allow baritone to mine through lava when enabled

### ISSUE THREAD

**Issue by j7y** [ImpactDevelopment/ImpactIssues#1860]
**Is your feature request related to a problem? Please describe.**
Often, servers use lava packets to block autminer as the bot assumes there is no path to the ores, with this addition the bot could ignore the lava and automine without limitation. This is a common problem I have.

**Describe the solution you'd like**
The ideal solution would be the implementation of a command such as #allowlavamine or something along those lines that would allow the player to tell the bot to ignore lava.

**Describe alternatives you've considered**
I'm not sure of any alternatives since this is a pretty straight forward feature.

**Additional context**
Here's an imgur link of what happens currently 
https://imgur.com/a/d7UuEbX  (there is gold ore under the lava)
Ideally, you would be able to allow the bot to go straight for the gold and ignore the lava.

**Comment by SentinelMKX** [comment]
Wrong GitHub, https://github.com/cabaletta/baritone <<

**Comment by j7y** [comment]
> Wrong GitHub, https://github.com/cabaletta/baritone <<

I added it there but thought to mention it here because this is a cheat client and this feature would bypass anti auto-miner on servers.
