### ISSUE TITLE
Mark Logout Positions

### ISSUE THREAD

**Issue by RicardoThanos** [ImpactDevelopment/ImpactIssues#1869]
Whenever someone logs out it's annoying if you need to open impact files then open the logout file then find the player who logged out

When someone logsout you can turn on/off the option that it marks where a player logged out
It would mark the top of the block with the player name as a nametag with a time if neccesary

You can should be able to change the color of the mark ontop of the block like make it rainbow, green, red, etc

**Comment by MightyKnight** [comment]
This is already implemented (see [here](https://github.com/ImpactDevelopment/ImpactIssues/issues/558#issuecomment-386460599)). Closing as invalid.

But it is currently not working, the bug is already reported: #1621, #1048
