### ISSUE TITLE
1.14.4 Impact crashes on launch but 1.12.2 does not

### ISSUE THREAD

**Issue by Johnyboi5** [ImpactDevelopment/ImpactIssues#1870]
**Describe the bug**
1.14.4 Crashes on start up
1.12.2 Doesent crashes on start up

**To Reproduce**
1. literally install 1.14.4
2. open up 1.14.4
3. install and open 1.14.4 impact

**Expected behavior**
1.14.4 open fine but no

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
1440x900
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://hastebin.com/oxulaqejoq.md  i will place this latest.txt from versions folder

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  1.14.4 impact version 4.8.2
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  cant even launch 
- Operating System:  Windows 10 64bit

</details>

**Additional context**
if i did something wrong contact me on discord dont go#2210

**Comment by lukamic321** [comment]
I'm having what I believe to be the same issue. I've tried with all the newest nightlies from the last 7 days (last time it worked for me) and it crashed on startup whether I have optifine or not.

Crash report:
https://pastebin.com/y0TfYQ35

Ping me if theres anything I missed, this is my first bug report. TwoWeetBixnMilk#6139

**Comment by mamiopro** [comment]
i crashed too but i will try forge now

**Comment by mamiopro** [comment]
however there is no impact for forge 1.14.4

**Comment by S-B99** [comment]
because forge 1.14.4 is really shitty

**Comment by MightyKnight** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/issues/2285#issuecomment-635463430
> In the future, don't use hastebin, they automatically delete pastes.

Closing this as **Invalid**, crash report unavailable.
