### ISSUE TITLE
Add "Ignore Not Exposed Ores" Option in AutoMine & Xray

### ISSUE THREAD

**Issue by Enteerman** [ImpactDevelopment/ImpactIssues#1873]
**Is your feature request related to a problem? Please describe.**
Some servers use Anti-X Ray, that makes stones that are not exposed, fake ores.

**Describe the solution you'd like**
Check if an ore block is surrounded by stone and ignore them.

**Describe alternatives you've considered**
You can also check if the ore block is exposed to air/fluids

**Comment by ScanmanTM** [comment]
🙂👉https://github.com/cabaletta/baritone/issues - automine suggestions

**Comment by dominikaaaa** [comment]
`#legitMine true`
