### ISSUE TITLE
I can't move while using Impact.

### ISSUE THREAD

**Issue by PatchyPretzel** [ImpactDevelopment/ImpactIssues#1875]
I can't move while using Impact. I go a few blocks forward, and it lags me back, even on a singleplayer world. I can move while using blink, though, so it may be something to do with the packets? It occurs on all versions with the newest Impact.

**Comment by SentinelMKX** [comment]
Disable Godmode in Portals module

**Comment by PatchyPretzel** [comment]
Thanks! It worked!
