### ISSUE TITLE
Crash on tittle screen on forge

### ISSUE THREAD

**Issue by MR-Spagetty** [ImpactDevelopment/ImpactIssues#1878]
Whenever I launch a forge game with impact installed as soon as Minecraft has finished loading the mods it tries to go into the main menu but crashes immediately.

**Comment by ScanmanTM** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
