### ISSUE TITLE
Auto Claim Detector AutoMine Baritone (Factions)

### ISSUE THREAD

**Issue by Tgamer500** [ImpactDevelopment/ImpactIssues#1879]
Whenever you're auto mining with baritone and run into a claim it will auto reroute.

Solution- add option that if a block reappears more than 3 times baritone will automatically reroute.

**Comment by Aaron2550** [comment]
I think scanning the chat, or having a keyword/sentence appear in chat reroutes baritone would be better because if you're on a laggy server you **will**  encounter lag spikes where blocks appear more than three times. Imagine mining sand with efficiency 5...

**Comment by Tgamer500** [comment]
> I think scanning the chat, or having a keyword/sentence appear in chat reroutes baritone would be better because if you're on a laggy server you **will** encounter lag spikes where blocks appear more than three times. Imagine mining sand with efficiency 5...

I think you do make a fair point and that would be a much better solution but I feel like they would have to make the keyword customizable per user since some servers have different settings than others.

**Comment by ScanmanTM** [comment]
🙂👉https://github.com/cabaletta/baritone/issues
