### ISSUE TITLE
A "Structure Build" module

### ISSUE THREAD

**Issue by SirAlmighty-Shibe** [ImpactDevelopment/ImpactIssues#1883]
**Is your feature request related to a problem? Please describe.**
No, if being lazy as hell is a problem, well, it probably is.

**Describe the solution you'd like**
A new module in the "World" section that allows you to copy structures or builds to files, then be able to recover them and build them back automatically block for block.
There could be a gui somewhere by the screen showing the blocks required. The building will automatically stop if there are no blocks left to place.

**Settings**
Auto Middleclicking - Automatically grabs required blocks from the inventory into your hotbar.
Range - Sets the range it builds at.
Speed - Building speed, to prevent ghost blocks.
Require ALL Blocks - Will need all the blocks required to complete the structure to begin building.
Show Gui - Shows a list of blocks needed.

**Saving and Loading**
There could be an additional module for saving, but the basic saving mechanic is right clicking for point 1, and left clicking for point 2. Middle click to write the structure to a file in a folder, possibly named the date, time, and the world/server it was saved in, or an actual way to name it.
Loading is the same, but left click to place the structure, and right click to rotate it, middle click to begin building.
The building could commence regardless if there is blocks in the way or not.

**Problems**
I'm not sure about how to get a specific structure in to load, but it could go as a list inside the module.

**Additional context**
This feature could work similarly to a structure block.

**Comment by mrphax0r** [comment]
What the fuck is a structure block

**Comment by ThebesAndSound** [comment]
you know impact comes with baritone right?

**Comment by 0-x-2-2** [comment]
#allowInventory
#build
