### ISSUE TITLE
Stripmining and  a Vanish glitch

### ISSUE THREAD

**Issue by DerShendi** [ImpactDevelopment/ImpactIssues#1884]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add a function to the automine Function that stripmines in a selected area and that whenever it sees ore clusters that it mines that cluster and continues
and now to the vanish bug request needs more explanation but in short, sometimes in minecraft you bug in a way that makes you like in a /vanish like state but not for everyone

**Describe alternatives you've considered**

**Additional context**

**Comment by SentinelMKX** [comment]
For each thing create own issue/ticket.

**Comment by SentinelMKX** [comment]
And I think there is needed more details about the vanish thing, a lot more details.

**Comment by ScanmanTM** [comment]
🙂👉https://github.com/cabaletta/baritone/issues - automine suggestions.
