### ISSUE TITLE
me pueden pasar las libreries del impact y cabaletta es lo que no me descarga

### ISSUE THREAD

**Issue by JHON13243** [ImpactDevelopment/ImpactIssues#1889]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by JHON13243** [comment]
![bandicam 2019-12-03 09-24-12-225](https://user-images.githubusercontent.com/56078266/70057052-df200100-15b2-11ea-90b2-6f21d9ff43d6.jpg)
![bandicam 2019-12-03 09-23-42-628](https://user-images.githubusercontent.com/56078266/70057071-e47d4b80-15b2-11ea-9e11-863e1b747ec6.jpg)

**Comment by ScanmanTM** [comment]
Impact doesn't support cracked launchers, get a job loser.
