### ISSUE TITLE
.modify  feature

### ISSUE THREAD

**Issue by Darko1green1LOrd** [ImpactDevelopment/ImpactIssues#1891]
Hello i would like .modify feature    i think it as it should have functions as Itemizer plugin , item modifyyng using creative mode is possible , client wurst already allows .rename .auhor etc      it would be nice like 
.modify enchant add (enchant) (level) - Adds enchant
.modify enchant remove (enchant) - removes said enchant
.modify enchant set (enchant)  (level) - replaces every enchant to the one you say
.modify enchant clear - clears enchants
.mofiy enchant hide (true or false) - Hides enchants , still be there but not shown when hover over the item with cursor
.modify book author set (Author Name)  - Changes author of book
.modify book edit     - Makes the book book and quill again making it editable
.modify item rename (name) - Renames the item use & for color codes
.modify item lore add (lore) - adds next line of lore
.modify item lore set (line) (lore) - replaces said line with lore u enter or if u wont enter line number 
.modify item Unbreakable (true or false) - makes item unbreakable or breakable 
replaces whole lore with said lore
.modify attr add (attribute) (level) - adds attribute fe KnockbackResistance
.modify attr set (attribute) (level) - replaces every attribute with the one you specified
.modify attr clear - clears all attributes
.modify remove (attribute) - removes said attribute 
.modify attr hide (true or false) - Hides attributes when hover over cursor the item including unbreakable

**Comment by mrphax0r** [comment]
Wurst src is right there Brady.

**Comment by dominikaaaa** [comment]
Closing this as won't fix as it only works in creative or singleplayer.
