### ISSUE TITLE
Unexpected issue occurred and the game has crashed.

### ISSUE THREAD

**Issue by Frappyy** [ImpactDevelopment/ImpactIssues#1895]
No error, no nothing. Just crashes pretty much immediately after launch. Using latest version 1.13.2 + latest Optifine for 1.13.2

1. Install Optifine 1.13.2 F5
2. Install Impact 4.8.2 with it for 1.13.2
3. Launch the game
4. See the error

**Comment by S-B99** [comment]
Please reopen this issue if it's still happening in latest.
