### ISSUE TITLE
Xray types chat message "Xray" when X is pressed?

### ISSUE THREAD

**Issue by Prime4G** [ImpactDevelopment/ImpactIssues#1896]
I can't figure out why or how to stop it, but when I press X for Xray, it types "Xray" in chat. I did it in game in the small server I play on and it almost got me caught .... The only way I can stop it is turning off chat ..?
Is there any way to stop it from typing in chat?

**Comment by SentinelMKX** [comment]
ESC -> Impact -> Macros
and delete your macros and restart client.

**Comment by Prime4G** [comment]
Thank you, I removed the macro but never restarted the client and thats why it never worked for me initially!
