### ISSUE TITLE
Fix the Impact forgemod

### ISSUE THREAD

**Issue by Quazar5** [ImpactDevelopment/ImpactIssues#1900]
Right now the forge mod is so broken it's not even funny.  ESP & search opacity/colors don't work, autocrystal gets stuck & is _really_ slow most of the time, all the speed modes besides boost are useless (this should raise the alarm seeing as Impact is legit known for its speedhacks), & just in general Impact doesn't work well with other clients.

I cannot give up the use of multiple clients because none of them really do everything well.  In my opinion, the Impact mod should be a higher priority than the other version as everyone I know uses it because Impact's not good enough to be used on its own.  If you think Impact is complete I'd politely suggest you take 5 minutes to look at the features of other clients.

Regards,
**_Quazar5_**

**Comment by ScanmanTM** [comment]
Cool essay. I highly doubt the forge mod will ever be prioritised over the vanilla versions.
If you want fixes or suggestions create a new issue using the templates, kthx.

**Comment by Quazar5** [comment]
I'VE BEEN CREATING ISSUE REPORTS/FEATURE REQUESTS FOR A MONTH NOW.  You've ignored them.

**Comment by ScanmanTM** [comment]
This client is a hobby, the devs don't work on this 24/7 and prioritise this over everything.
If you want your suggestions to be seen go to a paid client like futureclient.net

**Comment by Quazar5** [comment]
Wow.  Great support!

**Comment by LeafHacker** [comment]
This isn't a support channel, it is an issue tracker. If you've created issues then great, we can track them. This isn't an example of a track-able issue; it covers multiple topics.

As noted above Impact is a part time hobby, including for our "support" "team". I find the _expectation_ of support and the perceived right to dictate our priorities particularly offensive; Impact is something we did in a spare hour or two and then dumped onto the internet for free.

That's it. Nothing more. This isn't a product or a service, nor are we a company with customers or whatever.

**Comment by S-B99** [comment]
I mean at least label it as won't fix and preferably pin it? This breaks compatibility with a ton of mods.

**Comment by 0-x-2-2** [comment]
> I mean at least label it as won't fix and preferably pin it? This breaks compatibility with a ton of mods.

The only mods that break are coremods that are doing horrible things that breaks something and causes another mod to be blamed for it or just unlucky coremod conflicts.

**Comment by S-B99** [comment]
I've never had an issue with different coremods until recently honestly. Yes, you shouldn't mix them and load a million different modified mixins and the such but up until WWE 3.0 and this there's never been an issue. You guys changed something that does horrible things or it just happens to change the same stuff that other mods change.

**Comment by 0-x-2-2** [comment]
> I've never had an issue with different coremods until recently honestly. Yes, you shouldn't mix them and load a million different modified mixins and the such but up until WWE 3.0 and this there's never been an issue. You guys changed something that does horrible things or it just happens to change the same stuff that other mods change.

Impact's coremod does not do anything horrible afaik but WWE does however afaik. I also don't really understand the response did it not work before and it does now or ?

**Comment by S-B99** [comment]
The coremod didn't break compatibility before from what I can see

**Comment by 0-x-2-2** [comment]
> The Impact coremod didn't break compatibility before from what I can see

Impact's coremod has not changed in months. WWE afaik has been breaking Impact's hooks for months and they must of just finally broke a hook that will cause an instant crash instead of side effects like some features not working or rendering issues.

**Comment by zeroeightysix** [comment]
> > I mean at least label it as won't fix and preferably pin it? This breaks compatibility with a ton of mods.
> 
> The only mods that break are coremods that are doing horrible things ...

What do you mean by 'horrible things'? Mixin's `@Overwrite` or injections in general?
