### ISSUE TITLE
Build being able to plant crops

### ISSUE THREAD

**Issue by recklezzzdingo** [ImpactDevelopment/ImpactIssues#1907]
**Is your feature request related to a problem? Please describe.**
(Not issue with Impact) When building a large farm on a server going through and planting all the Sugar Cane (scane is most profitable) is extremely tedious. 

**Describe the solution you'd like**
Allow the Build module to plant crops when they can be planted.

**Describe alternatives you've considered**
Allow AutoFarm to plant Sugar Cane when it can be planted instead of only breaking the top 2.

**Additional context**
I spend like 4 hours planting scane so I just want to be able to highlight a level and run through and have it plant instead of planting each piece by hand.

**Comment by sedfg** [comment]
use baritone and schematica to do it

**Comment by recklezzzdingo** [comment]
The forge API for impact doesnt work with the baritone mod and i need the alt manager built into the client

**Comment by sedfg** [comment]
you know .b schematica exists? Use the (built in macro mod) to bind the a letter ".b resume" and ".b schematica" and then get an auto click to press the button every 30 seconds: problem solved.

**Comment by S-B99** [comment]
Closed due to inactivity and resolution.
