### ISSUE TITLE
Impact opens and runs on startup, crashes whenever entering a world (either single-player or multiplayer) 

### ISSUE THREAD

**Issue by GenerelSchwerz** [ImpactDevelopment/ImpactIssues#1916]
**Describe the bug**
Impact opens and runs on startup, crashes whenever entering a world (either single-player or multiplayer) CRASHES ON PLAYER BUTTON INPUT (entity movement)

**To Reproduce**
1. Install Impact normally
2. Launch from Minecraft launcher
3. Join a game
4. Move the character's position in any way (You can look around)

**Expected behavior**
I expected the game to run normally as it boots to the title screen correctly, yet it crashes whenever entering any world.

Screenshots:
![image](https://user-images.githubusercontent.com/43506958/71550523-b5cf7680-29a0-11ea-992f-71317b279e65.png)
Client does open

![image](https://user-images.githubusercontent.com/43506958/71550521-b0722c00-29a0-11ea-9efd-eb157ac4183a.png)
Impact settings are available

![image](https://user-images.githubusercontent.com/43506958/71550527-c8e24680-29a0-11ea-9f23-0a8a3d865e83.png)
Worlds open

![image](https://user-images.githubusercontent.com/43506958/71550532-d697cc00-29a0-11ea-8c11-b80a6d0f835c.png)
Entry into world works, crashes on player input

- Impact Version: 4.8.2 for 1.14.4
- Using Optifine?  No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 8.1 x64 bit

Full crash file: 
[crashlog.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4007582/crashlog.txt)

**Comment by 0-x-2-2** [comment]
jvm crash `C:\Users\PeteDad-Admin\AppData\Roaming\.minecraft\hs_err_pid11388.log` file is missing. but this is probably caused by opengl drivers crashing.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
