### ISSUE TITLE
#goto Shulker_Box

### ISSUE THREAD

**Issue by Jaym-null** [ImpactDevelopment/ImpactIssues#1926]
**Is your feature request related to a problem? Please describe.**
In baritone there is currently no way for you to find all shulker_boxes within a radius. 

**Describe the solution you'd like**
One command #goto shulker_box that would path to ANY nearby shulker. 

**Describe alternatives you've considered**
A user-created list-type system that can automatically run multiple commands in quick succession for the same end result. 

**Additional context**

**Comment by ThebesAndSound** [comment]
for baritone github
