### ISSUE TITLE
List system

### ISSUE THREAD

**Issue by Jaym-null** [ImpactDevelopment/ImpactIssues#1927]
**Is your feature request related to a problem? Please describe.**
when performing a command such as '#goto -10000 64 -10000'
there is no option to stop pathing IF something else were to occur. for instance you encountered a shulker_box.

**Describe the solution you'd like**
When the entity is detected and picked up by an ESP. a command is run to path directly to the object. and pause to wait for further user interaction. 

**Describe alternatives you've considered**
There are no alternatives to this solution. 

**Additional context**

**Comment by ThebesAndSound** [comment]
this issue is to do with baritone not impact, use the baritone github
