### ISSUE TITLE
Tracers to stationary entities + stationary entity selection. 

### ISSUE THREAD

**Issue by Jaym-null** [ImpactDevelopment/ImpactIssues#1928]
**Is your feature request related to a problem? Please describe.**
At the moment there is no option for tracers to be shown on chests, shulkers, end_chests etc. 
It would be nice if there were tracers to these objects, and also that there was optionality...for instance you only wanted shulker_box to have tracers. 

**Describe the solution you'd like**
An ability to give things like Chests, ender chests and Shulker_boxes tracers. 

**Describe alternatives you've considered**
No alternatives to this solution

**Additional context**

**Comment by ThebesAndSound** [comment]
isn’t this what the search module does
