### ISSUE TITLE
design suggestion and feature suggestion

### ISSUE THREAD

**Issue by hit3** [ImpactDevelopment/ImpactIssues#1929]
add rainbow in every visual modification and also add pvp stuff like keystrokes or cps

**Comment by Aaron2550** [comment]
add rainbow rainbows, +1

**Comment by fox777hks** [comment]
Can you please add that the bot always runs at the same points and that alternately first point 1, then point 2 and so on ...

Like a guard who always walks the same way.

**Comment by 0-x-2-2** [comment]
click rainbow
