### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by kevin3002** [ImpactDevelopment/ImpactIssues#1934]
Could auto trading with villagers become added? This way it's possible to not only farm crops or ores but also get ANY echanted book easily

**Comment by kevin3002** [comment]
It's always a pain to do it manually. The scicraft guys automated it already.

**Comment by ScanmanTM** [comment]
### **Please add a brief but descriptive title**

**Comment by S-B99** [comment]
This is an issue for the baritone repo
