### ISSUE TITLE
Add Aimbot Option for Miningdead gamemode on Havooc server

### ISSUE THREAD

**Issue by baolam0000** [ImpactDevelopment/ImpactIssues#1936]
**Is your feature request related to a problem? Please describe.**
i have seen impact have aimbot for a lot of minigames , so could you guys make for miningdead ?

**Describe the solution you'd like**
maybe change some old aimbot code

**Describe alternatives you've considered**
i was try to using another aimbot option in impact client seem not working perfectly
**Additional context**
This is server IP : miningdead.com

**Comment by S-B99** [comment]
Too specific and out of scope. 

Also literally nobody's heard of that server
