### ISSUE TITLE
Invert the way the "#sel ca" starts removing blocks

### ISSUE THREAD

**Issue by Yakshongas** [ImpactDevelopment/ImpactIssues#1937]
**Is your feature request related to a problem? Please describe.**
When I try to use the "#sel ca" it always starts from bottom to top
**Describe the solution you'd like**
Make the "#sel ca" start removing blocks from top to bottom
**Describe alternatives you've considered**
***
**Additional context**
***

**Comment by ScanmanTM** [comment]
1. Baritone stuff goes to the [baritone github](https://github.com/cabaletta/baritone/issues)
2. https://baritone.leijurv.com/baritone/api/Settings.html#layerOrder
