### ISSUE TITLE
Can't connect to any server.

### ISSUE THREAD

**Issue by dowoge** [ImpactDevelopment/ImpactIssues#1939]
**Describe the bug**
When i join a server i get the same error even after reinstalling everything. (minecraft, Impact, java, drivers)

**Screenshots**
![image](https://user-images.githubusercontent.com/59783653/72213530-cf071580-34be-11ea-803b-53b5f533cd4d.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NullPointerException
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  For 1.14.4
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  none since i can't even load on a server
- Operating System:  Windows 10 64bit

</details>

**Logs**
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4050156/latest.log)

**Comment by TheReaper1244** [comment]
This happened to me too but I tried going into a single player game and disabling all my hacks and then that fixed it

**Comment by mendel3** [comment]
this is rly weird, for anyone looking at this in the future, the minecraft IGN DOwOge is not the github account dowoge, I don't hack

**Comment by dowoge** [comment]
> this is rly weird, for anyone looking at this in the future, the minecraft IGN DOwOge is not the github account dowoge, I don't hack

lol?
