### ISSUE TITLE
Can't scroll clickgui with arrow keys on 1.12

### ISSUE THREAD

**Issue by xehpos** [ImpactDevelopment/ImpactIssues#1941]
The discord doesnt seem to be working but thats not my main problem.

**Is your question request related to a problem? Please describe.**
There are parts of the client that cannot be accessed without a scroll wheel. In the Tabs within the ClickGUI there are items that cannot be accessed without a scroll wheel or a select few can me accessed through .toggle or .bind commands.

**Describe what you are trying to achieve**
I would like some assistance on a alternative way of scrolling throughout the menus, if there isn't one then I would want one included.

**Additional context**
I am running version 4.8.3 on forge, no optifine, and 1.12.2.
I have no mouse with a scroll wheel and have no knowledge of any working alternative to the scroll wheel. I have tried to used the arrow keys and etc. but with no luck.

**Comment by LeafHacker** [comment]
This is incorrect. You can scroll tabgui frames using the up/down arrow keys. First click on a frame (category menu window thing) then press arrow keys.

**Comment by LeafHacker** [comment]
Hm, this appears to be broken on 1.12.2

**Comment by LeafHacker** [comment]
will be fixed in the next release/nightly
