### ISSUE TITLE
Auto eat bugged while tunneling

### ISSUE THREAD

**Issue by crispylemons** [ImpactDevelopment/ImpactIssues#1945]
When using baritone and auto eat it bugs out and it gets stuck eating food forever. This is an old unfixed issue.

https://github.com/ImpactDevelopment/ImpactIssues/issues/1903
https://github.com/ImpactDevelopment/ImpactIssues/issues/1902

**Comment by ScanmanTM** [comment]
You don't need to make a new issue just to tag old issues, not necessary at all!
