### ISSUE TITLE
Mob spawn overlay

### ISSUE THREAD

**Issue by Triggerhacks** [ImpactDevelopment/ImpactIssues#1946]
**Is your feature request related to a problem? Please describe.**
The light option allows increasing of gamma, but that makes it difficult to recognise where mobs can spawn.

**Describe the solution you'd like**
An option that allows an overlay that shows where mobs can spawn on blocks depending on light level and day/night.

**Describe alternatives you've considered**
I think Optifine supports this, but as it increases the chance of crashing the game I'd rather not use it

**Comment by aUniqueUser** [comment]
You can use F3 to view the light level, or just temporarily turn off light.

**Comment by Mcknife96** [comment]
Nah that really is a useful module to have your base completely lit up.
WWE has it and it is a bit laggy but works.

**Comment by S-B99** [comment]
Duplicate of #1597
