### ISSUE TITLE
keep spining around nonstop even after rebooting

### ISSUE THREAD

**Issue by rals423** [ImpactDevelopment/ImpactIssues#1950]
i have just vanilla and this. I have no idea how to fix this. its no my mouse or something. in normal mine craft it works fine.

**Comment by Aaron2550** [comment]
How about using a template for issues? Just turn off AntiAim or all modules and see what happens

**Comment by TheLastShifu** [comment]
You most likely had antiAFK on

**Comment by TheReaper1244** [comment]
Yeah you probably just turned anti AFK on by accident
