### ISSUE TITLE
.goto <something> should have an option to always be on and search for stuff

### ISSUE THREAD

**Issue by 7ony2** [ImpactDevelopment/ImpactIssues#1951]
The search function in Impact has a smaller range than the .goto <something> function. 
I was just looking for nether portals and when I saw one, I typed .b goto portal. Portal blocks that were hundreds of blocks away in unrendered (and unloaded from my client) chunks highlighted. They were only highlighted by search when I got closer.
There should be a way to keep the .goto <something> function always on (but not going towards that object) so that you could spot things from further away.

Another solution could be editing the Search function of Impact to have the same range of Baritone's .goto <>

**Comment by 7ony2** [comment]
Closed it by accident

**Comment by Gruigi** [comment]
ive noticed this it kinda pisses me off

**Comment by 0-x-2-2** [comment]
> Another solution could be editing the Search function of Impact to have the same range of Baritone's .goto <>

Baritone caches every chunk you have EVER loaded on disk as solid and not solid with some extras like portal or ender chest. This literally only works for "special" blocks like portals otherwise it does not work at all.

**Comment by S-B99** [comment]
Wait, where's the relevant code for that? Just curious

**Comment by 0-x-2-2** [comment]
> Wait, where's the relevant code for that? Just curious

The entire pathfinder.

**Comment by S-B99** [comment]
I meant the saving special blocks part

**Comment by 0-x-2-2** [comment]
Part of the format spec.

https://github.com/cabaletta/baritone/blob/17a06621f5149c1f76e52a7b946e7774ccf0cc95/src/main/java/baritone/cache/CachedRegion.java#L113

**Comment by S-B99** [comment]
Thanks <3
