### ISSUE TITLE
Mutable bugs in the macro system.

### ISSUE THREAD

**Issue by crispylemons** [ImpactDevelopment/ImpactIssues#1953]
## Describe the bug
The macro tab is a great feature just has a lot of bugs. There are four bugs. When creating the macro the second box which appears (after you add your first command in the macro) does not allow you to input text preventing mutable commands in one macro. Secondly when deleting the macro the key it was bound to will still run the macro, the macro is only deleted from the macro menu. Finally, If you have more than one macro you can only select them with right click. There are lot more like if you have a macro with mutable commands it does not show any of them. The whole macro system is very broken.

## How to reproduce
Self-explanatory

## Snapshot and version
Minecraft Version: 1.14.4
Impact Version: Impact nightly release 19
Using Optifine: OptiFine_1.14.4_HD_U_F5
Operating System: Windows 10 Pro
Using LiteLoader: N/A
Enabled mods: N/A

**Comment by MightyKnight** [comment]
Closing this as it covers multiple issues. See #2191, #2323.
