### ISSUE TITLE
impact 4.8.3 not working in +1.13.2 versions

### ISSUE THREAD

**Issue by jesinhell** [ImpactDevelopment/ImpactIssues#1955]
in impact 4.8.3 1.13.2 when i want to join any world or server, the world cannot loading.
it just stuck on loading world screen
here is my log 
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4109039/latest.log)

**Comment by S-B99** [comment]
> 2 million characters
> log is bigger then literally kami blue

Looks like something is throwing an NPE over and over again. That's huge holy shit

**Comment by Snowflake101** [comment]
It appears that a lot of the date in the log file is copy pasted?

**Comment by S-B99** [comment]
That's what I just said. An NPE is being thrown. @jesinhell can you please try reinstalling impact and see if the issue still happens with a clean `.minecraft`

**Comment by berrely** [comment]
Closed as stale
