### ISSUE TITLE
any version of impact dont start on 1.12.2

### ISSUE THREAD

**Issue by setysty** [ImpactDevelopment/ImpactIssues#1956]
**Describe the bug**
i installed impact with tutorial and run minecraft. on any version minecraft dont run, if i click play game dont started and minecraft stay open. if i click play 2 times, it be same, game dont started and launcher stay open.

- Impact Version: any for 1.12.2 minecraft
- Using Optifine? No
- Using LiteLoader? no
- Enabled mods: none
- Launcher: Titan minecraft laucher
- Operating System: Windows 10 64bit

**Comment by ScanmanTM** [comment]
Don't use a cracked launcher.
