### ISSUE TITLE
Impact chat (.) commands do not work

### ISSUE THREAD

**Issue by boasbakker** [ImpactDevelopment/ImpactIssues#1958]
All impact commands (starting with `.`) Do not work. For example, if I type `.help` in the chat, 'help' is literally said in the chat and it does nothing.

**Comment by ScanmanTM** [comment]
1. Do you even have impact loaded
2. Did you change the prefix

**Comment by LeafHacker** [comment]
> if I type `.help` in the chat, 'help' is literally said in the chat

Did you mean '.help' is printed to chat? It'd be very weird if typing '.help' printed as 'help'.

**Comment by boasbakker** [comment]
I mean .help is printed to chat.
I don't know how to change the prefix, so that can't be the case.
And I'm sure that I have impact loaded.
I use forge impact with other mods like minimap and 5zig, maybe that is the problem?

**Comment by S-B99** [comment]
How are you sure impact is loaded? And what other mods do you have, list *all* of them.

**Comment by S-B99** [comment]
Closed due to no response. Please reopen with more information
