### ISSUE TITLE
How can I get the source code?

### ISSUE THREAD

**Issue by EinsteinZheng** [ImpactDevelopment/ImpactIssues#1960]
I cannot use Discord

**Comment by ScanmanTM** [comment]
Impact source code isn't available for you to copy and paste from.

**Comment by flarn2006** [comment]
Why not?

**Comment by dominikaaaa** [comment]
> Impact source code isn't available for you to copy and paste from.

try having some reading comprehension. it's not available so you don't copy and paste from it.
