### ISSUE TITLE
Queue End Alert

### ISSUE THREAD

**Issue by Perry1900** [ImpactDevelopment/ImpactIssues#1966]
**Is your feature request related to a problem? Please describe.**
It isn't related to a problem in the client but it can really help casual 2b2t players without priority queue that afk in the queue and then find out they got afk kicked.

**Describe the solution you'd like**
My solution to this is a module that alerts you when you get in the server by playing a sound in the output audio device that you choose.

**Describe alternatives you've considered**
A module that /msg's you random stuff or sends a slight movement packet (around) every minute if you get in and don't play.

**Additional context**

**Comment by lummeta25** [comment]
or you can link the client to discord and you get a message

**Comment by S-B99** [comment]
Please see these 2 projects
https://github.com/themoonisacheese/2bored2wait
https://github.com/EmotionalLove/ReMinecraft

**Comment by Perry1900** [comment]
I didn't know you can link impact to discord to get a notification

The first project doesn't help me unless it prevents afk kick because I still won't know when I get in

I didn't really unserstand what the second project does

**Comment by S-B99** [comment]
It's a proxy which you can host yourself, which I'm pretty sure supports sending queue position to a webhook

**Comment by Luggibumm** [comment]
For the movement packet part use anti afk and i would advise you to activate autoeat as well!

**Comment by Perry1900** [comment]
Antiafk can kill me, can't it? I think it should just be another mode for antiafk

**Comment by Luggibumm** [comment]
How should it kill you? Just turn on walk and spin!

**Comment by S-B99** [comment]
That doesn't work. 2b's AntiAFK plugin is a lot more advanced.

**Comment by Perry1900** [comment]
I googled 2b2t afk kick and people said that talking in chat prevents afk kick and that you can /w yourself to do it without having people block you (it makes sense because bots don't get kicked often)
Btw antiafk can kill me because I am sometimes near lava

**Comment by Luggibumm** [comment]
What does it test for?
I've never been afk on 2b2t.
When im on i play

**Comment by S-B99** [comment]
This isn't even related to the original issue, and whispering to yourself or a similar message to random people is also patched.

**Comment by Luggibumm** [comment]
Perry1900 so dont afk near lava?!
And i dont really talk much in chat on 2b2t and still dont get kicked! As far as i know you can get kicked when the player is not walking for a while thats why you have to sometimes make pauses when entity speeding

**Comment by Luggibumm** [comment]
But i think you should remove the afk part and open a separate issue if you want to ask for a better antiafk mod!

**Comment by leijurv** [comment]
Very dumb question. First, just turn up your audio, a sound effect plays at queue positions 1 through 5. Second, turn on anti afk for your other request.

**Comment by S-B99** [comment]
LMAOOO i forgot, it actually does. I wonder if once this was added they would submit a bug report that the sound doesn't work.

**Comment by Perry1900** [comment]
It does but it plays it on my headsets and idk why but Minecraft doesn't allow me to change audio output device while the game is open (it just stops playing audio, and it isn't only in impact)

**Comment by S-B99** [comment]
That's not my fault. If impact added this you'd have the same issue 🧠

**Comment by Perry1900** [comment]
There is probably a way to make a specific sound play on a different audio output device (like most games have for voice chat but I am not sure it can be done the same way bc it is different coding lanuages)

**Comment by S-B99** [comment]
That's literally a you issue. That's your fault. I can personally just select which device to use. It's not the Impact authors fault that your audio doesn't work. 
![2020-02-28-110317_1920x1080_scrot](https://user-images.githubusercontent.com/17222512/75564328-ef147900-5a19-11ea-8f99-29d59f11fb70.png)
![2020-02-28-110315_1920x1080_scrot](https://user-images.githubusercontent.com/17222512/75564329-efad0f80-5a19-11ea-82b3-f4c6c3fe4d51.png)

**Comment by Aaron2550** [comment]
After changing ur audio device, Minecraft is a lil cunt and stops outputting audio, press F3 and T to reload some stuff and it works again

**Comment by Perry1900** [comment]
THANK YOU SO MUCH
