### ISSUE TITLE
AntiBats

### ISSUE THREAD

**Issue by GreenMan36** [ImpactDevelopment/ImpactIssues#1970]
**Is your feature request related to a problem? Please describe.**
I hate bats, they fly and sqeek

**Describe the solution you'd like**
Removes all bat models/doesn't render them. Mutes the bats. Also excludes them from any other hack like aimbot or killaura. They do nothing, they're there to not be there.

**Describe alternatives you've considered**
Resource pack. Doesn't really do it since the client still targets them.

**Additional context**
Seems to be included in ForgeHax.

**Comment by S-B99** [comment]
I'm glad [redacted] isn't as big as impact because of stupid issues like this

**Comment by StijnSimons** [comment]
minecwaft scwawy uwu >.<
