### ISSUE TITLE
You want to provide language file configuration items

### ISSUE THREAD

**Issue by XiaoZhengRS** [ImpactDevelopment/ImpactIssues#1974]
你们好Impact的团队,我是来自中国的一名Minecraft玩家,在使用你们提供的Impact中,感到十分困难,每个功能选项都需要翻译,对于一些母语非英文的玩家,没有语言配置文件是一个加入Impact使用者的一个很高门槛,这也不适于将Impact推向国际化,如果加上语言配置文件,我愿意提供中文的翻译.
Hello, impact team, I'm a minecraft player from China. It's very difficult to use the impact provided by you. Every function option needs to be translated. For some non English native speakers, no language profile is a high threshold for those who join the impact, which is also not suitable for promoting the impact to internationalization. If I add language profile, I'd like to Provide Chinese translation

**Comment by S-B99** [comment]
yes please give them repo access to translate

**Comment by takecmd** [comment]
I'd like to provide the Chinese translation, too

**Comment by StijnSimons** [comment]
> yes please give them repo access to translate

Why would they need repo access? Won’t just any language file work here?

**Comment by 0-x-2-2** [comment]
#1504
