### ISSUE TITLE
Can the current function solve this problem

### ISSUE THREAD

**Issue by zengkuankuan** [ImpactDevelopment/ImpactIssues#1975]
You sense that there might not be many
fish left in this area. Try fishing at least 3 
blocks away.

**Comment by zengkuankuan** [comment]
![QQ图片20200206124233](https://user-images.githubusercontent.com/53440794/73906746-eb8c4700-48de-11ea-9d21-5c06da9d99a5.png)

**Comment by Aaron2550** [comment]
Already suggested this, see https://github.com/ImpactDevelopment/ImpactIssues/issues/1457

**Comment by zengkuankuan** [comment]
> 已建议使用此方法，请参阅[＃1457](https://github.com/ImpactDevelopment/ImpactIssues/issues/1457)

It doesn't seem to solve the problem

**Comment by S-B99** [comment]
Yes it does...

**Comment by Aaron2550** [comment]
**AaronVB labeled this 11seconds ago: duplicate**
