### ISSUE TITLE
Internal Impact chat

### ISSUE THREAD

**Issue by Daenges** [ImpactDevelopment/ImpactIssues#1976]
**Is your feature request related to a problem? Please describe:**
I saw it in other clients and I think it would be an interesting feature to chat with other Impact users regardless of server or version.

**Describe the solution you'd like:**
So my idea is that you have an "Impact-users-only" chat which you can activate through the Hud and every user can see it in the normal mc chat if activated.
It would not depend on servers or versions and would show your username.

**Describe alternatives you've considered:**
An idea would be, beside the global chat, to let the users create sub-chats, so small groups they can chat in for example. (Like a party chat on servers, just they can do it not depending on servers)
Also you could ask directly through the client for help to other users who are more used to the client and get fast support.

**Additional context:**
I'm not that familiar with the technical stuff behind it, so be patient if you see that this request is actuly hillarious. But I think it would be cool and would kind of strength the community.

**Comment by S-B99** [comment]
So basically, irc

**Comment by S-B99** [comment]
Duplicate of #124

**Comment by Daenges** [comment]
Oh sorry! But yeah kind of that. Sorry didn't found the other one! :)
