### ISSUE TITLE
Impact Forge disabled some mods.

### ISSUE THREAD

**Issue by xinxcode** [ImpactDevelopment/ImpactIssues#1977]
Game Version: Forge 1.12.2
Impact Version: Latest - 1.12.2 - Forge
Im plating Omnifactory Mod, before using Impact, all recipes are appear in the JEI, like Crafting Table, Blast Furnace, etc. After installing Impact, some of the recipes are vanished, usually just Crafting Table's recipe that appear in the recipe GUI.
Im trying to reinstall the mod without Impact, and yea, it's fixed.. then I install Impact again, and now Im sure that some mods area disabled after Im installing Impact.
Please help me.
Thanks.
Love Impact.

**Comment by ScanmanTM** [comment]
Maybe impact forge is conflicting with the mod.
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
