### ISSUE TITLE
Add "multiconnect" from Earthcomputer.

### ISSUE THREAD

**Issue by Daenges** [ImpactDevelopment/ImpactIssues#1979]
**Is your feature request related to a problem? Please describe.**
At the moment you need to download the installer and install every version of the client seperatly, which is especially very tidious if you want to switch between several servers on different versions.

**Describe the solution you'd like**
I found multiconnect as a feature in another client. It's especially interesting for 1.15, because, as earthcomputer states, you can connect to servers down to version 1.13 without closing the game once.

**Additional context**
I saw that he released it as a fabric mod. I'm not that familiar with the technical stuff and didn't found another one suggesting this, so correct me if I'm wrong somewhere.

https://github.com/Earthcomputer/multiconnect

**Comment by 0-x-2-2** [comment]
Clientside Protocol hacks are flawed and do flag anti-cheats. There is a more complete mod here using ViaVersion on the client: https://github.com/ViaVersion/ViaFabric.

**Comment by Daenges** [comment]
Well in the end I don't really care about how it will be implemented, more that it will be implemented.
