### ISSUE TITLE
Forge 1.12.2 versions of impact, dont work

### ISSUE THREAD

**Issue by Cryptises** [ImpactDevelopment/ImpactIssues#1981]
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4178955/latest.log)
Minecraft does open in the task manager, but it never actually shows up, RAM goes up to almost 1GB and then goes back down to around 877MB. Never appears.
jre 8u241
(Yes I am using official)
[Mod list.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4178914/Mod.list.txt)

**Comment by S-B99** [comment]
Make sure you're using the official Minecraft launcher and jre 8u241

Also please provide your log and what other mods you're using

**Comment by Cryptises** [comment]
Minecraft never shows a crash log, as I always have to close it via Task manager, never shows up, never closes itself

**Comment by S-B99** [comment]
You can find logs in the .minecraft folder, as indicated by the issue template which you deleted.

**Comment by S-B99** [comment]
Also please follow the rest of the directions I gave you

**Comment by Cryptises** [comment]
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4178920/latest.log)

**Comment by Cryptises** [comment]
I see, I dont have the latest version of java. I suppose that's important, I will get that and try again

**Comment by Cryptises** [comment]
Nope, that did not fix

**Comment by S-B99** [comment]
Make sure your paths are set and you're using the latest. Check by running `java -version` in a terminal. Also make sure it is **jre** not **jdk**

**Comment by S-B99** [comment]
I looked at your log and it seems to be an issue with other core mods you have installed. Please try running only impact

**Comment by Cryptises** [comment]
I did, it ran properly

**Comment by S-B99** [comment]
Try readding your mods 1 by 1 and see what breaks it. Also see this https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

**Comment by Cryptises** [comment]
Alright I will try that.
