### ISSUE TITLE
Impact download doesnt work

### ISSUE THREAD

**Issue by mxhd** [ImpactDevelopment/ImpactIssues#1983]
The impact download (http://evassmat.com/K4AN) doesnt work, how can I solve this issue

**Comment by aUniqueUser** [comment]
[Download from the impact website ](https://impactclient.net)

**Comment by S-B99** [comment]
♿

**Comment by mxhd** [comment]
> [Download from the impact website ](https://impactclient.net)

when ever i download from there it takes me to that website and that website doesnt work

**Comment by mxhd** [comment]
> [Download from the impact website ](https://impactclient.net)

when ever i download from there it takes me to that website and that website doesnt work

**Comment by S-B99** [comment]
No it doesn't? Click the link to the actual impact website

**Comment by aUniqueUser** [comment]
https://impactclient.net/?brady-money-grubbing-completed=true

**Comment by ScanmanTM** [comment]
I would like to contribute to this issue, that link on the website does bring you to that evassmat link as its the adfly.
