### ISSUE TITLE
 shields aren't working while using swords 

### ISSUE THREAD

**Issue by HyperDexter** [ImpactDevelopment/ImpactIssues#1984]
While holding swords shields appear to not work even if they rise normally, arrow will hit and do damage, shield durability will not lower as if it's not used, it's still being tested but it appears that even blast damage (as a creeper esplosione) ins't reduced 
all these problems arise only if you have a sword in the main hand, with any other item the shield work normally and lose durability as intended,
I have already tried switching off any combat related hack that I may misused with no effects.

**Comment by mapokapo** [comment]
I'm having the same issue, shield rises in between attacks, but doesn't block anything

**Comment by MightyKnight** [comment]
This is likely caused by NoSlow, see #467
