### ISSUE TITLE
Can i put the impact in a modpack?

### ISSUE THREAD

**Issue by MendicraftGamer** [ImpactDevelopment/ImpactIssues#1986]
Hi, when i install the impact in a modpack on technic launcher the modpack dons´t open, Can you help me?

**Comment by S-B99** [comment]
use the official launcher. unofficial ones are not supported.

**Comment by MendicraftGamer** [comment]
i´m using

**Comment by S-B99** [comment]
no you're not. you said technic launcher in your issue

**Comment by S-B99** [comment]
if your modpack is forge based you can take the impact forge jar and insert it.

**Comment by MendicraftGamer** [comment]
i´m doing that

**Comment by MendicraftGamer** [comment]
the mod is tekxit 3 (official)

**Comment by MendicraftGamer** [comment]
ok, i put the mods in te minecraft launcher and run normally ,so i install the impact and start crashing again

**Comment by MendicraftGamer** [comment]
maybe the impact is incompatible with some mods

**Comment by S-B99** [comment]
please see the incompatibility faq page

**Comment by MendicraftGamer** [comment]
ok

**Comment by MendicraftGamer** [comment]
where i see that?

**Comment by S-B99** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

**Comment by MendicraftGamer** [comment]
tks

**Comment by MendicraftGamer** [comment]
is that, somo mods make the game crash with impact
