### ISSUE TITLE
smoothaim isnt working during baritone

### ISSUE THREAD

**Issue by JJ1112** [ImpactDevelopment/ImpactIssues#1992]
**Describe the bug**
today i was trying to use baritone with smoothaim on but smooth aim only moved up and down and not horizontal.

**To Reproduce**
1. enable smooth aim and killaura
2. let baritone explore a certain area
3. wait for a target to get in range

**Expected behavior**
i was expecting the smooth aim to target the mob but it didnt go to the mob (precision above 1 so its supposed to be on the hitbox)

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.8.2
- Using Optifine?  yes
- Using LiteLoader?  no
- Enabled mods:  middle click friends auto cheat, auto reconnect, killaura single, auto weapon, log position, autoarmor, smooth aim, antivanish, nametags, autoeat, tracers, light 
- Operating System:  windows 10 64bit

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
Can't reproduce this in latest.
