### ISSUE TITLE
All of Optifine for Minecraft 1.14.4 crashes with Impact.

### ISSUE THREAD

**Issue by MateoDoge** [ImpactDevelopment/ImpactIssues#1995]
**Describe the bug**
Optifine, when combined with Impact, ALWAYS crashes.

**To Reproduce**
Download any 1.14.4 version of Optifine.
Download Impact 4.8.3 with Optifine
Start minecraft

**Expected behavior**
A crash.
 

- Impact Version:  4.8.3. for minecraft 1.14.4
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods:  none
- Operating System:  Windows 10

**Comment by Aaron2550** [comment]
Typo: You apparently expect a crash

Ya got any logs for us? You can enable the logging console in the launcher settings or copy the log from your .minecraft folder. **Remember that _AFAIK_ launchers other than the official MC launcher arent supported**

**Comment by S-B99** [comment]
It's recommended not to use Optifine with Impact, it causes too many issues. Though you shouldn't have an entire crash.

**Comment by MateoDoge** [comment]
Im using the official MC launcher. @Aaron2550 , ping me in the Discord so i can share with you the crash logs.

**Comment by Aaron2550** [comment]
The error is always

> java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/TextureUtil
> 	at cuo.a(MainWindow.java:213)
> 	at cuo.a(MainWindow.java:172)
> 	at cyc.au(SourceFile:469)
> 	at cyc.b(SourceFile:394)
> 	at net.minecraft.client.main.Main.main(SourceFile:155)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: com.mojang.blaze3d.platform.TextureUtil
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 11 more
> Caused by: java.lang.SecurityException: class "com.mojang.blaze3d.platform.TextureUtil"'s signer information does not match signer information of other classes in the same package
> 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
> 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 13 more

Crashes happen for me too, see [http://stronghold.host/u/dPl8ugWAajvn.png](http://stronghold.host/u/dPl8ugWAajvn.png), using 4.8.3 and Optifine F4. Its AFAIK not related to the graphics "card" Im using a RX 5700 XT and @MateoDoge is using a Intel(R) UHD Graphics 620

**Comment by Aaron2550** [comment]
Before installing `4.8.3 with F4`, `4.8.0-20190824-nightly with optifine F3` ran perfectly fine for me. Now im getting

> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 16.02.20 22:22
> Description: Unexpected error
> 
> java.lang.NullPointerException: Unexpected error
> 	at cyc.e(SourceFile:931)
> 	at cyc.b(SourceFile:410)
> 	at net.minecraft.client.main.Main.main(SourceFile:155)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.14.4
> 	Minecraft Version ID: 1.14.4
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 3185544720 bytes (3037 MB) / 4294967296 bytes (4096 MB) up to 6442450944 bytes (6144 MB)
> 	CPUs: 12
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Launched Version: 1.14.4-Impact_4.8.0-20190824-nightly-OptiFine_HD_U_F3
> 	LWJGL: 3.2.2 build 10
> 	OpenGL: AMD Radeon RX 5700 XT GL version 4.6.13586 Compatibility Profile Context 19.12.3 26.20.15003.5016, ATI Technologies Inc.
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Very likely; Jar signature invalidated
> 	Type: Client (map_client.txt)
> 	Resource Packs: vanilla, file/AaronBase, file/AaronBetterLeavesModule
> 	Current Language: English (US)
> 	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 

everytime im trying to run it...

**Comment by ZeroMemes** [comment]
>It's recommended not to use Optifine with Impact, it causes too many issues. Though you shouldn't have an entire crash.

Errors with the most recent nightly builds have been reduced, basically all that remains is Xray compatibility.

**Comment by S-B99** [comment]
Ah alright, good to know.

**Comment by S-B99** [comment]
There was a recent update pertaining Optifine, please reopen this issue if it still happens.

**Comment by Aaron2550** [comment]
Still crashing with 1.14.4 Nightly 20200307 Optifine F5

**Comment by S-B99** [comment]
Please post your crash log.

**Comment by Aaron2550** [comment]
sry i didnt get an email for some reason. it seems newer nightlies work, it was probably just that one.
crash log here: [https://pastebin.com/xUuNpWFF](https://pastebin.com/xUuNpWFF)

**Comment by S-B99** [comment]
If the newer ones work then this can be closed.
