### ISSUE TITLE
Tunneller Feature (1x2, 2x2, 3x3)

### ISSUE THREAD

**Issue by TwilightKillerX** [ImpactDevelopment/ImpactIssues#1997]
**Description**
A feature which allows the customisation of baritone's tunnel command, with the inclusion of tunnel sizes. For example: **tunnel (width) (height) (depth)**; if unspecified defaults to 1x2 mining.

**Describe alternatives you've considered**
- A possible solution is mentioned in [this ](https://github.com/cabaletta/baritone/pull/740/files/a354e1ba60eeb3579487414c5698701cdd6b7590#diff-6c14664f9f5156056826fb139767ccb1), the feature was discussed [in this](https://github.com/cabaletta/baritone/issues/474) pull request
- #tunnel can be used 3 times with resets to the original position, to create a _x_*2 tunnel, but this is time-consuming

**Additional context**
![3x3 Tunnel Example](https://user-images.githubusercontent.com/61162878/74681391-32215180-51bb-11ea-95d0-5307ef8fa00a.png)

**Comment by ScanmanTM** [comment]
Why don't you make baritone related suggestions on the baritone github?

**Comment by ZeroMemes** [comment]
https://github.com/cabaletta/baritone/issues
