### ISSUE TITLE
InventoryMove does not work.

### ISSUE THREAD

**Issue by freaky767** [ImpactDevelopment/ImpactIssues#2000]
Using Forge 1.12.2, while in inventory, you can't move, with module "inventory"

- Impact Version: 4.8.3 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Just inventory, also am using AdvancedMacros mod
- Operating System: Windows 10

**Comment by ScanmanTM** [comment]
### Thank you for using the wiki, the community carefully put it together for others to use and gain knowledge!
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#inventory-move-doesnt-work-on-1122-forge

**Comment by S-B99** [comment]
mfw they waste issue #2000 on something like this
