### ISSUE TITLE
Cant Launch the game at all and get an error when i do

### ISSUE THREAD

**Issue by ImaMadLad** [ImpactDevelopment/ImpactIssues#2002]
**Describe the bug**
when i try to run the game it comes up The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/TextureUtil

**To Reproduce**
1. Go to Minecraft Launcher
2. Click on Play
3. Scroll down to Error that pops up

**Expected behavior**
I expected the game to open and be able to play

**Screenshots**
![unknown 1](https://user-images.githubusercontent.com/61247658/74863014-15188a00-5345-11ea-9e0f-043c62cc72c5.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 for 1.14.4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: None cant load game
- Operating System: windows 10 64 bit

</details>

**Additional context**
dont know how to fill out the rest if you need more i can try find out how

**Comment by S-B99** [comment]
Remove Optifine
