### ISSUE TITLE
Get out of here macro

### ISSUE THREAD

**Issue by ijadenfellow** [ImpactDevelopment/ImpactIssues#2006]
Make a button for say when your in a cave and you want to get to the surface quickly or just autonomously you can click or set the button to a hotkey and then have it cancel whatever action baritone is doing and get you to the surface.

**Comment by ZeroMemes** [comment]
This is really an issue for [Baritone](https://github.com/cabaletta/baritone), once it is added as a Baritone command, the existing macro system in Impact could be utilized to execute the command with a designated key.
