### ISSUE TITLE
A small, but fun suggestion.

### ISSUE THREAD

**Issue by MateoDoge** [ImpactDevelopment/ImpactIssues#2008]
**Is your feature request related to a problem? Please describe.**
There is no problem. I see this as more of a silly addition.

**Describe the solution you'd like**
To add the "GGbot"(i think that's the name) to the "Minigame" tab. GGbot is a bot for hypixel which automatically says "GG" after an user wins/loses a match, so they get Karma.

**Describe alternatives you've considered**
I've considered downloading GGbot itself, but, as far as i know, i cant merge it with Impact.

**Comment by S-B99** [comment]
just add it as a forge mod.

**Comment by MateoDoge** [comment]
How?

**Comment by S-B99** [comment]
Drag and drop to mods folder

**Comment by MateoDoge** [comment]
Can i combine it with impact?

**Comment by S-B99** [comment]
Impact is closed source, you cannot. You can use both as forge mods.

**Comment by MateoDoge** [comment]
Oh, so i can only use them separately?

**Comment by S-B99** [comment]
No, you can use them at the same time.

**Comment by MateoDoge** [comment]
ah thanks

**Comment by S-B99** [comment]
https://www.reddit.com/r/Minecraft/comments/2w2agw/is_it_possible_to_use_multiple_mods_at_once/
