### ISSUE TITLE
4th exploreForBlocks asking

### ISSUE THREAD

**Issue by bphd** [ImpactDevelopment/ImpactIssues#2012]
It's literally the only and good repo for asking Impact improvements " Please use this repo to report bugs and request features "

So, for the 4th time, I ask this option https://baritone.leijurv.com/baritone/api/Settings.html#exploreForBlocks to be turned on by default with "non legit mining", it's just logically and so better with. And no i can't turn it by myself because i don't use baritone only but the Impact client, and in the menu of Impact, there's no options to activate it. If you don't find interest in that, so just add this option to Impact menu, it will be a real improvement for the users of the client, don't just think for yourself please

**Comment by S-B99** [comment]
Please stop creating issues. This is the wrong repo as well. 

This is how you configure baritone. https://github.com/cabaletta/baritone/blob/master/USAGE.md

The same baritone that is in impact is baritone.

**Comment by cookiedragon234** [comment]
Thank you for contributing this issue to the official bawitwone repo, leiwurv will implement this as soon as he figures out how to program bawitwone bots to find ancient debris
