### ISSUE TITLE
Cant sprint while baritone paused

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#2017]
1.14.4

**Comment by S-B99** [comment]
Please fill out the issue template properly.

**Comment by thegamerx1** [comment]
you have the information you need

**Comment by S-B99** [comment]
No I don't.

**Comment by thegamerx1** [comment]
you didnt even test it

**Comment by S-B99** [comment]
Fill out the issue template properly.

**Comment by thegamerx1** [comment]
happy now?

**Comment by S-B99** [comment]
If this is a baritone issue it should be in the baritone repo instead.

**Comment by thegamerx1** [comment]
but maybe is impact?

**Comment by S-B99** [comment]
No, this is a baritone issue.
