### ISSUE TITLE
[Minor] [visual] trajectories bug

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#2020]
Trajectories move when bow not loaded

https://youtu.be/m0FIMYEDUXo

**Comment by S-B99** [comment]
This is intentional. The show the pulled back path when the bow is pulled back.

**Comment by thegamerx1** [comment]
why would you want it to move when its not even loaded

**Comment by S-B99** [comment]
Idk, it's a cool animation. I didn't code it, and it's functional when you're using the bow. It's still intentional and not a bug.
