### ISSUE TITLE
[Minor] [visual] shield animation

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#2021]
Sheild animation makes item that you are switching from also block for a brief moment
mode: pandora
https://youtu.be/VsPHPL--X_M

**Comment by S-B99** [comment]
This is intentional.

**Comment by thegamerx1** [comment]
everything is intentional?

**Comment by S-B99** [comment]
No, intentional features are intentional.

**Comment by thegamerx1** [comment]
why would you want the bow to show like its blocking for a second

**Comment by thegamerx1** [comment]
you didnt even talk it with the devs..

**Comment by S-B99** [comment]
Oh now I see the issue. The item you were holding before blocking is also used to block because the block animation starts before it switches item.

**Comment by thegamerx1** [comment]
oh you didnt even watch the video..

**Comment by S-B99** [comment]
Also there's no need to put issue labels in the issue title, labels exist for that

**Comment by thegamerx1** [comment]
i cant add labels only you can

**Comment by S-B99** [comment]
And there's no need to put them in the issue title. This repo doesn't filter issues by whether or not the bug is minor or visual or whatever.
