### ISSUE TITLE
Timer doesn't work with replay mod

### ISSUE THREAD

**Issue by Zipdox** [ImpactDevelopment/ImpactIssues#2026]
**Describe the bug**
Timer doesn't work with replay mod installed.
What I did notice though is that the speed indicator in the HUD says you're going faster even though you're not.

**To Reproduce**
1. Install replay mod.
2. Turn on timer and set multiplier to something high.
3. Walk.
4. See how you move at the same speed as normal.

**Expected behavior**
You walk faster.
 
<details>
- Impact Version: 4.8.3
- Using Optifine? yes
- Using LiteLoader? no
- Enabled mods: timer
- Operating System: Debian GNU/Linux bullseye/sid x86_64

</details>

**Comment by S-B99** [comment]
That's a replay mod issue. https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
