### ISSUE TITLE
internal exception:java.lag.nullpointexception ERROR

### ISSUE THREAD

**Issue by Doula123** [ImpactDevelopment/ImpactIssues#2027]
Everytime I try to join a specific server : cubecraft I get the internal exception:java.lag.nullpointexception error.

**Comment by S-B99** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
