### ISSUE TITLE
Wireframes arent showing, light doesnt do anything, speed sometimes get you stuck underneath blocks, terrain doesnt affect how fast we move up ladders

### ISSUE THREAD

**Issue by BlackHanbo** [ImpactDevelopment/ImpactIssues#2032]
**Describe the bug**
"Wireframes" were turned on yet nothing changes.
"Light" arent making any difference even though im not using optifine
"Speed" sometime gets you stuck underneath blocks
"Terrain" doesnt affect your speed when going up ladders
**To Reproduce**
Just turn them on will do
Turn on speed while running in a 2 block high space

**Expected behavior**
To see the world with the block outline
Expected to see the world better as if with night vision
Undisrupted speeding around
Moving up ladders faster
**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
One bug report per issue.
