### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by YuHuanTin** [ImpactDevelopment/ImpactIssues#2033]
[crash-2020-03-02_12.35.24-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4275745/crash-2020-03-02_12.35.24-client.txt)

my game have four crashes a day
:(

**Comment by ScanmanTM** [comment]
Can you use the bug template, kthx.

**Comment by S-B99** [comment]
Please fill out the bug template properly.

**Comment by YuHuanTin** [comment]
i'm sorry but what is bug template????


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bella Who"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 晚上9:11
收件人:&nbsp;"ImpactDevelopment/ImpactIssues"<ImpactIssues@noreply.github.com&gt;;
抄送:&nbsp;"埃菲尔铁塔"<2394555023@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ImpactDevelopment/ImpactIssues] game crash (#2033)




Please fill out the bug template properly.

**Comment by S-B99** [comment]
The one that comes up when you create a new issue. https://github.com/ImpactDevelopment/ImpactIssues/issues/new/choose

**Comment by YuHuanTin** [comment]
then what should i do？------------------ 原始邮件 ------------------
发件人: "Bella Who"<notifications@github.com>
发送时间: 2020年3月4日(星期三) 晚上10:33
收件人: "ImpactDevelopment/ImpactIssues"<ImpactIssues@noreply.github.com>;
抄送: "YuHuanTin"<2394555023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ImpactDevelopment/ImpactIssues] game crash (#2033)



The one that comes up when you create a new issue. https://github.com/ImpactDevelopment/ImpactIssues/issues/new/choose
 
&mdash;

**Comment by S-B99** [comment]
Fill out the template properly.

**Comment by YuHuanTin** [comment]
have any example？ 😂😂😂😂------------------ 原始邮件 ------------------
发件人: "Bella Who"<notifications@github.com>
发送时间: 2020年3月4日(星期三) 晚上10:36
收件人: "ImpactDevelopment/ImpactIssues"<ImpactIssues@noreply.github.com>;
抄送: "YuHuanTin"<2394555023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ImpactDevelopment/ImpactIssues] game crash (#2033)



Fill out the template properly.
 
&mdash;

**Comment by S-B99** [comment]
I linked the example. It's the template that comes up when you create a new issue.

**Comment by YuHuanTin** [comment]
ok i will do in tomorrow------------------ 原始邮件 ------------------
发件人: "Bella Who"<notifications@github.com>
发送时间: 2020年3月4日(星期三) 晚上10:38
收件人: "ImpactDevelopment/ImpactIssues"<ImpactIssues@noreply.github.com>;
抄送: "YuHuanTin"<2394555023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ImpactDevelopment/ImpactIssues] game crash (#2033)



I linked the example. It's the template that comes up when you create a new issue.
 
&mdash;

**Comment by YuHuanTin** [comment]
how i should do?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bella Who"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 晚上10:38
收件人:&nbsp;"ImpactDevelopment/ImpactIssues"<ImpactIssues@noreply.github.com&gt;;
抄送:&nbsp;"埃菲尔铁塔"<2394555023@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ImpactDevelopment/ImpactIssues] game crash (#2033)




I linked the example. It's the template that comes up when you create a new issue.

**Comment by YuHuanTin** [comment]
oh i think i know how to do


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bella Who"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 晚上10:38
收件人:&nbsp;"ImpactDevelopment/ImpactIssues"<ImpactIssues@noreply.github.com&gt;;
抄送:&nbsp;"埃菲尔铁塔"<2394555023@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ImpactDevelopment/ImpactIssues] game crash (#2033)




I linked the example. It's the template that comes up when you create a new issue.
