### ISSUE TITLE
Mac gui stuck

### ISSUE THREAD

**Issue by TechAle** [ImpactDevelopment/ImpactIssues#2036]
**Describe the bug**
When you change your window, the gui wont open.

**To Reproduce**
1) alt + f3 and change windows.

- Impact Version: 4.8
- Using Optifine? 
- Using LiteLoader? No
- Operating System: Mac os catalina

</details>

**Comment by S-B99** [comment]
What game version?

**Comment by TechAle** [comment]
minecraft 1.12.2

**Comment by TechAle** [comment]
it's fn + f3

**Comment by S-B99** [comment]
Why was this closed? Was it resolved?
