### ISSUE TITLE
"Light" arent making any difference even though im not using optifine

### ISSUE THREAD

**Issue by BlackHanbo** [ImpactDevelopment/ImpactIssues#2038]
**Describe the bug**
"Light" arent making any difference even though im not using optifine

**To Reproduce**
Just turning it on

**Expected behavior**
To have clear view of rendered blocks as much as possible

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by MightyKnight** [comment]
I can't reproduce your issue. What Impact version are you using?

Please test again and make sure in that you have turned `Brighten` on and  have `Gamma` turned up in Light settings.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
