### ISSUE TITLE
"Speed" sometime gets you stuck underneath blocks

### ISSUE THREAD

**Issue by BlackHanbo** [ImpactDevelopment/ImpactIssues#2039]
**Describe the bug**
"Speed" sometime gets you stuck underneath blocks

**To Reproduce**
Turn on "Speed" and run under blocks or passage ways that is 2 block high

**Expected behavior**
shouldnt be blocked or stucked underneath a block

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by 0-x-2-2** [comment]
It sounds like an AntiCheat problem.

**Comment by BlackHanbo** [comment]
i was playing on realms when it happened..

**Comment by S-B99** [comment]
Realms literally doesn't have an anticheat LMAO
