### ISSUE TITLE
AutoFish module not working on a cubecraft server

### ISSUE THREAD

**Issue by imabugreporter** [ImpactDevelopment/ImpactIssues#2043]
AutoFish module not working on cubecraft

**Comment by MrMineO5** [comment]
If it works on other servers then this is likely an anti-cheat.

**Comment by imabugreporter** [comment]
> If it works on other servers then this is likely an anti-cheat.

it just working on vanilla servers

**Comment by LeafHacker** [comment]
> I'm not sure exactly how the client detects when to click while fishing

there's different autofish _modes_. Each one uses a different detection method. Would you please specify which one(s) do and do not work?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
