### ISSUE TITLE
1.15.2 log spam

### ISSUE THREAD

**Issue by NFLD99** [ImpactDevelopment/ImpactIssues#2052]
**Describe the bug**
when using the 1.15.2 build the log gets spammed with
```
[12:07:54] [Netty Client IO #1/INFO]: Set TranslatableComponent{key='item.minecraft.golden_chestplate', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'s damage from 0 to 0
```
**To Reproduce**
1. use the 1.15.2 build of Impact
2. play for a bit, hold an item
3. open your latest.log
4. notice spam

**Expected behavior**
the log should not contain the spam

**Screenshots**
https://i.imgur.com/8o4i4iA.png
Non Impact | Impact

<details> 
  <summary><strong>Game output</strong></summary>
 

```
N/A
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
N/A
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact-nightly-20200304-1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: happens no matter what, even with all off
- Operating System: win 10 home 1909 OS Build 18363.657

</details>

**Additional context**
just makes logs messy

**Comment by ZeroMemes** [comment]
Fixed this a bit ago, isn't an issue in the latest nightly.
