### ISSUE TITLE
NullPointerException: Ticking screen while joining server.

### ISSUE THREAD

**Issue by AddisonPascal** [ImpactDevelopment/ImpactIssues#2055]
**Describe the bug**
Game crashed while joining a erver.

**To Reproduce**
1. Open Impact (4.8.3 for 1.12.2)
2. Click on Multiplayer
3. Double click on a server
4. Game immediately crashed, when I opened the launcher again it said:
The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Ticking screen

**Expected behavior**
To join the server like normal without crashing (it doesn't usually crash).

**Screenshots**
N/A

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Ticking screen
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/10/20 9:47 AM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at gw$a.a(SourceFile:388)
	at gw.m(SourceFile:220)
	at gw.a(SourceFile:228)
	at bkr.e(SourceFile:88)
	at bib.t(SourceFile:1640)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gw$a.a(SourceFile:388)
	at gw.m(SourceFile:220)
	at gw.a(SourceFile:228)
	at bkr.e(SourceFile:88)

-- Affected screen --
Details:
	Screen name: bkr
Stacktrace:
	at bib.t(SourceFile:1640)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 515230808 bytes (491 MB) / 738197504 bytes (704 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.12.2-Impact_4.8.3
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.6813, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (Australia)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: 
Auto Totem (Counter enabled, Visible)
Criticals (Mode: Packet, Particles enabled, Visible)
Anti Hunger (Mode: Effective, Visible)
Portals (GUI, Visible)
Auto Cheat (Visible)
Auto Reconnect (Delay 200, Visible)
Discord RPC
Log Position (Show Names enabled, Save Positions enabled, Visible)
Middle Click Friend (Visible)
Unpack (Visible)
Elytra+ (Mode: Control [Base Speed 4.0, Up Speed 1.0, Down Speed 1.0], Auto Boost Disabled, Takeoff Enabled, Visible)
No Push (Visible)
Sprint (Multi Directional, Keep, Visible)
Inventory (Shulker Tooltip 27, Shulker Collate, Extra Slots, Move Around, Look Around, Yaw Speed 6.0, Pitch Speed 4.0, Visible)
Anti Blind (Visible)
Anti Overlay (Water, Lava, Pumpkin, Scoreboard, Fire, Boss Bar, Elder Guardian, Visible)
ESP (Mode: Shader [Shader: Outline], Player, Friends: Include, Teammates: Include, Hostile, Passive, Items, Other, Rainbow Friends, Color: Custom, Width 1.0, Visible)
HUD (Watermark, Module List [Color: Random {Saturation 50, Brightness 100}, Style: Flare, Suffix {Color: Gray}], Text Shadow 0.69, Potion Effects, Coordinates: Inline [Nether, Overworld, Freecam], Facing, Armor, TTF Font, Time: None
Light (Brighten, Gamma 10.0, Skylight, Visible)
Nametags (Items: [Collate: None, Dynamic], Tamed [Dynamic], Sounds: [Duration: 2.0, Fade: 0.5, Dynamic], Health, Armor, Priority, Sleeping, Invisibles, Scale 2.59, Min Dist 27.11, Max Dist 16.0, Visible)
Radar (Mode: Dynamic, Path [Stipple Disabled, Stipple Length 2], Invisible, Sleeping, Player, Hostile, Passive, Opacity 59, Size 105, Blip Size 2.0, Visible)
Search (Max Blocks: 1000, Refresh Rate: 1000, Width: 1.0, Smooth Lines, Visible)
Storage ESP (Chest, Trapped Chest, Ender Chest, Dispenser, Furnace, Hopper, Shulker Box, Minecart Chest, Minecart Furnace, Minecart Hopper, Item Frame, Fade, Fade Distance 30.0, Line Width 1.0, Visible
Tracers (Player, Rainbow Damage, Smooth, Complete, Body, Opacity 1.0, Width 1.0, Visible)
Trajectories (Entities, Width 1.8, Visible)
Weather (Visible)

- Operating System: Windows 10 Pro Version 1909 Build 18363.657 64bit

</details>

**Comment by ScanmanTM** [comment]
Cannot reproduce, what server?
