### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Hadimhz** [ImpactDevelopment/ImpactIssues#2058]
maybe an option to make tunneler dig a 3x3 tunnels that would be really helpful

**Comment by S-B99** [comment]
It's already added.

**Comment by S-B99** [comment]
https://github.com/cabaletta/baritone/blob/master/USAGE.md

**Comment by StijnSimons** [comment]
Please add a brief but descriptive title

**Comment by S-B99** [comment]
Please add a brief but descriptive title

**Comment by aUniqueUser** [comment]
Please add a brief but descriptive title

**Comment by cookiedragon234** [comment]
@Hadimhz thank you for your brief but descriptive title
