### ISSUE TITLE
New modules

### ISSUE THREAD

**Issue by aimD7083** [ImpactDevelopment/ImpactIssues#2060]
infinite chat length, .bookbot(writes random ASCII or Unicode characters), anti book ban (TRIES to not send too many to the server at the same time), packet logger: logs packets in a (JSON) file.
.skin (changes your skin,(client-sided))

**Comment by S-B99** [comment]
Please open separate issues for each suggestion.

**Comment by aimD7083** [comment]
all of them are suggestions

**Comment by S-B99** [comment]
Yes. Open separate issues for each one.

**Comment by aimD7083** [comment]
ok

**Comment by aimD7083** [comment]
suggestion: infinite chat length, suggestion: .bookbot(writes random ASCII or Unicode characters), suggestion: anti book ban (TRIES to not send too many to the server at the same time), suggestion: packet logger: logs packets in a (JSON) file.suggestion:
suggestion:.skin (changes your skin,(client-sided))suggestion:

**Comment by aimD7083** [comment]
re-writed

**Comment by S-B99** [comment]
Separate issues. This is still the same one.

**Comment by aimD7083** [comment]
ok

**Comment by aimD7083** [comment]
</> start </>
suggestion, not an issue: infinite chat length, a suggestion not an issue: .bookbot(writes random ASCII or Unicode characters), a suggestion not an issue: anti book ban (TRIES to not send too many to the server at the same time), a suggestion not an issue: packet logger: logs packets in a (JSON) file suggestion, not an issue:
suggestion not an issue: .skin (changes your skin,(client-sided))
issues:
issue: the client lags a lot
issue: the bypasses are bad
issue: the client crashes a lot
</> end </>

**Comment by aimD7083** [comment]
also baritone spins a lot

**Comment by S-B99** [comment]
> Separate issues. This is still the same one.

**Comment by S-B99** [comment]
https://duckduckgo.com/?t=ffab&q=what+are+github+issues

**Comment by S-B99** [comment]
https://help.github.com/en/github/managing-your-work-on-github/about-issues

**Comment by aimD7083** [comment]
know wat idc

**Comment by StijnSimons** [comment]
📸

**Comment by aimD7083** [comment]
oh and also make franky module do anything usefull other than doing that

































































i have no idea of what it does

**Comment by StijnSimons** [comment]
pozzed

**Comment by S-B99** [comment]
it is useful. it does exactly what you think it does
