### ISSUE TITLE
ViaVersion server side error

### ISSUE THREAD

**Issue by yeet028** [ImpactDevelopment/ImpactIssues#2061]
![wdadwadadw](https://user-images.githubusercontent.com/62188419/76689973-12424980-6612-11ea-9f2c-639b72846d67.PNG)

**Comment by StijnSimons** [comment]
lmao

**Comment by S-B99** [comment]
How did you fuck that up yet manage to create an issue
![image](https://user-images.githubusercontent.com/17222512/76702540-e7530680-66a0-11ea-81f9-04f6809a939e.png)

**Comment by StijnSimons** [comment]
> impact community
