### ISSUE TITLE
Baritone Shifts too fast when placing blocks.

### ISSUE THREAD

**Issue by ToxicDevv** [ImpactDevelopment/ImpactIssues#2068]
**Describe the bug**
When trying to place a block, baritone will shift really fast and sometimes it will place a block, sometimes not.

**To Reproduce**
1.  Find a path to lava
2. Make sure that there is a single lava block, not multiple.
3. Make sure that there is stone or whatever block on each side of the lava.
4. Set the goal to one side and have baritone place the block.
5. See the fast shifting error.
**Expected behavior**
Baritone shifts way to fast and gives up, and you fall in the lava or you start drifitng back away from the lava.

**Screenshots**
None

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Dont have one
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
NA
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
none

**Comment by S-B99** [comment]
1. this is an issue for the baritone repo
2. cabaletta/baritone/issues/256 and cabaletta/baritone/issues/13
