### ISSUE TITLE
.plugins request timed out

### ISSUE THREAD

**Issue by gamerpiss** [ImpactDevelopment/ImpactIssues#2071]
Went on a server and did .plugins, returned the following error message instead of a plugins list:
![image](https://user-images.githubusercontent.com/61640052/76903629-9c312300-685b-11ea-9895-0e2a05929284.png)

Not sure if this is related to the client or if it is the server's fault. Also not sure if this has been answered or fixed already. If it is the server's I would like to know how they were able to hide this if possible. Using Impact 4.8 for 1.14.4.

**Comment by 0-x-2-2** [comment]
This means the server is blocking this.
