### ISSUE TITLE
Intelligent item saver 

### ISSUE THREAD

**Issue by tlslx199852GH** [ImpactDevelopment/ImpactIssues#2072]
I like the imapct client very much because it is very convenient. But I have a problem. When using item Saver, the script will automatically put the tool to be damaged into the backpack, but when the space of the backpack is insufficient, it will automatically throw the tool out of the backpack. So when using the mining command, I will have to pay attention to the durability of the pickaxe and try to switch manually, so as to prevent my enchanted top-level tools from being thrown out of the backpack by the script. So I suggest to develop a new function that can intelligently switch the same type of tool in the backpack and the item bar. When the durability of the tool in the item bar is about to disappear, it can switch with the brand-new tool in the backpack instead of removing the backpack.

**Comment by tlslx199852GH** [comment]
If you can see what I need, it's great. I really like this product

**Comment by ScanmanTM** [comment]
Whats with the year long essay, couldn't you have just summarised using the bug/suggestion template?

**Comment by S-B99** [comment]
Everything you suggested is already built into item saver.
