### ISSUE TITLE
Make impact more customizable like badlion or lunar

### ISSUE THREAD

**Issue by ArbiterXXX** [ImpactDevelopment/ImpactIssues#2074]
Basically what I'm suggesting is that make impact so that we can customize certains aspects of the options like in other clients like Badlion or lunar where you can customize aspects you cant in impact such as adjusting the HUD or Better fps and a bunch of other customizations you can do to get an advantage

**Comment by MightyKnight** [comment]
We don't accept such broad and imprecise feature suggestions.

Please describe your feature suggestion in detail and only report **one feature per issue**.
Use [this format](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md&title=Please+add+a+brief+but+descriptive+title) ([example](https://github.com/ImpactDevelopment/ImpactIssues/issues/557)).
