### ISSUE TITLE
a .enchant would be nice

### ISSUE THREAD

**Issue by corvoattano0g** [ImpactDevelopment/ImpactIssues#2076]
i have a pretty good suggestion i think what if you make a command that works if your in gamemode 1 and its like .enchant all and it gives all the enchants on a item no matter what the item is exp: ( player gets gm1 dose .enchant fire_protection 2 or fire_protection 1000 or .enchant all and puts all enchants on said item ) i know other clients like aristois can do it so why not this client ?

**Comment by S-B99** [comment]
What kind of anarchy server gives you gamemode 1

**Comment by corvoattano0g** [comment]
well who said im on a anarchy server  it would be a nice thing to have

**Comment by S-B99** [comment]
pretty useless as there isn't a single relevant server that people play on that gives you permission to enchant with commands
