### ISSUE TITLE
Netherwart doesn't plant in autofarm

### ISSUE THREAD

**Issue by RealSnazzy** [ImpactDevelopment/ImpactIssues#2080]
When autofarm is activated, the bot will break the netherwart, but won't replant it.

1. enable autofarm near netherwart
2. watch

**Expected behavior**
the netherwart wont be replanted

<details> 
 

 

- Impact Version: 4.8.3
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Autofarm
- Operating System: Windows 10 64bit

**Comment by S-B99** [comment]
You need to enable the replant setting.
