### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by phillipsawyer** [ImpactDevelopment/ImpactIssues#2081]
Auto mining & auto farming is really jittery and not smooth and it's pretty obvious when someone is using it. SmoothAim is brilliant, however there is no equivalent for auto mining / farming

It would be extremely useful to have smooth farming / mining, or simply a mod that makes all aiming smooth instead of jittery.

This may be tricky to implement since auto farm uses baritone but hopefully it's worth considering!

**Comment by S-B99** [comment]
Duplicate of #1992

**Comment by phillipsawyer** [comment]
I don't think it's a duplicate because he talks about smoothaiming not working while baritone is pathfinding, however mine is about smoothly aiming at the farmed blocks

**Comment by S-B99** [comment]
It's the same code to do that stuff, baritone wise.
