### ISSUE TITLE
add EntityLivingBase to the targets

### ISSUE THREAD

**Issue by 200317314** [ImpactDevelopment/ImpactIssues#2083]
add EntityLivingBase to the targets

**Comment by ScanmanTM** [comment]
use the template, kthx.

**Comment by LeafHacker** [comment]
While the template isn't 100% required, this issue has zero rational. A request without a justification is meaningless. What issue are you having that you think this would solve?

Regardless, this isn't going to happen, at least not in the way you requested. Potentially an "all" or an "all NPCs" button could be added or something?
