### ISSUE TITLE
Public mods options? Maybe bring more fun mods like headless and useless crap out into another section like labymod, discord integration...

### ISSUE THREAD

**Issue by survvz** [ImpactDevelopment/ImpactIssues#2091]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like..**
It would be cool to have another section of public mods made by Impact users

**Describe alternatives you’ve considered**
Just download the forge mod and get other mods from there... But I’m too much of a lazy shit lol

**Additional context**
Great utilitymod keep up the good work!

**Comment by ScanmanTM** [comment]
One suggestion per issue, make sure to go through every module in the menu before you submit an idea. Also follow the appropriate template.
