### ISSUE TITLE
Item Stacking hack/ nbt file enchanting hack

### ISSUE THREAD

**Issue by Kniggu** [ImpactDevelopment/ImpactIssues#2092]
**Is your feature request related to a problem? Please describe.**
Request, I dont understand these hacks but i haven't seen them in a long time and was wondering if they could be incorporated to the utility mod
**Describe the solution you'd like**

being able to stack things like soup/armor/shulker boxes

for the enchant idk how to make 32k items but that would be cool

**Describe alternatives you've considered**

sorry im stupid and don't know how to do this

**Additional context**
<3

**Comment by S-B99** [comment]
What kind of server gives you permission to do that lmao.

**Comment by LeafHacker** [comment]
A previous version of Minecraft (1.12.0 iirc) had a bug which allowed non-stackable items to be duplicated and stacked. This bug has since been fixed, so Impact can't offer any features based on it.

**Comment by S-B99** [comment]
lmaooooo that's hilarious

**Comment by Kniggu** [comment]
Lmao sorry I’m just retarded. Thanks for the client anyways it’s very nice
