### ISSUE TITLE
WaterSpeed for Cubecraft 

### ISSUE THREAD

**Issue by yoshimichael100** [ImpactDevelopment/ImpactIssues#2096]
**Is your feature request related to a problem? Please describe.**
I have to switch between LowHop and Strafe everytime i wanna walk super fast in water. 

**Describe the solution you'd like**
Maybe add a different module called WaterSpeed and add a mode called "Cubecraft" to it and make it so you can make the speed stupidly fast

**Describe alternatives you've considered**
Nothing to add here

**Additional context**
Nothing to add here
- Wumpus#0002

**Comment by S-B99** [comment]
Make a macro to do that.
