### ISSUE TITLE
Why when baritone is tunneling the angle tilt at 0.59 

### ISSUE THREAD

**Issue by brixqc** [ImpactDevelopment/ImpactIssues#2097]
**Is your feature request related to a problem? Please describe.**
Why when baritone is tunneling the angle tilt at 0.59 
![2020-03-27_12 07 42](https://user-images.githubusercontent.com/62760952/77776555-90e0b300-7024-11ea-94bb-8c2d3cfbd9b6.png)

**Describe the solution you'd like**
keep it at 0.26 and we can old the trigger for fast mining, right now when you hold the left click mouse it create hole under the player.
![2020-03-27_12 18 55](https://user-images.githubusercontent.com/62760952/77776975-3562f500-7025-11ea-873f-26ae5652bd23.png)

**Describe alternatives you've considered**
keep it at 0.26 if possible for tunneling 

**Additional context**
it on Oldfag.org with average ping 100 and a low tps.
![2020-03-27_12 22 21](https://user-images.githubusercontent.com/62760952/77777339-cdf97500-7025-11ea-9a89-10d600bda7d7.png)

**Comment by ScanmanTM** [comment]
https://github.com/cabaletta/baritone/issues
