### ISSUE TITLE
Can't play 1.13.2

### ISSUE THREAD

**Issue by AlxPlays** [ImpactDevelopment/ImpactIssues#2098]
everytime i launch 1.13.2, it closes instantly and gives this message 
![LULW](https://user-images.githubusercontent.com/53222735/77791672-01a4c100-705f-11ea-8948-78a28cae2a63.PNG)

**Comment by S-B99** [comment]
Fill out the issue template properly.

**Comment by LeafHacker** [comment]
you'll need to at least provide a crash-report and or latest.log as well as the exact version or Impact (not just the minecraft version)

**Comment by S-B99** [comment]
Which is why we have an issue template, to ask for that information.
