### ISSUE TITLE
Kicked while trying to join realms

### ISSUE THREAD

**Issue by ChiefAwesome301** [ImpactDevelopment/ImpactIssues#2099]
So the bug is with realms. Whenever I try to join my realm, I am in for a few secconds, then I get kicked with the message: "Internal exception: Java.IOException: An existing connection was forcibly closed by the remote host."

To reproduce the bug, just join a realm.

I expect I should be able to play on my realm.

- Impact Version: impact_nightly-20200326 with 1.15.2
- Using Optifine?  Yes
- Using LiteLoader? No
- Enabled mods: Weather, Criticals, Hitbox, Auto Eat, No Fall, HUD, and Radar.
- Operating System: Windows 10

My PC specs:
Intel core i5-7400k
Geforce RTX 2070 Super
32 gb ram

**Comment by S-B99** [comment]
Please attach a log file.

**Comment by ChiefAwesome301** [comment]
https://paste.ubuntu.com/p/NyHJjHNQmb/

**Comment by S-B99** [comment]
Attach then *entire* log
