### ISSUE TITLE
Cheststealer missing shulkerbox steal button

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#2101]
**Describe the bug**
Shulkerbox GUI is missing Steal button

**To Reproduce**
1. Open Shulkerbox
2. Realise steal button is missing

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact nightly 20200309 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: -
- Operating System: Windows

</details>

**Comment by MightyKnight** [comment]
Duplicate of #877
