### ISSUE TITLE
FastInteract use speed doesnt work when holding a block

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#2104]
**Describe the bug**
FastInteract;s use speed doesnt work when holding a block

**To Reproduce**
1. Turn on autointeract's fast use
2. Hold right click on a noteblock
3. Hold a block
4. Notice its not clicking at super speed

**Expected behavior**
Fast clicking on noteblock when holding a block

  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact nightly 20200309 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: -
- Operating System: Windows

</details>

**Comment by ScanmanTM** [comment]
Can you update to the newest nightly then edit your issues. The nightly you're using is 20 days old.

**Comment by ThaUnknown** [comment]
> Can you update to the newest nightly then edit your issues. The nightly you're using is 20 days old.

sorry, i must have had some issue when updating impact yesterday and didint update to latest
