### ISSUE TITLE
Donator cape doesnt display on elytra

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#2106]
**Describe the bug**
Donator cape doesnt display on elytra

**To Reproduce**
1. Be donator
2. Put on elytra

**Expected behavior**
Elytra should be visible
<details>
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact nightly 20200309 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: -
- Operating System: Windows

</details>

**Comment by MightyKnight** [comment]
Duplicate of #1512
