### ISSUE TITLE
Flight vanilla anti-kick doesnt work

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#2107]
**Describe the bug**
Flight vanilla anti-kick doesnt work

**To Reproduce**
1. Enable vanilla flight and anti-kick
2. Fly
3. Get kicked

**Expected behavior**
Not getting kicked

<details>
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact nightly 20200309 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: -
- Operating System: Windows

</details>

**Comment by MightyKnight** [comment]
Duplicate of #1604

**Comment by MightyKnight** [comment]
@ThaUnknown Please use Githubs search function to check if your problem already exists before creating a new issue.
