### ISSUE TITLE
Impact Register Page is broken

### ISSUE THREAD

**Issue by mosinman** [ImpactDevelopment/ImpactIssues#2109]
I just used PayPal to send $5 as a donation in order to get the 1.15.2 version of the impact client but when I finished entering my information and hit submit, it gave me an error message that said “: undefined”. Any help is appreciated!

**Comment by ScanmanTM** [comment]
Have you tried on a different browser? Incognito mode?

**Comment by mosinman** [comment]
That worked, thanks!

**Comment by LeafHacker** [comment]
Which browser did you have the error in?

**Comment by mosinman** [comment]
I had it in Chrome

**Comment by LeafHacker** [comment]
I can only assume something was cached incorrectly, until we fingerprint all our web assets this kinda thing can happen if we change any code. Closing for now
