### ISSUE TITLE
Elytra+ goes too fast when player has speed effect

### ISSUE THREAD

**Issue by HexCodeFFF** [ImpactDevelopment/ImpactIssues#2115]
**Describe the bug**
Elytra+ goes faster when the player has a speed potion effect

**To Reproduce**
1. Drink speed potion or set up beacon
2. fly in control mode
3. player goes much faster than normal and, if on a server with anticheat, gets kicked due to high speed

**Expected behavior**
Elytra+ speed stays constant

**Screenshots**
no

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.15 nightly-20200327
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: 
![image](https://user-images.githubusercontent.com/35177464/77860784-aeee1500-71d6-11ea-8f24-0983be5dd8c7.png)
elytra+ base speed is 3.98 because i cant set it back to 4
- Operating System: Windows 10 64bit

</details>

**Additional context**
Tested on mc.salc1.com

**Comment by ZeroMemes** [comment]
Fixed in 4.9
