### ISSUE TITLE
inv automine 

### ISSUE THREAD

**Issue by whycantiusemyname** [ImpactDevelopment/ImpactIssues#2117]
when you open any gui the automine will stop. plz let it work when you open a gui.

**Comment by S-B99** [comment]
Why do you keep closing and reopening this?

**Comment by LeafHacker** [comment]
This is probably more of a [baritone](https://github.com/cabaletta/baritone/issues/) issue

**Comment by S-B99** [comment]
They also opened another issue with the exact same text lol

I already commented on it

**Comment by Darko1green1LOrd** [comment]
You can do this https://youtu.be/1OpWyl6wnQQ

**Comment by S-B99** [comment]
I can't believe people are using bandicam in 2019

**Comment by Darko1green1LOrd** [comment]
> I can't believe people are using bandicam in 2019

Itz old vid and the thing that is shown here willl maybe help him/her

**Comment by S-B99** [comment]
Yea, I commented on the other issue that #mine works with inventories opened already
