### ISSUE TITLE
inventory movearound doesn't work

### ISSUE THREAD

**Issue by whycantiusemyname** [ImpactDevelopment/ImpactIssues#2119]
inventory move around doesn't work,i can't walk while open a gui
I use 4.8.3 in 1.12.2
At first, I thought it is conflicts with other modules
but i close all the modules and it still doesn't work
and i think it conflicts with  mod and i del all the mod and it still doesn't work(also i change to another cilent the bug is still here)

**Comment by ScanmanTM** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#inventory-move-doesnt-work-on-1122-forge
