### ISSUE TITLE
entitydesync

### ISSUE THREAD

**Issue by baixatemperatura** [ImpactDevelopment/ImpactIssues#2124]
*

**Is your question request related to a problem? Please describe.**
NO

**Describe what you are trying to achieve**
It would be amazing to see the entitydesync feature.

**Additional context**
Hi, your hack ia amazing. I Will be greatful If you could add entitydesync.

**Comment by ScanmanTM** [comment]
You could have at least used the right template. Also search before you make another issue, moron.

**Comment by S-B99** [comment]
I see someone fell for the april fools desync dupe...
