### ISSUE TITLE
mod version for 1.12.2

### ISSUE THREAD

**Issue by PItlosTails** [ImpactDevelopment/ImpactIssues#2126]
it would be very nice to get a mod version for 1.12.2, so i could use my other mods  at the same time as impact, wurst can do it which i would say is a major step over impact which i s sad as impact is the better client overall, could you please consider making the jar version into a mod?

**Comment by ScanmanTM** [comment]
There is a forge version in the installer?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
