### ISSUE TITLE
World/chunks not loading using Impact

### ISSUE THREAD

**Issue by Bezimienny025** [ImpactDevelopment/ImpactIssues#2129]
Hello

While playing with impact and having no problem online i wanted to test something on singleplayer. When i load the world i begin to build what i wanted. But then i wanted to explore the world but here comes the weird one. When i load impact from my mc and go to the single player the world around me don't want to load. When i go to normal mc the hole world load with no problems. Then i go back in to impact mc and loaded chunks don't load and same every where.

Her is the screen from my impact mc.
![Base Profile Screenshot 2020 04 01 - 22 16 42 04](https://user-images.githubusercontent.com/63019006/78183153-ba0ba400-7467-11ea-951b-3ffe46645d61.png)

I would like to know if i made bad impact options or i need impact for single player.

**Comment by S-B99** [comment]
Please fill out the issue template properly.

**Comment by Bezimienny025** [comment]
And now is good ?

**Comment by 0-x-2-2** [comment]
f3 + a

**Comment by Bezimienny025** [comment]
> f3 + a

Thx for iu tryid few times but stil chunks dont want to load.
![Desktop Screenshot 2020 04 03 - 09 22 05 52](https://user-images.githubusercontent.com/63019006/78334782-a60d9280-758c-11ea-9a7a-2fd7da2a9520.png)

Its in polish : Realod all chunks.

**Comment by S-B99** [comment]
That's not really an impact issue and we can't help you with that.
