### ISSUE TITLE
Extra Tab

### ISSUE THREAD

**Issue by RedCarlos26** [ImpactDevelopment/ImpactIssues#2130]
It would be nice to see the implementation of extra tab, witch shows all the players online in the tab list instead of showing just 50 or so maximum. This would be really useful to see clearly who is online on a minecraft server. This is already implemented in the future client and it’s really useful. The thing is that I prefer Impact for baritone and some other features so it would be really nice to see the extra tab feature in the Impact Utility Mod. 

Thanks for reading.

**Comment by S-B99** [comment]
kami wants to know your location

**Comment by RedCarlos26** [comment]
> kami wants to know your location

What?

**Comment by S-B99** [comment]
kami was the first client with extra tab lol

**Comment by RedCarlos26** [comment]
I didn’t new that. This isn’t surprising thought.

**Comment by 0-x-2-2** [comment]
> kami was the first client with extra tab lol

did you mean forgehax 📸
