### ISSUE TITLE
Hide and seek feature dose not work.

### ISSUE THREAD

**Issue by renvoi** [ImpactDevelopment/ImpactIssues#2132]
**Describe the bug**
I play Hide and seek (H&S) on play.hivemc.com and whe i turn the H&S feature it highlights the blocks but its up in the sky so you cant realy see where the blocks are hiding.
(Version 1.14.4)

**To Reproduce**
1. Go to play.hivemc.com
2. Go to H&S
3. Click on H&S feature

**Comment by cancerousname69** [comment]
This is not an impact-related issue. please close it.

**Comment by dominikaaaa** [comment]
Do you mean the highlighted block's highlight is higher then it's supposed to be? Can you please send a picture of the issue?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen with requested information.
