### ISSUE TITLE
I would like 2 Block Step

### ISSUE THREAD

**Issue by Yotta1** [ImpactDevelopment/ImpactIssues#2136]
**Is your feature request related to a problem? Please describe.**

--i would like that you add a mode to step which allows allows for the player to be able to step up 2 blocks at a time, this is like in the hacked client Future and many others.

**Describe the solution you'd like**

--When you walk into the block it will kinda teleport boost you up 2 blocks, so when you hit the face of the block you end up on the top of them

**Describe alternatives you've considered**
--A clear and concise description of any alternative solutions or features you've considered.

i am not sure if there is a way around it, i do not like the spider module as it takes to long to climb up the 2 blocks that i intend on climbing, but spider is useful as it can take you up many blocks.

**Additional context**

--thank you very much for reading this, i hope it is not to hard to add or fix. thank you so so much for this insane client. best of wishes during this hard time.

**Comment by S-B99** [comment]
This doesn't work on any modern server.
