### ISSUE TITLE
Build command only building with a very limited variety of blocks

### ISSUE THREAD

**Issue by OscillatorZ** [ImpactDevelopment/ImpactIssues#2140]
**Describe the bug**
When using the .build command to try to build a schematic (in the latest nightly, but the schematic created in 1.12.2) that contains no stone/cobble/netherack/dirt, it will not build. I noticed this first when trying to build map-art. It just ignored everything except stone. Once the stone portion was finished, it would not continue building with any of the other blocks ("Unable to do it"). I tried making a small 3x4 schematic made of only wool, instead of saying "unable to do it" it now just says "build complete" without doing anything. 

BongEatBong was also able to reproduce this bug on his machine. He also tried to build a small wool schematic, it would not build for him either.

**To Reproduce**
1. Create a small test schematic made of wool any color/bricks any type/diorite/andesite
2. Attempt to build in latest nightly.

**Screenshots**
just a few screenshots showing the correct blocks are in my hotbar, and that the schematic indeed loads fine in other schematic editors.
https://imgur.com/a/cxtsSB6

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Latest nightly build
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Win10

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
https://github.com/cabaletta/baritone/issues
