### ISSUE TITLE
Game give crash

### ISSUE THREAD

**Issue by 88585** [ImpactDevelopment/ImpactIssues#2142]
![image](https://user-images.githubusercontent.com/51754605/78471999-3c34ea80-773e-11ea-8226-28f4111f847e.png)
anyone help me ?

**Comment by MightyKnight** [comment]
You didn't provide enough information to find the cause of your issue.
Use the [issue template](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md&title=Please+add+a+brief+but+descriptive+title) next time when reporting a bug!

You can also go to the [official impact discord](https://impactclient.net/discord.html) for help.
