### ISSUE TITLE
Mod Authenticator bypass

### ISSUE THREAD

**Issue by Hackerokuz** [ImpactDevelopment/ImpactIssues#2143]
**Is your feature request related to a problem? Please describe.**
I wanted this because I know a few servers that are using [Mod Authenticator.](https://www.curseforge.com/minecraft/mc-mods/mod-authenticator)
Mainly servers that use [Event's UHC 2](https://www.curseforge.com/minecraft/modpacks/events-uhc-2) modpack and when I try to use Impact mod in these modpacks minecraft crashes or if I even start it up somehow when I join to server it says how I'm using banned mod and just kicks me.

**Describe the solution you'd like**
Fix random crashes on startup and hide this hack/mod from [Mod Authenticator.](https://www.curseforge.com/minecraft/mc-mods/mod-authenticator)

**Describe alternatives you've considered**
I've tried using other clients but none bypasss this,
I've tried changing this mod to dll so I can inject it in minecraft externaly but I'm too stupid to do that found this [video](https://www.youtube.com/watch?v=maI3xZlGHh0) that explains how to do it but it is in russian and too complicated for me to do.

**Additional context**
If possible find a way to fix a crash bug that is coused by mod called [VanillaFix](https://www.curseforge.com/minecraft/mc-mods/vanillafix)
I've also found  this [site](https://www.craftedforeveryone.com/convert-jar-file-to-dll-for-use-in-visual-studio-projects/) that explaines how to convert .jar to .dll but it is too complicated for me to do.
No crashlog appears when game crashes I've chacked in crashlog folder and in mc launcher!

**Comment by S-B99** [comment]
Open a separate issue for the crashes.

**Comment by LeafHacker** [comment]
TBH we don't really support modded minecraft much, there's just too many ways in which things can be broken by random mods, etc.
