### ISSUE TITLE
Mod crashes

### ISSUE THREAD

**Issue by Hackerokuz** [ImpactDevelopment/ImpactIssues#2145]
**Describe the bug**
Minecraft crashes with mods like [Mod Authenticator](https://www.curseforge.com/minecraft/mc-mods/mod-authenticator) and [VanillaFix](https://www.curseforge.com/minecraft/mc-mods/vanillafix) and in modpacks like [Event's UHC 2](curseforge.com/minecraft/modpacks/events-uhc-2)

**To Reproduce**
1. Go to Twitch launcher install modpack/mods and add impact in mods folder of the profile on twitch launcher
2. Start minecraft
3. Crash

**Expected behavior**
When I add impact in mods folder I would like it not to couse crashing.

**I wasn't able to find any crash log, I think it wasn't created whan game crashed**

- Impact Version: 1.12.2
- Using Optifine?  No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 64bit

**Comment by S-B99** [comment]
Try removing the mods from your mods folder, that should fix the issue.

**Comment by S-B99** [comment]
Please see this: https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
