### ISSUE TITLE
Inventory Move/Forge

### ISSUE THREAD

**Issue by RedCarlos26** [ImpactDevelopment/ImpactIssues#2146]
Inventory Move module isn’t working as intended when Impact is installed with Forge. To reproduce: install Impact for 1.12.2 with Forge. Try to walk while having the inventory open and the module activated.

Thanks for your time.

**Comment by ScanmanTM** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#inventory-move-doesnt-work-on-1122-forge
### Thank you for your time for reading the wiki & reading the other issues.

**Comment by RedCarlos26** [comment]
Can I have a link to a mod that does this please?1

**Comment by dominikaaaa** [comment]
https://github.com/kami-blue/client and https://github.com/fr1kin/ForgeHax/ are both forge mods and have it
