### ISSUE TITLE
A way to change the location of the coordinates on screen (Move from bottom right to bottom left, for example)

### ISSUE THREAD

**Issue by botpixel2** [ImpactDevelopment/ImpactIssues#2149]
When I stream using the client, I cover up the coordinates. However, the location of the coordinates means also covering up part of the in-game hand and whatever I am holding. I would like to be able to move the coordinates from the bottom right of the screen to the bottom left, as there isn't anything too important in that corner of the screen anyways.

**Comment by dominikaaaa** [comment]
Use the in game settings to change the position.
