### ISSUE TITLE
Impact 4.8.3 is continually crashing for Windows 10 java minecraft

### ISSUE THREAD

**Issue by Cwcat232** [ImpactDevelopment/ImpactIssues#2150]
I've been attempting to figure out what the bug is but have been unable to find what the cause is. I'm trying to use impact 4.8.3 for 1.12.2, which would crash. So I tried to use it for 1.14.4, which would also crash. I even attempted to use older versions of Impact, which would also crash. I have completely uninstalled and reinstalled Minecraft, also uninstalling and reinstalling impact versions, all of which seem to prove useless. 

This problem is completely new, and friends of mine are not meeting this issue. I have been using Impact for a few weeks and have not encountered this issue until yesterday. 

Technically, my Minecraft should be opening as normal, but obviously it is not. My Minecraft does open for my Optifine file and other normal versions of Minecraft, but not for any Impact files I try to use. 

 Impact Version: 4.8.3 for 1.12.2 and 1.14.4
Using Optifine: No
Using LitLoader: No
Enabled mods: None since it will not open
Operating System: Windows 10

**Comment by dominikaaaa** [comment]
Fill out the issue template properly please.
