### ISSUE TITLE
Installing Impact, with Wyntils crashes.

### ISSUE THREAD

**Issue by TimidTime** [ImpactDevelopment/ImpactIssues#2152]
Installing Impact 1.12.2 works on it's on, but with Wyntils, a 1.12.2 forge mod it shows this crash error.

![image](https://user-images.githubusercontent.com/35592871/78783624-4d545480-79e7-11ea-8087-d60ee542f703.png)

**Comment by dominikaaaa** [comment]
Try uninstalling Wyntils, that should fix the issue.
