### ISSUE TITLE
Option for Hunt module to wait to pick up drops

### ISSUE THREAD

**Issue by HexCodeFFF** [ImpactDevelopment/ImpactIssues#2158]
**Is your feature request related to a problem? Please describe.**
I usually use hunt to get food quickly but i have to keep disabling it to get the drops

**Describe the solution you'd like**
Much like how baritone will wait until it picks up ore drops, target and wait for mob drops to be picked up

**Describe alternatives you've considered**
I had to keybind hunt to keep disabling it to get the drops

**Comment by SylveonBottle** [comment]
Seems like a [Baritone](https://github.com/cabaletta/baritone/i) suggestion

**Comment by HexCodeFFF** [comment]
Right but isn't hunt an Impact module?

**Comment by dominikaaaa** [comment]
It uses baritone code, the "module" part just enables it and disables it.

**Comment by SylveonBottle** [comment]
I'll be looking forward to you re-posting this on Baritone's github page. I'd welcome the suggestion as I've ran into a similar problem before.

**Comment by HexCodeFFF** [comment]
https://github.com/cabaletta/baritone/issues/1536
