### ISSUE TITLE
Impact crashing on launch.

### ISSUE THREAD

**Issue by stefff03** [ImpactDevelopment/ImpactIssues#2159]
**Describe the bug**

Until yesterday I was able to play with impact client 4.8.3 for 1.12.2. Today every time I started it crashes at start every time.

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[Launcher] Starting Minecraft 1.12.2-Impact_4.8.3...
[Launcher] Launching in: C:\Users\Myname\AppData\Roaming\.minecraft
Starting garbage collector: 74 / 185 MB
Garbage collector completed: 44 / 185 MB
[Launcher] Processing post-launch actions. Assist launch: true
===============================================================================================
> [00:52:50] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 53783
> 	at java.lang.String.substring(Unknown Source)
> 	at clientapi.load.ClientTweaker.<clinit>(ClientTweaker.java)
> 	... 4 more
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (499 ms)
[Version:1.13.2-OptiFine_HD_U_E7] Resolving...
[Version:1.13.2-OptiFine_HD_U_E7] Inherits from 1.13.2
[Version:1.14.4-OptiFine_HD_U_F5] Resolving...
[Version:1.14.4-OptiFine_HD_U_F5] Inherits from 1.14.4
[Version:1.13.2-OptiFine_HD_U_E7] Resolving...
[Version:1.13.2-OptiFine_HD_U_E7] Inherits from 1.13.2
[Version:1.14.4-OptiFine_HD_U_F5] Resolving...
[Version:1.14.4-OptiFine_HD_U_F5] Inherits from 1.14.4
[Version:1.13.2-OptiFine_HD_U_E7] Resolving...
[Version:1.13.2-OptiFine_HD_U_E7] Inherits from 1.13.2
[Version:1.14.4-OptiFine_HD_U_F5] Resolving...
[Version:1.14.4-OptiFine_HD_U_F5] Inherits from 1.14.4
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1


```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods:
- Operating System: Windows 10 64bit

</details>

**Additional context**
I set the dedicated video card and updated java at the latest version and i removed resource packs. I tried with tlaunchcer and minecraft original launcher but nothing to do. I'm using impact vanilla

**Comment by dominikaaaa** [comment]
Use the official minecraft launcher.

**Comment by stefff03** [comment]
it doesn't work

**Comment by dominikaaaa** [comment]
your log file isn't from the official Minecraft launcher, therefor we won't help you with it.

**Comment by stefff03** [comment]
I tried with minecraft launcher, same problem

**Comment by stefff03** [comment]
[01:15:29] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker

**Comment by dominikaaaa** [comment]
Send the entire log file.

**Comment by stefff03** [comment]
This is the entire log file

**Comment by dominikaaaa** [comment]
No it's not.

**Comment by stefff03** [comment]
![Cattura](https://user-images.githubusercontent.com/63429708/78948586-325a1100-7ac9-11ea-8ec5-35c9c131f199.PNG)

**Comment by dominikaaaa** [comment]
If it instantly exits then that means Minecraft doesn't have enough ram allocated or you're not using the right Java version.

**Comment by stefff03** [comment]
i try to use more ram

**Comment by stefff03** [comment]
i'm using 5gb of ram and it crashes and i updated java like an hour ago

**Comment by stefff03** [comment]
![Cattura](https://user-images.githubusercontent.com/63429708/78948808-dd6aca80-7ac9-11ea-8046-8d146d65cadc.PNG)

**Comment by dominikaaaa** [comment]
Make sure Minecraft is using JDK 8u241 or newer, and Minecraft can use at least 4GB of ram

**Comment by stefff03** [comment]
how can I verify it?

**Comment by dominikaaaa** [comment]
Set the Java version manually and edit the java args to have 4GB

**Comment by stefff03** [comment]
-Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by dominikaaaa** [comment]
yes, so it's 4GB
make sure your system has 4GB of available ram and make sure it's using JRE 8u241 or newer

**Comment by stefff03** [comment]
what i can do now?
i'm using JDK 8u241

**Comment by stefff03** [comment]
i have 12gb of ram i ever used minecraft with 6gb

**Comment by dominikaaaa** [comment]
you need to use JRE 8u241

**Comment by stefff03** [comment]
![Cattura](https://user-images.githubusercontent.com/63429708/78949077-c9739880-7aca-11ea-883d-d7ac849a8816.PNG)

**Comment by dominikaaaa** [comment]
# JRE

**Comment by stefff03** [comment]
i'm installing it

**Comment by stefff03** [comment]
i have to uninstall jdk?

**Comment by dominikaaaa** [comment]
Yes.

**Comment by stefff03** [comment]
ok, I did it. It doesn't work

**Comment by stefff03** [comment]
OH NO I HAD ALREADY JRE AND NOT JDK

**Comment by stefff03** [comment]
SORRY

**Comment by stefff03** [comment]
I try with jdk?

**Comment by dominikaaaa** [comment]
No, you need JRE

**Comment by stefff03** [comment]
ok but it doesn't work

**Comment by stefff03** [comment]
what i can do now?

**Comment by stefff03** [comment]
I'm desperate, I don't know what to do anymore

**Comment by stefff03** [comment]
Are you here?

**Comment by LeafHacker** [comment]
Scan your system for viruses. Also, delete the contents of .minecraft (backup important stuff like your savegames first!), reboot your pc and reinstall Impact. Don't use tlauncher, it is known to cause issues.

**Comment by stefff03** [comment]
It didn't work but I reinstalled Windows and now Impact works.
