### ISSUE TITLE
Crashes upon starting.

### ISSUE THREAD

**Issue by ExtinctInsanity** [ImpactDevelopment/ImpactIssues#2160]
**Describe the bug**
I start the version like I would any other version and it starts to load like any other version I'd use and it just crashes about 20 seconds later. Also causes all other versions to crash, with or without client.

**To Reproduce**
1. Just install the nightly'
2. Click on 'Play' as normal
3. Scroll down to 'nothing'

**Expected behavior**
Just completely crashes

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
Please fill out the issue template properly next time, but this is likely due to you not logging into your donator account.
