### ISSUE TITLE
Is it possible to bypass Mod Authenticator By SkenonS?

### ISSUE THREAD

**Issue by Hackerokuz** [ImpactDevelopment/ImpactIssues#2162]
**Please consider joining our Discord server instead to get support**
http://http://discord.gg/MmhkCZ

**Is your question request related to a problem? Please describe.**
Is it possible to bypass Mod Authenticator By SkenonS?
This is client side anti cheat that is qute new and not really popular for now.
Here is a link for a anti cheat.
https://www.curseforge.com/minecraft/mc-mods/mod-authenticator

**Describe what you are trying to achieve**
I'm tring to bypess checks from this mod so that I am able to join a server without getting kicked.

**Additional context**
This anticheat mod is found in modpacks like [Event's UHC 2](https://www.curseforge.com/minecraft/modpacks/events-uhc-2) and Skenia IV Pack [Lite](https://www.curseforge.com/minecraft/modpacks/skeniapacklite)/[Full](https://www.curseforge.com/minecraft/modpacks/skenia-iv-pack-full) version
Ip of one of the servers that use Skenia IV Pack: server.skenons.com (You will need a premium account to get on a server)

As of now I've tried: 

- To hide impect file using [Universal Shield](http://www.everstrike.com/shield.htm) this however doesn't allow me to load impact.
- To turn impact mod into .dll file [without any seccess] in order to inject it after minecraft had loaded.
- Rename the file witch doesn't actually help because mod looks what is inside a file and ignores its name.

If anyone has any more ideas please put tham in comments

**Comment by dominikaaaa** [comment]
This is not an issue with impact.
