### ISSUE TITLE
TPS Sync module

### ISSUE THREAD

**Issue by msj20080623** [ImpactDevelopment/ImpactIssues#2166]
#### Original issue
在类似2b2t的服务器有许多组织，比如我跟随一个团员，但是如果速度一旦慢下来区块就不加载，就连接不上了！
我期望开发一个网络模块，只要团队开发一个网站，而科学家界面可以连接相应的团队服务器！进行登录后可以获取所有团队中玩家的位置！这样子就不用担心区块不加载了！
注意：我是个来自中国的6年级小学生，我说的所有的话都是通过翻译的，有中英两种，翻译网站为【fanyi.baidu.com】
In servers like 2b2t, there are many organizations. For example, I follow a group member, but if the speed slows down, the block will not be loaded and the connection will be lost!
I hope to develop a network module, as long as the team develops a website, and the scientist interface can connect to the corresponding team server! After login, you can get the location of players in all teams! In this way, you don't have to worry about the block not loading!
Note: I am a grade 6 primary school student from China. All my words are translated from Chinese and English. The translation website is fanyi.baidu.com
更
#### Reworded issue
Why this would be a good module: 
On servers like 2b2t.org, if the TPS is too low some actions such as placing blocks get desynced from the server
Describe the solution you'd like:
A TPS Sync module which synchronizes actions with the servers TPS

**Comment by msj20080623** [comment]
have man?
有人吗？

**Comment by ScanmanTM** [comment]
Isn't that what anti-desync was made for?

**Comment by dominikaaaa** [comment]
Oh yea
