### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Cazcez** [ImpactDevelopment/ImpactIssues#2168]
**Describe the bug**

**To Reproduce**
1- Install impact using windows installer
2- Go MC default launcher
3- Click on play
4- See error

**Expected behavior**
When i start game (on 1.14.4 without optifine or with optifine) always game crashing

- Impact Version: 4.8.3 for 1.14.4
- Using Optifine? I tried with optifine and without optifine (log is from without optifine)
- Using LiteLoader? No
- Enabled mods: Nothing 
- Operating System:  Windows 10 64bit 

<details>
  <summary><strong>Game output</strong></summary>
hastebin: https://hasteb.in/izohefek.md

**Comment by Cazcez** [comment]
i tried to reinstall minecraft and impact but not worked

**Comment by yesilhalil302** [comment]
I'm having the same problem

**Comment by daaddaadda** [comment]
Try to use the non-windows installer to get it.

**Comment by Cazcez** [comment]
> Try to use the non-windows installer to get it.

i already tried with non-windows installer

**Comment by ScanmanTM** [comment]
Can you run 1.14.4 without Impact?

**Comment by Cazcez** [comment]
> Can you run 1.14.4 without Impact?

yes

**Comment by Baolkun** [comment]
I have the same issue

**Comment by MightyKnight** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/issues/2285#issuecomment-635463430
> In the future, don't use hastebin, they automatically delete pastes.

Closing this as **Invalid**, game output link unavailable.
