### ISSUE TITLE
Xray problem

### ISSUE THREAD

**Issue by Dushuav2** [ImpactDevelopment/ImpactIssues#2172]
**Please consider joining our Discord server instead to get support**
http://http://discord.gg/MmhkCZ

**Is your question request related to a problem? Please describe.**
Xray is not working.

**Describe what you are trying to achieve**
I wanted to xray be fixed

**Additional context**
https://prnt.sc/ryjx4j

**Comment by dominikaaaa** [comment]
You sent a picture of it clearly working.
