### ISSUE TITLE
Search for end gateway

### ISSUE THREAD

**Issue by TxcEcko** [ImpactDevelopment/ImpactIssues#2176]
I tried using the search feature to search for end gateway blocks, was not possible. It is not an option on the search menu. I tried manually putting minecraft:end_gateway on search.cfg but didn't have any luck with that.

**Comment by dominikaaaa** [comment]
If you're playing in a pre flattening version this isn't possible.

![2020-04-14-101708_521x93_scrot](https://user-images.githubusercontent.com/17222512/79235078-2360bf00-7e39-11ea-910b-8741bd46841f.png)
