### ISSUE TITLE
kill messages

### ISSUE THREAD

**Issue by flae7** [ImpactDevelopment/ImpactIssues#2177]
**Is your feature request related to a problem? Please describe.**
i want to setup a baritone bot on hypixel pit and make it type something in chat after a kill.

**Describe the solution you'd like**
a chat option "Kill Messages" with customizable messages in a txt file or sth idk

**Describe alternatives you've considered**
a forge mod running alongside impact

**Additional context**
R.I.P Rick May

**Comment by dominikaaaa** [comment]
Use a macro.
