### ISSUE TITLE
Log position module doesn't work

### ISSUE THREAD

**Issue by Zyon134** [ImpactDevelopment/ImpactIssues#2178]
**Describe the bug**
The log position module doesn't work. It does nothing.

**To Reproduce**
1. Open ClickGUI
2. Click on Logout spots
3. See error

**Expected behavior**
You expect to see where players log out, but you don't.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
Please fill out the issue template properly.
