### ISSUE TITLE
Vanilla capes render incorrectly on 1.15.2

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactIssues#2180]
**Describe the bug**
On 1.15.2 capes using the vanilla 64x32 scale render incorrectly. Capes using 2x scale or higher render fine.

**To Reproduce**
1. Go to `.minecraft/Impact/assets`
2. Note/copy the filename of your Impact cape. Note it does not have a `.png` extension! It is entirely made up of a sha1 hash.
3. Copy a vanilla cape into your Impact `assets` folder. e.g: [mojang.png](https://user-images.githubusercontent.com/23565638/79467117-564fb200-7ff5-11ea-916d-e06243754d00.png)
4. Rename the vanilla cape to the name your Impact cape was using.
5. Launch Impact and go into F5 mode to inspect your cape.
6. Take your elytra on/off for good measure.

**Expected behavior (Impact 1.14.4)**
![image](https://user-images.githubusercontent.com/23565638/79467299-8bf49b00-7ff5-11ea-8909-4629aedfcd83.png)

**Actual behavior (Impact 1.15.2)**
![image](https://user-images.githubusercontent.com/23565638/79467719-01f90200-7ff6-11ea-9f9c-0e1498cd3327.png)

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly-20200412-1.15.2
- Using Optifine? Can reproduce with and without
- Enabled mods: N/A
- Operating System: Arch, btw

</details>

**Additional context**
@ZeroMemes had done some 1.15-specific work to get our existing capes rendering correctly with and without OptiFine. I wonder if that has broken vanilla capes?

**Comment by mastalol** [comment]
To add to this, the default capeskin for a donator makes the elytra go invisible, even if turned off.
Reproduce: Go ingame and press f5, with or without capes activated on the account.

**Comment by LeafHacker** [comment]
> To add to this

That's not how issues work, you open a new issue for each separate issue. Commenting about related issues (without actually filing the related issue) isn't helpful.

> the default capeskin for a donator makes the elytra go invisible

That should've been fixed by https://github.com/ImpactDevelopment/ImpactServer/commit/bbcc546bcc42ebbf920ba81370a0e76762a9a603

**Comment by LeafHacker** [comment]
This specific issue should be fixed by ImpactDevelopment/Impact@87624804e43dc650979c109588c240f6bfefd43a whenever the next nightly comes out.

**Comment by mastalol** [comment]
> This specific issue should be fixed by [ImpactDevelopment/Impact@8762480](https://github.com/ImpactDevelopment/Impact/commit/87624804e43dc650979c109588c240f6bfefd43a) whenever the next nightly comes out.

I apologize, New to Github. Will remember this for the future
