### ISSUE TITLE
some baritone commands aren't working, baritone loops when building

### ISSUE THREAD

**Issue by dirtySusan** [ImpactDevelopment/ImpactIssues#2181]
I'm trying to build a large schematic using baritone included with the latest impact release for 1.12.2, baritone version 1.2.10.  Certain commands listed on the baritone github page are not available when I go use them.  For example,  .b buildIgnoreBlock and .b buildIgnoreExisting don't work.  This is an issue because it sends baritone into a loop when it builds scaffolding.  It either destroys the block it just created or builds a pillar up and then jumps down and destroys it.  I should mention it works fine until it reaches a certain layer. 

I'm wondering if I could use schematica to fix this problem but I don't know if it's compatible with impact/baritone.  or

**Comment by dominikaaaa** [comment]
Fill out the issue template properly.
