### ISSUE TITLE
Baritone pillar build/destroy loop, some commands missing

### ISSUE THREAD

**Issue by dirtySusan** [ImpactDevelopment/ImpactIssues#2182]
**Is your question request related to a problem? Please describe.**
When trying to build a schematic I'm unable to use certain baritone commands such as buildIgnoreBlocks or buildIgnoreExisting.  Due to this, at a certain build layer Baritone loops between building and destroying pillars used to get up to the top layer.   

**Describe what you are trying to achieve**
I am trying to build scaffolding for a large schematic without baritone targeting the scaffolding/pillar block type for destruction.  

**Additional context**
I don't know if this is relevant but when I type .b set, the commands I mentioned above don't appear in the list.  1.12.2 btw

**Comment by dirtySusan** [comment]
Is this good?

**Comment by dominikaaaa** [comment]
What baritone version?

**Comment by dirtySusan** [comment]
it says 1.2.10

**Comment by dominikaaaa** [comment]
Update to latest and see if it still happens.

**Comment by dirtySusan** [comment]
how do i update the baritone

**Comment by dominikaaaa** [comment]
Download the latest impact version or download the 1.2.12 forge API jar and follow these instructions https://github.com/cabaletta/baritone/blob/master/SETUP.md#more-info

**Comment by dirtySusan** [comment]
impact is latest version but wouldn't baritone latest version be 1.2.13?

**Comment by dominikaaaa** [comment]
You're right, 1.2.13 is latest

**Comment by dirtySusan** [comment]
Okay, I'll try that thanks

**Comment by dirtySusan** [comment]
I don't know what I'm doing by why forge API?

**Comment by dominikaaaa** [comment]
because Impact has baritone built in, so you want to replace it

**Comment by dirtySusan** [comment]
so I downloaded baritone-api-forge-1.2.13

**Comment by dirtySusan** [comment]
I'm stuck on how I'm supposed to build it

**Comment by dirtySusan** [comment]
what instructions am I supposed to follow

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone/blob/master/SETUP.md#more-info

**Comment by dirtySusan** [comment]
yeah, i read through it but I'm stuck

**Comment by dirtySusan** [comment]
i follow the instructions for intellij?

**Comment by dirtySusan** [comment]
v1.2.13

Assets

baritone-api-1.2.13.jar
**baritone-api-forge-1.2.13.jar**
baritone-standalone-1.2.13.jar
baritone-standalone-forge-1.2.13.jar
baritone-unoptimized-1.2.13.jar
checksums.txt
checksums_signed.asc
Source code (zip)
Source code(tar.gz)

**Comment by dirtySusan** [comment]
Is the thing in bold the only thing that I need to download.  The instructions aren't good and everyone just keeps on giving me that link instead of actually helping.
