### ISSUE TITLE
1.15.2 unable to install

### ISSUE THREAD

**Issue by VaraWWW** [ImpactDevelopment/ImpactIssues#2183]
Whenever I try to install the Nightly 1.15.2 client the '1.15.2' option doesn't show up

1. Open the installer
2. Click on 'Options'
3. See error

**Expected behaviour**
For the 1.15.2 option to show up

**Screenshots**
**https://imgur.com/a/w7mijoV**

- Impact Version: 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 64bit

</details>

**Comment by dominikaaaa** [comment]
Download the latest nightly installer.
