### ISSUE TITLE
Clicking in Friends and Macro GUIs is completely broken in 1.14+

### ISSUE THREAD

**Issue by Daenges** [ImpactDevelopment/ImpactIssues#2191]
**Describe the bug**
You can only edit the first entry in both Friends and Macro GUI, because you are unable to switch the selection.

**To Reproduce**
1. Go in one of the interfaces.
2. Create more than one entry.
3. Try to switch the selection.
4. Doesn't work.

**Expected behavior**
You should be able to switch between the entries to edit them.

**Screenshots**
It is difficult to show that you can't switch through a screenshot.

- Impact Version: <4.8.3 /  20200412>
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: none
- Operating System: <Windows 10 64bit>

**Comment by dominikaaaa** [comment]
Can you send a video of this issue please?

**Comment by Daenges** [comment]
> 
> 
> Can you send a video of this issue please?

Okay, I made a video. I found out that you can switch in the macro section between the first two, with left-/rightclick, but not more. https://youtu.be/BzvQjLhtKRY

**Comment by MightyKnight** [comment]
Marking this as **critical**, You're literally not able to navigate the Macro GUI, might as well not be there.

**Comment by SWP360** [comment]
damn bro

**Comment by MightyKnight** [comment]
Apparently navigation is bound to mouse buttons. To navigate, press:

**1st:** MOUSE1 (left click)
**2nd:** MOUSE2 (right click)
**3nd:** MOUSE3 (middle click)
And so on...

I can also reach further options because my mouse has 5 buttons. All in all that seems strange.

**Comment by dominikaaaa** [comment]
brainletdy moment

**Comment by LeafHacker** [comment]
This sounds like the kinda thing that'd creep in while porting to a new Minecraft version. Does anyone know which versions it affects?

**Comment by Vort** [comment]
1.14.4 definitely have this problem. Did not tested other versions.

**Comment by Daenges** [comment]
> 
> 
> This sounds like the kinda thing that'd creep in while porting to a new Minecraft version. Does anyone know which versions it affects?

Okay, so I tested it in several versions in the recent nightly (20200601):
1.12.2 -> Friends and macro are working.
1.13.2 -> (No nightly available in the installer at all for this version, so in an outdated nightly: 20200423) Both are working!
1.14.4 -> (in 20200527)  Problem occures!
1.15.2 -> (in 20200527) Problem occures!

It is very strange that MightyKnights discovery with the mouse buttons only work for the makro tab. The friend GUI completely malfunktions.

**Comment by dominikaaaa** [comment]
Thanks for testing this

**Comment by LeafHacker** [comment]
Yep definitly a porting issue:

```java
this.selected = p_mouseClicked_5_; //FIXME check if p_mouseClicked_5_ is index or button
```
Will be fixed in tonight's nightly

**Comment by dominikaaaa** [comment]
> // FIXME

**Comment by Daenges** [comment]
> 
> 
> Yep definitly a porting issue:
> 
> ```java
> this.selected = p_mouseClicked_5_; //FIXME check if p_mouseClicked_5_ is index or button
> ```
> 
> Will be fixed in tonight's nightly

Okay, the Friend GUI is still bugged. If you click edit, you can neither change the nickname, nor the name. You are simply unable to click on the textboxes. And if you want to edit the macros, the text of the macro is cleared in edit window, so you don't know which macro you edit. Tested in 20200608.

**Comment by LeafHacker** [comment]
@daenges those are separate issues, but it is the first I've heard of them. Would you open them as another two (new) issues so they can be tracked individually? Ideally with the minecraft versions/impact versions affected by the respective issues. Thanks
