### ISSUE TITLE
Skin blink permanently broke all my skins  

### ISSUE THREAD

**Issue by HONKK** [ImpactDevelopment/ImpactIssues#2197]
Basically whenever i launch minecraft with any skin  its half corrupted but when i turn on skin blinker it recognizes if have other parts to the skin but as soon as i turn it off or switch to normal minecraft my skin is corrupted i tried uninstalling and reinstalling i tried uninstalling impact also didn't help so im clueless contact if you know how to fix pls

**Comment by LeafHacker** [comment]
How does toggling stuff in `Options ⇒ Skin Customization` affect your skin?

**Comment by HONKK** [comment]
Skin blinker broke it when i turned skin blinker on

**Comment by LeafHacker** [comment]
Sorry, could you be a bit more explicit?

Are you saying that toggling stuff in Skin Customization fixes your skin and then toggling Blink breaks it again? Or are you saying that Blink has broken Skin Customization somehow?

Do you have any screenshots of the issue(s) and of your normal skin too?

**Comment by HONKK** [comment]
i turned on blink and now the outer layer is broken some parts of the outer layer arent showing

**Comment by dominikaaaa** [comment]
Please follow the instructions that @LeafHacker gave you.

**Comment by dominikaaaa** [comment]
> How does toggling stuff in `Options ⇒ Skin Customization` affect your skin?

**Comment by Aaron2550** [comment]
> i turned on blink and now the outer layer is broken some parts of the outer layer arent showing

thats what blink is supposed to do...maybe read the tooltips before u click on random shit next time...

**Comment by dominikaaaa** [comment]
l o l

**Comment by Aaron2550** [comment]
get ready for my next issue
