### ISSUE TITLE
Adding a Auto Store Item Function

### ISSUE THREAD

**Issue by OptimizerGH** [ImpactDevelopment/ImpactIssues#2201]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, however it would be helpful.

**Describe the solution you'd like**
Add a function to able to store (non hotbar) items in chests automatically after inventory is filled from mining.

**Describe alternatives you've considered**
Be able to store specific items in chests, (ex. #autostore diamond_ore ),
Be able to store them in nearby chests or specified chests.

**Additional context**
I know this would be a very helpful feature for alot of players and would take quite some time to
implement but i think it would be worth it 👍

**Comment by dominikaaaa** [comment]
This is a suggestion for the baritone repo and has been suggested numerous times already. https://github.com/cabaletta/baritone/issues/605
