### ISSUE TITLE
Impact isn't showing up in the minecraft launcher

### ISSUE THREAD

**Issue by OmiZ101** [ImpactDevelopment/ImpactIssues#2205]
So I've just recently downloaded the impact 4.8.3.jar for 1.14.4, and when I open up my launcher to see where it the version is, it's not there. I double checked the version, re-downloaded the versions into the default minecraft directory, used both .exe and .jar, but to no avail. Is there any solution to this?

- Impact Version: < 4.8.3 1.14.4>
- Using Optifine? < no>
- Using LiteLoader? < NO>
- Enabled mods: 
- Operating System: < Windows 10 home 64 bit

**Comment by dominikaaaa** [comment]
You need to install Impact before it shows up in the launcher.

**Comment by OmiZ101** [comment]
Never mind, apparently the newer Minecraft launcher tends to prevent users from accessing unofficial version. I just switched to the legacy launcher and it works perfectly.
