### ISSUE TITLE
Keep x amount of items for AutoEject

### ISSUE THREAD

**Issue by turret001** [ImpactDevelopment/ImpactIssues#2208]
**Is your question request related to a problem? Please describe.**
No, this is a suggestion

**Describe what you are trying to achieve**
It would be nice to add a "keep x amount of items in inventory" option for autoeject. This could be useful for Baritone auto miner. 

**Additional context**
Nope

**Comment by turret001** [comment]
I'm sorry, I accidentally made this a question instead of suggestion. I'm not good with github

**Comment by MightyKnight** [comment]
Duplicate of #1669
