### ISSUE TITLE
edit colors & make custom font's possible

### ISSUE THREAD

**Issue by obamasbush** [ImpactDevelopment/ImpactIssues#2210]
some suggestions i've thought of that are merely gui & visual improvements

- allow custom colors (color wheel) for HUD Information elements (coordiantes, fps, tps, biome, etc.)
- allow custom ttf fonts (already possible but very difficult and hard for java newcomers) instead of just the Comfortaa font.

**Comment by dominikaaaa** [comment]
Duplicate of #680
