### ISSUE TITLE
Separate reach module

### ISSUE THREAD

**Issue by cancerousname69** [ImpactDevelopment/ImpactIssues#2212]
**Is your feature request related to a problem? Please describe.**
Impact currently does not have a Reach module. Most client modifications implement it in some way or another, and it is very uncommon to see one without.

**Describe the solution you'd like**
A module named "Reach", which modifies the players Attack- and Build range separately based on two sliders in the ClickGUI.

**Describe alternatives you've considered**
There are none.

**Comment by dominikaaaa** [comment]
Duplicate of #211
