### ISSUE TITLE
Addition of “Multi-Connect” feature?

### ISSUE THREAD

**Issue by TheFlyingDookey** [ImpactDevelopment/ImpactIssues#2213]
I have an idea for a new feature in future client releases. It’s called the Multi-Connect feature which allows a player to join a server of lower version than the client they’re playing on. It’s not my idea since I found of its existence through the Aristois client, but it seems pretty useful for players who like to play on their favorite client but won’t have to switch versions to play on an older version (e.g. you’re on 1.14 client but wanna play on 2b2t (1.12), the Multi-Connect would allow you to play on 1.12). It would be nice to see it on more than one client.

**Comment by dominikaaaa** [comment]
Closing this as won't fix, as this is extremely janky to implement and takes loads of work.
