### ISSUE TITLE
Mouse gets inverted when i sneak! (without having any hacks on)

### ISSUE THREAD

**Issue by Axelium27** [ImpactDevelopment/ImpactIssues#2214]
Whether I have hacks ON or OFF, when I sneak, the mouse gets inverted (as in when i move it upwards it goes down), 
I checked the in-game settings and everythings is fine, the issue only comes when i use my Impact Client minecraft profile...
I havent seen anyone else have this issue on other minecraft forums or whatever so please help !!!

- Impact Version: <4.8 for 1.14.4>
- Using Optifine? <No>
- Using LiteLoader? <No>
- Enabled mods: <None>
- Operating System: <Windows 10 64bit>

**Comment by LeafHacker** [comment]
Do you have sneak bound to Left Alt by any chance?

**Comment by Axelium27** [comment]
Yes!!!! i have it bound to left alt lol

**Comment by ScanmanTM** [comment]
Do .perspective toggle

**Comment by Axelium27** [comment]
Work perfectly!!! Thank you very much :)
