### ISSUE TITLE
Invalid token at donating

### ISSUE THREAD

**Issue by sentakuto** [ImpactDevelopment/ImpactIssues#2215]
**Is your question request related to a problem? Please describe.**
Hello, I just donated to get Access to the Donator Features. The Problem is following: After I donated and wanted to register, it said "Invalid token" I tried it a second time, so spend another 5$, but the same thing happened again

**Describe what you are trying to achieve**
I want my Minecraft Account to get Access to the Donator Features.

**Additional context**
I already donated for another Minecraft Account I own with the same Paypal, could that maybe be the cause of this Problem? 

![image](https://user-images.githubusercontent.com/64399144/80343517-51e18f80-8866-11ea-9c24-04bfa0e5fc4f.png)

**Comment by dominikaaaa** [comment]
That means your token expired, you left the page opened too long. Ask for help on the discord.
