### ISSUE TITLE
Chunk/World comparison using seed to detect player modifications

### ISSUE THREAD

**Issue by fluse1367** [ImpactDevelopment/ImpactIssues#2217]
**Is your feature request related to a problem? Please describe.**
On servers like 2b2t.org it can be sometimes really difficult to track players even when using the New Chunks module. Often you just walk around and stumble into a newly generated chunk, turn around try another direction an so on... really time consuming. 

**Describe the solution you'd like**
It would be really helpful if impact would be able to show you world modifications made by players.
I imagined something like the search module (with tracers) or the storage ESP module, that highlight blocks that wouldn't be there by natural generation. Of course for this, the seed would be needed in order for the client to generate the chunks by itself and compare it to the ones on the server.
You could track player way easier and accurately. But to not get too confused, it would be good if you can select (or rather exclude) the blocks that should be highlighted (like the search module), e.g. that air blocks wont be highlighted, if you don't want that. Also it could be important to limit the blocks highlighted to not lag or even freeze the game (maybe for chunks that were generated in another version of the game). Then a message like "There are other blocks that haven been modified but the highlight limit of x blocks has been reached."

**Describe alternatives you've considered**
You can start a second instance of minecraft and generate the world by yourself, but this is very inconvenient as you would have to constantly switch between the two instances and walk all the way in both instances. You would also have to figure out the differences by yourself.

**Additional context**
Of course the client would need to simultaneously generate a new world, that takes more cpu usage than just playing on a server, where the server takes care of generating the world. But when playing in singleplayer the client does generate the world by itself too.

**Comment by dominikaaaa** [comment]
This isn't possible because you can't know what version the chunk was created in. 

Also this would be too much work as you'd need to load Minecraft twice anyways.

**Comment by fluse1367** [comment]
> This isn't possible because you can't know what version the chunk was created in.

For this the highlight limit would apply. By comparing the bedrock the client could also try to "guess" if the chunk was generated in the current version of the game or not.

> Also this would be too much work as you'd need to load Minecraft twice anyways.

Why you'd need to load Minecraft twice? E.g the whole gui, entity spawning (and handling), redstone mechanincs aren't needed. Only the world generation. And there already programs out there that generate worlds.

**Comment by dominikaaaa** [comment]
And you can use those programs. Nobodies adding a feature that's unreliable and has to guess, which might not work.

**Comment by dominikaaaa** [comment]
Don't get me wrong, it's a neat idea but it's not really viable.
