### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by jeffboy70** [ImpactDevelopment/ImpactIssues#2218]
Describe the bug
My game launches then immediately crashes. I am not using optifine.

To Reproduce

Go to 'launcher'
Click on 'launch'
See error

**Comment by dominikaaaa** [comment]
Fill out the issue template properly.

**Comment by jeffboy70** [comment]
How do I find the log?

**Comment by dominikaaaa** [comment]
Inside the logs folder.

**Comment by jeffboy70** [comment]
It is not generating a log either

**Comment by dominikaaaa** [comment]
If it instantly crashes that means you need to use Oracle JDK 8
