### ISSUE TITLE
1. I'm banned for no reason. 2. I cannot install Impact.

### ISSUE THREAD

**Issue by mememasterboi** [ImpactDevelopment/ImpactIssues#2230]
1. I'm banned from your discord for no reason. I've never even been in it before.
2. It stops me from installing Impact 4.8 for minecraft 1.12.0

**Comment by LeafHacker** [comment]
4.8 doesn't have a version for 1.12.0. 4.8.3 supports 1.12.2, 1.13.2 and 1.14.4

> I'm banned from your discord for no reason. I've never even been in it before.

You've not included any information for us to look into that. Are you able to join via our [verification](http://impactclient.net/discord) process? If not, what is your discord ID?

**Comment by dominikaaaa** [comment]
What is stopping you from installing it? Reopen this issue once you've provided the requested information.
