### ISSUE TITLE
Regex chat filter

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ImpactDevelopment/ImpactIssues#2231]
Players using PhiBot, mooomooo, etc flood the chat with garbage. Mass /ignoring everyone is a pain.

**Describe the solution you'd like**
A way to regex filter out messages similar to [here](https://www.reddit.com/r/constantiam/comments/gak2vr/how_to_filter_out_annoying_bot_commands_without/)

**Comment by dominikaaaa** [comment]
Duplicate of #1707
