### ISSUE TITLE
Installer hangs on "DOWNLOADING http://impactclient.net/releases.json"

### ISSUE THREAD

**Issue by PittacusOfLorien** [ImpactDevelopment/ImpactIssues#2238]
**Describe the bug**
Installer appears to hang while downlaoding `releases.json` from http://impactclient.net/
Additionally, the window created is blank.

**To Reproduce**
1. Download latest version (0.8.6) of the ImpactInstaller from the github releases page.
2. Set Java environment as java-8-jre/jre
3. Execute `java -jar ImpactInstaller-0.8.6.jar`
4. A blank window is created.
5. Messages are printed to stdout, detailed in Crash report section.

**Expected behavior**
ImpactInstaller is launched successfully and presents the user with options for installing Impact client.

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sending event category=installer action=display label=null cid=2bf1a456-8dbb-11ea-a184-52c739696854 
Fetching releases from ImpactDevelopment/ImpactReleases
DOWNLOADING http://impactclient.net/releases.json
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 0.8.6.jar for 1.12.2
- Operating System: Arch Linux
- Java Environment: java-8-jre/jre
- Window Manager: bspwm

</details>

**Comment by dominikaaaa** [comment]
Use Oracle JDK https://www.oracle.com/java/technologies/javase-jdk8-downloads.html

**Comment by haztecaso** [comment]
Hello, I have the exact same issue, on arch linux with java-8-jre/jre (the oracle one).

**Comment by dominikaaaa** [comment]
`echo $JAVA_HOME`

**Comment by lachlantula** [comment]
I'm having the same issue on Arch as well with Oracle's jdk8 (set as system default) and Impact Installer 0.9.3. I receive the same output as OP by following the same reproduction steps. `echo $JAVA_HOME` does not return anything.

**Comment by l1ving** [comment]
> echo $JAVA_HOME does not return anything.

That's a you problem. Fix it first

**Comment by lachlantula** [comment]
Arch does not set nor use `JAVA_HOME` to my knowledge. It would point to `/usr/lib/jvm/default`, I believe.

**Comment by l1ving** [comment]
> nor use

entirely untrue 

>  It would point to /usr/lib/jvm/default, I believe.

Completely false 

https://wiki.archlinux.org/index.php/Java

**Comment by l1ving** [comment]
Closing this as resolved, user error. Open a new issue if you've completed the above steps and it still happens.

**Comment by LeafHacker** [comment]
> > nor use
> 
> entirely untrue 
> 
> >  It would point to /usr/lib/jvm/default, I believe.
> 
> Completely false 
> 
> https://wiki.archlinux.org/index.php/Java

AFAICT the OP is correct, that wiki article makes little-to-no mention of `JAVA_HOME`

**Comment by l1ving** [comment]
OpenJDK works fine. You **need** your Java home set or manually set your Java path in the Minecraft launcher on Linux. 

This is still user error

**Comment by oicleevan** [comment]
My $JAVA_HOME is set. This still occurs.

**Comment by DannyParker0001** [comment]
run `wmname LG3D`
