### ISSUE TITLE
ESP/Breadcrums/chunk borders are all grey

### ISSUE THREAD

**Issue by Zizzles27** [ImpactDevelopment/ImpactIssues#2239]
**Describe the bug**
I have a specific color picked for all the things mentioned in the title but when I go into a single player or multiplayer world everything except tracers and baritone paths turn grey. 

**To Reproduce**
1. Use impact 4.8.3(newest) run on forge for 1.12.2
2. Go into a single player or multiplayer world
3. Everything is grey

**Expected behavior**
ESP, breadcrumbs, chunk borders should be the colors I picked.

**Screenshots**
![6A6E0EED-67C4-4D47-B49F-9669750C3FD9](https://user-images.githubusercontent.com/64775330/80949882-1557eb80-8db2-11ea-8a9f-bf06ae771a0f.jpeg)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
I honestly have no idea what this means
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
Please fill out the issue template properly.
