### ISSUE TITLE
discord stumped linux crashes 

### ISSUE THREAD

**Issue by beartravels** [ImpactDevelopment/ImpactIssues#2249]
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4583279/latest.log)
pure vanilla log
![Screenshot from 2020-05-05 11-57-58](https://user-images.githubusercontent.com/64866787/81109304-bcca4080-8ece-11ea-8f81-354f3076e06e.png)
this is impacts log
i just fully reinstalled minecraft after using wurst and this is what i get when i install impact
i use ubuntu 18.04 64 bit
because I just reinstalled minecraft there is no crash report files

**Comment by dominikaaaa** [comment]
Use Oracle JDK 8

**Comment by beartravels** [comment]
is there a better way to download it
i cant download partial files

**Comment by dominikaaaa** [comment]
JRE* my bad

Extract this to ~/.local/bin and set your JAVA_HOME or Minecraft JRE path to it https://mega.nz/#!9xlXzDpa!b_WTeeKf1A3uvYvzA_bNXci5mI3RwRppQYZnBWvpodM

**Comment by beartravels** [comment]
np i think this is correct 
![Screenshot from 2020-05-05 13-27-55](https://user-images.githubusercontent.com/64866787/81112965-50524000-8ed4-11ea-961d-932a3d83a215.png)

**Comment by dominikaaaa** [comment]
When echoing you need to use the proper variable name, JAVA_HOME

Also you should set it in Minecraft's launcher to be sure

**Comment by beartravels** [comment]
![Screenshot from 2020-05-05 13-30-44](https://user-images.githubusercontent.com/64866787/81113177-a6bf7e80-8ed4-11ea-8eba-b99765e26445.png)

**Comment by beartravels** [comment]
gonna run minecraft

**Comment by beartravels** [comment]
![Screenshot from 2020-05-05 13-31-37](https://user-images.githubusercontent.com/64866787/81113240-c2c32000-8ed4-11ea-9425-9c2781a408a1.png)

**Comment by dominikaaaa** [comment]
As I said, set it in Minecraft

**Comment by beartravels** [comment]
itll take a momen ti am looing thru the launcher now

**Comment by beartravels** [comment]
whitch of the fulles in jr8 do i open for java exicutables

**Comment by dominikaaaa** [comment]
you select the `extracted folder/bin/java`

**Comment by beartravels** [comment]
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4583536/latest.log)
RUNNING

**Comment by dominikaaaa** [comment]
Well this is a different issue.

**Comment by beartravels** [comment]
huh?
