### ISSUE TITLE
Separate ItemEsp

### ISSUE THREAD

**Issue by kekkekek** [ImpactDevelopment/ImpactIssues#225]
I don't have the best pc, so normal ESP lags my mc. I would prefer to use the old ItemESP from 3.0 which doesn't lag and is useful when looking for items

**Comment by ZeroMemes** [comment]
There's multiple ESP modes, which one is causing the lag?

**Comment by LeafHacker** [comment]
Without looking too closely, it is possible the more complex filtering is
the issue, since I suspect most everything else is the same when only items
are enabled.

That said, I wouldn't expect a few filters to her too intensive...

**Comment by ZeroMemes** [comment]
I'm assuming that the Shader mode is causing the lag, re-rendering the entities that are targeted along with the shader program itself, which isn't *greatly* optimized. A simple solution to this would to be adding the old outline mode back in as an option for performance.

**Comment by kekkekek** [comment]
I only use the itemesp and the normal ESP I don't use, I prefer just items

**Comment by SuperOP535** [comment]
Can't you just uncheck other entities

**Comment by kekkekek** [comment]
Can you?

**Comment by ZeroMemes** [comment]
@kekkekek What *mode* are you using for ESP?
