### ISSUE TITLE
Impact disables replay mod

### ISSUE THREAD

**Issue by petroboti** [ImpactDevelopment/ImpactIssues#2250]
I can use the replay mod and impact individually but when i place both of them into the mods folder, only impact works with no problems.
Using minecraft 1.12.2 with forge 64bit

**Comment by dominikaaaa** [comment]
Try uninstalling replay mod, that should fix the issue.

**Comment by Moondarker** [comment]
Replay Mod is using Sponge Mixin v0.8 since v2.3.0, for now the only workaround is to use v2.2.0-b7 as Impact is still on Mixin v0.7.11
