### ISSUE TITLE
I cannot download this because adfly doesn't work.

### ISSUE THREAD

**Issue by yeojyeojo** [ImpactDevelopment/ImpactIssues#2253]
I have Norton, but I don't think that's the problem. Because it says Website can't be reached. But my norton alerts me that it is a "Malicious Domain". Please help!

**Comment by dominikaaaa** [comment]
Disable Norton.

**Comment by dominikaaaa** [comment]
https://impactclient.net/?brady-money-grubbing-completed=true&platform=exe
Or use this link
