### ISSUE TITLE
HoleESP, HoleBot and ChestAura

### ISSUE THREAD

**Issue by DuckyWucky69** [ImpactDevelopment/ImpactIssues#2254]
I recommend working on and implementing HoleESP, some HoleBot ( with baritone ) and ChestAura ( as seen in the title )

HoleESP >
I was thinking something like Red for the least safe blocks where you will take less damage than you would in the open, yellow for slightly better and green for the best spots to get into, maybe make a bot that automatically does that for you too, like a holebot?

ChestAura >
Opens and closes every chest around you so that if there are any illegal items they will be reverted or deleted, and easier to look for dupe stashes, maybe make it work with chest steal, so if chest steal is on it will keep the chest gui open for long enough to take as much from the chest as possible

**Comment by dominikaaaa** [comment]
Fill out the issue template properly. And open separate suggestions in separate issues. 

Also, duplicates of #2245, #1528, and the 2nd one had 0 detail whatsoever
