### ISSUE TITLE
impact crashing with future client

### ISSUE THREAD

**Issue by crylicwho** [ImpactDevelopment/ImpactIssues#2255]
**Is your question request related to a problem? Please describe.**
future client crashes impact. someone told me you have to rename impact to load its mixins first but how do you do that

**Describe what you are trying to achieve**
using impact and future at the same time

**Additional context**
link me to a issue that tells me how to do that or just tell me here

**Comment by dominikaaaa** [comment]
Fill out the issue template properly next time. As for renaming it, right click the forge mod and hit rename.
