### ISSUE TITLE
FreeCam Jumps

### ISSUE THREAD

**Issue by thetayloredman** [ImpactDevelopment/ImpactIssues#2264]
**Describe the bug**
Freecam makes the player get stuck in some kind of Jump loop.

**To Reproduce**
Turn on FreeCam
BAM DONE

**Expected behavior**
FreeCam to turn on

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
N/A
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
None was generated
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
none

**Comment by dominikaaaa** [comment]
Fill out the issue template properly.
