### ISSUE TITLE
Getting hurt and Dying when moving or Jumping

### ISSUE THREAD

**Issue by dkim19375** [ImpactDevelopment/ImpactIssues#2265]
**Describe the bug**
About 75% of the time, I get hurt and sometimes die. Armor does not do anything.
**To Reproduce**
I do not know why this happens. My best guess of how to reproduce is to turn on all the hacks I have turned on.

**Expected behavior**
Not get hurt.

**Screenshots**
![image](https://user-images.githubusercontent.com/65050767/81458022-68d98900-9166-11ea-9768-ae4f4956e7ce.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: All in screenshot; there's way to many.
- Operating System: Windows 10 64bit

</details>

**Additional context**
Sorry if I didn't put enough information

**Comment by dominikaaaa** [comment]
Probably NoFall or some other movement mod. I can't reproduce this issue in singleplayer.
