### ISSUE TITLE
Keystroke

### ISSUE THREAD

**Issue by 3njoyToilet** [ImpactDevelopment/ImpactIssues#2266]
**Is your feature request related to a problem? Please describe.**
I wish that the server could add keystrokes+ cps as it would help in pvp since you cannot download mods with the hack client

**Describe the solution you'd like**
A new feature called Keystrokes where It shows your CPS ect

**Describe alternatives you've considered**
Maybe a fix with the build and a tutorial on the baritone commands and schematics

**Additional context**
![image](https://user-images.githubusercontent.com/55245978/81473722-56a82b00-91f8-11ea-89f3-b74da7ad932b.png)

**Comment by 3njoyToilet** [comment]
Please read guys it would be a nice feature

**Comment by dominikaaaa** [comment]
This isn't in the scope of impact, just download any other mod that does this.
