### ISSUE TITLE
Macros won't be really removed without restart

### ISSUE THREAD

**Issue by impulsiva** [ImpactDevelopment/ImpactIssues#2268]
**Describe the bug**
Macros won't be removed without restarting the game.

**To Reproduce**
1. Add a macro
2. Run it
3. Remove it
4. Macro will keep working, while won't be displayed at Macros menu

**Expected behavior**
Macro should stop working on key press

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Operating System: Windows 10 x64

</details>

**Comment by dominikaaaa** [comment]
This should be fixed in 4.9 iirc.
