### ISSUE TITLE
add speed mine. speed up mining speed. etc

### ISSUE THREAD

**Issue by hanzedellion** [ImpactDevelopment/ImpactIssues#2271]
Please add an option that speeds up the mining speed. like those on other clients and also fast regen(it uses the players hanger faster but it heals faster)

and one more thing FULL BRIGHT: it brightens up everything(so players can see better but when turned off its still dark)

**Comment by dominikaaaa** [comment]
Please open individual issues for individual suggestions. Also for the first one, that's already a thing. The second one isn't possible. The 3rd one is already a thing.
