### ISSUE TITLE
hole ESP

### ISSUE THREAD

**Issue by MasterValler** [ImpactDevelopment/ImpactIssues#2272]
hole ESP is a hack that finds a safe spot in the bedrock/obsidian that is safe from crystals

the hole ESP should have (for example) red color for a completely safe area 1x2x1 hole, purple for a semi-safe area (some blocks are obidian ect) blue for a 1x1x1 hole whitch allows you to not be damaged, but your armor will be damaged.

alternative/better solution is when you kit a specific key/button on your keyboard it makes you go to the closest/safest area around you and turns off when it moves you.

**Comment by dominikaaaa** [comment]
#2245
