### ISSUE TITLE
Chest aura

### ISSUE THREAD

**Issue by MasterValler** [ImpactDevelopment/ImpactIssues#2273]
i think chestaura would help people rake care of dupe stashed by quickly checking if a chest is full or not and taking the certain items they want to have/take

an option to allow me to check whats in the chest by looking at it instead of opening it

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/81517553-4fbd0d80-9309-11ea-9dd1-3f9bb9a2c311.png)

**Comment by dominikaaaa** [comment]
#818
