### ISSUE TITLE
Auto Mount feature

### ISSUE THREAD

**Issue by CammB** [ImpactDevelopment/ImpactIssues#2277]
**Describe the solution you'd like**
An auto mount entity feature similar to future client that would assist in bypassing duping patch plugins.

**Comment by ScanmanTM** [comment]
Dupe of #1778, next time search for existing issues SalC1 fanboy.

**Comment by dominikaaaa** [comment]
Actually it's different. They're asking you to add a module which executes one line of code, which cancels mount packets.

**Comment by ScanmanTM** [comment]
You can reopen if you want.

**Comment by dominikaaaa** [comment]
The mount bypass relies on a shitty anti dupe plugin which some anarchy servers use. No doubt it'll be fixed within a week anyways
