### ISSUE TITLE
Installer download is offline 

### ISSUE THREAD

**Issue by thatamy** [ImpactDevelopment/ImpactIssues#2279]
When i press download it takes me to here: http://evassmat.com/K44b and comes up with:

"This site can’t be reachedThe webpage at http://evassmat.com/K44b might be temporarily down or it may have moved permanently to a new web address.
ERR_CONNECTION_ABORTED"

Could someone please help me with this?

**Comment by dominikaaaa** [comment]
@LeafHacker I confirmed this. Might wanna take a look at it.

**Comment by ScanmanTM** [comment]
Works for me, you probably have something blocking the URL, such as an anti-virus.

**Comment by dominikaaaa** [comment]
Are you sure it isn't cached?

![Screenshot_20200515-100340](https://user-images.githubusercontent.com/17222512/82058940-68c01880-9693-11ea-9843-189639aa889d.png)

**Comment by ScanmanTM** [comment]
Tested in incognito, edge, and on mobile
![Screenshot_20200515-173826](https://user-images.githubusercontent.com/46611235/82074865-4cdc6700-96d3-11ea-90d0-aa9d3141c753.png)

**Comment by dominikaaaa** [comment]
I tried going to the money grubbing link as well and it always brings me to the not found page. 

Android 10, Chrome 81

**Comment by LeafHacker** [comment]
There appears to be two issues being discussed here but I can't reproduce either.
The first issue, reported by op, is one of the ad-redirects not working. That appears to be resolved afaict and was probably just an outage on their part.

The second issue highlighted by @dominikaaaa looks like a bad link somewhere. The URL in the screenshot is .jar&donator=true but it should be .jar?nightly=true.

It's possible the incorrect URL is a red herring, but I can't think of any scenario where the server would 404; if the server was down it'd be a 5xx, for example.

**Comment by dominikaaaa** [comment]
That's possible, I'll try the url manually later

**Comment by dominikaaaa** [comment]
Works for me, my bad.
