### ISSUE TITLE
Freecam - Option to cancel movement packets

### ISSUE THREAD

**Issue by Lerbiq** [ImpactDevelopment/ImpactIssues#2283]
**Is your feature request related to a problem? Please describe.**
No. But it would be quite a useful feature.

**Describe the solution you'd like**
I cant code in java so I can't tell you how to code it in but since it's just packet canceling it shouldn't be that hard.

**Describe alternatives you've considered**
Using blink alongside freecam but the client disconnects after some time.

**Comment by dominikaaaa** [comment]
#848

**Comment by dominikaaaa** [comment]
also packet cancel also kicks you after some time

the difference between blink and packet cancel is that blink sends the packets back to the server when you unblink, and packet cancel doesn't
