### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by thatweirdkaden** [ImpactDevelopment/ImpactIssues#2285]
**Describe the bug**
Impact starts but then crashes immediately. 

**To Reproduce**
Start minecraft
start impact (vanilla)
crash

**Expected behavior**
Impact starts with no crash.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://hastebin.com/ecurexisan.makefile
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Latest
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: n/a
- Operating System: Windows 10 64Bit

</details>

**Additional context**

**Comment by MightyKnight** [comment]
Your crash report link doesn't work. Closing as **Invalid**.

**Comment by dominikaaaa** [comment]
In the future, don't use hastebin, they automatically delete pastes.
