### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by matttttthew** [ImpactDevelopment/ImpactIssues#2287]
When i try to install Impact it says the "the sites can not be reached The web page at http://evassmat.com/K44b might be temporarily down or it may have moved permanently to a new web address. I dont know if this is an add or the site of the download.
![error](https://user-images.githubusercontent.com/65406429/82058811-28759000-96bd-11ea-9bbd-1375f64f034b.PNG)

**Comment by dominikaaaa** [comment]
https://impactdevelopment.github.io/?brady-money-grubbing-completed=true&platform=exe
