### ISSUE TITLE
Irc Chat

### ISSUE THREAD

**Issue by Dinandpower** [ImpactDevelopment/ImpactIssues#2291]
Ive saw some cool other client who had "Irc"
Its normaly just a chat for client users and people use it so much
its maybe cool to try or atleast for premium users and maybe somerules
cuz its really useful for uses to help eachother and talk with others

Thx, Devs

**Comment by ScanmanTM** [comment]
Ive saw some cool other issue suggest this. 
Search issues before you make one.
