### ISSUE TITLE
come si risolve il prblema che impact 1.15.2 mi da arresto anomalo

### ISSUE THREAD

**Issue by Budinos** [ImpactDevelopment/ImpactIssues#2292]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
thank you for using the English language in a English community.
Closed: Didn't fill out a simple template.
