### ISSUE TITLE
Games crashes on start

### ISSUE THREAD

**Issue by Budinos** [ImpactDevelopment/ImpactIssues#2300]
**Describe the bug
the game crashes as soon as it opens with the night version, why?
I already know that you say that the ococount is not connected with the dashboard, what do you mean? can you help me how do i connect it
**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
You're not using the correct account.
