### ISSUE TITLE
All versions of Impact 4.7 keep crashing The game crashed whilst registering texture Error: java.lang.NullPointerException: Registering texture Was working last night but now it ain't working at all how do i fix it?

### ISSUE THREAD

**Issue by ThePurpleWurmple** [ImpactDevelopment/ImpactIssues#2307]
**Is your question request related to a problem? Please describe.**

**Describe what you are trying to achieve**

**Additional context**
Add any other context or screenshots about your question here.

**Comment by dominikaaaa** [comment]
fill out the proper template
