### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by oguh43** [ImpactDevelopment/ImpactIssues#2308]
**Describe the bug**
Game crafh

**To Reproduce**
1. start the game with latest nightly

**Expected behavior**
the game to start

<details> 
  <summary><strong>Game output</strong></summary>
 

```
https://pastebin.com/q1HacdyS
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: latest nightly
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: cant load
- Operating System: win10x64

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
Not launching with the account linked in the dashboard.
