### ISSUE TITLE
When logging in it glitches out

### ISSUE THREAD

**Issue by CoscoEmployee** [ImpactDevelopment/ImpactIssues#2309]
Whenever I enter a singleplayer world or multiplayer it bugs out and stays on the logging in screen. But if I press esc all it does it pop my cursor out and keeps the window frozen.

I have tried uninstalling and reinstalling but the problem persists. The last thing I remember doing was just putting on a lot of combat and movement hacks. Sorry if I didn't give enough background I couldn't remember well what hacks I put on specifically.

**Comment by dominikaaaa** [comment]
fill out the template

**Comment by LeafHacker** [comment]
You can open clickgui from the main menu or Impact Menu, so disable mods to figure out which is causing the issue
