### ISSUE TITLE
Mobspawn ESP, Cavefinder, Enchant color(fix for 1.15.2)

### ISSUE THREAD

**Issue by lSherozl** [ImpactDevelopment/ImpactIssues#2312]
Hello, I love this mod and I switched over from Wurst, here are some things I feel like are missing that would be a great add:

MobspawnESP: Allows you to see what blocks will spawn monsters, for example, if a block is not well lit up enough it will have a yellow outline(monsters can only spawn at day) or red(monsters can spawn anytime if there is little to no lighting at all), seen mods do this and wurst does it.

Cavefinder: Outlines caves when you look at the ground, so you can see the different pathways, you can use this picture as an example, many mods have used this:  
![image](https://user-images.githubusercontent.com/65663746/82449901-2c146880-9a69-11ea-9bf5-e3cf54b90bc1.png)

Enchant colour does not work on 1.15.2, no matter if I use an anvil or an enchanting table, please see if this is fixable.

One last thing that could be a good feature, is a tracing line for players, as in a line that always keeps tab of players and where they are moving

Thank you all for your hard work!!!

**Comment by dominikaaaa** [comment]
Open seperate feature requests / bugs in seperate issues.
