### ISSUE TITLE
Mobspawnesp, Cavefinder, PlayerESP

### ISSUE THREAD

**Issue by lSherozl** [ImpactDevelopment/ImpactIssues#2313]
Hello, I love this mod and I switched over from Wurst, here are some things I feel like are missing that would be a great add:

MobspawnESP: Allows you to see what blocks will spawn monsters, for example, if a block is not well lit up enough it will have a yellow outline(monsters can only spawn at day) or red(monsters can spawn anytime if there is little to no lighting at all), seen mods do this and wurst does it.
![image](https://user-images.githubusercontent.com/65663746/82450566-15badc80-9a6a-11ea-9ccd-fd4a665fc4f0.png)

Cavefinder: Outlines caves when you look at the ground, so you can see the different pathways, you can use this picture as an example, many mods have used this:
![image](https://user-images.githubusercontent.com/65663746/82450533-09cf1a80-9a6a-11ea-8916-632d0f09f41d.png)

PlayerESP: It would be helpful to have a specific mod to track players, like a coloured line tracing them or a box specific to them and not other entities.

Thank you for your hard work!

**Comment by dominikaaaa** [comment]
I asked you to seperate it into multiple issues in #2312, please

**Comment by lSherozl** [comment]
Oh sorry does each thing have to be seperate

**Comment by dominikaaaa** [comment]
ye
