### ISSUE TITLE
PlayerEsp

### ISSUE THREAD

**Issue by lSherozl** [ImpactDevelopment/ImpactIssues#2316]
Hello, I love this mod and I switched over from Wurst, here are some things I feel like are missing that would be a great add:

A PlayerESP dedicated to players would be great, for example, players have specific lines tracing them or a box outline specific only for them to distinguish them from the rest of mobs. I don't have any pictures to show, but when I had used wurst, it was a custom coloured line, that went from my crosshair to any player. Thank you

**Comment by dominikaaaa** [comment]
Tracers already do this I'm pretty sure, and you can change it to only players.
