### ISSUE TITLE
mountBypass feature -- allowing chests to be placed on donkeys on servers banning it

### ISSUE THREAD

**Issue by areilly03** [ImpactDevelopment/ImpactIssues#2318]
Now that future client has automount, it gives a huge advantage to those users on many 1.12.2 anarchy servers in regards to duping.  By adding this feature, compatible with servers like constantiam, Impact would easily be the best client.  Also, the hack would enable incredible duping.

**Comment by dominikaaaa** [comment]
This is already patched.

**Comment by dominikaaaa** [comment]
#2277
