### ISSUE TITLE
Baritone '#sel ca' then '#pause' doesn't stop auto mining but does stop tracking

### ISSUE THREAD

**Issue by charlesathon** [ImpactDevelopment/ImpactIssues#2319]
When using the baritone command #sel ca, the pause function only works on the pausing of the automatic block tracking but now doesn't stop the auto mining so the tool is still swinging and mining the blocks in front on the player. 

Edit: this is in the latest nightly release

**Comment by dominikaaaa** [comment]
Baritone repo is that way https://github.com/cabaletta/baritone
