### ISSUE TITLE
Hypixels murder mistery

### ISSUE THREAD

**Issue by cratoman** [ImpactDevelopment/ImpactIssues#2320]
**Is your feature request related to a problem? Please describe.**
I would like that you guys add all the items such as golden carrots, gold pickaxe etc to the items list that let the client recognize a player as murder. Maybe is better if there is an editable config that does that.
**Describe the solution you'd like**
Add that to the list:
STONE_SWORD
IRON_SHOVEL
STICK
WOODEN_AXE
WOODEN_SWORD
DEAD_BUSH
STONE_SHOVEL
BLAZE_ROD
DIAMOND_SHOVEL
FEATHER
PUMPKIN_PIE
GOLDEN_PICKAXE
APPLE (has an enchantment)
NAME_TAG
SPONGE
CARROT_ON_A_STICK
BONE
CARROT
GOLDEN_CARROT

thanks. If I contribute, I know Java, Python, C, Php, Javascript and Ruby
Discord: NickP05#6940

**Comment by dominikaaaa** [comment]
#2311
