### ISSUE TITLE
Command to turn nuker on/off. .nuker on / .nuker off

### ISSUE THREAD

**Issue by BeyondVial** [ImpactDevelopment/ImpactIssues#2328]
**Is your feature request related to a problem? Please describe.**
The toggle feature for nuker isn't the best and it'd be nice if you guys added commands to turn the nuker on / off with specific commands. ".nuker on" turns on nuker and if you do it twice it still keeps it on and vice versa for ".nuker off"

**Describe the solution you'd like**
".nuker on" and ".nuker off"

**Describe alternatives you've considered**
switching hack clients

**Additional context**
this would be an awesome feature and i'm sure it won't take to long. 
* make sure this happens for 1.12.2 *

**Comment by KMatias123** [comment]
why dont you just use .t nuker

**Comment by BeyondVial** [comment]
> why dont you just use .t nuker

im integrating the nuker into a script and I need something to make sure it is on because sometimes it's on and sometimes its off. Isn't it pretty easy to add this though?

**Comment by dominikaaaa** [comment]
um, that's your codes fault. store the state of the nuker or something

**Comment by dominikaaaa** [comment]
yes it's easy to add. it's completely useless.

**Comment by BeyondVial** [comment]
> yes it's easy to add. it's completely useless.

holy shit i've never seen such shit devs you could have legit added it in the time of you bitching about it god damn

**Comment by KMatias123** [comment]
just store a boolean if the nuker is on or off its not that hard

**Comment by dominikaaaa** [comment]
you're harassing the developers because you're too lazy to parse the chat and / or store a Boolean? god damn.

**Comment by MightyKnight** [comment]
Duplicate of #1516 btw.
@BeyondVial Meaning it may at some point be considered, however it's not difficult to work around that yourself.
