### ISSUE TITLE
Crashing Error on "Entity's Vehicle: ~~ERROR~~ NullPointerException: null"

### ISSUE THREAD

**Issue by miluuuuuu** [ImpactDevelopment/ImpactIssues#2329]
im getting this crash randomly everytime i do a mouse movement such as a flick, swinging a sword, hitting someone, etc. This crash happens with multiple hacked clients, but not on vanilla. normal clients such as a Optifine only client. The odd thing is i underclocked my GPU a small bit and it makes my game last longer before it crashes.

[crash-2020-05-24_06.11.04-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4673271/crash-2020-05-24_06.11.04-client.txt)

**Comment by dominikaaaa** [comment]
Fill out the template properly.
