### ISSUE TITLE
"Packet" mode for Flight (Not as the old NCP Flight)

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactIssues#233]
There's a packet fly that WORKS on NCP (its pretty slow and you dont need an elytra).
I think Future has that.

**Comment by zPeanut** [comment]
impact ≠ future

**Comment by TheForgottenKing** [comment]
We had it before, it got deleted

Regression?

**Comment by VitorISs** [comment]
@TheForgottenKing the old NCP Flight got patched

**Comment by ZeroMemes** [comment]
Added a while ago
