### ISSUE TITLE
Truesight, to see people who are in vanish

### ISSUE THREAD

**Issue by Randomtyyppi** [ImpactDevelopment/ImpactIssues#2330]
I really prefer impact over many clients ive tried, but there are some specific things on other clients that i wish impact had. Like Wurst' truesight, that allows player to see even ppl who are in vanish.

**Comment by dudeman123** [comment]
Vanish plugins that aren't invisibility potions cant be detected by clients as no packets are even sent of the player's existence.

**Comment by dominikaaaa** [comment]
and if they are invisibility potions, ESP can show them

**Comment by Mossshie** [comment]
TrueSight works by detecting packets, while in vanish the packets that the vanish player sends are incrypted in the serverside version, While with a potion with invisibility the packets are just showned, no incryption, no nothing, TrueSight on wurst, meteor and other hacked clients wont show up vanished people.

**Comment by catm3544-ux** [comment]
whats TrueSight?
mod addon like what?
