### ISSUE TITLE
Features Dont stop when tabbed out/open chat

### ISSUE THREAD

**Issue by StevisCodes** [ImpactDevelopment/ImpactIssues#2331]
**Is your feature request related to a problem? Please describe.**
No I just want maybe a feature that allows me to tab out without it pausing, i am on a laptop so thats my only option to do something else i cant have 2 screens xd. So like if I have automine and want to tab out to watch hulu or something while it keeps going it pauses cause when i tab out the option menu opens obviously
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LeafHacker** [comment]
F3+P
