### ISSUE TITLE
Feature so mobs take less knockback when hit

### ISSUE THREAD

**Issue by StevisCodes** [ImpactDevelopment/ImpactIssues#2332]
**Is your feature request related to a problem? Please describe.**
I've seen some cheats where they are allowed to modify knockback taken from hit, can we have this type of feature so i can have my mobs take almost 0 knockback when hit hahaha thank you.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dudeman123** [comment]
a hacked client is clientside, you cant modify the behavior of server-side entities.
