### ISSUE TITLE
Macro editing is broken

### ISSUE THREAD

**Issue by Vort** [ImpactDevelopment/ImpactIssues#2333]
**Describe the bug**
When I click on macro in the list, selection do not move to it, so I can't edit it.

**To Reproduce**
1. Go to Impact->Macros
2. Add 3 macros: test1 (F5), test2 (F6), test3 (F7)
3. Click on F6 macro with left mouse button.
4. Click on F6 macro with right mouse button.
5. Click on F7 macro with left mouse button.

**Expected behavior**
3. F6 macro is selected (nothing happens).
4. Who knows what (F6 macro become selected)
5. F7 macro is selected (nothing happens).

**Screenshots**
![macro](https://user-images.githubusercontent.com/1242858/82797515-db917680-9e7f-11ea-8907-7c68cdbb5cca.png)

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.8.3 for 1.14.4
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: NoFall, AntiOverlay, StorageESP, ESP Shader, Nametags, Tracers, Portals, Light.
- Operating System: Windows 7 SP1 x64
- Java: java-1.8.0-openjdk-1.8.0.252-2.b09.ojdkbuild.windows.x86_64.zip

</details>

**Additional context**
Sometimes I can't even add macro. Clicking on text box do nothing.

**Comment by MightyKnight** [comment]
Easy to reproduce. Apparently it has also been reported already: #2191
