### ISSUE TITLE
Building with Baritone

### ISSUE THREAD

**Issue by Trigger098** [ImpactDevelopment/ImpactIssues#2334]
**Describe the bug**
Unable to build with baritone

**To Reproduce**
1. Open Impact
2. type ".b build [name of schematic file]
3. press enter
4. Baritone does not build start building and replies with: "An unhanded exception occurred. The error is in your game's log

**Expected behavior**
Baritone will not build

**Screenshots**
If I try to take a screen shot my game crashes

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
https://github.com/cabaletta/baritone
