### ISSUE TITLE
elyra+ broken

### ISSUE THREAD

**Issue by NickelWW** [ImpactDevelopment/ImpactIssues#2337]
**Describe the bug**
the elyta+ "flight" mode does not work. it bugs out and Is basically useless

**To Reproduce**
turn on elytra+
set it to "flight"
try to use elytra

**Expected behavior**
it should boost your flying. (pretty sure)

- Impact Version: nightly for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Elyra+, various rendering mods (esp, Fullbright etc)
- Operating System: Windows 10 64Bit

**Comment by MightyKnight** [comment]
Would you care to explain what exactly you mean by "**it bugs out**".
Does #1696 describe the problem you're having?

**Comment by NickelWW** [comment]
I'm using "flight" mode (control way too obvious) 
#1696 ... kind of? it's more like, if you try to take off, you just snap to elytra form (you know, lying down) and back to normal standing (basically instantly, so it looks very flicky), and you gain some height. but you cant actually initiate flight.

**Comment by MightyKnight** [comment]
Thanks, that's actually what #1696 is. Just not explained in detail.
Please add further information there.
