### ISSUE TITLE
Minecraft Crash with Impact 1.12.2 and Labymod 3

### ISSUE THREAD

**Issue by duuqz** [ImpactDevelopment/ImpactIssues#2339]
I tryed to start Impact 1.12.2 with Labymod 3 with Forge because i would like to play with both. But every time i Start Forge with Labymod and Impact but it Crashed every second...

here is the Crash Report i hope it can be fixed <3
https://hastebin.com/exebujuteg

**Comment by dominikaaaa** [comment]
try uninstalling labymod

**Comment by duuqz** [comment]
i´ve already tryed it but it didnt work :/

**Comment by dominikaaaa** [comment]
then send the log of the crash without laby mod

**Comment by dominikaaaa** [comment]
then send the log of the crash without laby mod

**Comment by duuqz** [comment]
I can start it without Labymod it only Crash with Labymod

**Comment by dominikaaaa** [comment]
then don't use labymod

**Comment by duuqz** [comment]
but it would be nice if i can used it with labymod because it have some nice Features for better ingame feeling.

**Comment by dominikaaaa** [comment]
then report the bug to laby mod
