### ISSUE TITLE
Game launcher crashing 

### ISSUE THREAD

**Issue by Koklete** [ImpactDevelopment/ImpactIssues#2343]
**Describe the bug**

**To Reproduce**
1. Go to 'mc launcher'
2. Click on 'play'

**Expected behavior**
Game launches.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 for 1.14.4
- Using Optifine? no
- Using LiteLoader? No 
- Enabled mods: 
- Operating System: Linux Ubuntu 20.04 LTS 64 bit

</details>

**Additional context**
If you want a error log plz tell me how to get one bc im dumb

Game crashes when impact client is launched
I previusly had the old mc launcher and it worked there but today i updated to the new launcher and now impact dosent work ):

**Comment by Koklete** [comment]
btw the problem would most likely go away if i could get the old mc launcher but idk how to get it

**Comment by Sarptra** [comment]
**Screenshots**
If applicable, add screenshots to help explain your problem.
https://gyazo.com/f9c94de7a20eeadcb83019d47ba21724
**Game output**
17 k fatal error I cant uplod here
**Crash report**
17 k fatal error
**Additional Client Info**

    Impact Version: 4.8 for 1.13.3
    Using Optifine? no
    Using LiteLoader? No
    Enabled mods: no
    Operating System: Windows 10 64 bit

**Comment by Koklete** [comment]
When i launch mc tho i open that window but dosent show any logs

**Comment by Koklete** [comment]
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> https://gyazo.com/f9c94de7a20eeadcb83019d47ba21724
> **Game output**
> 17 k fatal error I cant uplod here
> **Crash report**
> 17 k fatal error
> **Additional Client Info**
> 
> ```
> Impact Version: 4.8 for 1.13.2
> Using Optifine? no
> Using LiteLoader? No
> Enabled mods: no
> Operating System: Windows 10 64 bit
> ```

What is this?

**Comment by ScanmanTM** [comment]
Make sure you're running java version 8.
Google how to get the log, no log no help.

**Comment by Koklete** [comment]
Do i strictly need java 8 or does java 11 work too?

**Comment by ScanmanTM** [comment]
Nah i thought I would joke about java 8, lollollollol LOOL
Yes you strictly need to run java 8

**Comment by Koklete** [comment]
oh k il try

**Comment by dominikaaaa** [comment]
reopen this if the issue persists
