### ISSUE TITLE
crash when I oppen a box on the mod minecolonies

### ISSUE THREAD

**Issue by hugo4567** [ImpactDevelopment/ImpactIssues#2344]
-- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 5/25/20 2:02 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1465)

-- Screen render details --
Details:
	Screen name: com.minecolonies.blockout.Screen
	Mouse location: Scaled: (240, 134). Absolute: (960, 540)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1465)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['fanhugoboss74'/8134, l='MpServer', x=803.57, y=71.00, z=-3686.22]]
	Chunk stats: MultiplayerChunkCache: 1681, 1681
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (765,71,-3611), Chunk: (at 13,4,5 in 47,-226; contains blocks 752,0,-3616 to 767,255,-3601), Region: (1,-8; contains chunks 32,-256 to 63,-225, blocks 512,0,-4096 to 1023,255,-3585)
	Level time: 10530551 game time, 11858321 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityBat['Chauve-souris'/14093, l='MpServer', x=723.46, y=16.10, z=-3699.77], EntityBat['Chauve-souris'/14094, l='MpServer', x=819.46, y=34.10, z=-3696.25], EntityBat['Chauve-souris'/14100, l='MpServer', x=757.25, y=63.01, z=-3641.54], EntityBat['Chauve-souris'/14104, l='MpServer', x=812.75, y=12.10, z=-3646.75], EntityBat['Chauve-souris'/14111, l='MpServer', x=754.68, y=49.32, z=-3638.11], EntityBat['Chauve-souris'/14113, l='MpServer', x=755.56, y=52.20, z=-3620.24], EntityBat['Chauve-souris'/14117, l='MpServer', x=766.91, y=20.19, z=-3753.49], EntityBat['Chauve-souris'/14118, l='MpServer', x=746.76, y=17.44, z=-3746.70], EntityBat['Chauve-souris'/14139, l='MpServer', x=808.45, y=10.56, z=-3657.41], EntityBat['Chauve-souris'/14140, l='MpServer', x=808.54, y=20.05, z=-3639.25], EntitySquid['Poulpe'/14150, l='MpServer', x=742.64, y=58.63, z=-3735.79], EntitySquid['Poulpe'/14151, l='MpServer', x=747.35, y=58.58, z=-3747.35], EntitySquid['Poulpe'/14169, l='MpServer', x=750.32, y=58.44, z=-3740.95], EntitySquid['Poulpe'/14170, l='MpServer', x=757.60, y=55.00, z=-3735.40], EntitySquid['Poulpe'/14171, l='MpServer', x=751.31, y=58.25, z=-3738.49], EntitySquid['Poulpe'/14172, l='MpServer', x=752.15, y=58.12, z=-3739.04], EntityBat['Chauve-souris'/14200, l='MpServer', x=765.75, y=61.09, z=-3649.25], EntityBat['Chauve-souris'/14201, l='MpServer', x=764.50, y=61.47, z=-3650.65], EntityBat['Chauve-souris'/14202, l='MpServer', x=762.48, y=61.83, z=-3654.40], EntityBat['Chauve-souris'/14203, l='MpServer', x=765.04, y=62.06, z=-3648.62], EntityTier1Rocket['Fusée Niveau 1'/8083, l='MpServer', x=817.50, y=71.40, z=-3588.50], EntityCitizen['Xavier Y. Bartelot'/12204, l='MpServer', x=808.83, y=71.00, z=-3675.13], EntityCitizen['Mélanie V. Gill'/12385, l='MpServer', x=797.68, y=71.00, z=-3663.87], EntityCitizen['Stephen H. Argentein'/12715, l='MpServer', x=816.39, y=71.00, z=-3653.86], EntityCitizen['Mélanie Z. Gerville'/12886, l='MpServer', x=814.13, y=71.00, z=-3650.72], EntitySquid['Poulpe'/14024, l='MpServer', x=842.06, y=60.37, z=-3656.68], EntitySquid['Poulpe'/14025, l='MpServer', x=847.58, y=60.00, z=-3654.35], EntitySquid['Poulpe'/14026, l='MpServer', x=843.83, y=62.60, z=-3661.46], EntitySquid['Poulpe'/14027, l='MpServer', x=835.40, y=62.00, z=-3669.60], GCEntityClientPlayerMP['fanhugoboss74'/8134, l='MpServer', x=803.57, y=71.00, z=-3686.22], EntityBat['Chauve-souris'/14062, l='MpServer', x=723.25, y=43.08, z=-3673.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6088982520 bytes (5806 MB) / 11811160064 bytes (11264 MB) up to 11811160064 bytes (11264 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx11G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                 | Source                                             | Signature                                |
	|:------ |:------------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                 | 9.42                    | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                 | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                         | minecraft.jar                                      | None                                     |
	| LCHIJA | securitycraft       | v1.8.18.2               | [1.12.2]+SecurityCraft+v1.8.18.2.jar               | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.244               | GalacticraftCore-1.12.2-4.0.2.244.jar              | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.244               | Galacticraft-Planets-1.12.2-4.0.2.244.jar          | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.12                  | AsmodeusCore-1.12.2-0.0.12.jar                     | None                                     |
	| LCHIJA | miscrails           | 1.0.0                   | Better-Railroads-1.0.0.jar                         | None                                     |
	| LCHIJA | blocklings          | 1.0                     | Blocklings+6.0.1_b+-+1.12.2.jar                    | None                                     |
	| LCHIJA | car                 | 1.2.12                  | car-1.12.2-1.2.12.jar                              | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358               | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.0                   | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore            | 4.6.6                   | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld           | 1.4.0                   | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | ptrmodellib         | 1.0.4                   | PTRLib-1.0.4.jar                                   | None                                     |
	| LCHIJA | props               | 2.6.3                   | Decocraft-2.6.3_1.12.2.jar                         | None                                     |
	| LCHIJA | doggytalents        | 1.15.1.4                | DoggyTalents-1.12.2-1.15.1.4-universal.jar         | None                                     |
	| LCHIJA | forgelin            | 1.8.4                   | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHIJA | cfm                 | 6.3.0                   | furniture-6.3.0-1.12.2.jar                         | None                                     |
	| LCHIJA | galaxyspace         | 2.0.11                  | GalaxySpace-1.12.2-2.0.11.jar                      | None                                     |
	| LCHIJA | icbmclassic         | 1.12.2-3.3.0.63         | ICBM-classic-1.12.2-3.3.0b63.jar                   | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | jei                 | 4.15.0.293              | jei_1.12.2-4.15.0.293.jar                          | None                                     |
	| LCHIJA | moarboats           | 4.1.2.1                 | moarboats-1.12.2-4.1.2.1.jar                       | None                                     |
	| LCHIJA | moreplanets         | 2.0.22                  | More-Planets-1.12.2-2.0.22-GC238.jar               | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCHIJA | neat                | 1.4-17                  | Neat+1.4-17.jar                                    | None                                     |
	| LCHIJA | ngtlib              | 2.4.15                  | NGTLib2.4.15-32_forge-1.12.2-14.23.2.2611.jar      | None                                     |
	| LCHIJA | reborncore          | 3.16.4.478              | RebornCore-1.12.2-3.16.4.478-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | thermalfoundation   | 2.6.7                   | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | thermalexpansion    | 5.5.7                   | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCHIJA | redstonearsenal     | 2.6.6                   | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar       | None                                     |
	| LCHIJA | rtm                 | 2.4.17                  | RTM2.4.17-36_forge-1.12.2-14.23.2.2611.jar         | None                                     |
	| LCHIJA | thermaldynamics     | 2.5.6                   | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LCHIJA | simplyjetpacks      | 2.2.14.67               | SimplyJetpacks2-1.12.2-2.2.14.67.jar               | None                                     |
	| LCHIJA | stevescarts         | 2.4.32.137              | StevesCarts-1.12.2-2.4.32.137.jar                  | None                                     |
	| LCHIJA | storagedrawers      | 1.12.2-5.4.1            | StorageDrawers-1.12.2-5.4.1.jar                    | None                                     |
	| LCHIJA | tombstone           | 3.7.4                   | tombstone-3.7.4-1.12.2.jar                         | None                                     |
	| LCHIJA | xlfoodmod           | 1.12.2-1.9.2            | XL-Food-Mod-1.12.2-1.9.2.jar                       | None                                     |
	| LCHIJA | structurize         | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
	| LCHIJA | minecolonies        | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1660/PCIe/SSE2'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.4.478
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.22 Extreme.zip
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by ScanmanTM** [comment]
Impact forge is very incompatible therefore no support will be provided due to many variables that can cause a crash.
