### ISSUE TITLE
Launcher refusing to start game (impact 5/21)

### ISSUE THREAD

**Issue by Fokz210** [ImpactDevelopment/ImpactIssues#2347]
**Describe the bug**
Minecraft launcher refused me to start the game 

**To Reproduce**
1. Select impact version
2. Click play
3. See error 

**Expected behavior**
Start the game or just crash

**Screenshots**
![image](https://user-images.githubusercontent.com/15275406/83329279-39173000-a291-11ea-8f16-8b5a86495474.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
No output
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
No crash report
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly-20200521 for mc 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 64bit

</details>

**Additional context**
Game just not even starting, using oficial minecraft launcher with licensed account

**Comment by ScanmanTM** [comment]
Have you tried updating to a new versions such as 0527?
_Any higher will crash_

**Comment by Fokz210** [comment]
Thanks, version 0527 works correctly, seems like it was bug of 0521
