### ISSUE TITLE
Wooden Fences & End Rods Not Combatible With Baritone?

### ISSUE THREAD

**Issue by Nhollas** [ImpactDevelopment/ImpactIssues#2348]
**Describe the bug**
I'm using https://cubical.xyz/ to create my schematics. To put it simply, it appears that baritone is unable to place wooden fences or end rods.

**To Reproduce**
1. Go to https://easyupload.io/a877g9 to download the schematic.
2. Try using it in game, with my tests it only places the cobble walls and says it's completed the build not including the fences / end rods.
3. Not sure if other blocks are not working or if there's a fix to this already?

**Expected behavior**
That baritone should be able to place all the nessarsay blocks.
**Screenshots**
Attached Image of what the schematic is. https://easyupload.io/b9v5zy
In game display of what is happening. https://easyupload.io/het00x

- Impact Version:  Impact Nightly-20200527 for 1.15.2
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  No additional mods than what's required.
- Operating System:  Win 10 64bit

</details>

**Additional context**
N/A

**Comment by ScanmanTM** [comment]
Baritone issues go onto the baritone repo.
https://github.com/cabaletta/baritone/issues
