### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Sicktek** [ImpactDevelopment/ImpactIssues#2349]
release 1.15.2-Impact_nightly-20200529

20:31:34.637
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.15.2/1.15.2.jar
20:31:34.657
Have local file C:\Users\Riseo\AppData\Roaming\.minecraft\versions\1.15.2\1.15.2.jar but don't know what size or hash it should be. Have to assume it's good.

**Comment by dominikaaaa** [comment]
Your ISP is blocking aws or it's rate limited. Try again later

**Comment by Sicktek** [comment]
What is an ISP ?

**Comment by dominikaaaa** [comment]
internet service provider
