### ISSUE TITLE
Baritone feature to allow baritone to find nearest chest with space available and place certain item ID # into it and return to whatever it was doing before.

### ISSUE THREAD

**Issue by ICantThink** [ImpactDevelopment/ImpactIssues#2350]
**Is your feature request related to a problem? Please describe.**
This would help me be able to mine things so much longer, at absolute minimum it would allow people to farm an extra 7 hours if they only sleep 7 hours a day and spend the rest of the day manually placing what they farm into a chest. For most people it would probably add an additional 16+ hours to farm. 

**Describe the solution you'd like**
I Mine lots of diamonds in this flat simple area and have to manually come back every time their inventory is full and place it into a chest. It would help significantly if they could just on their own detect when inventory is full and look for the closest chest, register if there is space in the chest and then place a specific item ID # which in this case it would be diamonds so 56, into the chest, and if that chest is full it finds the next closest chest. 
This could be used for so much more though, like people who want to farm literally anything this could save so much time and help significantly.

**Describe alternatives you've considered**
There aren't any clear alternatives.
**Additional context**
I would be willing to pay if this could be done any quicker or at all. This would help SO MUCH.

**Comment by dominikaaaa** [comment]
duplicate
