### ISSUE TITLE
1.12?Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Cocoispro** [ImpactDevelopment/ImpactIssues#2353]
**Is your feature request related to a problem? Please describe.**
Yes the problem is that it is not updated.

**Describe the solution you'd like**
I would like for there to be an updated version for impact on 1.12
**Describe alternatives you've considered**
idk

**Additional context**
I don't have any programming experience at all or any idea how difficult it is but I would think that making an updated version of impact for 1.12 would not be very hard because its in the same update as 1.12.2 but its 2 small updates behind.

**Comment by LeafHacker** [comment]
Supporting 1.12.0 would mean maintaining a separate branch of the codebase for very little benefit. We already have four branches of Impact being actively maintained & developed, we don't want to increase this for no reason. There's very few scenarios when a 1.12 client is desired over a 1.12.2 one.

**Comment by dominikaaaa** [comment]
I can't think of a single valid use case except a server owner being too lazy to update.
