### ISSUE TITLE
i pay $5 and no 1.15.2

### ISSUE THREAD

**Issue by MinoaBaccus** [ImpactDevelopment/ImpactIssues#2356]
I paid $1 dono then I realized I have to pay $5 for 1.15.2 so I pay an extra $4 can I pls have 1.15.2 or a refund my PayPal is proof https://i.imgur.com/al5ulyn.png and more proof https://i.imgur.com/AlpgK8f.png pls refund or give the $5 dono I want auto mine and other ):

**Comment by LeafHacker** [comment]
Please contact us on Discord for support. This is an issue tracker for tracking bugs and feature ideas for the Impact client.

The donation form only issues an Impact Account registration token if the donation amount for that specific donation is $5 or more. While we appreciate any donation, our automated system doesn't currently supported issuing rewards for cumulative amounts
