### ISSUE TITLE
impact commands do not work

### ISSUE THREAD

**Issue by AnUbiSaF** [ImpactDevelopment/ImpactIssues#2360]
![image](https://user-images.githubusercontent.com/66388991/83687308-436c5d80-a5f4-11ea-8fd4-f04531e74fa0.png)
- Impact Version: "4.8.3 for 1.12.2"
- Using Optifine?  No
- Using LiteLoader? No 
- Enabled mods: 
![image](https://user-images.githubusercontent.com/66388991/83687581-a100aa00-a5f4-11ea-933d-6e5e296517cf.png)
- Operating System: 
Windows 10 64bit
**Additional context**
Impact commands do not work, for example .b, .prefix, .help

**Comment by dominikaaaa** [comment]
mfw
