### ISSUE TITLE
Realms Authentication IG

### ISSUE THREAD

**Issue by Wickerr** [ImpactDevelopment/ImpactIssues#2361]
**Describe the bug**
So I am using the alt manager and trying to get my alt on my realm. The Impact version is Nightly-20200521, What happens is that when clicking on realms "Please try restarting Minecraft" shows up,

**To Reproduce**
1. Start Impact with Nightly-20200521
2. Click on Impact, alt, login
3. Head towards the main menu, click on realms
4. "Please try restarting Minecraft

- Impact Version:  no
- Using LiteLoader?  no 
- Enabled mods:  Anti hunger 
levitation control, elytra+, liquid interact auto weapon, bow aimbot, item saver, auto tool, auto eat, boatfly, hitbox
- Operating System:  windows 10 64bit

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
#2325
