### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by 3535772662** [ImpactDevelopment/ImpactIssues#2364]
![commands](https://user-images.githubusercontent.com/52690204/83943401-5b2f2600-a82e-11ea-8a28-166191fffbae.png)
I don't know how to trigger this problem. Is this a bug or something

**Comment by ScanmanTM** [comment]
### **Please add a brief but descriptive title.**
I don't see this being related to impact.

**Comment by dominikaaaa** [comment]
did someone already make a skid of kami blue v1.1.4 lol
