### ISSUE TITLE
More options for AutoBuild

### ISSUE THREAD

**Issue by lSherozl** [ImpactDevelopment/ImpactIssues#2366]
This client is good, but if you are using it on vanilla you can not use other mods at the same time like worldedit, now I don't know if this is possible or not, but add on to a client more options like Auto building a wall to what height you want, floor, filling in an area, copy, paste, undo and if possible even the schematic option for copying and pasting your worlds into another world. Either these new build options be added to the client itself or have a different program that works at the same time as the client be made for download would be cool.

**Comment by dominikaaaa** [comment]
.b help build
.b help click
.b help sel
