### ISSUE TITLE
Mob Spawn ESP to locate the spawn of mobs with the area being unlit

### ISSUE THREAD

**Issue by alexionn1** [ImpactDevelopment/ImpactIssues#2370]
can something be added to the menu? it would be nice For "Mob Spawn Esp" so you can see where they can spawn if its unlit it would be good for people who just play solo mc and not multiplayer like myself. Thank you

**Comment by dominikaaaa** [comment]
duplicate

**Comment by MightyKnight** [comment]
Of #1597

**Comment by alexionn1** [comment]
Sorry i didn't know this was a Duplicate my apologies and sorry for the last one i made too as that was a Duplicate my apologies again 👍

**Comment by AlexanderRitter02** [comment]
@alexionn1 No problem and no need to apologize, people create duplicates all the time.
We understand it's sometimes hard to find if the issue already exists, just make sure to _always search_ before creating an issue.

**Comment by MightyKnight** [comment]
@alexionn1 No problem, there is no need to apologize. people create duplicates all the time.
Just make sure to _always search_ if it already exists before creating a new issue.

**Comment by alexionn1** [comment]
Will do thank you @MightyKnight  This can be closed now if thats a possibility <3
