### ISSUE TITLE
Merge Anti-Blind and Anti-Overlay

### ISSUE THREAD

**Issue by Hexiro** [ImpactDevelopment/ImpactIssues#2373]
**Is your feature request related to a problem? Please describe.**
It's not a problem I just think under anti-overlay there are things like pumpkins, fire, etc so it would only make sense to just add nausea and blindness to that instead of making it the separate hack anti-blind

**Describe the solution you'd like**
Just Merge anti-blind and anti-overlay

**Comment by MightyKnight** [comment]
Would be good, because there are way too many modules already cluttering the ClickGUI.

On the contrary, Anti Overlay has way too many options too, so might make sense to keep them apart.

**Comment by Hexiro** [comment]
i agree with you but i stil think it would make more sense to just merge them. but that's just my take
