### ISSUE TITLE
Added Reach

### ISSUE THREAD

**Issue by lSherozl** [ImpactDevelopment/ImpactIssues#2374]
So I have switched over from Wurst, and one of the things that I have found missing is an increased reach option...the normal I think you can reach blocks is around 4, but like being able to break, and place blocks further than that is possible. It also helps with combat, as you can hit a player further from where they can reach you. Basically an increased range option for interacting with blocks and for combat. 

From my knowledge this is what different clients have been able to achieve, I believe the last 2 are outdated at 1.12.2 only so I think the max possible would be 6, but I could be wrong.  
Survival: 4
Creative: 5
Wurst Client: 6
Wolfram Client: 6
Aristois Client: 6
Omikron Client : 100
Jigsaw Client: 500

**Comment by MightyKnight** [comment]
Your issue is a **duplicate**, because it is already suggested in #211.
_Please search before creating a new issue._

You can vote vor add more information there.
