### ISSUE TITLE
Mob Spawn ESP

### ISSUE THREAD

**Issue by Eggresive** [ImpactDevelopment/ImpactIssues#2375]
**Is your feature request related to a problem? Please describe.**
I always switch to the wurst client when placing torches around my base, because it has an overlay that shows you where the light levels are low enough for monsters to spawn.

**Describe the solution you'd like**
I would like a similar overlay, with it showing where light levels are low enough for monster spawns, and where light levels will be low enough for monster spawning come nighttime.

**Describe alternatives you've considered**

**Additional context**

**Comment by lSherozl** [comment]
I would remove this if I were you, its a duplicate, I already suggested that and it got removed, the issues already been mentioned in the past, and your post will get removed

**Comment by MightyKnight** [comment]
As @lSherozl pointed out, this suggestion is already reported in #1597 and thus your issue is considered a **duplicate**.
You can vote vor add more information there.
