### ISSUE TITLE
Frame drops and game freezes

### ISSUE THREAD

**Issue by Lovendal** [ImpactDevelopment/ImpactIssues#2378]
**Describe the bug**
I get frame drops and my game freezes on impact 4.9 after some time

**To Reproduce**
1. Launch impact 4.9 on 1.15
2. Join a server
3. I get around 12 fps and my game freezes

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9 for 1.15
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Misc mods, jesus, riding, step, velocity, auto eat, no fall, auto tool, render mods, 
- Operating System: windows 10 64 bit

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
Can't reproduce with such little information about what you have enabled.
Most FPS drops caused by render mods, disable them.
