### ISSUE TITLE
1.12.2 nightly is not working

### ISSUE THREAD

**Issue by Jdog7217** [ImpactDevelopment/ImpactIssues#2379]
it alway crashes when i open 1.12.2 nighty
(https://github.com/ImpactDevelopment/ImpactIssues/files/4745953/crash-2020-06-08_08.37.39-client.txt)

**Comment by ScanmanTM** [comment]
Are you even a donator?

**Comment by dominikaaaa** [comment]
Use your donator account, or stop using cracked impact.
