### ISSUE TITLE
Disabling Movement Lock?

### ISSUE THREAD

**Issue by iTechyn** [ImpactDevelopment/ImpactIssues#2380]
Is there a way to disable the feature where holding option on Mac or alt on Windows will invert the mouse up and down and will lock the movement direction? this is highly frustrating as I have my sprint key bound to this as on Mac holding control (the default sprint) will change left click to right click, which I don't need to explain why that's annoying.

Is this a feature I can disable? If not, I would really like if there was a feature to disable or rebind this feature.

Forgot to mention: using Impact 4.9.1 with Optifine Preview 23 for 1.15.2

**Comment by dominikaaaa** [comment]
.perspective toggle

**Comment by dominikaaaa** [comment]
should probably be added to the wiki imo

**Comment by LeafHacker** [comment]
Should probably be a module

**Comment by dominikaaaa** [comment]
Ah.

**Comment by dominikaaaa** [comment]
I just grabbed the command from a duplicate issue

**Comment by LeafHacker** [comment]
Yeah perspective is its own thing and has its own toggle command because we haven't implemented a way for modules to have a "hold key to enable" meme rather than/in addition to the current "press key to toggle" meme.

**Comment by dominikaaaa** [comment]
just ask sakuya to write your bind system :p
