### ISSUE TITLE
Impact crashes when I try to launch it.

### ISSUE THREAD

**Issue by something12356** [ImpactDevelopment/ImpactIssues#2383]
When I attempt to launch minecraft with impact, it crashes

**To Reproduce**
1. Install minecraft on Ubuntu 18.04
2. Launch minecraft

**Expected behavior**
Minecraft launches
 

```No crash report appeared.```

 

- Impact Version: 4.9.1 for 1.15.2, 4.6-4.9 for 1.14 and 1.13 (tried all of them, none of them worked.)
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Nothing
- Operating System: Ubuntu 18.04

**Comment by dominikaaaa** [comment]
use oracle jdk
