### ISSUE TITLE
change gui color

### ISSUE THREAD

**Issue by eliasfakhiri** [ImpactDevelopment/ImpactIssues#2409]
hot

**Comment by MightyKnight** [comment]
@eliasfakhiri You literally created [25 useless issues](https://github.com/ImpactDevelopment/ImpactIssues/issues?q=is%3Aissue+author%3Aeliasfakhiri+is%3Aclosed) in one hour and **closed** all of them. I don't know why did that, but it **is** spam.

Listen, **this is warning**:
1. _Search_ if someone else already suggested it before creating a new issue
2. Follow the [_issue template_](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md&title=Please+add+a+brief+but+descriptive+title) and describe your suggestion in **detail**! (not like here just saying `"hot"`)
3. _Don't close_ your own issues without a reason

If you fail to understand this, you will eventually get banned. Thank you.
