### ISSUE TITLE
Add an option to Killaura to target dead entites

### ISSUE THREAD

**Issue by DasAlteUpdate** [ImpactDevelopment/ImpactIssues#2411]
**Is your feature request related to a problem? Please describe.**

Some servers use AntiDamageIndicators to protect people from seeing how many HP they have. But some of them set the HP value to 0 or -1 or something like that. That causes Impact to completly ignore them in Killaura or Hunt.

**Describe the solution you'd like**

I would like to have an option in Killaura and Hunt and every other module that ignores players with 0 or less HP, that allows you to attack them.

**Describe alternatives you've considered**

Another solution would be to attack by default even if someone has 0 HP or less.

Here is an example how a plugin could disable Killaura (the issue is not only in Impact) https://youtu.be/gsQH09tRmSc

**Comment by ScanmanTM** [comment]
Duplicate, open again and you'll get banned.

**Comment by dominikaaaa** [comment]
bruh why the hell do kids copy and paste their closed issue into a new one

**Comment by DasAlteUpdate** [comment]
bruh why the hell do kids make an closed source client but with a issue repo on github but ignore issues that are older than a year.

**Comment by zPeanut** [comment]
@DasAlteUpdate there are currently 708 open issues / suggestions on this github, its currently literally not possible to cover every single one of them in throughout detail.

thanks for understanding!

**Comment by dominikaaaa** [comment]
Imagine complaining that a free client with millions of downloads hasn't fixed some obscure issue that's specific to very few servers
