### ISSUE TITLE
Wireframe bug the wireframe doesn't work on 1.15.2

### ISSUE THREAD

**Issue by jonfinnelizaga** [ImpactDevelopment/ImpactIssues#2422]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by MightyKnight** [comment]
Duplicate of #2034.
Please search next time before reporting a bug.
