### ISSUE TITLE
How does the nofall bucket work i don't know how to use it?

### ISSUE THREAD

**Issue by jonfinnelizaga** [ImpactDevelopment/ImpactIssues#2430]
**Is your question request related to a problem? Please describe.**

**Describe what you are trying to achieve**

**Additional context**
Add any other context or screenshots about your question here.

**Comment by ScanmanTM** [comment]
It is broken.

**Comment by dominikaaaa** [comment]
@jonfinnelizaga please stop creating empty issues. you have to fill out the template.
