### ISSUE TITLE
What does franky do?

### ISSUE THREAD

**Issue by jonfinnelizaga** [ImpactDevelopment/ImpactIssues#2435]
**Is your question request related to a problem? Please describe.**

**Describe what you are trying to achieve**

**Additional context**
Add any other context or screenshots about your question here.

**Comment by dominikaaaa** [comment]
Please stop creating useless issues without the template filled out, as it's considered spam. 

Franky does whatever you think it does.

**Comment by MightyKnight** [comment]
Also, questions generally should be asked on the [Impact Discord](https://impactclient.net/discord).
