### ISSUE TITLE
Add Anti-Knockback too the client

### ISSUE THREAD

**Issue by RockHarder** [ImpactDevelopment/ImpactIssues#2439]
**Describe the solution you'd like**
Add A Feature that allows you to take a hit with out having any momentum other than the direction you are moving
**Describe alternatives you've considered**
or maybe even better, add a feature that allows you to take that knockback from a hit and redirect it in the direction you are facing.

**Comment by something12356** [comment]
Velocity does just this, it's just under a different name.
