### ISSUE TITLE
Adding an .reload command

### ISSUE THREAD

**Issue by InimicalPart** [ImpactDevelopment/ImpactIssues#2443]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes when I use Impact the client like glitches once today my world wouldn’t render and nothing would work then second time today when the ClickGUI wouldn’t show up, the .t command just said “[Impact] [module] ON” ([module] is the module name) repeatedly even tho I ran the same command 2+ times.

**Describe the solution you'd like**
I would want like to have a “.reload” command which reloads everything in Impact.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
None

**Comment by dominikaaaa** [comment]
I feel like making a proper bug report to fix bugs is better then a catch-all command that few people would know about

**Comment by En3rgyBoy** [comment]
Well yes, but the thing is that I don’t know how to reproduce the steps so it will be much harder to know what the bug is
