### ISSUE TITLE
Enchantment color doesn’t work on impact 4.8.9 for 1.15.2

### ISSUE THREAD

**Issue by eeeertgr** [ImpactDevelopment/ImpactIssues#2444]
![5F038C07-B3BD-402F-AA0F-E2ED4807297F](https://user-images.githubusercontent.com/66971155/84697572-62d08800-af1c-11ea-8113-49b0b55d02eb.jpeg)

**Comment by ScanmanTM** [comment]
Dupe, check issues before making one.
