### ISSUE TITLE
Suggestion List:

### ISSUE THREAD

**Issue by BasicallyLK** [ImpactDevelopment/ImpactIssues#2446]
Long List Inbound!

AutoEZ

Sends a message in chat after killing someone

AutoLog

Automatically log when in danger or on low health

BreakingWarning

Notifies you when someone is breaking a block near you.

AutoReply

Automatically reply to direct messages

AntiBookKick

Prevents being kicked by clicking on books

AutoNametag

Automatically nametags entities

BlockData

Right click blocks to display their data

Advanced Elytra Options:
Elytra Flight

Modifies elytras to fly at custom velocities and fall speeds

Elytra Replace

Automatically swap and replace your chestplate and elytra.

Others:

PortalGodMode

Don't take damage in portals

HoleESP

Show safe holes for crystal pvp

Quite a long list but these are things that would improve my experience with your client / Utility tool.

**Comment by ScanmanTM** [comment]
One suggestion per issue, make sure to check for dupes.
