### ISSUE TITLE
antixray add

### ISSUE THREAD

**Issue by Tehlikeli107** [ImpactDevelopment/ImpactIssues#2448]
** Is your feature request related to a problem? Please describe. **
The problem is that some servers have anti xray, or orebfuscator.

** Describe the solution you want **
You can orebfuscator bypass and add a feature like anti xray

** Describe the alternatives you think **

** Additional context **

**Comment by dominikaaaa** [comment]
I'm closing this as won't fix, because this is pretty much impossible to do and I haven't seen a single implementation of this that actually works on modern servers (example: Future client's one gets you instantly banned)

**Comment by MightyKnight** [comment]
How would that actually work @dominikaaaa?
Seems *entirely* impossible to me, but you say future had something related?

**Comment by dominikaaaa** [comment]
Futures seemed to work by hitting all the blocks in a radius around you to "reveal" the real ores, but that hasn't worked in a while. 

A few years ago, clients just reverse engineered the anti x-ray plugin math but these days they use randomly generated seeds.
