### ISSUE TITLE
A in-fire timer like potion effect

### ISSUE THREAD

**Issue by Dryhb** [ImpactDevelopment/ImpactIssues#2452]
**Is your feature request related to a problem? Please describe.**

When you are on fire (swim of fall in lava) you never when you'll stop burning, If you have time to go to the ow for some water or drink a fire resistance potion or a gapple. Having this timer would be great help.

**Describe the solution you'd like**

If it would be possible to have a display on the screen to see the time in fire left, it would be really helpful. I can see it fits well in the potion GUI like an effect like "in-fire - (1:30)". The time in fire can be very long so probably sometimes in minutes or even hours. 400tick when you touch lava and 20 more ticks every tick past in lava. This is it's dependent so maybe add the countdown in ticks and make a "translation" in mins at 20 it's and an estimation with the current tps.

**Describe alternatives you've considered**

Also, a setting to remove/lower the fire animation because it's really large on the screen

**Additional context**
Realy nice client tho :)

**Comment by dominikaaaa** [comment]
AntiOverlay / NoRender removes the effect already

**Comment by Dryhb** [comment]
Ho ok

**Comment by Fakeaccount12312** [comment]
> 
> 
> AntiOverlay / NoRender removes the effect already

It does not remove the effect, it just does not render it. It would indeed be nice to see if and how long you are burning especially with this module turned on.

**Comment by l1ving** [comment]
I just realized this module isn't really feasible anyways, due to server differences such as lag and the type of server and optimizations it has.
