### ISSUE TITLE
Can't see the hacks that are active

### ISSUE THREAD

**Issue by Minecraftingil** [ImpactDevelopment/ImpactIssues#2454]
I can't see which hacks are on and the details of them (for example, if you open autocheat, it won't show you which anticheat the server is using. It is really annoying!). this is a big problem, please fix it.

To reproduce, just open impact for 1.15.2, activate some hacks, and see that impact don't show them.

I should have been able to see the hacks that has been activated

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Comment by dominikaaaa** [comment]
I can't reproduce this issue, please provide a video.
