### ISSUE TITLE
Alt account switching results in authentication failure

### ISSUE THREAD

**Issue by Double0Sowell** [ImpactDevelopment/ImpactIssues#2456]
**Describe the bug**
I have two real minecraft accounts.  I have been able to switch between these two accounts at will until today using the Impact "alt" button on splash screen.  When I try to switch logins it gives "authentication Failure" on both of my accounts.  I have tried using Impact vanilla and forge. I have tried using a new installation on a separate computer.  Still have the same problem.  I can login using the account that I used to donate to impact with but I can not switch to my other account

**To Reproduce**
open minecraft launcher
choose impact 1.12.2 nightly 6/17/20
at splash screen choose impact button
choose alt button
select alt account 
press login  
selection returns "authentication failed"
delete account
add account login reenter account details
press login
selection returns "authentication failed"

**Expected behavior**
i expect the alt account to load and allow me to play under that account and then return to this screen and switch back to my other account at will

**Screenshots**

<details> 

 

- Impact Version:  20200617 nightly for 1.12.2
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods:  i have tried with none enabled
- Operating System: win 10 pro 64bit

</details>

**Additional context**
again i can log in with both accounts separately not using impact

**Comment by dominikaaaa** [comment]
Relaunch impact.

**Comment by dominikaaaa** [comment]
It's also possible mojang is rate limiting you, and you need to wait 24 hours

**Comment by Double0Sowell** [comment]
i have waited 24 hours and tried again before i posted the bug. I have relaunched impact several times.

**Comment by dominikaaaa** [comment]
Then the saved password for your alt is wrong.

**Comment by Double0Sowell** [comment]
no i can log in on either account if impact is not running

**Comment by Double0Sowell** [comment]
did you read the bug report

**Comment by dominikaaaa** [comment]
As I said, the only way that that's happening is if the saved password is wrong

**Comment by Double0Sowell** [comment]
well apparently that is not the only way.  I have deleted the login and added back in with the correct password several times. is it possible that impact is not updating the password even though it has been deleted and reset? it is being stored somewhere  can i manually erase it and add it back in?

**Comment by LeafHacker** [comment]
Are you using the username or the email?

**Comment by Double0Sowell** [comment]
I have been using the login name.  That is what was listed when i used it before it stopped working.  I went back in and typed in the email instead and password and now it is working. Thank you 
Sorry I see it changes the email to the login name after is is authenticated.  Now I understand. Sorry to take you time I appreciate you getting back to me.
