### ISSUE TITLE
Music Disk Client-Sided Playing (Or ServerSided)

### ISSUE THREAD

**Issue by ThatCodingGuy8** [ImpactDevelopment/ImpactIssues#2457]
As the name describes. An option that allows you to play music disks anywhere without a jukebox, and options for looping, etc. Client sided would be awesome but it would be more awesome if you could somehow server side it. Essentially, a personal non-existent jukebox.

**Comment by dominikaaaa** [comment]
I meannn this *is* literally 1 line of code but I don't see how it would be very useful or improve impact in any way

**Comment by ThatCodingGuy8** [comment]
Allows you to listen to music disks in-game without a jukebox, allowing you to listen in servers that either disallow them or in early game

**Comment by ThatCodingGuy8** [comment]
Or, if ServerSided, an optimal way to play stal on loop and watch people lose their minds

**Comment by dominikaaaa** [comment]
It's not possible to do that server sided.

**Comment by ThatCodingGuy8** [comment]
Still though, would be a nice addition for client side music. Or maybe just a built in audio player like sigma has.

**Comment by ZeroMemes** [comment]
If you want to listen to the game's music, you can open a Youtube video.

**Comment by dominikaaaa** [comment]
based
