### ISSUE TITLE
Impact 1.15.2 4.9.1 (ımpact version) no optifine crash

### ISSUE THREAD

**Issue by EmirhanGamer71** [ImpactDevelopment/ImpactIssues#2461]
https://paste.ubuntu.com/p/ZwPzWTcZbC/

**Comment by ScanmanTM** [comment]
Set operating system language to English. #2228

**Comment by EmirhanGamer71** [comment]
> Set operating system language to English. #2228

you mean the whole os? to fix the problem orrr to help me

**Comment by ScanmanTM** [comment]
Yes set whole os to English.
