### ISSUE TITLE
1.16 suggestion (Nether)

### ISSUE THREAD

**Issue by Dinandpower** [ImpactDevelopment/ImpactIssues#2462]
Hello i am an impact donator
and i have a suggestion for 1.16 nightly build when it comes out
it should be awesome if u add a feature to kill aura and xray

Killaura: that there is an option nether if u enable it it will target only bad mobs so it doesnt attack zombie pigmens or pigmens

Xray : That u add ancient debris to it and the nether gold It would be nice

Thank u for reviewing, Impact Developers

**Comment by ScanmanTM** [comment]
1. damn i wish the devs add in options such as passive and hostile into kill aura, wouldn't that be a dream come true
2. You think the devs manually add blocks to the xray list??
