### ISSUE TITLE
Rename the Jesus module to something else 

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2463]
Please add an option to rename all the modules because I’m trying to convince my friend to get impact (I already have it and the Premium) but my friend says no because they don’t think some of the names are respectful/appropriate.

I think a good solution would be to add a box next to the visible box in every module with a little pencil that says “Rename”
 
Please make this a feature

**Comment by dominikaaaa** [comment]
I don't see how this would improve Impact? If there's a specific module that's somehow offensive then we'd be happy to fix that, otherwise, giving reasons as to how this would improve impact would be helpful.

**Comment by yodaluca** [comment]
Ok then could you please rename the Jesus module to I don’t know like “Walk on water” please.

**Comment by dominikaaaa** [comment]
Why are you liking your own issues lmao

**Comment by yodaluca** [comment]
Please because I would really like to show my friend it but he won’t get it because he thinks that the Jesus module is offensive please or have a different options for the name please.  🙏

**Comment by MightyKnight** [comment]
If you are already creating such an issue, please **provide an explaination** to why you regard it as offensive.

For my part I don't see what's wrong with it. The name is just a general allusion to the biblical narration of Jesus walking on water.

**Comment by Peremious** [comment]
It isn't that the OP regards it as offensive, and they have stated as such multiple times. Their friend thinks it is. Personally I think that name is an apt description. It gets the job done. The OP is just asking for the ability to rename the hacks on the client in game. It won't hurt anyone and it will get the few people that find things offensive to start playing with Impact. I don't really see the problem.

**Comment by fffelix-jan** [comment]
I'm Christian and I'm OK with it, although I still don't really like the name. I think that a more generic name like "Water Walking", "Walk on Water", etc. would be better and less offensive to many people.

**Comment by ZeroMemes** [comment]
Impact 5 will have support for internationalization, so this will be able to be configured with a custom language file. No changes will be made to 4.* versions for this.

**Comment by dominikaaaa** [comment]
you're putting a lot of faith into user's ability to be able to figure out how to do that

**Comment by ZeroMemes** [comment]
Translations will have to be a community effort so when the time comes plenty of resources will be available.

**Comment by dominikaaaa** [comment]
i meant the actually installing the translation part

you *have* seen the type of issues people open here, right?

![dominikaaaa org-2020-07-08-14-16-29](https://user-images.githubusercontent.com/17222512/87105259-7673c380-c228-11ea-9acc-347018800c18.png)

l o l

**Comment by yodaluca** [comment]
Umm thanks??  So does that mean we will be able to rename them???

**Comment by dominikaaaa** [comment]
Yes, in 5.0

**Comment by yodaluca** [comment]
Any idea when that will be out￼

**Comment by dominikaaaa** [comment]
No.
