### ISSUE TITLE
Please add more Cape designs.

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2465]
I would like to have more cape options like a creeper and an enderman a lot of things like that.

A pig cape and some other ones also if maybe somehow you could make it where we can upload our own or design our own and have some solid color capes too.

Please just completely REVAMP caps thanks. :)

**Comment by ScanmanTM** [comment]
You might aswell just get an optfine cape.

**Comment by dominikaaaa** [comment]
I don't see how this is related to impact at all.
