### ISSUE TITLE
No Fall doesn’t work with AntiHunger

### ISSUE THREAD

**Issue by Kholy6** [ImpactDevelopment/ImpactIssues#2468]
**Describe the bug**

When AntiHunger and NoFall are aktive and you turn off NoFall it’s still on. You first have to disable AntiHunger before NoFall is really turned off

**To Reproduce**
1. Go to ‚return AntiHunger on, turn NoFall on. Turn NoFall off and it will still be on until you disable AntiHunger'

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  I think the latest 1.15.2 Optifine Build
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods: AntiHunger, NoFall
- Operating System:  MacOSX

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
This is completely intentional due to conflicting states between being on the ground and not being on the ground, as AntiHunger and NoFall both affect that. Though, please correct me if I'm wrong @ImpactDevelopment/issue-moderator
