### ISSUE TITLE
Cant Break A Block

### ISSUE THREAD

**Issue by RFGMLinks** [ImpactDevelopment/ImpactIssues#2469]
---
name: Cant Break A Block
about: Please file a separate report for each issue
title:So When i break it replaces so i break it more and it takes 4+ breakes to really break and drop the block and i went onto a difrent client and it works just fine this accures in single player and multiplayer
labels: Bug
assignees: ''

---

**Describe the bug**
So When i break it replaces so i break it more and it takes 4+ breakes to really break and drop the block and i went onto a difrent client and it works just fine this accures in single player and multiplayer

**To Reproduce**

**Expected behavior**
The Block should break the first time

**Screenshots**
Don't have any

- Impact Version: 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Anti Blind, Camera Clip, capes, ClickGui, Crosshair Plus, ESP, HUD, Light, Main Menu, Storage ESP, Trajectory, Anti Haserd, Sprint, Inventory, Anti Bot, Criticals, Anti, Desync, Anti vanish, Anti Cheat, Log Possison, Middle Click Friend, Anti Hunger
- Operating System: Windows 10 64 bit

</details>
So When i break it replaces so i break it more and it takes 4+ breakes to really break and drop the block and i went onto a difrent client and it works just fine this accures in single player and multiplayer

**Additional context**

**Comment by dominikaaaa** [comment]
Disable desync.

**Comment by RFGMLinks** [comment]
It didnt help

**Comment by dominikaaaa** [comment]
Provide a video then

**Comment by MP3Martin** [comment]
Turn off timer
