### ISSUE TITLE
Default Java not comptatible with Impact client

### ISSUE THREAD

**Issue by Sharingisnotillegal** [ImpactDevelopment/ImpactIssues#2473]
Hi, I'm unsure if this should be reported as an issue, as it is not a direct issue with the client.
The issue is that the bundled version that Minecraft/Ubuntu 18.04 gets you when you install the minecraft.deb is not compatible with Impact.
It's kind of to make it 'google-able'.
Workaround below.

Symptoms:
[Java from Default minecraft.deb]
Game start crash,

[Java from APT]
Impact buttons etc has been added to GUI but commands do not do anything ingame, can not open R-Shift menu.

[Java from homepage]
Works.

Suggested fix:
Unsure? Check for compatible Java version or give warning when installing impact, with a link to correct version.

Reproduction steps:
wget https://launcher.mojang.com/download/Minecraft.deb
Install Minecraft.deb

Launch Minecraft Launcher.

Select patch 1.15.2, and launch game.

Game launches. OK.
Close game.

Wget https://impactclient.net/ImpactInstaller.jar
Select [X] Allow executing File as program

Install for Vanilla Minecraft.

Install OK.

Launch game.
Crash.

Install java8 from APT repository
Game launches, Impact button can be seen in menu, ingame .b only sends message, does not interpret command.

Working fix
Wget [Java LINUX64 install link from site, it's bundled to some id cant link.]
sudo -i
[password]
mkdir /usr/java/
tar xvfz jre-8u251-linux-x64.tar.gz

Start Minecraft launcher, go to Installations, press "..." next to Impact 4.9
[More Options]
Java executable
/usr/java/jre1.8.0_251/bin/java
[Save]

Launch game.
Works.

[Information about system]
Ubuntu 18.04 (Bionic)
Gnome 3.28.2
Kernel: 4.15.0-106-generic

Thank you for your time and this lovely client.

**Comment by dominikaaaa** [comment]
This isn't an Impact issue. You need to use JDK 8 with Minecraft period, default Ubuntu Java doesn't work with Minecraft.

**Comment by LeafHacker** [comment]
To not pick slightly, java 1.8 is required for _modded_ Minecraft (anything using Launch Wrapper). Newer java versions may well work with newer Minecraft versions, but not if modded.
