### ISSUE TITLE
Auto Mine For ancient debris when 1.16 is released

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2474]
When Impact Updates to 1.16 can you add an auto mine Bot mode For ancient debris??

**Comment by yodaluca** [comment]
Hello 👋 people have been Renaming and adding/removing labels but no one has responded???

**Comment by dominikaaaa** [comment]
It has literally been 24 hours

**Comment by Daenges** [comment]
It is more a Baritone related question. Go to their github and ask there.

**Comment by yodaluca** [comment]
Ok thanks I did as you can see above. 🙂
