### ISSUE TITLE
Baritone says done after clearing area to place blocks and won’t build 

### ISSUE THREAD

**Issue by Andrew56001** [ImpactDevelopment/ImpactIssues#2475]
**Describe the bug**
A clear and concise description of what the bug is
.b build redeemer.schematic
**To Reproduce**
1. Go to .b (name of schematic.extension) 

**expected**
Baritone to build the downloaded schematic after clearing area.
**Screenshots**
Baritone clears area and says done building no block being placed.

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
that means you don't have the required blocks in your hotbar, or the schematic is empty
