### ISSUE TITLE
Adding Item Frames to Search Module

### ISSUE THREAD

**Issue by WelcomeToHello** [ImpactDevelopment/ImpactIssues#2478]
**Is your feature request related to a problem? Please describe.**
Kind of? Storage ESP has a very short range when it comes to item frames.

**Describe the solution you'd like**
I would like you guys to add "Item Frame" to the Search block list. If you could make two separate ones for one with an item and one without, that'd be great. Although I don't mind them being combined into one.

**Describe alternatives you've considered**
Nothing really. Search is unique and StorageESP really isn't going to tell you over a large distance, but increasing its distance as well as adding item frames to the Search module would be great.

**Additional context**
N/A

**Comment by dominikaaaa** [comment]
#1454
