### ISSUE TITLE
Add a Prone ability (ie. The GoProne mod or similar)

### ISSUE THREAD

**Issue by ToxiCookies** [ImpactDevelopment/ImpactIssues#2479]
The ability to go prone and crawl using a keybind seems pretty useful, and is already shown implementable via the GoProne mod for Forge. Perhaps via a double mini jump to activate elytra or something of the sort?

**Comment by dominikaaaa** [comment]
Please fill out the template, I can't tell what you're actually suggesting nor why it would be useful
