### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by Peremious** [ImpactDevelopment/ImpactIssues#2480]
Version: 1.15.2-Impact_4.9.1
OS: Linux Pop-OS!

Crashes the game as soon as it is launched with the typical "An unexpected issue has occurred". For some reason I don't even have crash reports. As in the folder is empty. I have no idea what to do.
![Screenshot from 2020-06-25 10-06-06](https://user-images.githubusercontent.com/43022063/85745759-8ee1cb00-b6cb-11ea-9e33-e673bce9926c.png)
![Screenshot from 2020-06-25 10-07-25](https://user-images.githubusercontent.com/43022063/85745923-b0db4d80-b6cb-11ea-8a1a-12f00396572c.png)
Edit: OS type

**Comment by dominikaaaa** [comment]
Use *Oracle* JDK 8.

**Comment by Peremious** [comment]
> Use _Oracle_ JDK 8.

Just to clarify, even though it is no longer a problem. I was using oracle JDK 8.
