### ISSUE TITLE
Minestrike hack not unctional on Mineplex

### ISSUE THREAD

**Issue by CrypteIsDefunct** [ImpactDevelopment/ImpactIssues#2482]
### First: 
Please do not say this is a duplicate of **#772**, that one is marked as closed, yet this problem **still exists**.

### Description: 
Colors that distinguish different teams through walls is dysfunctional. **Aimlock** and **autoshoot** are both **dysfunctional** as well and do not work no matter the setting configuration. I have tried in versions **1.12.2, 1.13.2, and 1.15.2.**

### Steps to reproduce the behavior:
1. Go to mineplex.com
2. Join a game of minestrike
3. Turn on the minestrike hack in the minigame menu
4. Turn on aimlock, it does not work
5. Try with autoshoot, it does not work

### Expected behavior:
Outlines of players in their respective team color should be seen through walls. Aimlock should automatically aim weapons at players of the opposing team. Autoshoot should shoot your gun automatically without right-clicking. 
 
### Details
- Impact Version: 4.8.3 for 1.12.2, 4.8.3 for 1.13.2, Impact Nightly for 1.15.2
- Using Optifine? Yes for 1.15.2, no for the other two
- Using LiteLoader? No
- Enabled mods: Sprint, Fullbright, No-slow, PlayerESP, StorageESP, Tracers, Search, AntiHunger, 
- Operating System: OS X El Capital

**Comment by dominikaaaa** [comment]
#1990

**Comment by dominikaaaa** [comment]
and it doesn't still exist, it was fixed and then broken again 🐒
