### ISSUE TITLE
Shared ESP between other Impact users (friends)

### ISSUE THREAD

**Issue by weezers** [ImpactDevelopment/ImpactIssues#2483]
**Is your feature request related to a problem? Please describe.**
No issue at all :)

**Describe the solution you'd like**
The ability to turn shared ESP on so people you .friended can also see players in range of you, no matter the distance.

**Comment by Daenges** [comment]
You would need some kind of communication between several instances. So, some kind of webserver which allows you this connection or you would do it over the minecraft chat, which is pretty bad.

1. It is easier to just communicate with your friend directly via Discord/Mc chat etc..
2. I don't think anyone will host a webserver (If this is even a conciderable sollution for it.) in the near future.
3. Using the minecraft chat is very unsafe and unpractical for the exchange of data per se. If you now want realtime exchange it is just not reliable.

**Comment by dominikaaaa** [comment]
Impact already uses heroku instances which could host all of this

**Comment by AdamTHM** [comment]
It's a good suggestion but on a mass scale this would either have too much of a delay or just straight up not work.

**Comment by ZeroMemes** [comment]
The user-preferred option would probably be to provide the software to host something capable of providing this inter-communication.
