### ISSUE TITLE
Question why was the option to change the path to where you install impact client removed?

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2489]
I notice in the new more recent installer for impact the option to change the path for it was removed. Why Is this? because I have a Minecraft+game band which pretty much allows me to play Minecraft on a USB stick and the new installer forces me to have to install it on my Minecraft on my PC then move it to my gameband which just takes more time so please Re-add this feature. It doesn’t do anyone any harm and for the people that need it in a different path can use it.

**Comment by dominikaaaa** [comment]
There is still an option for me (latest installer from the website)

**Comment by LeafHacker** [comment]
This option was hidden because the Official Launcher cannot be configured to use different directories, so including a way to change directory in the GUI was extra bulk/confusion.

You can still modify the minecraft launcher directory using a command line argument when running the Installer.
