### ISSUE TITLE
Impact crashes on Ubuntu

### ISSUE THREAD

**Issue by zbakusiowany** [ImpactDevelopment/ImpactIssues#2491]
**Describe the bug**
The game crashes on startup on Ubuntu 20.04 and 18.04

**To Reproduce**
1. Launch Impact

**Video**
https://youtu.be/0_7p1177tJ4

- Impact Version: 4.9 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Ubuntu 20.04 and 18.04

**Comment by dominikaaaa** [comment]
Use oracle JDK 8
