### ISSUE TITLE
Error Launching Impact On TLauncher

### ISSUE THREAD

**Issue by ZenoMilk12** [ImpactDevelopment/ImpactIssues#2492]
I'm getting an error when I try to launch Impact 1.15.2 Vanilla on TLauncher.
![Annotation 2020-07-02 233056](https://user-images.githubusercontent.com/63191158/86406720-4ffbd880-bcbc-11ea-81d8-1ad3f623ff38.png)

**Comment by dominikaaaa** [comment]
don't use tlauncher.
