### ISSUE TITLE
Standalone account switcher

### ISSUE THREAD

**Issue by usnet-000** [ImpactDevelopment/ImpactIssues#2494]
Since I'm not always playing on servers where I want to use a utility client, I was looking around for an in game account switcher.
I tried the in-game-account-switcher forge mod but it was really janky and it didn't really work.
This made me wonder whether you could make your wonderful account switcher a standalone mod for ppl like me.

**Comment by LeafHacker** [comment]
Have you tried multimc? It has the ability to choose between multiple accounts when launching the game.

**Comment by usnet-000** [comment]
I already use it, I meant an ingame account switcher

**Comment by dominikaaaa** [comment]
Doesn't impact already have this??

**Comment by usnet-000** [comment]
Did you even read what I wrote?

**Comment by dominikaaaa** [comment]
Oh I see. Well Impact isn't open source, this isn't happening.

**Comment by usnet-000** [comment]
That’s why I made the suggestion
