### ISSUE TITLE
Alts???

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2495]
What does the alts tab in settings do????

**Comment by dominikaaaa** [comment]
It allows you to open the alts menu

**Comment by yodaluca** [comment]
Witch does????

**Comment by dominikaaaa** [comment]
Witch does [this](https://minecraft.gamepedia.com/Witch)

**Comment by yodaluca** [comment]
*Facepalm* I suck at spelling ok

**Comment by yodaluca** [comment]
Can you tell or give me a video of what I can do with impact with the alt Manager?????

**Comment by dominikaaaa** [comment]
you can manage your alts

**Comment by yodaluca** [comment]
OMG WHAT ON EARTH  
DOES THAT EVEN MEAN 😡😡😡😡

**Comment by dominikaaaa** [comment]
I can't tell if you're 10 or if you're trolling. If you don't know what an alt is then you don't need to use the alt manager
