### ISSUE TITLE
Crosshair+ T style

### ISSUE THREAD

**Issue by Electric26** [ImpactDevelopment/ImpactIssues#2496]
**Is your feature request related to a problem? Please describe.**
Crosshair+ doesn't have an option for [T style crosshair](https://csgo-tutorial.com/wp-content/uploads/2019/04/cl_crosshair_t-1-csgo.jpg)s.

**Describe the solution you'd like**
T style crosshairs to be added.

**Describe alternatives you've considered**
Writing my own overlay.

**Additional context**
[T style crosshair](https://csgo-tutorial.com/wp-content/uploads/2019/04/cl_crosshair_t-1-csgo.jpg)

**Comment by dominikaaaa** [comment]
Use a resource pack

**Comment by Electric26** [comment]
What?? If you’re supposed to use a resource pack to change your crosshair, why does Crosshair+ exist in the first place? It’s literally one if statement (+ menu entry). I’d have done it myself if it was open source. Not to mention no texture pack exists for a T crosshair (at least that I’m aware).

**Comment by dominikaaaa** [comment]
> Not to mention no texture pack exists for a T crosshair (at least that I’m aware).
Yea, and this suggestion would also improve the client for a total of like 1 person. You can just use a resourcepack and crosshair+ applies to it
