### ISSUE TITLE
New chunks issue

### ISSUE THREAD

**Issue by DaggerDudeGitHub** [ImpactDevelopment/ImpactIssues#2498]
**Describe the bug**
It seems that new chunks does not work and does not render anything when I have it on. I'm not sure if it is an issue with optifine or not but it does not do anything
**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
Are you even on a spigot server??
