### ISSUE TITLE
When im open minecraft with impact 1.15.2 game is crashing.

### ISSUE THREAD

**Issue by limoncull** [ImpactDevelopment/ImpactIssues#2500]
When im open minecraft with impact 1.15.2 game is crashing.

opening the game

**Screenshots**
![UGHGH](https://user-images.githubusercontent.com/65875997/86855374-dd776800-c0c2-11ea-870c-d621fa2e10cf.PNG)

<details> 
  <summary><strong>Game output</strong></summary>
 
An unexpected issue occurred and the game has crashed we're sorry for the inconvenience
```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4887595/latest.log)

```

```

</details>

<details> 
  <summary><strong></strong></summary>
 

- Impact Version: 4.9 (1.15.2)
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: nothing
- Operating System: Windows 10 64 bit

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
set operating system to english
