### ISSUE TITLE
What does the alt manager do?

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2501]
I know what an alt account is but I don’t understand what or why you need and alt manager can someone tell me what it does??

**Comment by dominikaaaa** [comment]
It lets you log into other alts.

**Comment by yodaluca** [comment]
So you can like have multiple accounts in one game but in the same launcher and also is there like a PVP mode

**Comment by dominikaaaa** [comment]
????

**Comment by yodaluca** [comment]
Replying too: ???????
????????????????????

**Comment by yodaluca** [comment]
??????

**Comment by dominikaaaa** [comment]
this issue has been resolved. if you still don't understand what an alt manager is for then just don't use it
