### ISSUE TITLE
Make Impact at least Source-Available 

### ISSUE THREAD

**Issue by fffelix-jan** [ImpactDevelopment/ImpactIssues#2504]
**Is your feature request related to a problem? Please describe.**
Many people, including me, are worried that there might be backdoors in Impact, although it is one of the most popular utility clients. 

**Describe the solution you'd like**
May the source code be made available, please? It's OK if the licence agreement for the source code forbids you from distributing your own versions of the code if you don't want it. We only need to look at it. Thanks!

**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by dominikaaaa** [comment]
no
