### ISSUE TITLE
Auto-eat and left hand

### ISSUE THREAD

**Issue by PerchunPak** [ImpactDevelopment/ImpactIssues#2505]
**Describetion the bug**
Auto-eat don't want eat when food at left hand, when this is auto mine this is comfortably. But when you haven't totem it is not comfortable

1. Get small satiety
2. Get some food
3. Get food to left hand
4. Turn on auto-eat
5. Auto-eat don't want eat
 

- Impact Version: 4.9.1 for 1.15.2
- Using Optifine? Not now
- Using LiteLoader? ot now
- Enabled mods: Auto-eat 
- Operating System: Windows 10 64bit

Just add new parametr to auto-eat "Left hand eat"

**Comment by dominikaaaa** [comment]
#1493
