### ISSUE TITLE
Skulker Box Preview

### ISSUE THREAD

**Issue by Shibe-Doge** [ImpactDevelopment/ImpactIssues#2508]
**Is your feature request related to a problem? Please describe.**
I don't like having an list of all the items in the skulker box.

**Describe the solution you'd like**
A mini chest-like display.
Or a new overlay that goes on a corner or something. Hopefully it can be moved around.

**Describe alternatives you've considered**
I tried getting a Forge mod for that. I don't like it a lot because I need to have forge and the mod updated.

**Comment by dominikaaaa** [comment]
impact already has this though
