### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by PotetaGH** [ImpactDevelopment/ImpactIssues#2511]
**The bug**
When i use flight doesnt matter what flight mode its on all, when i fly i sometimes just get teleported down

**To Reproduce**
1. Go to 'Flight set mode to vanilla'
2. Click on 'Go fly'
3. See error

**Expected behavior**
It just teleports me down

**Screenshots**
you cant screenshot this

<details> 
  <summary><strong>Game output</strong></summary>
 

```
idk what this means
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9.1
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods:  Flight only
- Operating System:  windows 10 64bit

</details>

**Comment by dominikaaaa** [comment]
CNR
