### ISSUE TITLE
Error Invalid signature on Impact release 4.9.1-1.15.2

### ISSUE THREAD

**Issue by JAsrx** [ImpactDevelopment/ImpactIssues#2513]
**Describe the bug**
The Windows version cannot be installed after downloading
Install for:vanlla
Minecraft version:1.15.2
Impact version:4.9.1(latest)
Include OptiFine NO

**Comment by dominikaaaa** [comment]
Use the jar installer if you don't know how to click the "run anyways" button

**Comment by JAsrx** [comment]
> 如果您不知道如何单击“仍然运行”按钮，请使用jar安装程序

I've tried to prompt the same error for jar installation. The button does not still run after the error is prompted. Please help me, thank you

**Comment by dominikaaaa** [comment]
then you either didn't download the real installer or something is blocked by your firewall or ISP

**Comment by JAsrx** [comment]
> 那么您要么没有下载真正的安装程序，要么防火墙或ISP阻止了某些内容

I use win7 system and have closed the firewall, the installation program for different browsers to download and try to install, but these methods can not work

**Comment by JAsrx** [comment]
Please help me
