### ISSUE TITLE
Can't type commands or messages

### ISSUE THREAD

**Issue by MakeshiftMelon** [ImpactDevelopment/ImpactIssues#2515]
Whenever I type a command, whether a vanilla command or Impact command, the unknow command message will appear. If I type a regular message, it will not be sent. This happens on servers and singleplayer.

I turned off all of the client settings I had on and everything worked fine

Using version 1.12.2
Not using Optifine
Not using Light Loader
Windows 10 64bit

**Comment by dominikaaaa** [comment]
then type a valid command

**Comment by MakeshiftMelon** [comment]
All commands that I write are valid, if it says 'Do /help for list of commands", and I do /help, the unknown command message will still appear.

**Comment by dominikaaaa** [comment]
Use the impact prefix, not /
