### ISSUE TITLE
Different settings for norender

### ISSUE THREAD

**Issue by Ardenzard** [ImpactDevelopment/ImpactIssues#2522]
My request is that you guys should add more settings to norender because currently it only stops rendering dropped items. 

You guys should make it so you can choose what it should not render for example skylight updates, shield, firework explosions, tnt entities and more

Currently kami blue has a feature similar to this so you can look at that for examples of good things to add to norender or other clients

**Comment by dominikaaaa** [comment]
#510 #2340 #1302
