### ISSUE TITLE
Impact with Forge crashing on launch

### ISSUE THREAD

**Issue by FredBrioche** [ImpactDevelopment/ImpactIssues#2527]
**Describe the bug**
When started Minecraft launches and when the Mojang logo is gone it immediatly crashes. If vanillafix is used to prevent the crash all GUI is pure black in a world or on a server. The Impact button is also missing.

**To Reproduce**
launch Impact with forge 1.12.2-14.23.5.2768
**Expected behavior**
I expected the program to launch normally like it did before and for everything to work like intended.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Black Screen 
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4942844/latest.log)
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact-4.9.1-1.12.2
- Using Optifine? Happens with and without
- Using LiteLoader? I don't think so and don't know how to check
[default - Copy.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4942837/default.-.Copy.txt)
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4942844/latest.log)

- Enabled mods: [default - Copy.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4942837/default.-.Copy.txt) I don't know because I can't see as it crashes on launch or diables all gui if forced to proceed
- Operating System: Windows 10 Version 2004 Build 19041.338

</details>

**Additional context**
Didn't happen before. I didn't change any of the settings or anything it has worked with the same conditions (as far as I know) I don't think I changed anything.

**Comment by dominikaaaa** [comment]
Please provide a crash report.

**Comment by dominikaaaa** [comment]
Oh oops, you put it in the wrong section.

**Comment by dominikaaaa** [comment]
> Error getting Impact API token from minecraft login java.io.IOException: /login/minecraft is not ok, it's 401

Are you using the official launcher?

**Comment by FredBrioche** [comment]
Yes

**Comment by dominikaaaa** [comment]
¯\\\_(ツ)_/¯

**Comment by FredBrioche** [comment]
So no fix

**Comment by FredBrioche** [comment]
Is it backdoored or something

**Comment by dominikaaaa** [comment]
No lmao. I just don't know the fix, I'm leaving this open in case someone else does.

**Comment by FredBrioche** [comment]
ok

**Comment by FredBrioche** [comment]
are you also the Kami Blue dev?

**Comment by FredBrioche** [comment]
I just deleted the Impact folder and ran forge with Impact and it all works now.

**Comment by dominikaaaa** [comment]
Good to know

**Comment by PoltixeTheDerg** [comment]
I seem to be getting the same problem and didn't want to open a new issue so I'm just commenting here instead, I'm playing with MultiMC instead of forge but it definitely is the exact same crash issue ```
[main/ERROR]: Error getting Impact API token from minecraft login
java.io.IOException: /login/minecraft is not ok, it's 401
```
I tried deleting the Impact folder as they said and it didn't help in my case, just recreated it and crashed again
Game version and such is identical to them except for me being on a slightly older version of windows (1909 18363.959)

Crash log: https://paste.ee/p/9ubIi

**Comment by LeafHacker** [comment]
The error message your quoting only means you aren't logged into an Impact Account; i.e. you aren't a donator.

Whatever is causing you issues is probably further down in the logs and/or crash-report, unless you are trying to run a nightly build of Impact.

You're best off opening a new issue and posting full logs etc.

**Comment by furydeath9** [comment]
Guess this never got fixed since you still can't run impact with forge not that it matters now that the client is dead
