### ISSUE TITLE
I keep getting muted by mods for bad reasons

### ISSUE THREAD

**Issue by EuSuntFantoma** [ImpactDevelopment/ImpactIssues#2529]
I'm being muted by mods for bad reasons
Ok so I didnt even spam when they said I did and
They saying @ for no reason when I wouldve just received one warning 
Then they saying I'm begging for mod when Another mod told me it would get me mod and that's how they got it and I believed them

And i think they should be demoted and i unmuted my username is EuSuntFantoma

**Comment by EmeraldSnorlax** [comment]
ok

**Comment by DoctorBang** [comment]
What a madlad.

**Comment by ISubbbed** [comment]
Stop spamming ez

**Comment by dominikaaaa** [comment]
sorry, I can't reproduce this issue, it doesn't happen to me
