### ISSUE TITLE
version option list 

### ISSUE THREAD

**Issue by ashersallee3** [ImpactDevelopment/ImpactIssues#2530]
all i wanted is to happen was that you could change the versions on the multiplayer to 1.7 to 1.16 as a scroll thing in the multiplayer section so you can hack on other servers and have fun

**Comment by dominikaaaa** [comment]
template

**Comment by yodaluca** [comment]
Jello/sigma 5 has jello portal witch is essential that and yes I'd love this feature!!!

**Comment by dominikaaaa** [comment]
please make an issue following the template if you want to make a suggestion

**Comment by dominikaaaa** [comment]
also, sigma violates viaversion / viaconnects license by including it without saying what they're using for the version switching. 

It's probably a "no" anyways, because of how Impact is designed.
