### ISSUE TITLE
Fancy chat messes up macro impact commands

### ISSUE THREAD

**Issue by User-developer** [ImpactDevelopment/ImpactIssues#2531]
**Describe the bug**
When fancy chat module is enabled, instead of the macros bypassing the font change, they print in chat "fancied" and thus commands don't work

**To Reproduce**
1. Enable fancy chat
2. Set .help as macro an assign it to a key
3. Press the key to enable the macro
4. Instead of the command working it prints in chat with the font

**Expected behavior**
The macro activating the internal impact command

- Impact Version: 4.9.1 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: (they don't affect)
- Operating System: Windows 10 64bit

**Comment by dominikaaaa** [comment]
wait does fancychat literally intercept keystrokes lmaooooo

**Comment by Tomodachi94** [comment]
I think it does, @l1ving

**Comment by l1ving** [comment]
ruh

**Comment by Tomodachi94** [comment]
?
