### ISSUE TITLE
Peek gui (shulker toolip)

### ISSUE THREAD

**Issue by razvicretu** [ImpactDevelopment/ImpactIssues#2533]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem.

**Describe the solution you'd like**
I would like to do something to the "Inventory" cheat, something about shulkers so when you hover over a shulker it will show you the contents of it, not just a big list

**Describe alternatives you've considered**
WWE has this feature and it is very helpful, when some items are named, it's hard to figure out what they are and it would be more easy if you could hover over it in the echest for example instead of taking it into your hand, type .peek and then see what is inside

**Additional context**
This is the mod that me, lots of my friends and other players would love to see implemented into the client: https://www.curseforge.com/minecraft/mc-mods/shulker-tooltip

**Comment by dominikaaaa** [comment]
#2193
