### ISSUE TITLE
auto mine option no longer shown in ClickGUI

### ISSUE THREAD

**Issue by hotgrabba** [ImpactDevelopment/ImpactIssues#2534]
I was using the impact launcher for a day and it was working fine and out of nowhere the auto mine feature disappeared from the GUI while i was playing which was weird. ive tried reinstalling the lancher but the auto mine features doesnt seem to come back

**Comment by dominikaaaa** [comment]
Reset your settings to default, or make your GUI smaller. It probably went off screen somehow
