### ISSUE TITLE
Crash when enter in a world (singleplayer and multiplayer)

### ISSUE THREAD

**Issue by Joseleelsuper** [ImpactDevelopment/ImpactIssues#2535]
[crash.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4964414/crash.txt)

This issue occurs in all versions of Minecraft with impact and in 4.9.1 impact version.
the languages ​​used were spanish and english(US)

**Comment by dominikaaaa** [comment]
Use the official minecraft launcher or multimc
