### ISSUE TITLE
Add install path field (last seen in 0.8.6)

### ISSUE THREAD

**Issue by SirAxolot** [ImpactDevelopment/ImpactIssues#2536]
**Is your feature request related to a problem? Please describe.**
Due to personal circumstances, I keep my Minecraft installation in a Gameband, and as such have a nonstandard install location.

**Describe the solution you'd like**
Reintroduce the option to chose a custom install location.

**Describe alternatives you've considered**
I have downloaded the 0.8.6 installer, but there are features that I lose due to this choice.

**Additional context**
N\A

**Comment by dominikaaaa** [comment]
There is a choice, it just doesn't appear for some people
