### ISSUE TITLE
Impact crashes upon start.

### ISSUE THREAD

**Issue by stop-bark** [ImpactDevelopment/ImpactIssues#2537]
**Describe the bug**
Whenever I launch Impact, it instantly goes back to the launcher and show's a error, the minecraft window doesn't even open.

**To Reproduce**
1. Go to Impact Installer
2. Install 1.15.2 Impact
3. Launch 1.15.2 Impact

**Expected behavior**
Open Impact without a crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/60797172/88366252-5815d800-cd91-11ea-8e91-a321a7ae2eab.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[06:21:24] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Wasn't generated.
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 7 64 BIT

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
Fill out the issue template properly. "Wasn't generated" is nearly impossible

**Comment by KappaDisc** [comment]
Nearly means still possible, but I checked my crash logs only thing I saw was from yesterday

**Comment by KappaDisc** [comment]
> Fill out the issue template properly. "Wasn't generated" is nearly impossible

Nearly means still possible, but I checked my crash logs only thing I saw was from yesterday

**Comment by ScanmanTM** [comment]
A log is produced in logs folder, upload latest.log

**Comment by KappaDisc** [comment]
> A log is produced in logs folder, upload latest.log

The game output is the latest.log, it's only 1 line idk why

**Comment by dominikaaaa** [comment]
Then you're not using JDK/JRE 8

**Comment by KappaDisc** [comment]
> Then you're not using JDK/JRE 8

Uhh I have JDK, JRE I'll download it tommorow since its 1am here.

**Comment by dominikaaaa** [comment]
If you have it, your Java home isn't set properly. 
This is the easiest way of fixing it for minecraft
![Screenshot_20200724_180827](https://user-images.githubusercontent.com/17222512/88439251-ac907600-cdd8-11ea-9654-8bc6d307aacd.png)

**Comment by iiLeafy** [comment]
> If you have it, your Java home isn't set properly.
> This is the easiest way of fixing it for minecraft
> ![Screenshot_20200724_180827](https://user-images.githubusercontent.com/17222512/88439251-ac907600-cdd8-11ea-9654-8bc6d307aacd.png)

Uhh, I set up my java home, and I also tried that java executable it still gives me the same error.

**Comment by l1ving** [comment]
Closed as stale. Reopen if you can still reproduce this.

**Comment by stop-bark** [comment]
I got a entirely new pc, and it works on this one.
