### ISSUE TITLE
[AFK-Fishing] Switch to another fishing rod when one breaks.

### ISSUE THREAD

**Issue by nibrobb** [ImpactDevelopment/ImpactIssues#2538]
I got kicked from a server with a very long queue because my afk-fishing didn't switch to another rod when the one I was using broke. This was annoying.

I would like Impact to switch to another usable rod when the one currently in use breaks.

I am aware of the possibility of using mending on tools such as the fishing rod, but not all players have that luxury. My suggestion is for the ones that do not have access to the Mending enchantment.

**Comment by dominikaaaa** [comment]
Autotool
