### ISSUE TITLE
teleports you back periodically

### ISSUE THREAD

**Issue by leonhma** [ImpactDevelopment/ImpactIssues#2539]
for the first ten or so minutes everything worked fine, but then impact started to teleport me back to where i was a second ago every second (always the same location).  tried 1.14.4 and 1.15.2 both with and without optifine, but always the same. it started while using baritones automine. maybe some config was changed because now it happens imediately when i join a server/create a new world. please help..

**Comment by dominikaaaa** [comment]
Disable portal godmode
