### ISSUE TITLE
autocraft

### ISSUE THREAD

**Issue by ceedee63** [ImpactDevelopment/ImpactIssues#2541]
Although this might be hard to pull off, I´d love to see a feature, which lets you select an item to craft e.g. bread and make baritone walk to a crafting bench closeby and craft some with the ressources Autofarm got. Maybe add a bar, with which you can set the amount at which stuff is converted, e.g. 2 stacks of wheat wont do anything in the inventory but 3 will trigger baritone to walk to the workbench and make a stack of bread.

**Comment by dominikaaaa** [comment]
already suggested like a million times
