### ISSUE TITLE
impact+voxelmap=instant crash

### ISSUE THREAD

**Issue by joeyjumper94** [ImpactDevelopment/ImpactIssues#2542]
**Describe the bug**
if you use forge 1.12.2 impact with voxelmap, the game will crash before the game window appears

**To Reproduce**
you will need:
Impact-4.9.1-1.12.2.jar
and voxelmap from https://www.curseforge.com/minecraft/mc-mods/voxelmap/files/3017424
place both into the mods folder of a forge 1.12.2 client and open the launcher, then select the installation and hit play
the launcher window disappears and and after a few seconds the launcher window will reappear with the message "game crashed"
**Expected behavior**
the game window should appear with forge loading the mods.
**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
try uninstalling voxelmap, that should fix the issue

**Comment by joeyjumper94** [comment]
i also need voxelmap, i have a fair amount of data in it,

**Comment by joeyjumper94** [comment]
and yeah, removing voxelmap does stop the crashes, but it also removes my ability to find my way around.
and getting lost on a server similar to 2b2t is a great way to die horribly.

**Comment by dominikaaaa** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

Use another minimap mod
