### ISSUE TITLE
alt list verification (suggestion)

### ISSUE THREAD

**Issue by leonhma** [ImpactDevelopment/ImpactIssues#2544]
maybe verify all alts in a list on import. could be done like this: if an altlist doesnt have #impactaltlist (#impactlist signals that the list has been exported from impact and already been checked) in its first line (export altlists with #impactaltlist in the first line from now on), try to log in with every single account -> if failed, delete it. would be nice to have for like not having to check hundreds of accounts yourself

**Comment by dominikaaaa** [comment]
Won't fix. You'd get rate limited by mojang instantly and we don't want more kids complaining "why doesn't alt switcher work pls fix!!!!!"
