### ISSUE TITLE
Hunt unable to follow friends if player is disabled

### ISSUE THREAD

**Issue by jontyms** [ImpactDevelopment/ImpactIssues#2546]
**Describe the bug**
Hunt unable to follow friends if player is disabled
**To Reproduce**
1. Go to hunt
2. Enable
3. Disable player and enable friend
4. Hunt will be unable to path to anything

**Expected behavior**
I expected hunt to follow friends even if player is disabled
**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.3 for 1.12.2 forge
- Using Optifine?  No
- Using LiteLoader? No
- Enabled mods: Hunt
- Operating System: Windows 10 64bit

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
That's intentional

**Comment by dominikaaaa** [comment]
There's already a suggestion to add the option, before you ask
