### ISSUE TITLE
i keep crashing on Impact ij ust installed impact And i try join multplayer and i crash then i try joining single player here the crash log one is for singleplayer and the other is for multiplayer and i crash 

### ISSUE THREAD

**Issue by Xoadsxd** [ImpactDevelopment/ImpactIssues#2549]
[crash-2020-07-28_22.46.50-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4997995/crash-2020-07-28_22.46.50-client.txt)
[crash-2020-07-28_22.48.23-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4997996/crash-2020-07-28_22.48.23-client.txt)

**Comment by dominikaaaa** [comment]
reset your config
