### ISSUE TITLE
Unpack "reverse" mode

### ISSUE THREAD

**Issue by jefferyw08** [ImpactDevelopment/ImpactIssues#255]
although unpack is a really simple concept and is rarely useful - it could be improved to be useful in more situations. there should be a mode "normal": whenever you have an item that can be crafted into something with only itself, shift+rmouse should "unpack" that item and craft it into whatever the product is

**Comment by ZeroMemes** [comment]
@jefferyw08 Could you elaborate? re-reading this has me a little confused.

**Comment by MightyKnight** [comment]
2 years old, no answer, closing.
