### ISSUE TITLE
1.15.2 "Portals" locks movement and camera after sleeping in an bed

### ISSUE THREAD

**Issue by Philipp766** [ImpactDevelopment/ImpactIssues#2559]
**Bug**
I am playing on an localhost server with some mods. 
I slept in an bed and after I stood back up and tried to move or pan the camera the player snaps back into position how he left the bed. If I self destruct i can move normal again

**To Reproduce**
Go to an bed and sleep in it.  You have to have the Portals module on 

**Expected behavior**
Normal movement after leaving bed.

**to fix again**
turn the portals module off and on again

**Mods on the server**
grind-enchantments
infinity fix
lithium and phosphor
 
**Used features**
![2020-08-03_17 49 06](https://user-images.githubusercontent.com/45693638/89201448-cccaec80-d5b1-11ea-81b9-908602606679.png)

- Impact Version: 4.9 on 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Operating System: "Windows 10 64bit

**Comment by ScanmanTM** [comment]
Were you holding left alt by any chance?

**Comment by ScanmanTM** [comment]
Wait a minute, how did you get them mods on 1.15?

**Comment by dominikaaaa** [comment]
Phosphor is a Fabric mod?? Are you running a Fabric server???

**Comment by Philipp766** [comment]
No, i wasnt holding left alt

**Comment by Philipp766** [comment]
and yes, I am running an fabric localhost server

**Comment by ScanmanTM** [comment]
Reproduced in SP, its specifically portal god mode causing it.

**Comment by Philipp766** [comment]
I noticed that too. Thats why I edited the title and the description

**Comment by dominikaaaa** [comment]
> Reproduced in SP, its specifically portal god mode causing it.

That's how Portal God Mode works, you're not supposed to be able to move or look around while it's enabled

**Comment by dominikaaaa** [comment]
You can reproduce the same "issue" in any other client that has PGM

**Comment by dominikaaaa** [comment]
Closed as resolved and no more activity. Please comment if you have any further questions
