### ISSUE TITLE
A Baritone mod to automatically grind mob spawners

### ISSUE THREAD

**Issue by Toritos01** [ImpactDevelopment/ImpactIssues#2560]
**Is your feature request related to a problem? Please describe.**
When a single player is using a Mob Spawner to grind for experience points, it is necessary to wait near the spawner, and then move to a different location to kill the mobs. 

**Describe the solution you'd like**
A Baritone implementation could be added onto Impact that would work as follows:
First you configure it, you tell it a location for the spot you need to stand for mobs to spawn(could be either a baritone waypoint or coordinates) and you tell it a location where you need to go to kill the mobs. You also give it an amount of time that you want it to wait at the spawning location, allowing you to wait longer for more mobs.
Here is what the module would do:
type #wp g [Spawn Loaction]
type #path
Wait for a number of seconds defined by the user
type #wp g [Kill Location]
type #path
Enable Kill Aura(To kill mobs)
Disable Kill Aura
Repeat this process until the user turns off the module

**Describe alternatives you've considered**
The alternative method to grinding a mob spawner is to have a friend or an alt account AFK at the spawner to keep it spawning mobs, this module's main purpose would be for situations where a second player cannot be used.

**Additional context**

**Comment by ScanmanTM** [comment]
bro thats pog, would be poggers if you actually submitted it to the baritone repo.
https://github.com/cabaletta/baritone/issues

**Comment by dominikaaaa** [comment]
This can already be done with the Hunt module in Impact

**Comment by Toritos01** [comment]
@dominikaaaa Can it? It seems to me like the hunt module just tracks down and walks you to any target entities in the area, but not necessarily walk you back to the spawning area after you kill them, and also I don't think there's a way to make it only target one type of hostile mob. And even if there were, it might decide to go somewhere away from the spawner to look for more of that mob(for example if there was a zombie in a nearby cave, while you're trying to grind a zombie spawner
