### ISSUE TITLE
Minigames: MurderMystery

### ISSUE THREAD

**Issue by ItzJustSamuel** [ImpactDevelopment/ImpactIssues#2561]
I was just testing it and noticed how sometimes it doesn't detect whos the murderer because of the other weapons people use and the new weapons server adds on. Is there a way to edit the list and add the ID of the weapons it should detect?

**Comment by ScanmanTM** [comment]
no

**Comment by ItzJustSamuel** [comment]
so there isn't a config?

**Comment by dominikaaaa** [comment]
no

**Comment by dominikaaaa** [comment]
try using the search button next time, this has been reported like 29834982349823432984982 times
