### ISSUE TITLE
an autoclicker

### ISSUE THREAD

**Issue by mrredston** [ImpactDevelopment/ImpactIssues#2563]
**Is your feature request related to a problem? Please describe.**
i would like an autoclicker or spammer for anything
**Describe the solution you'd like**
just something that clicks anything a key or left click or right click and that you can edit like with the auto clicker that exists at the moment but with you able to change it to any key or anything else your pc can do you could combine it with other hacks to like making it autoclick numpad 7 and set auto potion numpad 7
**Describe alternatives you've considered**
i have no idea.

**Additional context**

**Comment by dominikaaaa** [comment]
Macros??????

**Comment by mrredston** [comment]
> Macros??????

what the hell is macros

**Comment by dominikaaaa** [comment]
It does exactly what you described in this issue

**Comment by skerit** [comment]
Hmm, how would you configure a macro to automatically rightclick the mouse in a loop?
I can only seem to execute commands or say something in chat, not simulate a key or click.
(Can't seem to find any info on the way macros are defined)

**Comment by dominikaaaa** [comment]
I'm pretty sure Impact macros don't support emulating keys / buttons but I could be wrong

**Comment by skerit** [comment]
Makes sense, otherwise there would be some kind of documentation on it somewhere. I switched to using Impact with Forge and installed the TapeMouse mod, which works fine for this.
