### ISSUE TITLE
better .drop

### ISSUE THREAD

**Issue by mrredston** [ImpactDevelopment/ImpactIssues#2564]
**Is your feature request related to a problem? Please describe.**
i would like it possible to say if you have more then ... stacks of an item throw it away instead of just saying throw it away 100%

**Describe the solution you'd like**
tbh i already said it up there 

**Describe alternatives you've considered**
idk im good at suggesting stuff that annoyed me not good at figuring out 

**Additional context**

**Comment by Daenges** [comment]
I made a similar Suggestion a while ago. #2141
