### ISSUE TITLE
the hunt feature

### ISSUE THREAD

**Issue by mrredston** [ImpactDevelopment/ImpactIssues#2565]
**Is your feature request related to a problem? Please describe.**
it always annoys me that if i want to just annoy people hunt instantly dies

**Describe the solution you'd like**
maby make hunt have some kind of smart feature aka straving around an enemy and trying to stay as far back as possible if you have more range or something like it

**Describe alternatives you've considered**

**Additional context**

**Comment by TonyDangermouse** [comment]
I made a similar suggestion in the baritone github thing
