### ISSUE TITLE
Suggestion for new Elytra+ mode

### ISSUE THREAD

**Issue by Mortaper** [ImpactDevelopment/ImpactIssues#2571]
The current Elytra+ module is good, but I think it lacks a very important feature. This feature will benefit a lot of players, and it will make the overall flying experience much better.

I think it will benefit everyone if the ability to fly horizontally without losing any altitude would be implemented into the Elytra+ module, as it will make flying around the world using the elytra quicker, simpler, and would prevent things like accidently crashing into a hill, or ground from happening. This will also mean that players can fly in a straight path, just by pressing W, where as now it involves pressing the space bar occasionally and pointing the mouse upwards. 

Tips for controls: Entering elytra flight mode is still the same, but when pressing space, it will make your character accend at the same spot, pressing LShift will make you descent at the same spot. Once a desired altitude is reached, the player should stay there, with the y-axis not changing. 

Of course this is just a suggestion, but it would be great if the developers can implement this into Impact with the next update.

**Comment by dominikaaaa** [comment]
This has been suggested 38283829 times
