### ISSUE TITLE
Prop hunt don’t work

### ISSUE THREAD

**Issue by Gouverneur-Berry** [ImpactDevelopment/ImpactIssues#2574]
Ye so the prop hunt cheat don’t work for shit it ain’t showing anyone

**To Reproduce**
1. log in 
2. join a prop hunt server 
3. turn on cheat
4. it ain’t work lol

**Expected behavior**
I expected the blocks who are people to light up

 

- Impact Version: <1.12.1 (not sure wich one)>
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

**Additional context**
It just don’t fucking work fam

**Comment by dominikaaaa** [comment]
try searching next time
