### ISSUE TITLE
Axe option in autoclicker

### ISSUE THREAD

**Issue by iamral** [ImpactDevelopment/ImpactIssues#2575]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to fight with axe, but I can't select it in autoclicker

**Describe the solution you'd like**
Add axe in autoclicker (there're only sword now)

**Describe alternatives you've considered**
Add a function that allows you to select an item by yourself (like selecting blocks in xray). It can be done by using a command too, like .autoclicker item diamond_axe or something like this

**Comment by dominikaaaa** [comment]
#802
