### ISSUE TITLE
Impact Premium Chest Issue

### ISSUE THREAD

**Issue by IHackedAmazon** [ImpactDevelopment/ImpactIssues#2576]
I found a bug, when you're walking on chests it crashes the game. https://youtu.be/-DWpA0WI6do
[2020-08-09-7.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5047552/2020-08-09-7.log)

**Comment by dominikaaaa** [comment]
This is a Baritone issue. please make a report here: https://github.com/cabaletta/baritone
