### ISSUE TITLE
Autofish doesn't work correctly with antiaim

### ISSUE THREAD

**Issue by iamral** [ImpactDevelopment/ImpactIssues#2578]
**Describe the bug**
Rod isn't used in the front of you, it's used in random place (because of antiaim)

**To Reproduce**
1. Turn on antiaim
2. Turn on autofish
3. Done

**Expected behavior**
Rod should be used in direction that the player is looking, not antiaim

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: https://i.imgur.com/KLnRe7K.png
- Operating System: Linux Mint 20

</details>

**Comment by ScanmanTM** [comment]
no shit, do you even know what antiaim does
