### ISSUE TITLE
JavaScript / JS Support for more customizability

### ISSUE THREAD

**Issue by undercoverGuy** [ImpactDevelopment/ImpactIssues#2582]
**Is your feature request related to a problem? Please describe.**
nah

**Describe the solution you'd like**
JavaScript scripting support.
Can be done like LiquidBounce. https://github.com/CCBlueX/LiquidBounce/tree/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/script
(Their implementation includes deobfuscation)
Impact is a really good client, but it lacks some small features. Not just Impact developers would easily be able to include additional features.
I haven't really looked at https://github.com/eclipsesource/J2V8, but that also seems like a great alternative to nashorn.

**Comment by dominikaaaa** [comment]
this has already been suggested, search next time please

**Comment by undercoverGuy** [comment]
i actually tried to use the search, found nothing on here with the keywords 'script', 'javascript' and 'js'

**Comment by dominikaaaa** [comment]
Yea I'm *sure* you used the search

![image](https://user-images.githubusercontent.com/17222512/90072368-558a0c80-dcc5-11ea-915c-64d7f6335eb6.png)

This one would also accomplish what you're asking for: #911
