### ISSUE TITLE
crash on start cant open

### ISSUE THREAD

**Issue by shadowbunshin** [ImpactDevelopment/ImpactIssues#2586]
[latest.log](https://github.com/ImpactDevelopment/Installer/files/4410304/latest.log)
i tried 4.8.2 and 4.8.3 with clean install
Mixin apply failed mixins.impact.json:accessor.AccessorPlayerEntity

**Comment by TheCoolestCoderGuy** [comment]
Can you try installing the latest version of impact?: (4.9.1)

**Comment by l1ving** [comment]
Can't reproduce on latest.
