### ISSUE TITLE
Impact 4.9.1 Instant crash on minecraft 1.15.2

### ISSUE THREAD

**Issue by GewGaul** [ImpactDevelopment/ImpactIssues#2588]
My minecraft keeps crashing when I launch, I am using Lubuntu and have tried as many fixes as i have found. I do not know how you would re-create this because i do not know what is causing this problem.

My log:
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5087842/latest.log)

My output:
19:58:55.351
Preparing to launch minecraft client for 1.15.2-Impact_4.9.1
19:58:55.921
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.15.2/1.15.2.jar
19:58:55.921
Have local file /home/l/.minecraft/versions/1.15.2/1.15.2.jar but don't know what size or hash it should be. Have to assume it's good.
19:58:59.395
Checking installations.
19:58:59.395
Minecraft client 1.15.2-Impact_4.9.1 is ready to start.
19:58:59.396
Starting!
19:58:59.598
Using default game log configuration client-1.12.xml (outputs XML)
19:59:02.729
Loading tweak class name clientapi.load.ClientTweaker
19:59:02.781

Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 21890
	at java.lang.String.substring(String.java:1963)
	at clientapi.load.ClientTweaker.<clinit>(ClientTweaker.java)
	... 4 more
19:59:02.781
Process crashed with exit code 1

**Comment by dominikaaaa** [comment]
Use JDK 8

**Comment by Supergamer5465** [comment]
Do you mean openjdk or oracle?

**Comment by LeafHacker** [comment]
AdoptOpenJDK 8 is pretty much identical to Oracle's jdk, but it is fully open source

**Comment by sosigman23** [comment]
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A9126FA826C1E968</RequestId>
<HostId>720iF8lwUat5+1k5oPV3Ir2EkGDhgsN7ceqtH+KA2dh5oXm6NiwPlEnXE8T32hBaR3N5xhe0WIk=</HostId>
</Error> i just get this error pls help
