### ISSUE TITLE
Baritone #click causes Minecraft-Crash + Solution

### ISSUE THREAD

**Issue by JustMaaarc** [ImpactDevelopment/ImpactIssues#2589]
**Describe the bug**
Using the #click Command of Bariton causes the Game to crash in various versions (With/out OptiFine)

**To Reproduce**
1. Open Chat
2. Type in #click
3. Either Right or Left-click anywhere
4. Game Crashes

**Expected behavior**
I expected the Client to register the Position i Clicked and make bariton automaticly go there. (or goal it so I would have to use #path to activate)

**Screenshots**
It appears to working now. Odd
Since this Problem has appeared alot for me and my friends recently i still think it's something to put an eye out for

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
 [ I cannot recreate the Problem atm since works now for some reason. It did happen recently again though ]
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9.1
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods:  None (with and without the bug appeared)
- Operating System: Windows 10 64bit

</details>

**Additional context**
A Solution (if the bug appears more often and cannot be fixed correctly)
would be to make the client register the coordinates the player is directly looking at and then make it execute the #goto command to these exact coordinates. (I'm sure this is quite obvious)

**Comment by dominikaaaa** [comment]
1. This is the impact repo
2. this issue is already reported
3. a fix for this issue is already in place. It's almost ready to be merged
