### ISSUE TITLE
https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md&title=Please+add+a+brief+but+descriptive+titlePlease add a brief but descriptive title

### ISSUE THREAD

**Issue by GewGaul** [ImpactDevelopment/ImpactIssues#2591]
My minecraft keeps crashing when I launch, I am using Lubuntu and have tried as many fixes as i have found. I do not know how you would re-create this because i do not know what is causing this problem. I made a post last night with the same problem but got closed with "use JDK 8" which I have done, but tried again. Please do not close this unless I say it has been fixed.

Log:
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5091706/latest.log)

Output:
00:27:01.997
Preparing to launch minecraft client for 1.15.2-Impact_4.9.1
00:27:01.998
Prepared asset index
00:27:02.036
Have 2150 total files to check or download
00:27:02.037
Waiting for 2150 futures
00:27:02.560
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.15.2/1.15.2.jar
00:27:02.560
Have local file /home/l/.minecraft/versions/1.15.2/1.15.2.jar but don't know what size or hash it should be. Have to assume it's good.
00:27:03.499
Checking installations.
00:27:03.499
Minecraft client 1.15.2-Impact_4.9.1 is ready to start.
00:27:03.500
Starting!
00:27:03.531
Nothing to download!
00:27:03.531
Extracting 8 files!
00:27:03.607
Using default game log configuration client-1.12.xml (outputs XML)
00:27:03.607
Installing versions!
00:27:05.494
Loading tweak class name clientapi.load.ClientTweaker
00:27:05.544

Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 21890
	at java.lang.String.substring(String.java:1963)
	at clientapi.load.ClientTweaker.<clinit>(ClientTweaker.java)
	... 4 more
00:27:05.544
Process crashed with exit code 1

**Comment by dominikaaaa** [comment]
Use JDK 8

**Comment by dominikaaaa** [comment]
If you have it installed then you don't have your JDK home set properly.

**Comment by dominikaaaa** [comment]
If you don't know how to set it just change the java executable to look like this
![image](https://user-images.githubusercontent.com/17222512/90545149-33294080-e156-11ea-92f3-1624e726c2d9.png)

Ofc change the path to where you installed it

**Comment by GewGaul** [comment]
I have done this, as i said this did not work
![screenshot-fafbf14b](https://user-images.githubusercontent.com/69831116/90562604-b69b5f80-e15f-11ea-8dce-6842df611b1e.jpg)

**Comment by GewGaul** [comment]
> Oh it was not zoomed in, it says: /usr/lib/jvm/java-8-openjdk-amd64/bin/java

**Comment by dominikaaaa** [comment]
it should be `/usr/bin/java`
