### ISSUE TITLE
Mob Spawn ESP

### ISSUE THREAD

**Issue by MrNutMOO** [ImpactDevelopment/ImpactIssues#2592]
Maybe the devs can add a feature under render called Mob Spawn ESP which highlights the blocks on which mobs can spawn. You should also be able to change between friendly and hostile so you can spawn proof your base easier. As Impact is a utility mod, I feel like that would be a great addition to the client which would save people a lot of effort spawnproofing their base.

**Comment by dominikaaaa** [comment]
this has already been suggested
