### ISSUE TITLE
Change HUD Font

### ISSUE THREAD

**Issue by MeetPing** [ImpactDevelopment/ImpactIssues#2593]
**Is your feature request related to a problem? Please describe.** No.

**Describe the solution you'd like**  Change the font of the Hud as it can only be toggled by the custom font and minecraft font.
i had an idea to be able to change the font to a custom font like OTF or TTF

**Describe alternatives you've considered** Make my own client with my font i choose idk, stupid question.

**Additional context** Maybe Premium feature?

**Comment by dominikaaaa** [comment]
I suggested this 2 years ago
