### ISSUE TITLE
GREEN LINE of auto farm and auto pick up items

### ISSUE THREAD

**Issue by hkal00** [ImpactDevelopment/ImpactIssues#2597]
**Is your feature request related to a problem? Please describe.**

I am currently farming a very large farm using auto farm. But every time I use auto farm, a lot of green lines appear on the screen and the game becomes very very very slow.
 And I can't pick up all the items on the farm, so I can't pick up some items.

**Describe the solution you'd like**

I don't think those green lines are necessary sometimes. So I would like you to add a setting that removes that green line or a setting that sets the transparency of the color. 
And I want you to add a function that auto picks up items near me or sucks them like a magnet.

**Describe alternatives you've considered**

It's the same as above.

**Additional context**

**Comment by dominikaaaa** [comment]
![Screenshot_20200824-110612.png](https://user-images.githubusercontent.com/17222512/91061194-e207c980-e5f9-11ea-9e36-15cfcc520bda.png)
