### ISSUE TITLE
Auto backdoor discord module

### ISSUE THREAD

**Issue by DoctorBang** [ImpactDevelopment/ImpactIssues#2601]
![image](https://user-images.githubusercontent.com/67933806/91620444-95075880-e955-11ea-989f-9de67e2e91e5.png)

Need I say anymore? Best suggestion. Brady should get right to work on it.

**Comment by dominikaaaa** [comment]
what a great suggestion

**Comment by DoctorBang** [comment]
![image](https://user-images.githubusercontent.com/67933806/91622550-3b0a9100-e95d-11ea-9dfb-378966168b50.png)


You heard the man.
