### ISSUE TITLE
MineStrike cheat module not working

### ISSUE THREAD

**Issue by Slhsmile** [ImpactDevelopment/ImpactIssues#2602]
The MineStrike cheat has stopped working, pls fix it. 

Thank you in advance :3

**Comment by dominikaaaa** [comment]
duplicate

**Comment by Slhsmile** [comment]
> duplicate

sry

**Comment by dominikaaaa** [comment]
That's okay, the bug has been reported by like 30 other people. Link to the original: https://github.com/ImpactDevelopment/ImpactIssues/issues/1990

**Comment by Slhsmile** [comment]
> That's okay, the bug has been reported by like 30 other people. Link to the original: https://github.com/ImpactDevelopment/ImpactIssues/issues/1990

and when will it be fixed?

**Comment by dominikaaaa** [comment]
As I said in the original 2 months ago,

> No, there just isn't a milestone so there isn't an ETA
