### ISSUE TITLE
Auto crafting

### ISSUE THREAD

**Issue by Jcp22034** [ImpactDevelopment/ImpactIssues#2603]
Idea: you can go to a crafting table, click an "Autocraft" button on a specified recipe. this would pop up a small menu looking for a specified amount to craft. The client would then calculate how many items are necessary to craft the specified amount. It would craft from your inventory if you had the amount. If you didn't, it would go to storage blocks in a certain (customizable) radius, picking the items it needed out before going back to the crafting table and crafting what the user requested.

**Comment by dominikaaaa** [comment]
this has been suggested 382849299191 times
