### ISSUE TITLE
Wiki Autocheat link leads to self destruct

### ISSUE THREAD

**Issue by boogalewie** [ImpactDevelopment/ImpactIssues#2605]
**Describe the bug**
Wiki Autocheat link leads to self destruct

**To Reproduce**
1. Go to 'https://github.com/ImpactDevelopment/ImpactIssues/wiki'
2. Click on 'AutoCheat'

**Expected behavior**
Would lead to an autocheat page

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by dominikaaaa** [comment]
can reproduce

**Comment by dominikaaaa** [comment]
This is because there is no information for autocheat on the wiki. Use the website: https://impactclient.net/features.html
