### ISSUE TITLE
ClickGUI won't show up

### ISSUE THREAD

**Issue by Supergamer5465** [ImpactDevelopment/ImpactIssues#2607]
**Describe the bug**
When I press right shift I can see my cursor, but nothing else and I can press esc to return to the game. It is like an invisible menu that I cannot interact with. However, I can still use some features without accessing the clickGUI by binding them to specific keys.

**To Reproduce**
1. type ".bind clickgui rshift"
2. press right shift key

**Expected behavior**
The contents of the GUI appear

**Screenshots**
screenshotting is impossible since nothing appears except my cursor

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: any
- Operating System: Crostini

</details>

**Additional context**
I'm running minecraft on a chromebook

**Comment by dominikaaaa** [comment]
yea uh don't

if you really wanna run it on a chromebook, compile the Linux package yourself and enable Linux support without emulators.
