### ISSUE TITLE
Minestrike Hack isnt working anymore

### ISSUE THREAD

**Issue by BerrysHill** [ImpactDevelopment/ImpactIssues#2613]
The minestrike hack no longer works on mineplex, while minestrike item esp still works, the aimbot and colored player esp do not work at all. Is there a reason to this?
![2020-09-05_15 38 04](https://user-images.githubusercontent.com/70821007/92313157-ecc54580-ef8d-11ea-9fc1-f20490624ec6.png)

**Comment by dominikaaaa** [comment]
duplicate
