### ISSUE TITLE
.zip file to the versions folder alternate installment method?

### ISSUE THREAD

**Issue by RealisticLimit1987** [ImpactDevelopment/ImpactIssues#2615]
Is it possible that an alternate installment option using a .zip folder that you extract a folder to .minecraft\versions be added?
I have seen this feature in other utility mods/clients and it makes a good way for a more 'lite' installment method.

**Comment by dominikaaaa** [comment]
> for a more 'lite' installment method.

it's more heavy then the current install system 😐
