### ISSUE TITLE
Impact crashing my game while loading (Multimc)

### ISSUE THREAD

**Issue by Levi783** [ImpactDevelopment/ImpactIssues#2623]
**Describe the bug**
So when i was attempting to launch the game with the hacked client installed with 1.12.2 It crashed Prior to me attempting to launch it I'm not too sure what happened because i dont have much expeirience with hacked clients yet.

**To Reproduce**

**Expected behavior**
What i expected to happen was that i was to have my game load up normally then load into 2b2t where i could use my hacked client.

**Screenshots**

<details> 
So Ive been watching youtubers use hacked clients on 2b2t to y'know hack n stuff so i wanted to do the same and try it for my self, When i launched my game Or tried to it imediantly crashed I installed the latest version of Impact for 1.12.2. Im still not too sure what happened.
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.5
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: None
- Operating System: Windows 10 64bit
</details>

**Additional context**

**Comment by dominikaaaa** [comment]
you need to provide your log
