### ISSUE TITLE
Things ive seen that should be added

### ISSUE THREAD

**Issue by yecabab** [ImpactDevelopment/ImpactIssues#2624]
I was playing on some other clients because there's no impact for 1.13 and I found 2 things that I think should be added to impact the first is
1.fly speed so we can adjust what speed our fly goes
2.I forgot what its called but all it does is as u get to the end of a block you crouch so it also works when u try to speed bridge 

So there's my 2 things that I really hope can be added to the client and the for looking at this suggestion

**Comment by dominikaaaa** [comment]
1. There's a reason there isn't an option
2. Impact has that
