### ISSUE TITLE
Baritone Schematics| so i have been trying to build things using baritone but the thing is i cant find a schematic anywhere and u please give me a website where i can install schematics

### ISSUE THREAD

**Issue by ABRAR-KHALIL-RAHMAN** [ImpactDevelopment/ImpactIssues#2625]
**Is your question request related to a problem? Please describe.**

**Describe what you are trying to achieve**

**Additional context**
Add any other context or screenshots about your question here.

**Comment by dominikaaaa** [comment]
No
