### ISSUE TITLE
fix murder mysteries

### ISSUE THREAD

**Issue by humboldt123** [ImpactDevelopment/ImpactIssues#2627]
I was told for a fast pass use the phrase "Kami Goblin"

https://cdn.discordapp.com/attachments/634010567107149824/756537131425595598/unknown.png

**Comment by ricoip** [comment]
skrub moment

**Comment by DoctorBang** [comment]
Skrub moment

**Comment by sourTaste000** [comment]
skrub moment

**Comment by dominikaaaa** [comment]
duplicate

**Comment by humboldt123** [comment]
![image](https://user-images.githubusercontent.com/38266782/93625944-b685be00-f9b0-11ea-8e8c-563d8b9668ce.png)
