### ISSUE TITLE
I can't interact with the world or move.

### ISSUE THREAD

**Issue by ZWORX52** [ImpactDevelopment/ImpactIssues#2628]
(Kami Goblin)
When I join a single player world with Impact (the version does not matter), I can't move. On my screen when I move or look somewhere else, every second or so (sometimes it's more like 5 minutes) it teleports me back to the starting position and facing. But when my friend looks at me, I'm not moving at all. It lets me move but not interact with the world (kill, break, open inventories, pick up items, move). This only happens with Impact, and reinstalling did not work. I am running v4.9.1 and it seems that only my computer has this problem because my friends are running the same version of Impact and have no problems. I have not found any hacks that might cause my problem, so therefore I think it's a bug.

**Comment by dominikaaaa** [comment]
> so therefore I think it's a bug.

no, it's user error

disable portal god mode

**Comment by ZWORX52** [comment]
Thank you for helping!
