### ISSUE TITLE
Impact Client Download Website Down

### ISSUE THREAD

**Issue by b1vd** [ImpactDevelopment/ImpactIssues#2629]
Whenever I try to Download Impact Client on the java download, the website slowly loads and it is down.
And cannot instill Impact Client.

I go to https://impactclient.net/
And go to the Java download.
I click it and the website loads.
When it does the website is down.
Preventing me from instally it.

I expected to be able to install Impact Client correctly.

![Screen Shot 2020-09-19 at 12 33 46 AM](https://user-images.githubusercontent.com/71539415/93659105-d1d3e600-fa0f-11ea-8a54-817ad662cd32.png)

Please fix this bug or tell me a way to fix this bug.
- IGN: b1vd

**Comment by dominikaaaa** [comment]
Works fine now
