### ISSUE TITLE
Latest version for Mac downloads 4.0

### ISSUE THREAD

**Issue by b1vd** [ImpactDevelopment/ImpactIssues#2630]
When I Install Impact Client It's Outdated, I retry over and over again.

I go to https://impactclient.net/ and instill jar because i'm on mac.
I instill it successfully.
When I open it, it asks me to reinstall it due to it being outdated.
I do, but the same thing happens.

I was expected to be able to use the hacked client without outdated version.

![Screen Shot 2020-09-19 at 10 04 38 AM](https://user-images.githubusercontent.com/71539415/93669105-9234ea80-fa5f-11ea-8363-61047ef5c96a.png)

- IGN: b1vd

**Comment by dominikaaaa** [comment]
What did you select in the installer?

**Comment by berrely** [comment]
Close as stale
