### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by SpencerComputers** [ImpactDevelopment/ImpactIssues#2632]
**Is your feature request related to a problem? Please describe.**
I would like to leave Impact running overnight with AutoMine on, problem is my inventory will of course get full. Only solution to this is to sell the items in your inventory.

**Describe the solution you'd like**
I think an option in the ClickGUI to have an AutoSell would be nice, with variables you can change such as the time interval in which this happens, and perhaps the command that is executed, turning it into not just an AutoSell but instead an AutoChat feature.

**Describe alternatives you've considered**
Only way I can think of is to create a macro of some sort, however I have not looked to closely into this.

**Additional context**
This could be used for Skyblock, Prison and Survival servers to AFK mine.

**Comment by HowAboutIf** [comment]
How stupid are you

**Comment by berrely** [comment]
How stupid are you

**Comment by liquiad** [comment]
shut up

**Comment by BongEatBong** [comment]
Use spammer you simpleton

.help spammer

**Comment by 7-Oaks** [comment]
Please dont use impact on servers where its not allowed.

**Comment by BongEatBong** [comment]
> Please dont use impact on servers where its not allowed.

Nowhere in his post does he indicate that he intends to use Impact anywhere it's not allowed. Not very polite to assume.

**Comment by dominikaaaa** [comment]
Closed as resolved.
