### ISSUE TITLE
HUD GUI renders only numbers and symbols when switched to non TTF font

### ISSUE THREAD

**Issue by LOLYDERP** [ImpactDevelopment/ImpactIssues#2635]
When I uncheck TTF font it doesn't show text, only numbers, and symbols 
![2020-09-21_17 11 39](https://user-images.githubusercontent.com/65100089/93833496-a0386600-fc2d-11ea-8d95-639c0ba26ccd.png)
![2020-09-21_17 12 06](https://user-images.githubusercontent.com/65100089/93833498-a1699300-fc2d-11ea-83a3-d39253276fdf.png)

**Comment by dominikaaaa** [comment]
Fill out the issue template properly

**Comment by berrely** [comment]
Under HUD in the ClickGUI, what options have you changed, have selected, etc. (a screenshot would be useful of the settings)

**Comment by LeafHacker** [comment]
This could be platform specific and/or minecraft version specific. It might also be specific to optifine of forge installs. Could you please specify which of these you're using?

**Comment by CoverageCraft** [comment]
I have been having the same issue for a while now. Still no fix.

**Comment by berrely** [comment]
Close as stale
