### ISSUE TITLE
Special bot backup

### ISSUE THREAD

**Issue by BitorBit1357** [ImpactDevelopment/ImpactIssues#2639]
Add new button in gui/compact "backup"

Only active when:
This command will work if other player is midle click friend and backup is on aloso on.

What does do:
If enemy player goes to the bot:
bot will go away from him and it will call back up bots to kill him together (slider 0.2seconds to 8seconds-how long to wait of an attacking player)
Killaura will be on when thea are attacking.
Bots will first go to cordinates of attacked bot than when bot renders a enemy it will stop going to the cordinates of the bot and it will start attacking player, when attacked bot is full hunger and it sees that bots are attacking enemy, he will attack to.

Buttons : 
compat/backup
compat/backup/checkattack(time)
compat/backup/minhunger(number)
compat/backup/distance(how far from the enemy(min0 to 30(0-number)))
compat/backup/showcalltimer(on/off(it will display delay from compat/backup/checkattack and it will count to 0 than call bots for help))
compat/backup/visible(on/off) <- uk what is it
compat/backup/keybind(key) <- uk what is it

**Comment by DoctorBang** [comment]
oH nO! bArItOnE's GoInG tOo KiLl Us AlL!!!!!

**Comment by BitorBit1357** [comment]
Man i have a big brain

**Comment by BitorBit1357** [comment]
Teamwork is the stronger than just one person, but bots in teamwork, people have no chanse

**Comment by CesiumCs** [comment]
📸

**Comment by dominikaaaa** [comment]
Closed as duplicate

**Comment by BitorBit1357** [comment]
> Closed as duplicate

?

**Comment by dominikaaaa** [comment]
Someone else already suggested this

**Comment by BitorBit1357** [comment]
Did you read good

**Comment by dominikaaaa** [comment]
Yes

# :moyai:

**Comment by BitorBit1357** [comment]
Yes but i said BOTS not PLAYERBOTS, real bots

**Comment by dominikaaaa** [comment]
ok

**Comment by dominikaaaa** [comment]
# :+1:

**Comment by BitorBit1357** [comment]
So technicly nowone else said that

**Comment by dominikaaaa** [comment]
ok
