### ISSUE TITLE
The game failed to load or start

### ISSUE THREAD

**Issue by 3535772662** [ImpactDevelopment/ImpactIssues#2641]
An error log
I'm using the HMCL starter
[debug.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5287929/debug.log)
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5287930/latest.log)

**Comment by berrely** [comment]
By HMCL do you mean https://libraries.io/github/huanghongxun/HMCL/?

**Comment by l1ving** [comment]
Use the official launcher

**Comment by 3535772662** [comment]
> HMCL是指https://libraries.io/github/huanghongxun/HMCL/吗？

 Yes, I looked at the crash log and found a conflict caused by Launchwrapper -1.12

**Comment by l1ving** [comment]
> Use the official launcher
