### ISSUE TITLE
Auto Pick Up items option

### ISSUE THREAD

**Issue by sanikdah** [ImpactDevelopment/ImpactIssues#2644]
**Is your feature request related to a problem? Please describe.**
It very much upsets me when I'm doing something like using Hunt+KA to farm food or using baritone autofarm/mine when i have to manually pause it, go, pick up the items, and then resume.
**Describe the solution you'd like**
Just add an option in either baritone or hack selector settings to have baritone go and pick up the item and then go back to what it was doing.
**Describe alternatives you've considered**
Waiting for the developers of baritone to add that feature even though in their forums they say that they probably never will add it.
**Additional context**
N/A

**Comment by l1ving** [comment]
>  Waiting for the developers of baritone to add that feature even though in their forums they say that they probably never will add it.

You do realize the Baritone and Impact devs are the same people, right?

**Comment by sanikdah** [comment]
no i actually did not know that, thanks for the info and i actually solved it anyways, sorry for your time :(
