### ISSUE TITLE
Add Feature: Mount Bypass

### ISSUE THREAD

**Issue by TheCoolestCoderGuy** [ImpactDevelopment/ImpactIssues#2648]
**Is your feature request related to a problem? Please describe.**
I Have a problem When I'm on a server (Ex: Treemc) They Disable Chest On Donkeys. So I Cannot Move Items On Donkeys

**Describe the solution you'd like**
I've Liked Impact To Add Mount Bypass. It Basically Allows You To Bypass The Server Protection Against Disabled Chests On Donkeys

**Describe alternatives you've considered**
I Have An Alternatives Which Is The Future Client Which has Those Features (Called Automount on future Client). But Future Client Is A Paid Client.

**Additional context**
N/A

**Comment by l1ving** [comment]
Duplicate
