### ISSUE TITLE
2 Modules I want Added

### ISSUE THREAD

**Issue by AfkBranta** [ImpactDevelopment/ImpactIssues#2649]
**Is your feature request related to a problem? Please describe.**
I cannot crystal pvp for shit without hole esp and inventory preview is a luxury

**Describe the solution you'd like**
I would just like to see inventory preview and hole esp (like kami blue) like you know you can move a lil inventory preview box around and see everything in your inventory in the game and hole esp speaks for itself I hope

**Describe alternatives you've considered**
KAMI Blue which I already use anyway because I can't live without hole esp and inventory preview

**Additional context**
Example of inventory preview:
![image](https://user-images.githubusercontent.com/56791945/95025425-aed44380-0657-11eb-8378-ed7de9c040a2.png)

**Comment by berrely** [comment]
Haha imagine hoping a useful feature will be added. 🤣 Good joke

**Comment by AfkBranta** [comment]
> Haha imagine hoping a useful feature will be added. 🤣 Good joke

Haha thanks I know I'm a comdeian

**Comment by l1ving** [comment]
duplicate

**Comment by l1ving** [comment]
I find it absolutely hilarious that you used my screenshot of half broken gui scaling to show the inventory viewer
