### ISSUE TITLE
Franky restraining order

### ISSUE THREAD

**Issue by DoctorBang** [ImpactDevelopment/ImpactIssues#2652]
**Describe the bug**
FRANKY KILLED MY ENTIRE FAMILY BEFORE MY EYES

**To Reproduce**
1. Turn on Franky
2. Watch.

**Expected behavior**
I expected Franky to do exactly what I thought it did, but it did the unexpected.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
No output, only death
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Franky
- Operating System: HaikuOS

</details>

**Comment by LeafHacker** [comment]
This is intended behaviour

**Comment by DoctorBang** [comment]
I see

**Comment by l1ving** [comment]
mfw duplicate of #2646
