### ISSUE TITLE
#farm radius 

### ISSUE THREAD

**Issue by CoolNinja539** [ImpactDevelopment/ImpactIssues#2654]
i would love if you could make it so #farm could only farm a certain area

i want it so you could use #sel or #click to select an area and it would only farm there instead of going somewhere completely different. 

i tried lowering render distance and it didn’t work 

**Additional context**

**Comment by Cergey2202** [comment]
#farm is the Baritone cammand, and you are contacting the Impact cheat developers, you should contact the baritone developers
