### ISSUE TITLE
I can't download impact forge mod

### ISSUE THREAD

**Issue by mine-cart** [ImpactDevelopment/ImpactIssues#2662]
When downloading the file, the installer is unresponsive, and the file size is always 0kb
and my wifi is good
![NZ2UXA%AEZ6HTG2_D2H8GB8](https://user-images.githubusercontent.com/71575638/95654849-7213bb00-0b35-11eb-8fc8-8ca44d221ccf.png)
![W5OG7I%GA~54RVTO$6 8@(S](https://user-images.githubusercontent.com/71575638/95654890-b901b080-0b35-11eb-956d-ff22aacdf22e.png)

**Comment by l1ving** [comment]
Your firewall is blocking it then
