### ISSUE TITLE
Search Shader option not working

### ISSUE THREAD

**Issue by O3nboi** [ImpactDevelopment/ImpactIssues#2663]
**Describe the bug**
In Impact Client, for some reason, if I activate the "Search" hack it automatically deactivates the "shader" option and when it is active I am unable to activate the option
**To Reproduce**
1. Go to the click GUI
2. Click on the render tab
3. Scroll down to search and activate it
4. Try and activate the "shader" option

**Expected behavior**
You would expect the shader box to work like it does in any other hack with the "shader" option, but it is unable to activate

- Impact Version: 4.9.1 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Elytra+, Ridable with step and speed deactivated, Inventory with shulker tooltips, Autototem, criticals, velocity, nofall (Bucket),Autoweapon, Storage ESP, ESP, Anti Desync, Jesus, Light
- Operating System: Windows 10 64bit

**Comment by l1ving** [comment]
get a better computer

**Comment by LeafHacker** [comment]
Possibly optifine related, try without optifine and/or with different optifine settings
