### ISSUE TITLE
crash on Mojang screen 

### ISSUE THREAD

**Issue by goombo** [ImpactDevelopment/ImpactIssues#2667]
so I downloaded impact today and I downloaded it with the windows option. i set it as 4.9_1 and 1.12.2 after I was done with that I went to Minecraft and launched it under that but it keeps freeing and not going past the Mojang loading screen. 

1 download impact on 4.9
2 go to launch on mc launcher 
3 launch

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Copy and paste the appropriate one and fill out the requested information
- [Example bug template](https://gist.githubusercontent.com/l1ving/a0e174c4338cfb043fd674ff27a0a6aa/raw/de031898596cc7e4eb82ab0cc4f3719243f4075b/bug.md)
- [Example suggestion template](https://gist.githubusercontent.com/l1ving/c19a9bf70e7faf4829b0dc0fc2e5f268/raw/7dacde4466dc9c92e5253bdab57f4aec8ff91450/suggestion.md)
- [Example question template](https://gist.githubusercontent.com/l1ving/7f383161eb4fcab96e6c1f439c26d220/raw/f59af220a8ba88fe3535e33316a8b28669d868d4/question.md)
