### ISSUE TITLE
Impact + Liteloader w/Forge Follow up

### ISSUE THREAD

**Issue by BBloom81** [ImpactDevelopment/ImpactIssues#2670]
Trying to follow the below by ZeroMemes from issue 917 but can't for the life of me find the json that needs to be modified.
Found what may be it in \meta\com.mumfrey.liteloader but removing all url lines still has the org folder overwritten.
Suggestions?

EDIT:  If I launch Offline, everything loads fine after deleting org folder, but I'm sure you expect this.

My bad, because LiteLoader is a fat jar, the Mixin version it uses is bundled into the jar itself. Here are the steps to fix:

### 1) Delete the Mixin version from the LiteLoader jar

Delete the "org" folder in the root directory of the LiteLoader jar, it should only contain Mixin so this will be fine. Mine is already deleted.

![image](https://user-images.githubusercontent.com/24485393/52526197-e4eed380-2c7a-11e9-99fb-87880ad29887.png)

### 2) Remove the URL from the LiteLoader JSON

This will prevent the LiteLoader jar from being "fixed" and having the Mixin version restored. Again, mine is already deleted. Below is what it should look like once removed.

![image](https://user-images.githubusercontent.com/24485393/52526233-34cd9a80-2c7b-11e9-9255-e770420ed389.png)

_Originally posted by @ZeroMemes in https://github.com/ImpactDevelopment/ImpactIssues/issue_comments/462078924_

**Comment by l1ving** [comment]
Closed as resolved.

**Comment by BBloom81** [comment]
I know this is "resolved" as far as protocol, but I was hoping you could actually point me to the json file location as well as the lines that need removing.
Sorry for thinking bothering you l1ving, I'll just purchase Future client I guess.

**Comment by l1ving** [comment]
Oh I thought you were posting a solution. The json would be in your versions folder?? I guess?

**Comment by berrely** [comment]
Close as stale
