### ISSUE TITLE
Automouth/autoride

### ISSUE THREAD

**Issue by LavaWord** [ImpactDevelopment/ImpactIssues#2671]
Id like to have autoride/automouth feature added
What is it supposed to do: put you automaticlly on a ridable animal such as lamas donkeys and horses but without you clicking on it. Like upon pressing the chosen key bind or toggling it on you are put on the nearest ridable animal within 2 or 3 Blocks. 
IM requesting it because it is some of the ways dupe items

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by LavaWord** [comment]
> This is a duplicate. Please search before creating an issue next time.

Im sorry but i cant find another suggestion like this one would you link me it

**Comment by l1ving** [comment]
#2277, #2318, #2648. I suggest you learn the difference between mou**nt** and mou**th**
