### ISSUE TITLE
Donator Download

### ISSUE THREAD

**Issue by Dinandpower** [ImpactDevelopment/ImpactIssues#2674]
My Discord has faded away cuz of security issues and ive donated could i get the donator launcher so i can bind it to my discord again thank you

**Comment by CesiumCs** [comment]
if you still have impact premium you can click open dashboard after clicking the impact button in esc

**Comment by l1ving** [comment]
Log into https://impactclient.net. If you donated before the account system, contact a moderator on the discord with proof of donation.
