### ISSUE TITLE
Suggestion add mount bypass

### ISSUE THREAD

**Issue by Darth-Burrito** [ImpactDevelopment/ImpactIssues#2675]
its useful for most dupes

**Comment by l1ving** [comment]
Duplicate. Please learn how to use your eyes next time and find the MAGICAL search bar. It's honestly such a wonderful invention, it allows you to **search** for issues by their contents or even the title of the issue!!

**Comment by l1ving** [comment]
Using the MAGICAL search bar I found 

# #2277, #2318, #2648, #2671

All of which have an **identical** issue title to yours! How amazing!

**Comment by l1ving** [comment]
The issue template you have since deleted also allows developers to know more information about what you're asking. If this was not a duplicate issue I would have NO idea what this issue is describing.
