### ISSUE TITLE
First launch of Impact get stuck, and then crash

### ISSUE THREAD

**Issue by ViktorianoCZ** [ImpactDevelopment/ImpactIssues#2676]
Hello,

When i try to launch Impact from MC launcher for the first time, it gets stuck at "Preparing" after a while it jumps to "Downloading 2.51MB / 5.3 MB" then it crashes with message:

Failed to download file.
Name: Impact-4.9.1-1.15.2.jar
URL: https://github.com/ImpactDevelopment/ImpactReleases/releases/download/4.9.1-1.15.2/Impact-4.9.1-1.15.2.jar
Error details: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out
Filename on disk: Impact-4.9.1-1.15.2.jar
Path: /home/viktor/.minecraft/libraries/com/github/ImpactDevelopment/Impact/4.9.1-1.15.2/Impact-4.9.1-1.15.2.jar
Exists: Nonexistent

I've tried to download this file from github manually and put it into ~/.minecraft/libraries/com/github/ImpactDevelopment/Impact/4.9.1-1.15.2/Impact-4.9.1-1.15.2.jar, but it didn't work.

There's probably some problem with github download page, because when I was downloading it I had to refresh the download site several times before the download began.

I'm running Linux Mint 20  and Java 8 OpenJDK (but the issue is same when i use java 11 OpenJDK) and few months ago when i was trying to download Impact everything was ok.

**Comment by l1ving** [comment]
>  Error details: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out

It's down or your ISP / Firewall or something is blocking it. Try again later, or try a different version.

**Comment by maxid406** [comment]
Just deleting the installation of impact in launcher and executing it again worked for me at least on windows 10,

might work on mint aswell
