### ISSUE TITLE
Blank window on linux

### ISSUE THREAD

**Issue by nonetrix** [ImpactDevelopment/ImpactIssues#2678]
**Describe the bug**
when I try to open the inpact installer with linux it does not display anything in the window

**To Reproduce**
1. install gentoo or one of the really hard ones for fun
2. try to open impact installer

**Expected behavior**
The installer displays a window

**Screenshots**
https://imgur.com/a/t5LOZh7

running form a terminal does not spawn a window for some reason and fails to find a main class(I don't code in java sorry if that is wrong) even though I copy and pasted the path so it should be right

```
Error: Could not find or load main class .home.nonetrix.Downloads.ImpactInstaller-0.9.3.jar
Caused by: java.lang.ClassNotFoundException: /home/nonetrix/Downloads/ImpactInstaller-0/9/3/jar
```

command:
```
java /home/nonetrix/Downloads/ImpactInstaller-0.9.3.jar
```
 

- Impact Version:  1.12.2 0.9.3
- Using Optifine? nah
- Using LiteLoader? no but I'm using mutimc if that's what LiteLoader also is
- Enabled mods: none 
- Operating System: arch linux Xorg xmonadWM nvidia drivers

**Comment by l1ving** [comment]
> install gentoo or one of the really hard ones for fun

User error. Install Openjdk 8

**Comment by CesiumCs** [comment]
you also need to tell java `-jar` if you're going to do it from the terminal
