### ISSUE TITLE
Impact Installer not Working

### ISSUE THREAD

**Issue by GDFrostByte** [ImpactDevelopment/ImpactIssues#2683]
**Describe the bug**
Whenever I try to open the Impact Installer, an error message pops up with the text: could not bind shell folder to interface.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install impact installer
2. Open Impact Installer

**Expected behaviour**
For Impact install to actually work

**Screenshots**

![image](https://user-images.githubusercontent.com/60950885/97356621-ea38eb00-186e-11eb-9bf4-e9f441b32847.png)

**Additional context**
apparently its a known issue

**Comment by l1ving** [comment]
No, it's not a known issue, and if it was then you don't go and make a duplicate issue. Fill out the issue template.

**Comment by l1ving** [comment]
- [Example bug template](https://gist.githubusercontent.com/l1ving/a0e174c4338cfb043fd674ff27a0a6aa/raw/de031898596cc7e4eb82ab0cc4f3719243f4075b/bug.md)
- [Example suggestion template](https://gist.githubusercontent.com/l1ving/c19a9bf70e7faf4829b0dc0fc2e5f268/raw/7dacde4466dc9c92e5253bdab57f4aec8ff91450/suggestion.md)
- [Example question template](https://gist.githubusercontent.com/l1ving/7f383161eb4fcab96e6c1f439c26d220/raw/f59af220a8ba88fe3535e33316a8b28669d868d4/question.md)
