### ISSUE TITLE
Crashes Immediatly

### ISSUE THREAD

**Issue by Robot1337** [ImpactDevelopment/ImpactIssues#2686]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000052246adf, pid=16276, tid=15700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [msvcr100.dll+0x36adf]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x000000001a4a3800):  JavaThread "Swing-Shell" daemon [_thread_in_native, id=15700, stack(0x00000000234e0000,0x00000000235e0000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x0000000000000000

Registers:
RAX=0x0000000000000000, RBX=0x00000000235deda0, RCX=0x0000000000000000, RDX=0x000000001f43d4b0
RSP=0x00000000235ded48, RBP=0x00000000235def50, RSI=0x000000001f697088, RDI=0x000000001a4a39f8
R8 =0x000000001f43d4b0, R9 =0x0000000000000000, R10=0x0000000000000000, R11=0x0000000000000246
R12=0x0000000000000000, R13=0x0000000023211088, R14=0x00000000235def90, R15=0x000000001a4a3800
RIP=0x0000000052246adf, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x00000000235ded48)
0x00000000235ded48:   000000005200a166 0000000000000000
0x00000000235ded58:   000000001a4a39f8 000000001f697088
0x00000000235ded68:   000000001f43d4b0 000000001a4a39f8
0x00000000235ded78:   000000005200ab31 000000001f43d4b0
0x00000000235ded88:   000000001a2f5e00 0000000003417a00
0x00000000235ded98:   00000000d59ae100 0000000000000000
0x00000000235deda8:   0000000000000000 000000001a4a3800
0x00000000235dedb8:   000000005169fe72 0000000000000000
0x00000000235dedc8:   00000000d7a56070 00000000235def08
0x00000000235dedd8:   0000000000000000 0000000000000000
0x00000000235dede8:   0000000003759bb5 000000001764dc20
0x00000000235dedf8:   00000000235dee50 0000000022982008
0x00000000235dee08:   00000000d7a10000 00000000235deec0
0x00000000235dee18:   00000000d59ae858 00000000235dee20
0x00000000235dee28:   0000000017ae67b8 00000000235dee78
0x00000000235dee38:   0000000017ae9528 0000000000000000 

Instructions: (pc=0x0000000052246adf)
0x0000000052246abf:   99 03 00 cc 33 c0 48 8b 5c 24 40 48 8b 74 24 48
0x0000000052246acf:   48 83 c4 30 5f c3 cc cc cc cc cc cc cc 48 8b c1
0x0000000052246adf:   0f b7 10 48 83 c0 02 66 85 d2 75 f4 48 2b c1 48
0x0000000052246aef:   d1 f8 48 ff c8 c3 cc cc cc cc cc cc cc 45 33 c0 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00000000235deda0 is pointing into the stack for thread: 0x000000001a4a3800
RCX=0x0000000000000000 is an unknown value
RDX=0x000000001f43d4b0 is an unknown value
RSP=0x00000000235ded48 is pointing into the stack for thread: 0x000000001a4a3800
RBP=0x00000000235def50 is pointing into the stack for thread: 0x000000001a4a3800
RSI=0x000000001f697088 is an unknown value
RDI=0x000000001a4a39f8 is an unknown value
R8 =0x000000001f43d4b0 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x0000000000000246 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x0000000023211090} 'getDisplayNameOf' '(JJI)Ljava/lang/String;' in 'sun/awt/shell/Win32ShellFolder2'
R14=0x00000000235def90 is pointing into the stack for thread: 0x000000001a4a3800
R15=0x000000001a4a3800 is a thread

Stack: [0x00000000234e0000,0x00000000235e0000],  sp=0x00000000235ded48,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [msvcr100.dll+0x36adf]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.awt.shell.Win32ShellFolder2.getDisplayNameOf(JJI)Ljava/lang/String;+0
j  sun.awt.shell.Win32ShellFolder2.access$1600(JJI)Ljava/lang/String;+4
j  sun.awt.shell.Win32ShellFolder2$13.call()Ljava/lang/String;+15
j  sun.awt.shell.Win32ShellFolder2$13.call()Ljava/lang/Object;+1
j  java.util.concurrent.FutureTask.run()V+42
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run()V+7
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
=>0x000000001a4a3800 JavaThread "Swing-Shell" daemon [_thread_in_native, id=15700, stack(0x00000000234e0000,0x00000000235e0000)]
  0x000000001a4b1800 JavaThread "Image Fetcher 0" daemon [_thread_blocked, id=4812, stack(0x00000000233e0000,0x00000000234e0000)]
  0x000000001a2a0000 JavaThread "D3D Screen Updater" daemon [_thread_blocked, id=4788, stack(0x0000000022dd0000,0x0000000022ed0000)]
  0x000000001a21e000 JavaThread "googleanalyticsjava-thread-1" daemon [_thread_blocked, id=2772, stack(0x0000000022cd0000,0x0000000022dd0000)]
  0x000000001a1a3800 JavaThread "TimerQueue" daemon [_thread_blocked, id=3632, stack(0x0000000022ad0000,0x0000000022bd0000)]
  0x0000000003310800 JavaThread "DestroyJavaVM" [_thread_blocked, id=6220, stack(0x0000000003210000,0x0000000003310000)]
  0x000000001a00f800 JavaThread "AWT-EventQueue-0" [_thread_blocked, id=11244, stack(0x00000000227d0000,0x00000000228d0000)]
  0x000000001a0f5800 JavaThread "ForkJoinPool.commonPool-worker-1" daemon [_thread_blocked, id=15984, stack(0x00000000226d0000,0x00000000227d0000)]
  0x0000000019f17800 JavaThread "AWT-Windows" daemon [_thread_in_native, id=9664, stack(0x000000001aeb0000,0x000000001afb0000)]
  0x0000000019f16800 JavaThread "AWT-Shutdown" [_thread_blocked, id=14452, stack(0x000000001adb0000,0x000000001aeb0000)]
  0x0000000019f14000 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=9196, stack(0x000000001acb0000,0x000000001adb0000)]
  0x0000000019855800 JavaThread "Service Thread" daemon [_thread_blocked, id=15648, stack(0x0000000019c30000,0x0000000019d30000)]
  0x0000000017fc7800 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=9164, stack(0x0000000019730000,0x0000000019830000)]
  0x0000000017fc2800 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=12120, stack(0x0000000019630000,0x0000000019730000)]
  0x0000000017fbc000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=12664, stack(0x0000000019530000,0x0000000019630000)]
  0x0000000017fba800 JavaThread "Attach Listener" daemon [_thread_blocked, id=3512, stack(0x0000000019430000,0x0000000019530000)]
  0x0000000017fb9800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=8528, stack(0x0000000019330000,0x0000000019430000)]
  0x0000000003407000 JavaThread "Finalizer" daemon [_thread_blocked, id=9492, stack(0x0000000019230000,0x0000000019330000)]
  0x00000000033fe000 JavaThread "Reference Handler" daemon [_thread_blocked, id=7044, stack(0x0000000019130000,0x0000000019230000)]

Other Threads:
  0x0000000017f87000 VMThread [stack: 0x0000000019030000,0x0000000019130000] [id=11616]
  0x0000000019858000 WatcherThread [stack: 0x0000000019d30000,0x0000000019e30000] [id=4960]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 38400K, used 8874K [0x00000000d5980000, 0x00000000d8400000, 0x0000000100000000)
  eden space 33280K, 11% used [0x00000000d5980000,0x00000000d5d31540,0x00000000d7a00000)
  from space 5120K, 99% used [0x00000000d7a00000,0x00000000d7ef9650,0x00000000d7f00000)
  to   space 5120K, 0% used [0x00000000d7f00000,0x00000000d7f00000,0x00000000d8400000)
 ParOldGen       total 87552K, used 3345K [0x0000000080c00000, 0x0000000086180000, 0x00000000d5980000)
  object space 87552K, 3% used [0x0000000080c00000,0x0000000080f44658,0x0000000086180000)
 Metaspace       used 19852K, capacity 20196K, committed 20480K, reserved 1067008K
  class space    used 2666K, capacity 2769K, committed 2816K, reserved 1048576K

Card table byte_map: [0x00000000127d0000,0x0000000012bd0000] byte_map_base: 0x00000000123ca000

Marking Bits: (ParMarkBitMap*) 0x0000000051d24040
 Begin Bits: [0x0000000013280000, 0x0000000015250000)
 End Bits:   [0x0000000015250000, 0x0000000017220000)

Polling page: 0x0000000000ff0000

CodeCache: size=245760Kb used=4874Kb max_used=4874Kb free=240885Kb
 bounds [0x0000000003410000, 0x00000000038e0000, 0x0000000012410000]
 total_blobs=2061 nmethods=1496 adapters=478
 compilation: enabled

Compilation events (10 events):
Event: 1.560 Thread 0x0000000017fc7800 1493       3       java.util.concurrent.ThreadPoolExecutor::execute (132 bytes)
Event: 1.561 Thread 0x0000000017fc7800 nmethod 1493 0x00000000038c5150 code [0x00000000038c53a0, 0x00000000038c6388]
Event: 1.561 Thread 0x0000000017fc7800 1494       3       java.util.concurrent.FutureTask::awaitDone (171 bytes)
Event: 1.562 Thread 0x0000000017fc7800 nmethod 1494 0x00000000038c6850 code [0x00000000038c6aa0, 0x00000000038c7948]
Event: 1.562 Thread 0x0000000017fc7800 1492       1       java.awt.image.Raster::getHeight (5 bytes)
Event: 1.562 Thread 0x0000000017fc7800 nmethod 1492 0x00000000038c7f90 code [0x00000000038c80e0, 0x00000000038c81f0]
Event: 1.564 Thread 0x0000000017fc7800 1495       3       javax.swing.UIDefaults$TextAndMnemonicHashMap::get (358 bytes)
Event: 1.568 Thread 0x0000000017fc7800 nmethod 1495 0x00000000038c8250 code [0x00000000038c8cc0, 0x00000000038d0e18]
Event: 1.568 Thread 0x0000000017fc7800 1496       3       javax.swing.DefaultListCellRenderer::firePropertyChange (40 bytes)
Event: 1.568 Thread 0x0000000017fc7800 nmethod 1496 0x00000000038d55d0 code [0x00000000038d5760, 0x00000000038d5af8]

GC Heap History (2 events):
Event: 1.252 GC heap before
{Heap before GC invocations=1 (full 0):
 PSYoungGen      total 38400K, used 33280K [0x00000000d5980000, 0x00000000d8400000, 0x0000000100000000)
  eden space 33280K, 100% used [0x00000000d5980000,0x00000000d7a00000,0x00000000d7a00000)
  from space 5120K, 0% used [0x00000000d7f00000,0x00000000d7f00000,0x00000000d8400000)
  to   space 5120K, 0% used [0x00000000d7a00000,0x00000000d7a00000,0x00000000d7f00000)
 ParOldGen       total 87552K, used 0K [0x0000000080c00000, 0x0000000086180000, 0x00000000d5980000)
  object space 87552K, 0% used [0x0000000080c00000,0x0000000080c00000,0x0000000086180000)
 Metaspace       used 19195K, capacity 19530K, committed 19840K, reserved 1067008K
  class space    used 2535K, capacity 2636K, committed 2688K, reserved 1048576K
Event: 1.263 GC heap after
Heap after GC invocations=1 (full 0):
 PSYoungGen      total 38400K, used 5093K [0x00000000d5980000, 0x00000000d8400000, 0x0000000100000000)
  eden space 33280K, 0% used [0x00000000d5980000,0x00000000d5980000,0x00000000d7a00000)
  from space 5120K, 99% used [0x00000000d7a00000,0x00000000d7ef9650,0x00000000d7f00000)
  to   space 5120K, 0% used [0x00000000d7f00000,0x00000000d7f00000,0x00000000d8400000)
 ParOldGen       total 87552K, used 3345K [0x0000000080c00000, 0x0000000086180000, 0x00000000d5980000)
  object space 87552K, 3% used [0x0000000080c00000,0x0000000080f44658,0x0000000086180000)
 Metaspace       used 19195K, capacity 19530K, committed 19840K, reserved 1067008K
  class space    used 2535K, capacity 2636K, committed 2688K, reserved 1048576K
}

Deoptimization events (10 events):
Event: 0.983 Thread 0x000000001a21e000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x000000000362e754 method=java.lang.CharacterDataLatin1.digit(II)I @ 82
Event: 1.020 Thread 0x000000001a21e000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000003655410 method=java.io.ByteArrayInputStream.read()I @ 8
Event: 1.047 Thread 0x000000001a21e000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000036c21ac method=java.util.concurrent.ConcurrentHashMap.putVal(Ljava/lang/Object;Ljava/lang/Object;Z)Ljava/lang/Object; @ 181
Event: 1.049 Thread 0x000000001a21e000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000036f7654 method=java.util.Arrays.equals([B[B)Z @ 23
Event: 1.339 Thread 0x0000000019f17800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000037bec18 method=java.util.concurrent.ConcurrentHashMap.addCount(JI)V @ 121
Event: 1.373 Thread 0x000000001a00f800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00000000035bca68 method=java.lang.String.equals(Ljava/lang/Object;)Z @ 8
Event: 1.373 Thread 0x000000001a00f800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00000000035bca68 method=java.lang.String.equals(Ljava/lang/Object;)Z @ 8
Event: 1.373 Thread 0x000000001a00f800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00000000035bca68 method=java.lang.String.equals(Ljava/lang/Object;)Z @ 8
Event: 1.373 Thread 0x000000001a00f800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00000000035bca68 method=java.lang.String.equals(Ljava/lang/Object;)Z @ 8
Event: 1.533 Thread 0x000000001a00f800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000038ab854 method=java.util.Hashtable.get(Ljava/lang/Object;)Ljava/lang/Object; @ 48

Internal exceptions (10 events):
Event: 0.808 Thread 0x000000001a0f5800 Exception <a 'java/io/IOException'> (0x00000000d6bffa88) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.808 Thread 0x000000001a0f5800 Exception <a 'java/io/IOException'> (0x00000000d6bffcc0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.808 Thread 0x000000001a0f5800 Exception <a 'java/io/IOException'> (0x00000000d6bffec8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.834 Thread 0x000000001a00f800 Implicit null exception at 0x00000000036fb356 to 0x00000000036fb685
Event: 0.835 Thread 0x000000001a00f800 Implicit null exception at 0x00000000036546d6 to 0x00000000036549f5
Event: 0.837 Thread 0x000000001a00f800 Implicit null exception at 0x0000000003690115 to 0x0000000003690311
Event: 0.837 Thread 0x000000001a00f800 Implicit null exception at 0x00000000037170db to 0x0000000003717551
Event: 0.895 Thread 0x000000001a00f800 Exception <a 'java/io/IOException'> (0x00000000d6e70ba8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.895 Thread 0x000000001a00f800 Exception <a 'java/io/IOException'> (0x00000000d6e70de0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.895 Thread 0x000000001a00f800 Exception <a 'java/io/IOException'> (0x00000000d6e70fe8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 1.399 loading class sun/awt/shell/Win32ShellFolder2$5 done
Event: 1.492 loading class sun/awt/shell/Win32ShellFolder2$18
Event: 1.493 loading class sun/awt/shell/Win32ShellFolder2$18 done
Event: 1.493 loading class sun/awt/shell/Win32ShellFolder2$ColumnComparator$1
Event: 1.493 loading class sun/awt/shell/Win32ShellFolder2$ColumnComparator$1 done
Event: 1.494 loading class sun/awt/shell/Win32ShellFolder2$11
Event: 1.494 loading class sun/awt/shell/Win32ShellFolder2$11 done
Event: 1.533 Thread 0x000000001a00f800 Uncommon trap: trap_request=0xffffff65 fr.pc=0x00000000038ab854
Event: 1.533 Thread 0x000000001a00f800 DEOPT PACKING pc=0x00000000038ab854 sp=0x00000000228cce10
Event: 1.533 Thread 0x000000001a00f800 DEOPT UNPACKING pc=0x000000000345582a sp=0x00000000228ccdc8 mode 2

Dynamic libraries:
0x00007ff660330000 - 0x00007ff660367000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\javaw.exe
0x00007ffc73770000 - 0x00007ffc73966000 	C:\Windows\SYSTEM32\ntdll.dll
0x00007ffc71800000 - 0x00007ffc718bd000 	C:\Windows\System32\KERNEL32.DLL
0x00007ffc71350000 - 0x00007ffc71618000 	C:\Windows\System32\KERNELBASE.dll
0x00007ffc719f0000 - 0x00007ffc71a9c000 	C:\Windows\System32\ADVAPI32.dll
0x00007ffc72780000 - 0x00007ffc7281e000 	C:\Windows\System32\msvcrt.dll
0x00007ffc72600000 - 0x00007ffc7269b000 	C:\Windows\System32\sechost.dll
0x00007ffc734c0000 - 0x00007ffc735e3000 	C:\Windows\System32\RPCRT4.dll
0x00007ffc72030000 - 0x00007ffc721d0000 	C:\Windows\System32\USER32.dll
0x00007ffc717a0000 - 0x00007ffc717c2000 	C:\Windows\System32\win32u.dll
0x00007ffc717d0000 - 0x00007ffc717fa000 	C:\Windows\System32\GDI32.dll
0x00007ffc70f00000 - 0x00007ffc71009000 	C:\Windows\System32\gdi32full.dll
0x00007ffc71700000 - 0x00007ffc7179d000 	C:\Windows\System32\msvcp_win.dll
0x00007ffc71010000 - 0x00007ffc71110000 	C:\Windows\System32\ucrtbase.dll
0x00007ffc61050000 - 0x00007ffc612eb000 	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.488_none_ca04af081b815d21\COMCTL32.dll
0x00007ffc71b20000 - 0x00007ffc71b50000 	C:\Windows\System32\IMM32.DLL
0x0000000052210000 - 0x00000000522e2000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\msvcr100.dll
0x0000000051520000 - 0x0000000051da3000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\server\jvm.dll
0x00007ffc73370000 - 0x00007ffc73378000 	C:\Windows\System32\PSAPI.DLL
0x00007ffc59360000 - 0x00007ffc59369000 	C:\Windows\SYSTEM32\WSOCK32.dll
0x00007ffc6af00000 - 0x00007ffc6af0a000 	C:\Windows\SYSTEM32\VERSION.dll
0x00007ffc59cf0000 - 0x00007ffc59d17000 	C:\Windows\SYSTEM32\WINMM.dll
0x00007ffc729e0000 - 0x00007ffc72a4b000 	C:\Windows\System32\WS2_32.dll
0x0000000052200000 - 0x000000005220f000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\verify.dll
0x00000000521d0000 - 0x00000000521f9000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\java.dll
0x00000000521b0000 - 0x00000000521c6000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\zip.dll
0x00007ffc72a50000 - 0x00007ffc73191000 	C:\Windows\System32\SHELL32.dll
0x00007ffc6ed30000 - 0x00007ffc6f4c5000 	C:\Windows\SYSTEM32\windows.storage.dll
0x00007ffc721d0000 - 0x00007ffc72525000 	C:\Windows\System32\combase.dll
0x00007ffc70920000 - 0x00007ffc7094c000 	C:\Windows\SYSTEM32\Wldp.dll
0x00007ffc732c0000 - 0x00007ffc7336e000 	C:\Windows\System32\SHCORE.dll
0x00007ffc736d0000 - 0x00007ffc73725000 	C:\Windows\System32\shlwapi.dll
0x00007ffc70de0000 - 0x00007ffc70e06000 	C:\Windows\SYSTEM32\profapi.dll
0x00007ffc70870000 - 0x00007ffc70888000 	C:\Windows\SYSTEM32\CRYPTSP.dll
0x00007ffc6ff60000 - 0x00007ffc6ff94000 	C:\Windows\system32\rsaenh.dll
0x00007ffc71620000 - 0x00007ffc71647000 	C:\Windows\System32\bcrypt.dll
0x00007ffc70da0000 - 0x00007ffc70dce000 	C:\Windows\SYSTEM32\USERENV.dll
0x00007ffc71270000 - 0x00007ffc712ef000 	C:\Windows\System32\bcryptprimitives.dll
0x00007ffc70890000 - 0x00007ffc7089c000 	C:\Windows\SYSTEM32\CRYPTBASE.dll
0x0000000052190000 - 0x00000000521aa000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\net.dll
0x00007ffc70650000 - 0x00007ffc706ba000 	C:\Windows\system32\mswsock.dll
0x00007ffc70320000 - 0x00007ffc7035b000 	C:\Windows\SYSTEM32\IPHLPAPI.DLL
0x00007ffc71bb0000 - 0x00007ffc71bb8000 	C:\Windows\System32\NSI.dll
0x00007ffc693b0000 - 0x00007ffc693c7000 	C:\Windows\SYSTEM32\dhcpcsvc6.DLL
0x00007ffc6a290000 - 0x00007ffc6a2ad000 	C:\Windows\SYSTEM32\dhcpcsvc.DLL
0x00007ffc70360000 - 0x00007ffc7042b000 	C:\Windows\SYSTEM32\DNSAPI.dll
0x0000000052170000 - 0x0000000052181000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\nio.dll
0x0000000052140000 - 0x0000000052164000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\sunec.dll
0x0000000051fa0000 - 0x0000000052138000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\awt.dll
0x00007ffc72530000 - 0x00007ffc725fd000 	C:\Windows\System32\OLEAUT32.dll
0x00007ffc6e500000 - 0x00007ffc6e590000 	C:\Windows\SYSTEM32\apphelp.dll
0x00007ffc6e690000 - 0x00007ffc6e72e000 	C:\Windows\system32\uxtheme.dll
0x00007ffc731a0000 - 0x00007ffc732b5000 	C:\Windows\System32\MSCTF.dll
0x00007ffc718c0000 - 0x00007ffc719ea000 	C:\Windows\System32\ole32.dll
0x00007ffc6f7e0000 - 0x00007ffc6f7f2000 	C:\Windows\SYSTEM32\kernel.appcore.dll
0x00007ffc6ea40000 - 0x00007ffc6ea6f000 	C:\Windows\system32\DWMAPI.DLL
0x00007ffc6c090000 - 0x00007ffc6c25e000 	C:\Windows\system32\d3d9.dll
0x00007ffc5cb10000 - 0x00007ffc5cc12000 	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1c83a5d7cffd7bff\nvldumdx.dll
0x00007ffc70aa0000 - 0x00007ffc70ab2000 	C:\Windows\SYSTEM32\msasn1.dll
0x00007ffc6a790000 - 0x00007ffc6a7c1000 	C:\Windows\SYSTEM32\cryptnet.dll
0x00007ffc71110000 - 0x00007ffc7126d000 	C:\Windows\System32\CRYPT32.dll
0x00007ffc712f0000 - 0x00007ffc71350000 	C:\Windows\System32\WINTRUST.DLL
0x00007ffc726a0000 - 0x00007ffc726bd000 	C:\Windows\System32\imagehlp.dll
0x00007ffbfca20000 - 0x00007ffbfe43b000 	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1c83a5d7cffd7bff\nvd3dumx.dll
0x00007ffc6f7b0000 - 0x00007ffc6f7d3000 	C:\Windows\SYSTEM32\gpapi.dll
0x00007ffc5e390000 - 0x00007ffc5e3cb000 	C:\Windows\SYSTEM32\dxcore.dll
0x00007ffc70eb0000 - 0x00007ffc70efe000 	C:\Windows\System32\cfgmgr32.dll
0x00000000514d0000 - 0x0000000051517000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\fontmanager.dll
0x0000000051480000 - 0x00000000514c2000 	C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\t2k.dll
0x00007ffc61a70000 - 0x00007ffc61b6c000 	C:\Windows\SYSTEM32\textinputframework.dll
0x00007ffc6df40000 - 0x00007ffc6e29e000 	C:\Windows\System32\CoreUIComponents.dll
0x00007ffc6e2d0000 - 0x00007ffc6e3c2000 	C:\Windows\System32\CoreMessaging.dll
0x00007ffc6fbf0000 - 0x00007ffc6fc23000 	C:\Windows\SYSTEM32\ntmarta.dll
0x00007ffc6d860000 - 0x00007ffc6d9b6000 	C:\Windows\SYSTEM32\wintypes.dll
0x00007ffc67700000 - 0x00007ffc6770a000 	C:\Windows\System32\rasadhlp.dll
0x00007ffc67720000 - 0x00007ffc6779f000 	C:\Windows\System32\fwpuclnt.dll
0x00007ffc61b90000 - 0x00007ffc61ba7000 	C:\Windows\system32\napinsp.dll
0x00007ffc61b70000 - 0x00007ffc61b8b000 	C:\Windows\system32\pnrpnsp.dll
0x00007ffc61a10000 - 0x00007ffc61a25000 	C:\Windows\system32\wshbth.dll
0x00007ffc6aff0000 - 0x00007ffc6b00d000 	C:\Windows\system32\NLAapi.dll
0x00007ffc61990000 - 0x00007ffc619a2000 	C:\Windows\System32\winrnr.dll
0x00007ffc6b4b0000 - 0x00007ffc6b560000 	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.488_none_4238de57f6b64d28\comctl32.dll
0x00007ffc73410000 - 0x00007ffc734b9000 	C:\Windows\System32\clbcatq.dll
0x00007ffc6c730000 - 0x00007ffc6c827000 	C:\Windows\system32\propsys.dll
0x00007ffc6b220000 - 0x00007ffc6b237000 	C:\Windows\system32\NetworkExplorer.dll
0x00007ffc62730000 - 0x00007ffc628e4000 	C:\Windows\SYSTEM32\WindowsCodecs.dll
0x00007ffc54c20000 - 0x00007ffc54c85000 	C:\Windows\System32\thumbcache.dll
0x00007ffc59590000 - 0x00007ffc595ad000 	C:\Windows\SYSTEM32\MPR.dll
0x00007ffc66f80000 - 0x00007ffc66f8b000 	C:\Windows\System32\drprov.dll
0x00007ffc701b0000 - 0x00007ffc7020a000 	C:\Windows\System32\WINSTA.dll
0x00007ffc60320000 - 0x00007ffc60338000 	C:\Windows\System32\ntlanman.dll
0x00007ffc60300000 - 0x00007ffc6031e000 	C:\Windows\System32\davclnt.dll
0x00007ffc60260000 - 0x00007ffc6026d000 	C:\Windows\System32\DAVHLPR.dll
0x00007ffc70000000 - 0x00007ffc70017000 	C:\Windows\System32\wkscli.dll
0x00007ffc50d30000 - 0x00007ffc50d42000 	C:\Windows\SYSTEM32\cscapi.dll
0x00007ffc70430000 - 0x00007ffc7043c000 	C:\Windows\System32\netutils.dll
0x00007ffc53e30000 - 0x00007ffc53e84000 	C:\Windows\System32\dlnashext.dll
0x00007ffc39d60000 - 0x00007ffc39dc4000 	C:\Windows\System32\PlayToDevice.dll
0x00007ffc65d20000 - 0x00007ffc65d40000 	C:\Windows\System32\DevDispItemProvider.dll
0x00007ffc6b6e0000 - 0x00007ffc6b765000 	C:\Windows\System32\MMDevApi.dll
0x00007ffc70c60000 - 0x00007ffc70c8c000 	C:\Windows\System32\DEVOBJ.dll
0x00007ffc378e0000 - 0x00007ffc37981000 	C:\Windows\system32\wpdshext.dll
0x00007ffc61580000 - 0x00007ffc61726000 	C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.572_none_fae9a23b76193bbb\gdiplus.dll
0x00007ffc59b30000 - 0x00007ffc59bd1000 	C:\Windows\System32\PortableDeviceApi.dll
0x00007ffc71bc0000 - 0x00007ffc72027000 	C:\Windows\System32\SETUPAPI.dll
0x00007ffc595b0000 - 0x00007ffc595e7000 	C:\Windows\System32\EhStorShell.dll
0x00007ffc3feb0000 - 0x00007ffc3fed6000 	C:\Windows\System32\EhStorAPI.dll
0x00007ffc6bbf0000 - 0x00007ffc6bc04000 	C:\Windows\System32\WTSAPI32.dll
0x00007ffc6a220000 - 0x00007ffc6a22d000 	C:\Windows\SYSTEM32\LINKINFO.dll
0x00007ffc6c680000 - 0x00007ffc6c68c000 	C:\Windows\SYSTEM32\Secur32.dll
0x00007ffc70d60000 - 0x00007ffc70d9c000 	C:\Windows\SYSTEM32\SSPICLI.DLL
0x00007ffc65d00000 - 0x00007ffc65d19000 	C:\Windows\SYSTEM32\samcli.dll
0x00007ffc65150000 - 0x00007ffc65174000 	C:\Windows\SYSTEM32\SAMLIB.dll
0x00007ffc6f5a0000 - 0x00007ffc6f784000 	C:\Windows\SYSTEM32\dbghelp.dll

VM Arguments:
java_command: io.github.ImpactDevelopment.installer.Installer
java_class_path (initial): C:\Users\Giovanni\Downloads\ImpactInstaller-0.9.3 (1).exe;lib\installer-0.9.3.jar
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=C:\Program Files\Google\Chrome\Application;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Giovanni\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin
USERNAME=Giovanni
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

I don't know what caused it since I have Java, but here is a crash log.

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 19041 (10.0.19041.546)

CPU:total 4 (4 cores per cpu, 1 threads per core) family 6 model 58 stepping 9, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, aes, clmul, erms, tsc, tscinvbit, tscinv

Memory: 4k page, physical 8333252k(1096904k free), swap 19867588k(4387568k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.51-b03) for windows-amd64 JRE (1.8.0_51-b16), built on Jun  8 2015 18:03:07 by "java_re" with MS VC++ 10.0 (VS2010)

time: Wed Oct 28 16:49:58 2020
elapsed time: 1 seconds (0d 0h 0m 1s)

**Comment by l1ving** [comment]
Use newer Java
