### ISSUE TITLE
Totem pop counter

### ISSUE THREAD

**Issue by ZWORX52** [ImpactDevelopment/ImpactIssues#2688]
**Is your feature request related to a problem? Please describe.**
Whenever I'm crystal pvping, it's almost always hard to keep track of how many totems I've popped on other people.

**Describe the solution you'd like**
Whenever I pop a totem, a counter shows up somewhere (many in chat, the module list, or on the person I popped: if I popped 7 of player IMPACTLOL's totems, on IMPACTLOL's character, there would be something saying: "Totems Popped: 7") The message could be customizable (although it doesn't have to be) and maybe an option to show it wherever you want (maybe the mode of the module, or an option in the module).

**Additional context**
I couldn't find a video about it, but other clients have a feature like this (in chat they say <player> has popped <totems> totems.

**Comment by l1ving** [comment]
duplicate
