### ISSUE TITLE
Freecam sounds

### ISSUE THREAD

**Issue by ZWORX52** [ImpactDevelopment/ImpactIssues#2690]
**Is your feature request related to a problem? Please describe.**
When I use Freecam, I would like it to be that the sounds can be heard from where the Freecam is - maybe an option in the Freecam settings?

**Describe the solution you'd like**
When the option is on, wherever the Freecam is, that is where you hear sounds from.

**Comment by mvrozanti** [comment]
That's how it works today

**Comment by l1ving** [comment]
works for me
