### ISSUE TITLE
AutoXpBottle

### ISSUE THREAD

**Issue by ZWORX52** [ImpactDevelopment/ImpactIssues#2692]
**Describe the solution you'd like**
When activated, it would take Xp bottles from your inventory and/or select them in your hotbar and throw them at your feet until the number of XP bottles set is reached. E.g.: The module is turned on, and it grabs a stack of xp bottles out of your inventory and throws them at your feet until either there are no more xp bottles in your inventory, or the set amount of xp bottles to throw is reached. The main reason I would like this to be a thing is because you could hold your sword while throwing xp bottles (using something similar to how Scaffold places blocks while not selecting blocks, possibly). Or, you could make it so that it automatically activates when your armor durability is low, throwing xp until the set amount of armor durability is reached.

**Describe alternatives you've considered**
You could do it manually using Fast Interact, but it is slow, and you have to hold the xp bottles.

**Comment by l1ving** [comment]
> The main reason I would like this to be a thing is because you could hold your sword while throwing xp bottles

Just use the offhand. I don't see how this is useful otherwise.
