### ISSUE TITLE
Separated reach option in Impact

### ISSUE THREAD

**Issue by p1u70n** [ImpactDevelopment/ImpactIssues#2694]
**Is your feature request related to a problem? Please describe.**
This is about a feature request. I'm frustrated to see that there is not a separate Reach option outside of Kill-Aura. 

**Describe the solution you'd like**
I would like to have the possibility to enable Reach like we can do with Aimbot but only for reach.

**Describe alternatives you've considered**
Add a new option called 'Reach' with options like the size of the reach will be a good idea I think.

**Additional context**
I really hope that this feature request is going to be accepted and to be added to the next update!

Thanks for reading this,
Pluton.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by p1u70n** [comment]
Ok sorry, so is this feature going to be added soon?

**Comment by l1ving** [comment]
#211, #792
