### ISSUE TITLE
retard mode

### ISSUE THREAD

**Issue by CesiumCs** [ImpactDevelopment/ImpactIssues#2695]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when rarts come to #help asking where Xray is or how to open clickgui etc

**Describe the solution you'd like**
Add a Retard Mode enabled by default and can be disabled by smart people that points our very basic but apparently not obvious to everyone features such as the ability to scroll, how to expand modules, a constant reminder of the clickgui bind, and automatically keeps enabled modules in the clipboard for when they inevitable need to visit the help channel

**Describe alternatives you've considered**
staff continue to deal with rarts

**Additional context**
join impactclient.net/discord for hundreds of examples

**Comment by CesiumCs** [comment]
:sob:

**Comment by l1ving** [comment]
It's a decent idea but it would instead drive more people to the help channel ask different things such as "how do I turn off the clickgui reminder" *cough* rusherhack *cough* and "why can't I copy anything with impact opened"

**Comment by DoctorBang** [comment]
Closing this suggestion was short-sighted and disgusting. In order for Impact to grow, it needs to appeal to all groups of people, including those who are mentally challenged. As a result, this mode would be perfect to teach people how to use Impact.

**Comment by DoctorBang** [comment]
> It's a decent idea but it would instead drive more people to the help channel ask different things such as "how do I turn off the clickgui reminder" _cough_ rusherhack _cough_ and "why can't I copy anything with impact opened"

Add a tutorial for the tutorial.

**Comment by elonmusksama** [comment]
I really need to take a shit rn

**Comment by CesiumCs** [comment]
> I really need to take a shit rn

not sure i understand. please go into more detail

**Comment by CesiumCs** [comment]
@elonmusksama pretty please?

**Comment by DoctorBang** [comment]
This could be a serious issue. Good job on taking the initiative to look into it.

**Comment by berrely** [comment]
my shits are of the upmost quality

**Comment by DoctorBang** [comment]
Good to hear. Here at Impact Client(tm) we love satisfied customers.

**Comment by berrely** [comment]
A shit a day keeps the rarts at bay™
