### ISSUE TITLE
Issue with ESP

### ISSUE THREAD

**Issue by terminator-alligator** [ImpactDevelopment/ImpactIssues#2700]
When using ESP with the shade mode turned on
And with the outline mode turned on and also having items enabled 
If an item is dropped on the ground near you it will cause your hand and items held to turn darke

It's just a weird shader bug I imagine it has something to do with OptiFine

Operating system windows
Minecraft version 1.12.2
Impact version 4.9.1
Not using forge

**Comment by berrely** [comment]
Optifine does weird shit. It's a known bug

**Comment by berrely** [comment]
No one really knows why tbh

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
