### ISSUE TITLE
goto stop

### ISSUE THREAD

**Issue by AleReeal** [ImpactDevelopment/ImpactIssues#2703]
When I use the goto command sometimes the player stops before reaching the goal
1) Place a block above the player
2) Write the goto command with its coordinates 
3) See error
When the player is under a block and I give to the command goto a position above it, instead of breaking the block above it, nothing happens

**Comment by berrely** [comment]
Thank you for the detailed bug report with loads of context.

**Comment by AleReeal** [comment]
When I use the goto command sometimes the player stops before reaching the goal
1) Place a block above the player
2) Write the goto command with its coordinates 
3) See error
When the player is under a block and I give to the command goto a position above it, instead of breaking the block above it, nothing happens

**Comment by AleReeal** [comment]
Sorry I press the enter key by accident

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Copy and paste the appropriate one and fill out the requested information
- [Example bug template](https://gist.githubusercontent.com/l1ving/a0e174c4338cfb043fd674ff27a0a6aa/raw/de031898596cc7e4eb82ab0cc4f3719243f4075b/bug.md)
- [Example suggestion template](https://gist.githubusercontent.com/l1ving/c19a9bf70e7faf4829b0dc0fc2e5f268/raw/7dacde4466dc9c92e5253bdab57f4aec8ff91450/suggestion.md)
- [Example question template](https://gist.githubusercontent.com/l1ving/7f383161eb4fcab96e6c1f439c26d220/raw/f59af220a8ba88fe3535e33316a8b28669d868d4/question.md)
