### ISSUE TITLE
goto stops

### ISSUE THREAD

**Issue by AleReeal** [ImpactDevelopment/ImpactIssues#2704]
**Describe the bug**
When I use the goto command sometimes the player stops before reaching the goal

**To Reproduce**
1. Place a block above the player
2. Write the goto command with its coordinates
3. See error

**Expected behavior**
When the player is under a block and I give to the command goto a position above it, instead of breaking the block above it, nothing happends

**Screenshots**
![2020-11-09_10 18 30](https://user-images.githubusercontent.com/74153606/98522532-1b54ea80-2275-11eb-8780-7c89291d96b5.png)
![2020-11-09_10 18 49](https://user-images.githubusercontent.com/74153606/98522577-29a30680-2275-11eb-9280-7ddc050073ee.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
No game output
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
No crash report
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9 for 1.15.2
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods: Killaura, Autoweapon, Autoarmor, Autoeat, Hunt
- Operating System:  Win 10 64 bit

</details>

**Additional context**
No

**Comment by berrely** [comment]
Please open an issue on the [Baritone repo](https://github.com/cabaletta/baritone), as this is unrelated to Impact.
