### ISSUE TITLE
ESP Crash

### ISSUE THREAD

**Issue by 01TheRealShadow** [ImpactDevelopment/ImpactIssues#2706]
Describe the bug
When I load into a world or server my game gets stuck on the loading screen although I can hear the game around me because I have on ESP

To Reproduce
1. Turn on ESP in the menue
2. Click on join a server or world
3. See error

Expected behavior
I expected to be able to join normally but it started last night

Screenshots

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9 for 1.12.2
- Using Optifine? Yes but no shaders
- Using LiteLoader? No
- Enabled mods: Elytra+, Capes, AntiHunger, auto eat, nofall, noslow, no push and auto totem
- Operating System: Windows 10 64Bit

Additional context
it is only ESP that does the crash

**Comment by CesiumCs** [comment]
and you're certain you aren't using something like optifine's internal shaders?

**Comment by 01TheRealShadow** [comment]
I'm not

**Comment by 01TheRealShadow** [comment]
I could double check

**Comment by CesiumCs** [comment]
double check for me? its hard to notice internal shaders

**Comment by 01TheRealShadow** [comment]
ok found the problem it was internal shaders

**Comment by 01TheRealShadow** [comment]
thanks for the help
