### ISSUE TITLE
FPS drop in main GUI.

### ISSUE THREAD

**Issue by alooofficialBD** [ImpactDevelopment/ImpactIssues#2712]
- This is my first time filing a report here, sorry if it does contain any mistakes. 

Anyways, whenever I am on a server and use Impact, I get 27 to 30 fps if I use the main GUI and when I press the F3 button it goes back to my desired fps (60fps)

SCREENSHOT:
![image](https://user-images.githubusercontent.com/20794965/98945898-100af480-24eb-11eb-86d3-3801f2526ead.png)

[Also, I was using optifine here - still having the same issue with other versions too]

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by alooofficialBD** [comment]
> This is a duplicate. Please search before creating an issue next time.

How do I look for the original post?

**Comment by l1ving** [comment]
With the search bar. #915.
