### ISSUE TITLE
Construct chunk view image for world as the player moves around in it

### ISSUE THREAD

**Issue by mvrozanti** [ImpactDevelopment/ImpactIssues#2713]
This could be a useful visual representation to keep track of what chunks the player has been to.

When activated, Impact would write (and eventually append) to a (png?) file on disk

Maybe having some sort of in-game indicator of whether the player has been to that chunk or not could be as useful, but that would make that information not as easily presentable as mentioned above.

**Comment by l1ving** [comment]
JourneyMap already does that, and Baritone already caches the chunks you've been to

**Comment by mvrozanti** [comment]
I did not know about JourneyMap, thanks!

**Comment by mvrozanti** [comment]
It's forge-only though, isn't it? Maybe Impact could do this solo (?)

**Comment by l1ving** [comment]
Yes, that's why I didn't close this

**Comment by mvrozanti** [comment]
I'm surprised this didn't turn out to be a duplicate.

**Comment by l1ving** [comment]
Well I'm pretty sure someone has suggested something similar to journeymap around 3 years ago and it was rejected, but with how much better the radar has gotten I'll leave it open as a replacement
