### ISSUE TITLE
Joining servers crashes the game

### ISSUE THREAD

**Issue by MichelTGM** [ImpactDevelopment/ImpactIssues#2714]
Hi i'm trying join servers on impact 1.12.2 and my game will crash. I have the crash report.
[hs_err_pid35460.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5533347/hs_err_pid35460.log)

**Comment by SourcedCoded** [comment]
If you have optifine on and shaders on. Turning on shader ESP will crash your game, some other features will crash your game because of shaders too.

**Comment by l1ving** [comment]
Fill out the template if that solution doesn't help

**Comment by MichelTGM** [comment]
I turned on shaders, it still crashes

**Comment by SourcedCoded** [comment]
READ what I said again, VERY carefully. 
Turning on shaders with esp or other features will crash your game

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
