### ISSUE TITLE
AntiWorkBench feature

### ISSUE THREAD

**Issue by ifxory-plugins** [ImpactDevelopment/ImpactIssues#2715]
This feature for Grief servers. You can't bypass workbench GUI, and can't throw enderpearl. But what if disable wb gui using cheat? You can throw enderpearl and etc. If you can throw enderpearl you can use bug with doors.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
