### ISSUE TITLE
Autoclicker

### ISSUE THREAD

**Issue by liulihaocai** [ImpactDevelopment/ImpactIssues#2716]
**Describe the bug**
Autoclicker cannot click when open GUI(inventory,ClickGUI)

**To Reproduce**
when i open a gui,it cant click.
version:newest ,impact forge 1.12.2

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
