### ISSUE TITLE
Is Impact A virus? (malware/adware)

### ISSUE THREAD

**Issue by Zerotwo4049** [ImpactDevelopment/ImpactIssues#2718]
So I was just hearing about impact a few days ago in a voice chat with a few people and one of them was using impact while the other said "it's a virus don't use it" so I am not too sure if I can trust it, I've been using the hacked client aristois and I want to take a break from it so I am gonna use Impact but is impact really a virus (malware/adware)

**Comment by CesiumCs** [comment]
impact is safe, even famous 2b2t youtuber feetmc said so!

**Comment by l1ving** [comment]
bruh

**Comment by Zerotwo4049** [comment]
Thanks for the info
