### ISSUE TITLE
PART 2 game will crash when joining servers 1.12.2

### ISSUE THREAD

**Issue by MichelTGM** [ImpactDevelopment/ImpactIssues#2722]
**Describe the bug**
When i join servers my game will crash

**To Reproduce**
1. open Impact 1.12.2
2. Click on Multiplayer
3. Scroll down to a server
4. join server
5. Get Error

**Expected behavior**
supposed to join server and not crash

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1 for 1.12.2
- Using Optifine?  yes/no (happens with both)
- Using LiteLoader?  No
- Enabled mods: nothing
- Operating System:  Windows 10 64bit

</details>

**Additional context**
log will be the file atteched
[hs_err_pid35460.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5556644/hs_err_pid35460.log)
EDIT: Nevermind i fixed it

**Comment by l1ving** [comment]
>  EDIT: Nevermind i fixed it

bruh
