### ISSUE TITLE
Fancy Chat Breaks Ability to Send Commands

### ISSUE THREAD

**Issue by Tomodachi94** [ImpactDevelopment/ImpactIssues#2723]
## Describe the bug
When using the fancy chat feature, when attempting to send vanilla /commands (.impact commands don't have this bug) instead of executing the command, it sends the command to chat.

## To Reproduce
1. Launch Impact (obvious but needed to be said) and load up any old world or server
2. Activate the Fancy Chat utility
3. Attempt to run a vanilla /command
4. See command in chat instead of command executed.

Miscellaneous information
<details>

- Impact Version: 4.9.1 
- Using Optifine? No (formerly was, but problem still occurs without OptiFine) 
- Using LiteLoader? No 
- Enabled mods: Fancy Chat 
- Operating System: Windows 10 64bit with Forge

</details>

**Additional context**
- Using Impact with Forge

Thank you for making Impact!

**Comment by CesiumCs** [comment]
this do be a duplicate issue doe

**Comment by CesiumCs** [comment]
#2531
