### ISSUE TITLE
uuid spoofing for impact client and possible an experimental feature zone for beta testers

### ISSUE THREAD

**Issue by nezh-nl** [ImpactDevelopment/ImpactIssues#2724]
**Is your feature request related to a problem? Please describe.**
Impact client should have more features

**Describe the solution you'd like**
impact client to add things like uuid spoofing, and an experimental feature zone
**Describe alternatives you've considered**
switching to liquid bounce
**Additional context**
![image](https://user-images.githubusercontent.com/64954064/99479101-89459400-2990-11eb-9a21-50c20f71e158.png)

**Comment by l1ving** [comment]
What is this suggestion even supposed to be??

> UUID spoofing

*which* UUID??

> experimental feature zone

what?
