### ISSUE TITLE
Baritone with Build Module

### ISSUE THREAD

**Issue by ZWORX52** [ImpactDevelopment/ImpactIssues#2728]
**Is your feature request related to a problem? Please describe.**
Not really, but this would really help Baritone's auto-building of any kind.

**Describe the solution you'd like**
When Baritone is building anything (e.g.: selections, blocks for pathing, etc.) and a setting (useImpactBuild? allowBuildHack?) is on, it would tell Impact's Build module what block it wants placed and where. This would make selection filling and bridging a lot faster, simpler, and more accurate.

**Describe alternatives you've considered**
Possibly a Build to what baritone wants setting in the Build module (or something similar)?

**Comment by l1ving** [comment]
Can you actually describe what this suggestion would do?

**Comment by ZWORX52** [comment]
Basically let Baritone build in places it would not normally be able to, for example placing a block without looking where it placed the block. So it could place from as far away as possible with build and behind it as well, to save time by not having to go to the place it wants to place the block - it can just get near it and place.

**Comment by l1ving** [comment]
https://github.com/cabaletta/baritone
