### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ty246** [ImpactDevelopment/ImpactIssues#2729]
My minecraft crashes everytime I launch impact. What should I do?
Recording Here: http://www.mediafire.com/file/nmeic1nx5am945w/2020-11-22_15-04-08.mkv/file

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
