### ISSUE TITLE
.goto bug,elytra+

### ISSUE THREAD

**Issue by Jonas19923** [ImpactDevelopment/ImpactIssues#2730]
when you say in the chat .goto and a coord and the goto go against a vine it will bug. and you cant .goto when you ride a horse it will also bug.

on 0b0t.org and 2b2t the elytra + isnt working idk why

**Comment by CesiumCs** [comment]
> on 0b0t.org and 2b2t the elytra + isnt working idk why

elytra is just ruined on 2b, dunno about 0b0t

> you cant .goto when you ride a horse

cabaletta/baritone#616

> when you say in the chat .goto and a coord and the goto go against a vine it will bug

seems like a baritone bug

also you should follow template

**Comment by l1ving** [comment]
this man's seriously reacted to his own issue with :+1:
