### ISSUE TITLE
Can you put out the mod file??

### ISSUE THREAD

**Issue by abc13131412** [ImpactDevelopment/ImpactIssues#2731]
When I click the install,the installer didn't work!!! And give me a fake mod file...(0 KB)

**Comment by abc13131412** [comment]
Maybe GFW blocked that...

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
