### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by keirman** [ImpactDevelopment/ImpactIssues#2733]
**Describe the bug**
when i load the game crashes

**To Reproduce**
Steps to reproduce the behaviour:
1. Go on 'forge impact'
2. walk a block 
3. the game crashes 
4. See error java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j

**Screenshots**
![image](https://user-images.githubusercontent.com/75199250/100536954-13f18300-321c-11eb-950a-0bdce430c979.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
