### ISSUE TITLE
This isn't really a impact related question but imma put it here

### ISSUE THREAD

**Issue by Z3R0-cmd** [ImpactDevelopment/ImpactIssues#2736]
I'm making a client with ur clientAPI, And I have run into some problems. For some reason I can't join your server to ask people on there, Please either unban me (Z3R0#5139) or just give me some advice on exporting my clientAPI client. (I have some issue being able to have the clientapi library imported or something, msg me on discord for more info (Z3R0#5139)

**Comment by l1ving** [comment]
Unrelated to Impact.

**Comment by Z3R0-cmd** [comment]
Where should I ask then? :/

**Comment by CesiumCs** [comment]
the repo for whatever client api probably

**Comment by Z3R0-cmd** [comment]
@CesiumCs its archived so I cannot.
