### ISSUE TITLE
Question regarding the version 1.16 Impact release

### ISSUE THREAD

**Issue by beskhu3epnm** [ImpactDevelopment/ImpactIssues#2738]
**Is your question request related to a problem? Please describe.**
When is Impact for 1.16 set to be released? I assumed it would drop months ago when 1.16 arrived. I went to the effort of joining the Discord (involved filling out a CAPTCHA and granting Discord extra permissions to use my account), and politely asked if Impact 1.16 was coming soon. Someone asked me to click an FAQ link, which actually just kicked me from the Discord and I'm unable to rejoin.

There is no information on the official Impact client site about the 1.16 release, no contact email, and the official Twitter has zero tweets.

**Comment by l1ving** [comment]
no

**Comment by l1ving** [comment]
just wait for it to be released

**Comment by beskhu3epnm** [comment]
You fuckers are toxic.

**Comment by l1ving** [comment]
And you're impatient.
