### ISSUE TITLE
cant install impact

### ISSUE THREAD

**Issue by VATTERTe** [ImpactDevelopment/ImpactIssues#2742]
**Describe the bug**
I cant install it from the website it says it either has been moved or removed
**To Reproduce**
1. Go to https://impactclient.net/
2. Click on download java/windows version
3. See error

**Expected behavior**
it is expected to get send to the problem and not work

**Screenshots**
it is not appliable

**Additional context**
try to do it and fix it if you can please send me a direct link

**Comment by l1ving** [comment]
https://impactclient.net/?brady-money-grubbing-completed=true&platform=exe
