### ISSUE TITLE
I cant download the client 

### ISSUE THREAD

**Issue by Ianlee07** [ImpactDevelopment/ImpactIssues#2746]
Hello, I have a problem, when I enter the official impact client page and I want to download the jar or windows it does not let me and it keeps loading and in the end google me.  It gives an error, but if I have a good Internet connection

**Comment by BlueBurgersTDD** [comment]
Download it here
[.jar file](https://impactclient.net/?brady-money-grubbing-completed=true&platform=jar)
[.exe file](https://impactclient.net/?brady-money-grubbing-completed=true&platform=exe)
