### ISSUE TITLE
Multiple selections in Build

### ISSUE THREAD

**Issue by ZWORX52** [ImpactDevelopment/ImpactIssues#2747]
**Is your feature request related to a problem? Please describe.**
Not really, but this would make Build a lot more useful.

**Describe the solution you'd like**
Capability to create multiple selections in Build, like Baritones #sel command.

**Describe alternatives you've considered**
I guess you could make a queue of selections instead of all at once, like do this (predefined) selection, then this one, etc.

**Comment by l1ving** [comment]
1. wrong repository
2. already suggested
