### ISSUE TITLE
Custom Presets

### ISSUE THREAD

**Issue by rxversedcode** [ImpactDevelopment/ImpactIssues#2749]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Maybe a thing that you can save a preset of hacks like if you want custom presets for one server you can toggle it on and you can customize it and save it as another thing.

**Describe alternatives you've considered**
I don’t know.

**Additional context**
I don’t know.

**Comment by rxversedcode** [comment]
What i’m trying to say is that you can toggle a preset for a server and you can customize the preset because some anti cheats can detect what hacks your using like Velocity or Flight, so if you want custom settings to have maybe for example velocity chances is 30 percent or something.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
