### ISSUE TITLE
When ever I turn on almost anything under "HUD" My game crashes on 1.12.2

### ISSUE THREAD

**Issue by MichelTGM** [ImpactDevelopment/ImpactIssues#2750]
**Describe the bug**
The title says it

**To Reproduce**
1. Go to the click GUI
2. Click on Hud
3. Scroll down to any setting

**Expected behavior**
The game doesn't crash and i can play

**Screenshots**
I can't

 

 

- Impact Version: <4.9.1 for 1.12.2>
- Using Optifine? <Yes>
- Using LiteLoader? <No>
- Enabled mods: <Just HUD>
- Operating System: <Windows 10 64bit>

**Additional context**

**Comment by l1ving** [comment]
If you're not going to include any basic troubleshooting information or logs, ask for help on the discord

https://impactclient.net/discord.html
