### ISSUE TITLE
not all knife skins work with the murder minigame hack

### ISSUE THREAD

**Issue by ofri30** [ImpactDevelopment/ImpactIssues#2751]
not really a bug more like an issue but not all the knife skins with the murder hack because some are not weapens so here is all the knife skins

![image](https://user-images.githubusercontent.com/75720564/101599488-858eb580-3a02-11eb-9c1f-7412c24b1667.png)

![image](https://user-images.githubusercontent.com/75720564/101599598-ad7e1900-3a02-11eb-85d6-5be85c27a323.png)

**Comment by l1ving** [comment]
# 🗿
