### ISSUE TITLE
Scaffold Bot Slab

### ISSUE THREAD

**Issue by RlKirbywastaken** [ImpactDevelopment/ImpactIssues#2752]
It wastes so many slabs while scaffold bot on it makes normal blocks from scaffold bot
 

- Impact Version: 1.15.2
- Using Optifine?  yes
- Using LiteLoader?  no
- Enabled mods: scaffold
- Operating System: <!-- e.g. "Windows 10 64bit" or "Fedora 24" Windows 10

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
