### ISSUE TITLE
Impact freezes after joining a server

### ISSUE THREAD

**Issue by Piotrmal** [ImpactDevelopment/ImpactIssues#2753]
When I start up minecraft everything is fine but when after I join a server screen freezes and I can't do anything. Now the same is happening when I try join a server without Impact. I don't know what happened beacuse Impact was working correctly for the last two days.

**Expected behavior**
Impact shouldn't freezes and should work as before

 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Crash report was not generated.
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9.1 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: none
- Operating System: Windows 64bit

</details>

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)

**Comment by CesiumCs** [comment]
shaders
either turn off esp or turn off optifine shader

**Comment by Piotrmal** [comment]
> 
> 
> shaders
> either turn off esp or turn off optifine shader

I'm not using shaders
