### ISSUE TITLE
Impact freezes after joining a server

### ISSUE THREAD

**Issue by Piotrmal** [ImpactDevelopment/ImpactIssues#2755]
**Describe the bug**
When I start up minecraft everything is fine but when after I join a server screen freezes and I can't do anything. Now the same is happening when I try join a server without Impact. I don't know what happened beacuse Impact was working correctly for the last two days.

**To Reproduce**

**Expected behavior**
Impact shouldn't freezes and should work as before

<details> 
  <summary><strong>Game output</strong></summary>
 
</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Crash report was not generated.
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: none
- Operating System: Windows 10 64bit

</details>

**Comment by l1ving** [comment]
Closing, bug report incomplete
