### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by BLUELIGHTTIGER** [ImpactDevelopment/ImpactIssues#2757]
**Is your feature request related to a problem? Please describe.**
@0-x-2-2 bring some codes from your client XD
And add stash finder also please fix aim bot,
Fix nametags and add nameprotect.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CesiumCs** [comment]
did you make this just to ping 0x

> Fix aim bot

care to say whats wrong with it

> Fix nametags

care to say whats wrong with it

**Comment by l1ving** [comment]
> some codes

grammers

**Comment by BLUELIGHTTIGER** [comment]
Ok i dont care about grammers cau it not my first language i dont care about grammers of this 2nd language. @l1ving

**Comment by l1ving** [comment]
Did you try reading any of the other comments?? You didn't even follow the template

**Comment by l1ving** [comment]
Make a new issue with the requested information from Cesium, and the issue template filled in.
