### ISSUE TITLE
Impact crashing

### ISSUE THREAD

**Issue by MinusZaxis** [ImpactDevelopment/ImpactIssues#2758]
For some reason impact (forge ver) crashes my game and says:
"An unexpected issue occured and the game has crashed" with the exit code 0
I have removed all the mods one by one and impact is the one crashing. I have used impact before and now it doesnt work

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)

**Comment by CesiumCs** [comment]
the only information you gave us was
* forge version
* crashes with code 0
* multiple other mods

what do you expect anyone to do with so little information? "oh sorry we must have forgotten to disable the crash every time you try to play setting, we'll disable that for you"
