### ISSUE TITLE
Automatic Potion Drinking (Invisibility, Swiftness)

### ISSUE THREAD

**Issue by OnurAkinn** [ImpactDevelopment/ImpactIssues#2761]
**Is your feature request related to a problem? Please describe.**
I auto lapis on the Faction server. However, the actors take my picture and report it to the managers. That's why I'm banned all the time.

**Describe the solution you'd like**
I also want to drink Invisibility and Swiftness potions every 3 minutes while auto-mining. Because my name will not appear. The actors can't take my photo and ban me.

**Describe alternatives you've considered**
With the command "#autopot invisibility", let's add the potions we want to the bot and drink it until it's finished in our inventory.

**Comment by l1ving** [comment]
#1424, #429

**Comment by OnurAkinn** [comment]
@l1ving 
links have no valid solution

**Comment by l1ving** [comment]
This was a suggestion
