### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by prototype01001** [ImpactDevelopment/ImpactIssues#2762]
The game crashed whilst mouseclicked event handler
Error: java.lang.StackOverflowError: mouseClicked event handler
Codice di uscita: -1
 

if you go to created by Brady ... and then click done it crashes the game

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
