### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by dsaads** [ImpactDevelopment/ImpactIssues#2765]
**Describe the bug**
Just downloaded the client and i insta crash after opening the profile for impact 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/52396930/102587607-01eb5d80-40c1-11eb-8538-90060811bb50.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by AverageComet250** [comment]
Can you please add the info at the bottom (Additional Client Info).

This is needed to find out if the error is a comparability issue.

**Comment by donteatapples** [comment]
I have the same issue on a Mac on 1.12.2 no OptiFine and with the new nightly build of impact

**Comment by l1ving** [comment]
Closing, invalid, missing crucial information.
