### ISSUE TITLE
clicking impact then done crashes

### ISSUE THREAD

**Issue by ehylo** [ImpactDevelopment/ImpactIssues#2766]
**Describe the bug**
clicking impact at the main menu then done crashes the game
**To Reproduce**
launch impact 
at the main menu click the button labeled "impact"
Click the done button
experience the crash

**Expected behavior**
it would bring me back to the main menu

mmc log https://paste.ee/p/3rnML

- Impact Version: < first nightly  for 1.16.4 >
- Using Optifine? < No >
- Using LiteLoader? < No >
- Enabled mods: < none >
- Operating System: <win 10 pro>

**Comment by l1ving** [comment]
Duplicate.

**Comment by ehylo** [comment]
see is searched for this and couldn't find it, would be helpful if you linked or said the original issue so I can go there and watch it

**Comment by l1ving** [comment]
#2772

**Comment by l1ving** [comment]
Sorry, didn't mean to reopen. That one is newer but has more info than the others
