### ISSUE TITLE
Biome HUD is broken

### ISSUE THREAD

**Issue by Teenkung123** [ImpactDevelopment/ImpactIssues#2768]
![20201218_175741](https://user-images.githubusercontent.com/51858378/102609361-e71af680-415d-11eb-923f-7c5e6f5e5a24.png)
It broken
real minecraft Biome what im in : basalt-deltas
biome what impact HUD show : bsv@6c7ef2ee 
[edit]
it happen to all biome

**Comment by l1ving** [comment]
Closing, invalid. 

Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
