### ISSUE TITLE
Impact crashes when lauching minecraft

### ISSUE THREAD

**Issue by Tiutau** [ImpactDevelopment/ImpactIssues#2770]
i have played with impact a while and today when i tried to play with it it just crashes when trying to get to the minecraft the error message is this Error: java.lang.NullPointerException: Unexpected error Exit Code: -1
can someone help???

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
