### ISSUE TITLE
[1.16.4 Nightly] Clicking credits button causes a crash

### ISSUE THREAD

**Issue by SoNothingMC** [ImpactDevelopment/ImpactIssues#2772]
**Describe the bug**
Clicking the `Created by Brady, LeafHacker, and leijurv.` text on the main title screen crashes Impact.

**To Reproduce**
Case A
1. Click on `Created by Brady, LeafHacker, and leijurv.` in the Main Menu
2. Crashes

Case B
1. Click on `Created by Brady, LeafHacker, and leijurv.` in the Main Menu
2. Click the `Done` button
3. Crashes

**Expected behavior**
Case A: The credits screen is shown.
Case B: The title screen/main menu is shown.

**Screenshots**
N/A

<details> 
  <summary><strong>Game output</strong></summary>
 
View on [Pastebin](https://pastebin.com/xUkW1qgp)

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

View on [Pastebin](https://pastebin.com/M0UkDCi9)

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly-20201218 for 1.16.4 
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods: Main Menu with `Custom` enabled 
- Operating System: Windows 10 Pro 64bit, version 20H2 (build 19042.685) 

</details>

**Additional context**
The credit screen flashes for a second before the crash.

**Comment by CesiumCs** [comment]
fixed in newer nightly
