### ISSUE TITLE
 [1.16.4 Nightly] Clicking Alts button causes a crash

### ISSUE THREAD

**Issue by SoNothingMC** [ImpactDevelopment/ImpactIssues#2773]
**Describe the bug**
Clicking the `Alts` button on the main title screen crashes Impact.

**To Reproduce**
1. Click on `Alts` in the Main Menu
2. Crashes

**Expected behavior**
The alt selector is shown.

**Screenshots**
N/A

<details> 
  <summary><strong>Game output</strong></summary>
 
View on [Pastebin](https://pastebin.com/xiuMbMdC)

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

View on [Pastebin](https://pastebin.com/Py8iZXy9)

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly-20201218 for 1.16.4 
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods: N/A 
- Operating System: Windows 10 Pro 64bit, version 20H2 (build 19042.685) 

</details>

**Additional context**
The `Saving world...` screen is shown before the crash, presumably because Minecraft is panic-saving before crashing.

**Comment by CesiumCs** [comment]
fixed in newer nightly
