### ISSUE TITLE
[1.16.4 Nightly] Clicking any button within Impact menu causes a crash

### ISSUE THREAD

**Issue by SoNothingMC** [ImpactDevelopment/ImpactIssues#2774]
> Well, the ~~years~~ crashes start coming and they don't stop coming

**Describe the bug**
Clicking any button inside the Impact menu crashes Impact

**To Reproduce**
1. Click on `Impact` in the Main Menu
2. Click any button
3. Crashes

**Expected behavior**
The respective menu is shown.

*These outputs/reports are after clicking the "Done" button.*
<details> 
  <summary><strong>Game output</strong></summary>
 
View on [Pastebin](https://pastebin.com/S7p0Fjiw)

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

View on [Pastebin](https://pastebin.com/UgEp4L6p)

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly-20201218 for 1.16.4 
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods: N/A 
- Operating System: Windows 10 Pro 64bit, version 20H2 (build 19042.685) 

</details>

**Additional context**
N/A

**Comment by SoNothingMC** [comment]
oops shift+entered the issue - closing for now

**Comment by CesiumCs** [comment]
sorry for the notification spam but... fixed in newer nightly
