### ISSUE TITLE
[1.16.4 Nightly] Misaligned Impact account email

### ISSUE THREAD

**Issue by SoNothingMC** [ImpactDevelopment/ImpactIssues#2775]
**Describe the bug**
The account email in the Impact menu is misaligned.

**To Reproduce**
1. Click the Impact button in the main menu
2. See error

**Expected behavior**
A correctly represented email address is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/32032824/102640103-f23d4900-4194-11eb-979c-71d43b8bb76d.png)
*nightly-20201218*

![image](https://user-images.githubusercontent.com/32032824/102640289-3597b780-4195-11eb-8ec1-f3f8a70f0a94.png)
*4.9.1*

<details> 
  <summary><strong>Game output</strong></summary>
 
View on [Pastebin](https://pastebin.com/7uxTC9Dg)

</details>

*Crash report not generated*

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly-20201218 for 1.16.4
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods: N/A 
- Operating System: Windows 10 Pro 64bit, version 20H2 (build 19042.685) 

</details>

**Additional context**
Clicking the "Open Dashboard" button crashes Impact (#2774)

**Comment by CesiumCs** [comment]
fixed in newer nightly
