### ISSUE TITLE
[1.16.4 Nightly] No Impact Button in Game

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [ImpactDevelopment/ImpactIssues#2776]
No Impact button when in game and you press escape

1. press escape
2. no button

Should show a button

https://postimg.cc/3dB8cYdf

<details> 
  <summary><strong>Game output</strong></summary>
 

```
No Crash
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
No Crash
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  nightly-20201218 for 1.16.4 
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  Doesn't really apply
- Operating System:  Windows 10 64bit

</details>

**Additional context**
I have tried pressing shift, it doesnt show up, but the steal button on chests does

**Comment by berrely** [comment]
![](https://i.postimg.cc/MpknXGxw/2020-12-18-12-04-15.png)

Transcluded image

**Comment by berrely** [comment]
Are you sure you haven't accidentally hidden it by pressing `lshift`?

**Comment by CesiumCs** [comment]
fixed in newer nightly
