### ISSUE TITLE
[1.16.4 Nightly] Clickgui does not close

### ISSUE THREAD

**Issue by Fakeaccount12312** [ImpactDevelopment/ImpactIssues#2777]
**Describe the bug**
The clickgui does not close after pressing right shift or disabling it manually, it is only displayed as not active.

https://user-images.githubusercontent.com/64163394/102651035-17699180-416c-11eb-9dbd-b68d641dcd59.mp4

**To Reproduce**
1. Open the clickgui
2. Disable the clikgui module

**Expected behavior**
Clickgui closes

<summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly-20201218 for 1.16.4 
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Clickgui and Main Menu which cannot be disabled
- Operating System: Windows 10 64bit

**Additional context**
I can only close it with ESC

**Comment by CesiumCs** [comment]
fixed in newer nightly
