### ISSUE TITLE
FOV lock

### ISSUE THREAD

**Issue by Scoob1113** [ImpactDevelopment/ImpactIssues#2780]
I'm always frustrated when I sprint and stop, my fov goes crazy, jumping from my normal 90 to like 110 and I hate it, especially with speed 2 or more, the jerking between FOV is crazy to me.
Could you guys code in a fov lock that never changes your fov no matter sprinting or speed or anything? I know other non-hacked clients have that feature.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
