### ISSUE TITLE
impact wont load

### ISSUE THREAD

**Issue by iamABOI** [ImpactDevelopment/ImpactIssues#2781]
when i load impact it just says

 the game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: -1

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
