### ISSUE TITLE
doesnt even load

### ISSUE THREAD

**Issue by ody007gr** [ImpactDevelopment/ImpactIssues#2782]
when i try to lauch it it instantly closes and brings me back to the minecraft laucher with error 
![2020-12-19](https://user-images.githubusercontent.com/76242569/102684123-91d2f980-41de-11eb-8609-4d338dcd5a86.png)
i have the 1.15.2 and the 1.16.2 and they do the same thing

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
