### ISSUE TITLE
air jump doesn’t work in 1.16.4

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2783]
**Describe the bug**
In the new nightly bulid of 1.16.4 air jump just doesn't work.
**To Reproduce**
1. Go to 1.16.4 impact nightly
2. Click on right shift
3. Scroll down to air jump and turn it on
4. Try air jumping and see bug

**Expected behavior**
Jump in the air
**Screenshots**
N/A
<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: latest nightly 1.16.4
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods: 
- Operating System: 
Windows 10 64bit

</details>

**Additional context**

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
