### ISSUE TITLE
Biome type in top left hand corner doesn’t work

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/ImpactIssues#2784]
**Describe the bug**
Instead of showing the biome it says like 1536B@56 in nightly 1.16.4
**To Reproduce**
1. Go to impact nightly 1.16.4
2. Activate biome type
3. See error

**Expected behavior**
Show what biome type your in.
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: latest nightly 1.16.4
- Using Optifine?  No
- Using LiteLoader?  No
- Operating System: 
Windows 10 64bit
</details>

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
