### ISSUE TITLE
[INSTALLER] Optifine Null Error

### ISSUE THREAD

**Issue by reidlabwastaken** [ImpactDevelopment/ImpactIssues#2786]
Edit: 1.16.4
**Describe the bug**
When installing Optifine Impact, null error.

**To Reproduce**
1. Click install for 'Optifine'
2. Click install.
3. Null error appears.
![image](https://user-images.githubusercontent.com/45904911/102699962-ea65bf00-41fd-11eb-8c60-39f1248ec8c1.png)

**Expected behavior**
Installs cleanly with optifine.

**Comment by l1ving** [comment]
Missing logs, fill in the template and reopen.

**Comment by SoNothingMC** [comment]
Please use Installer 0.8.6
