### ISSUE TITLE
How to use .rename command

### ISSUE THREAD

**Issue by BLUELIGHTTIGER** [ImpactDevelopment/ImpactIssues#2788]
**Is your question request related to a problem? Please describe.**
@l1ving Please tell me what .rename do and how to use it?

I have 
**Describe what you are trying to achieve**
I want to know what .rename command do and how to use it
**Additional context**
Add any other context or screenshots about your question here.

**Comment by BLUELIGHTTIGER** [comment]
Also i forgot to mention that when i do 
Ex: .rename noob 
It say you name should identical to last one in case of sensetive.

**Comment by l1ving** [comment]
Fill out the issue template properly

**Comment by l1ving** [comment]
Oh. well I misread this as a suggestion, on mobile. 

`.help rename`

General support should be done on the discord at https://impactclient.net/discord
