### ISSUE TITLE
Help for .rename command

### ISSUE THREAD

**Issue by BLUELIGHTTIGER** [ImpactDevelopment/ImpactIssues#2789]
**Is your question request related to a problem? Please describe.**
Please tell me what .rename do and how to use it? Also  @l1ving   stop deleting my issues.and buy the way i use .help rename but this was not enough.
Curiosity to know what  .rename command do

**Describe what you are trying to achieve**
When i use EX: .rename setup , error pop in chat 
Your new name should identical to last one in case of sensetive.

**Additional context**
Add any other context or screenshots about your question here.
I dont have screen shot right now.

**Comment by l1ving** [comment]
I said general troubleshooting should be done on the discord if you don't want to provide the requested information.

**Comment by BLUELIGHTTIGER** [comment]
Are you serious you again close my post wait maybe player will help me
 And i dont have discord account I will make

**Comment by BLUELIGHTTIGER** [comment]
Stop @l1ving

**Comment by BLUELIGHTTIGER** [comment]
Stop closing my comments maybe player will help me out
