### ISSUE TITLE
Impact And Alts button crashes your game

### ISSUE THREAD

**Issue by Salihius2** [ImpactDevelopment/ImpactIssues#2793]
**Describe the bug**
Game Crashes when you press Impact/Alts button on main menu

Crash message:
The game crashed whilst mouseclicked event handler
Error: java.lang.StackOverflowError: mouseClicked event handler
Exit Code: -1

- Impact Version: 1.16.4-Impact_nightly-20201218
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Main Menu
- Operating System: Windows 10 64 Bit English

**Additional context**
When you use "Alts" button on the main menu (just click it), Game crashes.

When you use Impact button on the Main Menu its working but. Anything on that menu will crash your game if you click them.

[crash-2020-12-20_23.04.11-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/5721435/crash-2020-12-20_23.04.11-client.txt)

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
