### ISSUE TITLE
[BUG] Alts don't work on 1.16.4

### ISSUE THREAD

**Issue by QuacktasticDev** [ImpactDevelopment/ImpactIssues#2795]
**The Bug**
It's just when I go to the menu, I press alts, and the magic happens there, it crashes. Not only I have this problem, but also everyone who has 1.16.4 Nightly.

**To Reproduce**
1. Launch Impact 1.1.6.4 (Nightly)
2. Click on alts.
3. Boom, crashes right there.

**Expected behavior**
I expected it to go to the alts screen right away.

**Game Output**
```
The game crashed whilst mouseclicked event handler
Error: java.lang.ExceptionInInitializerError
Exit Code: 1```

**Additional Information**
- Impact Version: 1.16.4 Premium
- Using Optifine? Yes
- Using LiteLoader? I don't know what that is so, no.
- Enabled mods: It's just at the main menu, not in-game.
- Operating System: Windows 10 64bit

**Additional context**
When I click on alts in the main menu, it just freezes, says "Saving World" and crashes right away, I don't know what it is saving because this is in the main menu, but this is a weird bug for sure.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
