### ISSUE TITLE
[1.16.4 Nightly] Game Crashes When Launched

### ISSUE THREAD

**Issue by MichelTGM** [ImpactDevelopment/ImpactIssues#2796]
**Describe the bug**
When I Launch The Game The Game Will Crash

**To Reproduce**
1. Go to 'Minecraft Launcher'
2. Click on 'Impact 1.16.4 Nightly'
3. Scroll down to 'Play'

**Expected behavior**
The Game To Launch

**Screenshots**
i can not provide screenshots

 

- Impact Version: <Nightly 1.16.4>
- Using Optifine? <No>
- Using LiteLoader? <No>
- Enabled mods: <No Mods>
- Operating System: <Windows 10 64bit>

[hs_err_pid11728.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5726739/hs_err_pid11728.log)

**Additional context**

**Comment by l1ving** [comment]
Use a donator account.
