### ISSUE TITLE
impact crashes when chosing what xray picks up

### ISSUE THREAD

**Issue by jumpchief** [ImpactDevelopment/ImpactIssues#2799]
impact crashes when chosing what xray picks up. when configuring the impact xray it give crash report: The game crashed whilst mouseclicked event handler
Error: java.lang.StackOverflowError: mouseClicked event handler
Exit Code: -1

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
