### ISSUE TITLE
[1.16.4 Nightly] Baritone goes back and forth from it's mine choices, without mining it's first target if enough of it is nearby in Auto Mine

### ISSUE THREAD

**Issue by DefyEnjoyCantCode** [ImpactDevelopment/ImpactIssues#2800]
**Describe the bug**
This happens with Auto Mine. If enough of something is nearby each other, for example, coal, Baritone will scramble to every option, without going to its original target first. This causes you to get nothing out of what you're actually trying to get.

**To Reproduce**
1. Go to an area with enough of that substance, like coal.
2. Activate your Auto Mine selected for your substance.
3. Watch as Baritone will try to get to every option without actually finishing mining the specified target first.

**Expected behavior**
I thought Baritone would go to each one by one, but it just kept going to every option, without actually mining the wanted target first.

**Screenshots**
None was taken, sorry.

- Impact Version: 1.16.4
- Using Optifine? No
- Using LiteLoader? Don't think so
- Enabled mods: None other than anti-bot targeting for packets.
- Operating System: Windows 10, 64 Bit
</details>

**Additional context**
I believe this happened when I was above ground from the target, and when the targets were scrambled/pushed away from each other.

**Comment by l1ving** [comment]
This is not an Impact specific bug, this is a Baritone bug (user error)

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
