### ISSUE TITLE
[1.12.2] [1.16.4] Loosing hotkey settings for NUMPAD

### ISSUE THREAD

**Issue by davidblumer** [ImpactDevelopment/ImpactIssues#2802]
When switching between latest versions for 1.12.2 and 1.16.4 all hotkey settings for NUMPAD-keys are lost.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
