### ISSUE TITLE
[1.16.4 Nightly] Crash on game start

### ISSUE THREAD

**Issue by timoreo22** [ImpactDevelopment/ImpactIssues#2804]
**Describe the bug**
Game crashes at start

**To Reproduce**
1. Start the game
2. Crash.

**Expected behavior**
The game should run

**Screenshots**
N/A

<details> 
  <summary><strong>Game output</strong></summary>
 

```
https://pastebin.com/sTfg7zSg
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://hastebin.com/yazazubuyo.yaml
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  1.16.4-nightly-20201218
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: N/A
- Operating System: Windows 10 64bit

</details>

**Additional context**
N/A

**Comment by l1ving** [comment]
Who keeps giving out the donator jars? Lol

Login with a donator account

**Comment by CesiumCs** [comment]
> Who keeps giving out the donator jars?

installer 0.9
we reverted on the website but seems like people are still getting it

**Comment by l1ving** [comment]
cloudflare moment

**Comment by timoreo22** [comment]
i downloaded that one on the github releases for ImpactInstaller, i was thinking it was the free one

**Comment by l1ving** [comment]
well 1.16.4 nightlies are donator only
