### ISSUE TITLE
impact not starting(error uploading files)

### ISSUE THREAD

**Issue by dolphin-cat** [ImpactDevelopment/ImpactIssues#2805]
![Capture](https://user-images.githubusercontent.com/67221448/103211814-e3336500-4911-11eb-80c8-b9d0a9166ac0.PNG)
impact version: 1.15.2-Impact_4.9.1-OptiFine_HD_U_G5_pre1 with optifine pre-installed

**Comment by l1ving** [comment]
Stop pirating software.
