### ISSUE TITLE
Teleoprting Me To Where I Spawned Every Few Seconds

### ISSUE THREAD

**Issue by poleaxx3** [ImpactDevelopment/ImpactIssues#2807]
So I was walking around in my world when Impact literally started teleporting me back to where I was a second ago.. I tried turning off my hacks but it still happened, and when I used a different client, it worked. I have no idea why, and even when I restarted my computer, it still happened.

I have no Idea not to replicate this, it just randomly happened.

I expected Impact to work fine without glitching

https://gyazo.com/f3a62c476498e8324dbdb3f0ce830be2

<details> 
  <summary><strong>Game output</strong></summary>
 

```
idk how to check
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
none
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9.1
- Using Optifine?  No
- Using LiteLoader?  no
- Enabled mods:  none
- Operating System:  windows 10 64 bit

</details>

**Comment by CesiumCs** [comment]
> I tried turning off my hacks but it still happened

rofl
this is literally caused by portal godmode

**Comment by poleaxx3** [comment]
> > I tried turning off my hacks but it still happened
> 
> rofl
> this is literally caused by portal godmode

okay

**Comment by l1ving** [comment]
mfw user error
