### ISSUE TITLE
Screen glitches and computer freezes

### ISSUE THREAD

**Issue by Havael** [ImpactDevelopment/ImpactIssues#2808]
Everytime I start the impact client my computer glitches out and frezees needing t be forcefully reset to return to normal. There is no exact time this happens but the shortest was right on the menu screen and the longest was 5 minutes into the game.

I was playing on singleplayer with no optifine or forge mods using the latest release of impact for 1.12.2 and here are my error logs:
[2020-12-30-1.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5753125/2020-12-30-1.log)
[2020-12-30-4.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5753126/2020-12-30-4.log)
[2020-12-30-5.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5753129/2020-12-30-5.log)

I am trying to use impact for a longer period of time without it frezing my computer and I hope this is enough information to help

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
