### ISSUE TITLE
[1.16.4 Nightly] java.lang.StackOverflowError: mouseClicked event handler

### ISSUE THREAD

**Issue by VirxEC** [ImpactDevelopment/ImpactIssues#2809]
**Describe the bug**
Click button yes, game crash yes

**To Reproduce**
1. Activate the custom home screen thing
2. Click 'Impact'
3. Click any button (ClickGUI, for example)
4. Crash

**Expected behavior**
Don't crash my damn game

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst mouseclicked event handler
Error: java.lang.StackOverflowError: mouseClicked event handler
Exit Code: -1
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Description: mouseClicked event handler

java.lang.StackOverflowError: mouseClicked event handler
	at djz.localvar$displayGuiScreen$HEAD$zzp000(SourceFile:2874)
	at djz.a(SourceFile)
	at net.impactclient.3P.e(3P.java:67)
	at djz.a(SourceFile:896)
	at net.impactclient.3P.e(3P.java:67)
	at djz.a(SourceFile:896)
	at net.impactclient.3P.e(3P.java:67)
	at djz.a(SourceFile:896)
	-- repeated like a billion times --


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at djz.localvar$displayGuiScreen$HEAD$zzp000(SourceFile:2874)
	at djz.a(SourceFile)
	at net.impactclient.3P.e(3P.java:67)
	at djz.a(SourceFile:896)
	at net.impactclient.3P.e(3P.java:67)
	at djz.a(SourceFile:896)
	at net.impactclient.3P.e(3P.java:67)
	at djz.a(SourceFile:896)
	-- repeated like a billion times --
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  Nightly for 1.16.4
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  Main Menu w/ Custom
- Operating System:  Windows 10 64 bit

</details>

**Additional context**
I'm mad

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by EmeraldSnorlax** [comment]
> This is a duplicate. Please search before creating an issue next time. 

im amazed at how youre still sane doing this

**Comment by l1ving** [comment]
# :pray: :weary:
