### ISSUE TITLE
Error with spam.json and NullPointerException

### ISSUE THREAD

**Issue by ImpactError102** [ImpactDevelopment/ImpactIssues#2814]
Never used Impact before, but I assume that I need to write something to spam.json but I don't know what a config for it looks like.

1. Launch 1.12.2 Impact nightly
2. crash

Game Output:
```
Unable to load spam config file: Spam config file is in invalid format
java.lang.NullPointerException
	at bib.t(SourceFile:1597)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process crashed with exit code -1
```
Crash report:
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/31/20 12:57 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bib.t(SourceFile:1597)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 204536536 bytes (195 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_nightly-20201230
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.32 27.20.1032.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 
```

- Impact Version: 1.12.2-Impact_nightly-20201230
- Using Optifine?: no
- Using LiteLoader?: no
- Enabled mods:  none
- Operating System: Windows 10 64bit

I tried everything I could find, e.g. delete .minecraft, update LWJGL, restartcomputer, reinstall Impact, run 1.12.2 before running Impact. I copy and pasted a macros.json file into Impact because I got an error prior to this saying "Error loading macros config" and it seemed to fix 1/4 of the errors

**Comment by l1ving** [comment]
> Unable to load spam config file: Spam config file is in invalid format

Delete the file

**Comment by LeafHacker** [comment]
> > Unable to load spam config file: Spam config file is in invalid format
> 
> Delete the file

That might be a solution on the user's end, but it doesn't make the bug any less real - namely impact shouldn't produce corrupt spam.json files AND impact shouldn't crash trying to read a corrupt one

**Comment by l1ving** [comment]
Oh, I didn't know that. Well if the user manually edits the file that's their fault, but you can reopen this issue if you want to idiot proof it

**Comment by Jarhead20** [comment]
I am having the same issue however deleting the spam.json file didn't work. Putting empty curly brackets inside of the file did stop it from putting invalid format into console though but still crashes.  I'll just try an earlier build for now but I hope this gets solved.

**Comment by LeafHacker** [comment]
> I am having the same issue however deleting the spam.json file didn't work. Putting empty curly brackets inside of the file did stop it from putting invalid format into console though but still crashes.  I'll just try an earlier build for now but I hope this gets solved.

Sounds like you're getting two **separate** issues - you probably have a different error message when the spam file isn't invalid

**Comment by CesiumCs** [comment]
> Well if the user manually edits the file that's their fault

i get the same error and i havent touched impacts folder in this instance, but it also doesnt crash my game. i am using the 1.16.4 nightly though
![image](https://user-images.githubusercontent.com/24397680/103463673-0daf6480-4cfc-11eb-88f8-9b0f3d9fc09a.png)

**Comment by LeafHacker** [comment]
> i get the same error and i havent touched impacts folder in this instance, but it also doesnt crash my game

Thanks for the info. Sounds like these users are reporting unrelated crashes - most likely they are non-donators trying to run a nightly build. The spam.json being invalid error is probably just a red herring and unrelated to the crashes.
