### ISSUE TITLE
Losing all settings after using.

### ISSUE THREAD

**Issue by VotedBlox** [ImpactDevelopment/ImpactIssues#2815]
My entire options got reset. GUI scale dum, music loud, and worst of all no full bright.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
