### ISSUE TITLE
Stupid bug for canary.

### ISSUE THREAD

**Issue by VotedBlox** [ImpactDevelopment/ImpactIssues#2816]
It resets your Minecraft's settings back to default.
**To Reproduce**

1. Start any version of Minecraft.
2. Change something like FoV, GUI scale, or FPS.
3. Start impact canary.
4. All your settings go to default.

I expected my GUI scale, FoV, and brightness to be the same as they should.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
