### ISSUE TITLE
[1.16.4 Nightly] Minecraft options getting reset.

### ISSUE THREAD

**Issue by VotedBlox** [ImpactDevelopment/ImpactIssues#2817]
MISTAKE IN THE TITLE, IT IS FOR NIGHTLY.

**Describe the bug**
It resets your Minecraft's settings back to default.

**To Reproduce**
1. Start any version of Minecraft.
2. Change something like FoV, GUI scale, or FPS.
3. Start impact nightly.
4. All your settings go to default.

**Expected behavior**
I expected my GUI scale, FoV, and brightness to be the same as they should.

**Screenshots**
I can't

- Impact Version: Canary 20201218 for 1.16.4
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: N/A
- Operating System: Windows 10 Home 64 Bit

**Additional context**
I was using 1.12.2 impact before 1.16.4. Usually, It wouldn't change.

**Comment by l1ving** [comment]
y'all do realize you can edit the title, right 😐

**Comment by l1ving** [comment]
cnr
