### ISSUE TITLE
AutoDisconnect

### ISSUE THREAD

**Issue by Nachoo06** [ImpactDevelopment/ImpactIssues#2818]
I use AutoDisconnect when i playing in an anarchy server. When my health dwindles, it disconnects me from server. Okey, fine thats safe. But sometimes, when i reconnected the server, i am dead. Please, fix it.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
