### ISSUE TITLE
Cannot break blocks

### ISSUE THREAD

**Issue by EpicEfeathers** [ImpactDevelopment/ImpactIssues#2819]
**Issue**
I downloaded Impact for Minecraft version 1.12.2 for 2b2t, but since I didn't want to wait to test it, I started a single player flat vanilla world to play with it. Everything else worked fine, except for the fact that I couldn't break or place blocks. When I played the world without impact, it worked fine. 

**To reproduce**
To reproduce, open up a single player flat vanilla world, and try to break/place blocks.

**Expected behaviour**
I expected to be able to place and break blocks.

- Impact Version: Whichever version for Minecraft 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Criticals, Anti bot, Auto Weapon, Camera Clip, Auto Totem, Bow Aimbot, GhostHand, AutoCheat, SafeWalk, Anti Blind,  Air jump, No push, No slow, Hitbox
- Operating System: MacBook Pro 16GB

**Comment by l1ving** [comment]
I wonder what ghosthand does
