### ISSUE TITLE
Auto farm Cocoa beans

### ISSUE THREAD

**Issue by needlessrelic** [ImpactDevelopment/ImpactIssues#2820]
i feel like the auto farm feature has alot of potential, cocoa beans is as simple as breaking and placing just like any other farm however for some reason it does not get recognised by the auto farm feature.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
