### ISSUE TITLE
Auto Farm Cocoa Beans

### ISSUE THREAD

**Issue by needlessrelic** [ImpactDevelopment/ImpactIssues#2821]
The problem is that the 'auto farm' feature in impact does not recognise cocoa beans and cannot farm them.

I would like 'auto farm' to be able to use cocoa beans on a jungle log and only harvest the fully grown cocoa,  just like how the name suggests.

there isnt any alternatives to my request, or nothing comes to mind.

**Comment by l1ving** [comment]
Already suggested, and you ignored the template again.
