### ISSUE TITLE
WTap

### ISSUE THREAD

**Issue by OddNinja** [ImpactDevelopment/ImpactIssues#2822]
**Is your feature request related to a problem? Please describe.**
This feature isn't related to a problem, it's something that I see on some other clients and I would love to see it on Impact.

**Describe the solution you'd like**
A module that when you hit any entity, they will take as much knockback as they do when you Sprint + Attack them without having to sprint.

**Describe alternatives you've considered**
Sprinting and attacking them, the reason I want this to be a module is that this can take some time to go back and charge up again.

**Additional context**
None

**Comment by l1ving** [comment]
This doesn't work outside of singleplayer
