### ISSUE TITLE
Nuker & Macro

### ISSUE THREAD

**Issue by Flexy07** [ImpactDevelopment/ImpactIssues#2824]
**Is your feature request related to a problem? Please describe.**
Yes, I set up an in-game macro that left clicks automatically while impact's nuker is on but impact's nuker doesn't work with the macro apparently,because the nuker isn't breaking any blocks while the macro is left clicking.I can't use the auto-break option because it breaks things too fast that the server keeps kicking.

**Describe the solution you'd like**
Adding nuker speed modification could work,or adding a feature that nuker works when you click a button except only left clicking

**Describe alternatives you've considered**
I wrote a script that automatically keeps activating/deactivating the nuker every 10 ticks,but it starts to work quite buggy when the server kicks me even once.

**Additional context**
I'm using Macro/Keybind mod,maybe you can try setting it up.I can provide info if you want.You can also reach me on Discord if I somehow forget coming back here. Can Potter #5802

**Comment by Jarhead20** [comment]
Impact's nuker won't currently work with macro mod unless you do what you are doing. I wish this had been implemented to save me the time of making my own nuker in a module.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
