### ISSUE TITLE
Custom nuker area

### ISSUE THREAD

**Issue by Jarhead20** [ImpactDevelopment/ImpactIssues#2825]
**Is your feature request related to a problem? Please describe.**
Its very annoying when you have to design a farm around how far the nuker reaches

**Describe the solution you'd like**
An option to where you can input a custom area such as .nuker area -1 -1 -1 +1 +1 +1 where the first 3 args make the position relative to the player as pos1 and the last 3 args make the pos2 so that it forms an area.  You could also make it output a calculated max range to inform the user.

**Describe alternatives you've considered**
Well I made my own nuker.

**Additional context**
If I get round to it I can probably make a video or something showing what I mean if it is unclear.

**Comment by l1ving** [comment]
I wonder what the selection command is for

**Comment by Jarhead20** [comment]
Can you please explain how I could use the selection command with nuker

**Comment by CesiumCs** [comment]
`#sel 1` in first corner
`#sel 2` in opposite corner
`#sel cleararea`
you can leave nuker on if it makes you happy, dunno whatll happen though
