### ISSUE TITLE
The client disconnect’s me when i am on fire or hit by lava. 

### ISSUE THREAD

**Issue by mangohazex** [ImpactDevelopment/ImpactIssues#2826]
When ever I try to connect a server which I stepped onto lava it keeps disconnecting me

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
