### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by TheObsidianKing** [ImpactDevelopment/ImpactIssues#2829]
**Describe the bug**
Game keeps crashing for no reason

**To Reproduce**

**Expected behavior**
Bug gets fixed

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

![]

https://cdn.discordapp.com/attachments/763915667405406208/796532740094033960/Minecraft_Launcher_1_6_2021_7_13_10_PM.png


```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  none
- Operating System:  Windows 10

</details>

**Additional context**

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
