### ISSUE TITLE
Impact 4.9.1 crashing minecraft when starting, even with java 8.

### ISSUE THREAD

**Issue by sosigman23** [ImpactDevelopment/ImpactIssues#2833]
- Impact Version: 4.9.1 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: none
- Operating System: Windows 10 64bit

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
