### ISSUE TITLE
piglins are detected as animals not monsters you should update this and anti cactus doesn't work

### ISSUE THREAD

**Issue by ko3nd3drumm3r** [ImpactDevelopment/ImpactIssues#2834]
piglins are detected as animals not monsters you should update this and anti cactus doesn't work

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
