### ISSUE TITLE
Cant satrt the game (1.15.2)

### ISSUE THREAD

**Issue by Lightening1127** [ImpactDevelopment/ImpactIssues#2840]
i can't  start 1.15.2 it says this      "The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: drm
Exit Code: -1"

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
