### ISSUE TITLE
[1.16 Nightly] "Biome" field on HUD shows weird string of characters

### ISSUE THREAD

**Issue by berrely** [ImpactDevelopment/ImpactIssues#2841]
**Describe the bug**
On the Impact HUD, the biome field shows a weird string of characters. It doesn't seem to look random and it is in every world.

**To Reproduce**
1. Join any world on Impact 1.16.
2. Look at the top left HUD

**Expected behavior**

**Screenshots**
The current biome would be given

<details> 
  <summary><strong>Game output</strong></summary>
N/A
</details>

<details> 
  <summary><strong>Crash report</strong></summary>
N/A
</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: Impact 1.16.4 Nightly 20210109
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: HUD
- Operating System: Windows 10 64bit

</details>

**Additional context**
![](https://i.imgur.com/aMVFszx.png)

**Comment by l1ving** [comment]
me when someone does .toString on an object

**Comment by ZekerDEATH** [comment]
honestly thought this was the intended effect and I just didn't understand what it was supposed to mean ngl x_x

**Comment by l1ving** [comment]
how is this not fixed lol

**Comment by LeafHacker** [comment]
> me when someone does .toString on an object

Up until 1.16, the `Biome` class had a `getDisplayName()` method. 1.16 removed this method in favour of looking up biome names in the `LanguageMap` so that translations can be supported.

This should be fixed in tonight's nightly.
