### ISSUE TITLE
the client doesnt run

### ISSUE THREAD

**Issue by thenotofthenot** [ImpactDevelopment/ImpactIssues#2842]
the bug
the client gives a error and never run

**To Reproduce**
1. Go to since iam poor this is on tlauncher

**Expected behavior**
the impact client doesnt run

**Screenshots**
![xox](https://user-images.githubusercontent.com/77288453/104206618-94c5b080-5451-11eb-92e9-1588ffc0bce6.PNG)

<details> 
  <summary><strong>Game output</strong></summary>
 

you can see in the screenshot

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 
<!-- If a crash report file was generated, you can paste its contents between the ``` marks -->
the screen shot tells you

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine?  No 
- Using LiteLoader? r No 
- Enabled mods: none
- Operating System: windows

</details>

**Additional context**

**Comment by l1ving** [comment]
Read the error message
