### ISSUE TITLE
Addition of Auto32k feature

### ISSUE THREAD

**Issue by RealisticLimit1987** [ImpactDevelopment/ImpactIssues#2847]
I searched for this and all the other ones were invalid or closed before anyone could look at them (i think) 
an addition of an auto32k feature would immensely help me on an anarchy server i play on that has them enabled

**Comment by Flurrrr** [comment]
Please use the [suggestion](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md) template correctly

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
