### ISSUE TITLE
Movement weird

### ISSUE THREAD

**Issue by SarifzSez** [ImpactDevelopment/ImpactIssues#2850]
So, In Impact (the latest version, version for 1.12.2) the movement and digging is funny, it's like you're stuck looking in one direction though you can see around, if you turn backwards and press W, you move backwards, and if you turn sidewards, and click w, you'll still move the same direction, any fix?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
