### ISSUE TITLE
Loging in

### ISSUE THREAD

**Issue by Elegantgrape** [ImpactDevelopment/ImpactIssues#2851]
**Log in issue**

**To Reproduce**

**Expected behavior**
When I try to join 2b or any other server i get stuck in a loging in screan and when ever i try to canclel the log in it puts me back
**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by CesiumCs** [comment]
theres a template that shows up so that we can get information we need, its not there just to make a bug report look long
