### ISSUE TITLE
More payment options without CC

### ISSUE THREAD

**Issue by unabjuuh** [ImpactDevelopment/ImpactIssues#2853]
**Is your feature request related to a problem? Please describe.**
not having CC

**Describe the solution you'd like**
More payment options that dont need a CC

**Describe alternatives you've considered**
paysafecard paypal sofort litterly anything without CC
i believe there is stripe that has more payment options

**Additional context**

**Comment by l1ving** [comment]
use paypal

**Comment by CesiumCs** [comment]
> use paypal

https://github.com/ImpactDevelopment/ImpactServer/commit/9e66c8d58dcd7cbe60fe34a54dae6807905cc6ae

![image](https://user-images.githubusercontent.com/24397680/109203051-b1077d80-7771-11eb-80f2-3863d20ad9a8.png)

**Comment by l1ving** [comment]
oh lmao
