### ISSUE TITLE
game crashed many and many times.

### ISSUE THREAD

**Issue by Ares164286** [ImpactDevelopment/ImpactIssues#2854]
Can I fix a bug that crashes when Shulker teleports?

**Comment by CesiumCs** [comment]
do you think you could edit this issue to follow the [bug report template](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md&title=Please+add+a+brief+but+descriptive+title)?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
