### ISSUE TITLE
Adfly links not working

### ISSUE THREAD

**Issue by XDKaioden** [ImpactDevelopment/ImpactIssues#2856]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
/////////////////////////////////////////////////////////
its on the title

**Comment by CesiumCs** [comment]
you'll have to use https://impactclient.net/?brady-money-grubbing-completed=true&platform=exe
we really should just ditch adfly lol ive seen it not work for so many people

**Comment by berrely** [comment]
Incorrect issue template, a solution provided.

**Comment by LeafHacker** [comment]
For the record, adfly is no longer being used
