### ISSUE TITLE
so my graphics card has an out of date version of opengl. and i not sure if i can fix it or not but if i can please tell me its making it hard to install the client

### ISSUE THREAD

**Issue by impacthackclientuser** [ImpactDevelopment/ImpactIssues#2862]
**Is your question request related to a problem? Please describe.**

**Describe what you are trying to achieve**

**Additional context**
Add any other context or screenshots about your question here.

**Comment by impacthackclientuser** [comment]
oops i did not see the other text box

**Comment by berrely** [comment]
Not an Impact issue.
