### ISSUE TITLE
Chorus plant Baritone farm

### ISSUE THREAD

**Issue by Kriss-Hietala** [ImpactDevelopment/ImpactIssues#2864]
**Describe the bug**
#mine minecraft:chorus_plant farms the items in inefficient way. It goes to the tree, breaks it and then immediately goes to another. Because of that the majority of fruits are laying on the ground and are not picked up. That's with #minescandropped items true. Increasing the value in #minedroploiterdurationmsthankslouca from 250 to 2000 helps only a little because the fruits not drop directly on player but in bigger radius.
**To Reproduce**
1. Go to 'end islands'
2. Type #mine minecraft:chorus_plant
3. Look at the trail of items left behind on the floor
4. Panik

**Expected behavior**
Picking up items on the floor before going to next tree

**Screenshots**
![image](https://user-images.githubusercontent.com/77977701/105721972-72d62e80-5f25-11eb-9873-6892b2eabcaf.png)
![image](https://user-images.githubusercontent.com/77977701/105722472-fd1e9280-5f25-11eb-8a41-8e1137dd2d84.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9.1 nightly
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: visible on screen
- Operating System:  Windows 10 64bit

</details>

**Additional context**

**Comment by LeafHacker** [comment]
This should really be reported on the baritone GitHub, since it's not an issue with Impact

/cabaletta/baritone

**Comment by l1ving** [comment]
why did you think the impact repo is the place to report baritone repo issues
