### ISSUE TITLE
Impact 1.12.2 crashes whilst waiting in 2b2t queue

### ISSUE THREAD

**Issue by catnapping** [ImpactDevelopment/ImpactIssues#2867]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by JustAnOkapi** [comment]
please add the crash report

**Comment by berrely** [comment]
@catnapping Please attach your crash report.

**Comment by berrely** [comment]
Please fill out the issue template.
