### ISSUE TITLE
impact 1.12.2 keeps crashing

### ISSUE THREAD

**Issue by patrik1123456** [ImpactDevelopment/ImpactIssues#2868]
**Describe the bug**
impact crashes instantaly

**Expected behavior**
it working

- Impact Version: Impact-4.9.1-1.12.2
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: none
- Operating System: windows 10 pro 64 bit

send help

**Comment by JustAnOkapi** [comment]
join the discord

**Comment by patrik1123456** [comment]
> join the discord

what is the discord link?

**Comment by progenit** [comment]
hi, i need help with impact, it doesent allow me to enter minecraft with it 
![Captura](https://user-images.githubusercontent.com/78099168/106023831-76a1b680-60c7-11eb-8407-aab0acee2bd1.PNG)

**Comment by CesiumCs** [comment]
buy the game

**Comment by CesiumCs** [comment]
i closed this thinking that screenshot was related to the original issue, but even if it isnt, the original issue doesnt have enough detail anyway

**Comment by patrik1123456** [comment]
> i closed this thinking that screenshot was related to the original issue, but even if it isnt, the original issue doesnt have enough detail anyway

but how can i fix the issue i want to use it

**Comment by CesiumCs** [comment]
idfk man i dont even know what the problem is
go ask in our [discord](https://impactclient.net/discord) where someone who actually knows what theyre talking about can troubleshoot with you
