### ISSUE TITLE
Customizability for Parkour hack to bypass GWEN anticheat, randomizing how far from the edge of the block to jump frmo

### ISSUE THREAD

**Issue by TKan010714** [ImpactDevelopment/ImpactIssues#2869]
Hi, I have a suggestion for Impact. It's probably the best client I've used due to customizability . I was wondering if customization for parkour could be added. I assume right now, it jumps at the very end of the block. GWEN anticheat detects  this and prevents you from parkouring by stopping your jump, causing you to fall off of the block since not jumping off the block means falling. Maybe if there was a setting that randomizes the number of pixels/coordinate offset from the edge of block to jump from, so it jumps from slightly before the edge of the block but not at the exact edge to be more legit and confusing to the anticheat.

For example, suppose the hack normally jumps off the edge of the block at 2.300 in the x coordinate. If we add a randomizer of 0.001-0.005, it may jump when the x coordinate is 2.295, 2.296, 2.297, 2.298, 2.299, or 2.300. I would think this would bypass anticheat. Maybe there could be a setting for offset from the block and then a randomizing option to randomize the offset.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
