### ISSUE TITLE
Add module

### ISSUE THREAD

**Issue by RedstoneMiner18** [ImpactDevelopment/ImpactIssues#2871]
In the impact menu there is a NoRender for items, with the option "prevent items from spawning in entirely"
This is very usefull if there are loads and loads of items.
However, there isnt a NoRender for entities. Which is a lot more usefull.
So my suggestion is to add a NoRender for entities.
It can be added to the already existing NoRender for items, and then maybe a customiser for what to render and what not (e.g. players, mobs passive/hostile, armor stands, etc)
Thanks for reading and I hope this gets added, as im probably not the only one thinking this would be very usefull.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
