### ISSUE TITLE
Baritone Getting Stuck Using cleararea

### ISSUE THREAD

**Issue by ZekerDEATH** [ImpactDevelopment/ImpactIssues#2876]
**Describe the bug**
When I use #sel cleararea or any variant after picking positions (#sel set air etc) Baritone will move to a block and then just stand there, if I try to move away it moves back. I'm using layerOrder true, and I've turned on build in layers as well (as suggested in the Discord). allowInventory is true as well. I'm using Baritone to dig a big hole. It has also done similar when digging a different hole, simply sitting still and mining whatever it can reach but not moving towards the blocks it's supposed to be mining as it should.

**To Reproduce**
I haven't seen anybody else talking about this by the way so I don't know if this will produce the bug for you but
1. sel 1, sel 2, (I believe it has to be a pretty decent sized difference in y level, maybe 5 or more blocks, and probably a large square area though where I'm having an issue now isn't really that big, less then 20x15 for sure)
2. Using layerOrder true and build in layers (I believe the bug would still happen without them)
3. Run sel cleararea or something to the same effect
4. The bot may mine for some time but eventually will get stuck in a sense.

**Expected behavior**
I expected the bot to mine each layer of blocks all the way down to my second position, but instead it got stuck.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
![image](https://user-images.githubusercontent.com/78389771/106533448-6e72be00-64af-11eb-998b-80c0b2403645.png)
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
I'm using this on my own server hosted by Shock Byte on paper 1.16.4, just trying to dig a large hole.

**Comment by ZekerDEATH** [comment]
Update: It mines anything on the top-most layer of the selection when placed, then returns to "its spot".

**Comment by l1ving** [comment]
why did you think the impact repo is the place to report baritone repo issues
