### ISSUE TITLE
Accessibility to Hide Auto-Respawn Button in Death Screen

### ISSUE THREAD

**Issue by nicelogicyt** [ImpactDevelopment/ImpactIssues#2880]
Suggestion: Add a way to hide or show the auto-respawn button in death screen since it might get annoying once in a while.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
