### ISSUE TITLE
AutoTotem Smart Module Not Working.

### ISSUE THREAD

**Issue by SKRecreated** [ImpactDevelopment/ImpactIssues#2882]
**Describe the bug**
The AutoTotem Module "Smart" is not working. 
**To Reproduce**
1. Go to auto totem
2. Click on click on smart
3. See error

**Expected behavior**
I thought auto totem would switch to a totem when I was about to die. 
**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

If I fell off of a high place (A fall that could kill me) it would switch. If I was pvping it wouldnt switch. If I was using crystals it wouldnt switch.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
