### ISSUE TITLE
Please add HoleESP

### ISSUE THREAD

**Issue by SKRecreated** [ImpactDevelopment/ImpactIssues#2883]
**Is your feature request related to a problem? Please describe.**
Im always mad when people in 2b2t are hunting me down and I have no idea where the nearest safe bedrock hole is. (Well maybe im not mad but it would be nice if I knew where to go.)

**Describe the solution you'd like**
I would like HoleESP added so I dont get mushed. 
**Describe alternatives you've considered**
Ive considered using sal but its not as good as impact. 
**Additional context**

**Comment by donteatapples** [comment]
yes

**Comment by berrely** [comment]
Duplicate of #2245
