### ISSUE TITLE
Empty space after opening and closing module dropdown

### ISSUE THREAD

**Issue by DotDivee** [ImpactDevelopment/ImpactIssues#2885]
When you expand a module to see its settings, after you have closed the dropdown the bottom of the scrollable module window remains empty.

1. Expand any module
2. Close It
3. Scroll down to the bottom of the module window

The lower area will be empty and scrolling up is the only way of fixing the issue.

![image](https://user-images.githubusercontent.com/69803052/107069140-6a111280-67d9-11eb-8c70-fcd6cc727cda.png)
![image](https://user-images.githubusercontent.com/69803052/107069185-785f2e80-67d9-11eb-805c-35e5c1ef7ef3.png)

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
