### ISSUE TITLE
Bookbot and Automount

### ISSUE THREAD

**Issue by iCxsmic** [ImpactDevelopment/ImpactIssues#2887]
I think Impact should come with Bookbot and Automounts mods Pre-installed

**Comment by berrely** [comment]
Bookbot already mentioned in #1812. No idea what automount is.

**Comment by iCxsmic** [comment]
Automount is a Mod that Mounts the player to a Donkey, Llama and Mules with a chest that bypasses Server anti donkey chest
Future has this feature

**Comment by l1ving** [comment]
auto mount has 5 duplicates now
