### ISSUE TITLE
UI Hider Button

### ISSUE THREAD

**Issue by DreamsnatcherDev** [ImpactDevelopment/ImpactIssues#2888]
When I’m playing with my friends on my ur survival world they also check if anyone is cheating, they do this by asking you to screenshare, I really like impact but I can use it because I can’t hide the UI, instead I have to use wurst because there’s a disable wurst.

I think that you should hide a button in controls or statistics and once pushed, disabled all hacks hid the impact logo and make right shift do nothing. When this button is clicked again, it reactivates. 

Maybe instead you could add a config to disable the impact logo so nothing can be seen without pressing right-shift.

I really think this could help the client for those who cheat in a small community.

**Comment by l1ving** [comment]
no

**Comment by l1ving** [comment]
self destruct is already a thing
