### ISSUE TITLE
Baritone avoids targeted block

### ISSUE THREAD

**Issue by 4Orion4** [ImpactDevelopment/ImpactIssues#2889]
**Is your question request related to a problem? Please describe.**
My question is related to a problem. When I tell baritone to mine a specific block, it just mines stone and constantly changes its path when it gets near the specific block. I don't get any of what I told it to get.

**Describe what you are trying to achieve**
I want baritone to mine what I tell it and I want you genius github developers to give me precise instructions on how to do that.

**Additional context**
I am on version 1.16.4 of Minecraft and 1.6.2 of baritone. I am using Optifine an Aristois in addition to Baritone.

(By the way liv if you see this. I contacted you on keybase about a problem with kami blue I was having. You never responded. I fixed it myself, if you were wondering.)

**Comment by l1ving** [comment]
> You never responded

Because it's rude to contact someone personally for support for a block game

**Comment by l1ving** [comment]
This isn't an impact issue, either

**Comment by CesiumCs** [comment]
![image](https://user-images.githubusercontent.com/24397680/109162935-c4512380-7746-11eb-8654-293d4aaeabcb.png)
