### ISSUE TITLE
2b2t mining issue

### ISSUE THREAD

**Issue by denysterepa** [ImpactDevelopment/ImpactIssues#2892]
The issue I'm experiencing is the fact that when I enable auto mine on 2b2t server the blocks do not seem to break while mined when the player position is right next to the mined block, is there any way to tweak the bots path so that it will at least keep some minimal distance to the block? Although the bot works when mining down. But not when mining sideways. Thank you in advance.

here is the link to the video I have recorded to make it more clear.
https://www.youtube.com/watch?v=9F1ULVBVbts&feature=youtu.be

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
