### ISSUE TITLE
Baritone ignores stained glass while building schematic

### ISSUE THREAD

**Issue by backAir** [ImpactDevelopment/ImpactIssues#2893]
**Describe the bug**
while building a schematic baritone acts like if the stained glass in the schematic doesn't exist and doesn't place it.

**To Reproduce**
Make a schematic with stained glass in it
build it using baritone and it will place every block except the stained glass and then say "Done building"

**Expected behavior**
The stained glass being placed

 

- Impact Version: Baritone standalone
- Using Optifine? No

**Comment by backAir** [comment]
I did it in 1.16.4

**Comment by l1ving** [comment]
Not an impact issue
