### ISSUE TITLE
module - arrow avoid / enemy arrow trajectories

### ISSUE THREAD

**Issue by W3nzis** [ImpactDevelopment/ImpactIssues#2894]
A module that would avoid arrows by just walking on sides or whatever. I guess you can use baritone to do this. Also very nice module would be enemy arrow trajectories that would show enemies bow trajectories and when they shoot the trajectory would be locked (maybe change color as that'd be the arrow trajectory then, not only enemy aiming).  I think that would be fun. Adjustable colors and alpha are great as always.
I hope everything is clear enough, I'm still learning english ;/

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
