### ISSUE TITLE
i can edit ur page

### ISSUE THREAD

**Issue by mems2010** [ImpactDevelopment/ImpactIssues#2895]
ok so if you to https://github.com/ImpactDevelopment/ImpactIssues/wiki/Setup-FAQ then on the bottom where the creative comments thing is then I was able to edit it, you might wanna fix that
![image](https://user-images.githubusercontent.com/71182102/107803732-e87e2f00-6d5a-11eb-8bfa-a54bbf5c3d83.png)

**Comment by LeafHacker** [comment]
This is intended. Wiki's are written and maintained by the community as a whole. If you go to Wikipedia, for example, you will be able to edit pages there too.
