### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by jharrison123** [ImpactDevelopment/ImpactIssues#2896]
Hi just saying that when you try to use the macro on the 1.16.4 version

**Comment by Flurrrr** [comment]
Duplicate of #2855

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
