### ISSUE TITLE
I've installed the client, but I can't install it because there is no "vanilla" option. I'm using Windows, by the way.

### ISSUE THREAD

**Issue by outCookie** [ImpactDevelopment/ImpactIssues#2897]
I've installed the client, but I can't install it because there is no "vanilla" option. I'm using Windows, by the way.

**Comment by Blizzen** [comment]
I'd suggest adding more details, when you say "I have installed it but cant install it", the developer probably wont understand what you are asking

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
