### ISSUE TITLE
Item Frame hitbox is taking a whole block

### ISSUE THREAD

**Issue by Mittisune** [ImpactDevelopment/ImpactIssues#2898]
Item Frame hitboxes when using Impact (1.12 - 1.15)
![image](https://user-images.githubusercontent.com/30058769/107856881-048cd980-6e0a-11eb-8db6-0ac5381b8c07.png)

(couldnt uploud the video here cuz its too big)
https://www.youtube.com/watch?v=dDWnrMlggfg&feature=youtu.be

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
