### ISSUE TITLE
.spam reload does not work as intended

### ISSUE THREAD

**Issue by Blizzen** [ImpactDevelopment/ImpactIssues#2899]
**Describe the bug**
.spam reload does not re-parse the spam.json text document. I tried editing the spam.json doc manually to add custom spams, but the messages don't update in the client after typing .spam reload. I was suggested to make a bug report about .spam reload, but saving and closing the text file and restarting the client will just revert the text file to its original state. This is on 1.12.2

**To Reproduce**
type ".spam setup"
type "a","1000","a" to create a 1 second a spam profile.
goto spam.json, replace the spamline "a" to "b"
type .spam reload
type .spam set a
type .spam start
you will output "a" every second, not "b"
the text file will stay saved as "b" but will continue to spam "a"
if you type .spam save now, it will reset the text file to "a"

**Expected behavior**
After editing the spam.json file and reloading the spam module, I expect the spam to be updated to whatever was entered into spam.json. This is not the case, even If i restart the whole game.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
