### ISSUE TITLE
X-Ray Legit mode

### ISSUE THREAD

**Issue by iamyou** [ImpactDevelopment/ImpactIssues#2900]
Just like it
https://github.com/Wurst-Imperium/Wurst7/pull/297#issue-565287316
Which can bypass ore obfuscator

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
