### ISSUE TITLE
impact and randompatches conflict

### ISSUE THREAD

**Issue by whycantiusemyname** [ImpactDevelopment/ImpactIssues#2901]
[minecraft-exported-logs-2021-02-15T15-43-19.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5980132/minecraft-exported-logs-2021-02-15T15-43-19.log)
with only impact and randompatches

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
