### ISSUE TITLE
Minecraft Premium Accounts don't work in the alt manager

### ISSUE THREAD

**Issue by Kholy6** [ImpactDevelopment/ImpactIssues#2904]
**Describe the bug**
Minecraft premium accounts  "Failed Authentication"

**To Reproduce**
1. Go to 'the main menu'
2. Click on 'alts'
3. Scroll down to '/'
4. See error "Failed Authentication"

**Expected behavior**
A successful login 

 

- Impact Version:  20210214 for 1.16.5
- Using Optifine?  No
- Using LiteLoader? 
- Enabled mods:  /
- Operating System:  Windows 10 64bit

**Comment by IlCanePerIlGatto** [comment]
I think that to put a premium acc in the alts manager you need to put the right password of the acc that you want to put in the manager.

This is just my opinion + I'm not a staff.

**Comment by LeafHacker** [comment]
You must enter the same login credentials used when logging into the Launcher. Usually this is email and password.

**Comment by Kholy6** [comment]
> You must enter the same login credentials used when logging into the Launcher. Usually this is email and password.

That's what I do. And I can login in the Launcher, but it doesn't work ingame. Have the problem with 3 Alts

**Comment by l1ving** [comment]
I can't reproduce this issue with Mojang accounts. Make sure you're using legitimately purchased accounts which were created before December of 2020
