### ISSUE TITLE
Impact Nightly 1.16.5/1.16.4 crashes on start

### ISSUE THREAD

**Issue by Dragonia132** [ImpactDevelopment/ImpactIssues#2905]
**Describe the bug**
When i launch the game with either Impact Nightly 1.16.4 and Impact NIghtly 1.16.5 it crashes shortly after launching the game with the exit code 0.
I have tried many things that were listed as a solution to the same problem (but for vanilla) such as runing the launcher in compatibility mode with windows vista, updating jave, reinstalling java and none worked.

**To Reproduce**
1. Go to the launcher
2. select Impact Nightly on 1.16.4 or 1.16.5 as the version
3. click play
4. when the game launches it immediatly crashes with the exit code 0

**Expected behavior**
the game does not crash and runs without any issuses

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact nightly for 1.16.5 20210216 and 
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: none
- Operating System: Windows 10 64bit

</details>

**Additional context**
the crash report:
[hs_err_pid1040.log](https://github.com/ImpactDevelopment/ImpactIssues/files/6002800/hs_err_pid1040.log)

**Comment by IlCanePerIlGatto** [comment]
Maybe you aren't a donator so this is why it doesn't let you launch it.

Ye, you need to be a donator to use nighly versions.
