### ISSUE TITLE
Impact Nightly 1.16.5 | Stop auto-fish for no reason

### ISSUE THREAD

**Issue by jules552** [ImpactDevelopment/ImpactIssues#2906]
Hello, 
I'm trying to use auto-fish and after a random amount of auto-fish working succesfully it suddenly stop fishing. I've tried the 3 differents method to auto-fish but the 3 have the same issue. It's maybe i'm doing something badly but other auto-fish seam to works properly but not the Impact's one.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
