### ISSUE TITLE
Add a "Spleef" Module

### ISSUE THREAD

**Issue by IlCanePerIlGatto** [ImpactDevelopment/ImpactIssues#2907]
**Describe what you are trying to achieve**
Add a minigame module called Spleef. I want that when actived it automatically mines under people and yeah thats it

**Additional context**
Maybe add the range to how far away it mines and something to customize how large the hole that will be mined be

**Comment by Flurrrr** [comment]
IIRC mini-game modules are deprecated as impact is a utility client, not a cheat-client or hack/hacked client
