### ISSUE TITLE
NOT LAUNCHING!!!

### ISSUE THREAD

**Issue by LolekLiam** [ImpactDevelopment/ImpactIssues#2914]
Pls help. Impact client is not launching on TLauncher. It gives me this error message: 
![error](https://user-images.githubusercontent.com/63475764/109045971-83202b80-76d4-11eb-94b8-22bd82fa9d90.png)

**Comment by EmeraldSnorlax** [comment]
every time i feel shit about myself i like to check up on this repo to remind myself that there are other people i can be disappointed in

**Comment by EmeraldSnorlax** [comment]
impact does not support cracked launchers. please see this page [this page](https://www.minecraft.net/en-us/store/minecraft-java-edition/buy)
