### ISSUE TITLE
Search bar in gui

### ISSUE THREAD

**Issue by filipwtf** [ImpactDevelopment/ImpactIssues#2915]
**Is your feature request related to a problem? Please describe.**
It sometimes is difficult to find modules since their are a few.

**Describe the solution you'd like**
Add a search bar somewhere in the GUI, that highlights the module you are searching for,

**Describe alternatives you've considered**
Make a UI more modern like Lunar client/Badlion Client it makes it easier to navigate through the modules

**Additional context**

**Comment by l1ving** [comment]
did you try typing

**Comment by filipwtf** [comment]
Oh thanks!
