### ISSUE TITLE
Shader option in ESP is not displaying on 1.12.2

### ISSUE THREAD

**Issue by abodnar-creator** [ImpactDevelopment/ImpactIssues#2917]
I already re-installed impact, but i am still not able to see it.. I can only see these modes:
2D
Skeleton
Box

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
