### ISSUE TITLE
Launching Premium with a non-linked account

### ISSUE THREAD

**Issue by Omega172** [ImpactDevelopment/ImpactIssues#2923]
**Is your question request related to a problem? Please describe.**
I am trying to launch Impact Premium Nightly 1.16.5 from the vanilla launcher but when I do it crashes. So I was trouble shooting and I found out if I try to launch it when not using the minecraft account linked to my impact account it crashes.

**Describe what you are trying to achieve**
I would like it if it didn't crash when I try to launch it on a different account or the ability to link more than one minecraft account to my impact account. Although it is not that that difficult to just go the the account dashboard and change the linked username.

**Additional context**
Add any other context or screenshots about your question here.
No other additional information.

**Comment by l1ving** [comment]
Use the alt manager to switch accounts in game.
