### ISSUE TITLE
game crashes every time i do .b build example.schematic

### ISSUE THREAD

**Issue by LucasDavis** [ImpactDevelopment/ImpactIssues#2925]
i tried to make baritone build me a car but after 4 block have been placed, it crashes, i dont know if their was a block that was a modded block from forge, or its the nightly version that caused it (Impact 1.16.5)

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a Baritone [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
