### ISSUE TITLE
impact speed breaks when using latest version of impact and inertia

### ISSUE THREAD

**Issue by rand0m0User** [ImpactDevelopment/ImpactIssues#2926]
**Describe the bug**
a conflict between impact and inertia or inertia and impact prevents speed(from working at all) and fly from working properly(slow even at max speed on the 'vanilla' mode)

**To Reproduce**
modlist:
    Impact-4.9.1-1.12.2.jar
    Inertia Client 3.1.3 - 1.12.2.jar 
    mobends-0.24_for_MC-1.12.jar
    RealFirstPerson2-1.12.2-1.2.3.jar
    salhack-github-2.05-release.jar
    SoundFilters-0.11_for_1.12.jar
    
bug happens equally in singleplayer and multiplayer
isolated(ran with only the first 2 items on the modlist) it down to Inertia and Impact, might be a mixin conflict

**Expected behavior**
speed(vanilla) refuses to work and fly(vanilla) is broken/ignores the flyspeed slider when inertia loaded
no other modules that i know of have any other problems

**Screenshots**
not a visual bug

<details> 
  <summary><strong>Game output</strong></summary>
 

```
there is no console spam, errors or warning regarding impact or inertia
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
there is no crash
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1 for 1.12.2
- Using Optifine? yes
- Using LiteLoader? no
- Enabled mods: speed(vanilla) any speed and fly(vanilla), have tested with a fresh(no other modules enabled) impact config, still happens with the same mod configuration
- Operating System: 10 64bit

</details>

**Additional context**
nothing in salhack is broken, and the issue persists even if its not present

and i made shure to check for updates of the mods that conflict, and they are the latest versions. and check for an issue matching the problem i have, none were found

only reason im *trying* to use inertia is for the note bot (would be a welcome addition to impact to be able to load nbs or mid files and play them on a 5x5 platform of note blocks)

**Comment by l1ving** [comment]
Impact will not receive bug fixes for the forge specific version, read the wiki.

**Comment by fawwaz1234** [comment]
too many clients. what did u expect lmao
