### ISSUE TITLE
My mouse wont work outside of minecraft when using impact 1.12.2

### ISSUE THREAD

**Issue by NotAnEnemy123** [ImpactDevelopment/ImpactIssues#2927]
**Describe the bug**
When I use impact 1.12.2 and open another application I am unable to click on anything on said application. I can only click on minecraft even though it is running in the background. I can still use my Keyboard though

**To Reproduce**
use Linux
install minecraft over mojang
install Impact 1.12.2
--> mouse wont work outside minecraft

**Expected behavior**
my mouse working outside of minecraft

- Impact Version: <4.9" -->
- Using Optifine? < No -->
- Using LiteLoader? < No -->
- Enabled mods: <doesnt matter -->
- Operating System: <Linux Ubuntu 20.04>

**Additional context**
I wiped my Pc and reinstalled everything even the operating system without changing any of the setting and it still wouldnt work

https://user-images.githubusercontent.com/80005653/109872419-b0d51980-7c6c-11eb-8a90-e17aa801a205.mp4

**Comment by LeafHacker** [comment]
This isn't an impact issue.

This is an issue in either Minecraft or lwjgl; for whatever reason Minecraft in fullscreen mode is pretty quirky on Linux.

I haven't checked if this applies to Xorg, Wayland or both though.

The simplest workaround would be to use a maximized window rather than fullscreen mode.

**Comment by l1ving** [comment]
This is a Minecraft bug, I reported it several years ago. There's a workaround for KDE if you google the issue

**Comment by NotAnEnemy123** [comment]
sorry for the trouble and thanks for the help
