### ISSUE TITLE
Impact download

### ISSUE THREAD

**Issue by CallmeAlex12** [ImpactDevelopment/ImpactIssues#2929]
Hello, there is a problem. When I download Impact client there was a error:520. The Problem:"There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team."
![Capture](https://user-images.githubusercontent.com/80059526/110001897-855e3780-7d1d-11eb-8c95-cef6fbdfd4ed.PNG)

**Comment by l1ving** [comment]
Works fine for me
