### ISSUE TITLE
#goto command doesn't work

### ISSUE THREAD

**Issue by chris819t** [ImpactDevelopment/ImpactIssues#2935]
I'm using "baritone-standalone-fabric-1.6.3" in 1.16.5 like it says and everything I've tried so far except for #goto command doesn't seem to work, it will path find but it won't move at all even when doing #path

EDIT: apparently #mine doesnt work either

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)

**Comment by chris819t** [comment]
i did ask in the Discord and nobody helped me

**Comment by l1ving** [comment]
1. You did not fill in the issue template
2. This is not the Baritone repo
3. Too bad, be patient and wait for a response then.
