### ISSUE TITLE
premium impact crashes upon startup 1.16.5

### ISSUE THREAD

**Issue by DarkXL6** [ImpactDevelopment/ImpactIssues#2942]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by DarkXL6** [comment]
I can give a crash report if that would help

**Comment by DarkXL6** [comment]
I donated and then downloaded Impact for 1.16.5. After installing I tried to run MC and it crashed right after the launcher started. I checked and made sure my java is upto date. Any ideas on what else to do?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)

**Comment by fawwaz1234** [comment]
link ur acc on the dashboard

**Comment by fawwaz1234** [comment]
ah just thats mean ur acc is already linkedd. hm or something else idk
