### ISSUE TITLE
How to link minecraft account to impact premium

### ISSUE THREAD

**Issue by DarkXL6** [ImpactDevelopment/ImpactIssues#2945]
**Describe the bug**
I originally could not run minecraft on 1.16.5 (issue report #2944). I was told I needed to link my minecraft account to my impact account. When i try to do this, I get a "Error linking minecraft: internal server error". Am I doing something wrong? How do I get around this error. Thanks.

**To Reproduce**
1. Go to 'impact premium client'
2. Click on 'link minecraft'

**Expected behavior**
Link minecraft account so I can use impact premium on 1.16.5 

**Screenshots**
![Screenshot_20210309-222535_Bing](https://user-images.githubusercontent.com/80369349/110624168-db8f0880-816b-11eb-97fe-f6f703f8bff4.jpg)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  1.16.5 nightly 20210308
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods:  none
- Operating System:  windows 10 64bit

</details>

**Additional context**

**Comment by l1ving** [comment]
Ask on the discord
