### ISSUE TITLE
Kicks out of server queue

### ISSUE THREAD

**Issue by Gorlix1337** [ImpactDevelopment/ImpactIssues#2953]
**Kick out of server queue**
after 20 or 30 seconds of being in a server queue on the last nigthly version of 1.16.5 it kicks me out with messages:
[Proxy] Lost connection to server.
Ther server you were previously on went down, you have been connected to a fallback server

**To Reproduce**
1. Join russian anarchy server IP: karasique.com (not sponsored btw)
2. Wait a little bit in server queue if the server is full.
3. Get kicked suddenly with server or proxy error.

**Expected behavior**
I expected to join the server and play, but if the server is full and i cant 

**Screenshots**
https://media.discordapp.net/attachments/819560976936337421/820242928935895071/unknown.png
https://media.discordapp.net/attachments/819560976936337421/820252084204077056/IbbVB0d2G4E.png

<details> 
  <summary><strong>Game output</strong></summary>
 

```
idk
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
no crashes
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.16.5 nigthly-20210308
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 64bit

</details>

**Additional context**
If you joined and you are on bedrock this is not a server queue, if you're in End thats where it will kick you.

**Comment by Gorlix1337** [comment]
also doesnt kick on official 1.16.5, forgot to mention

**Comment by l1ving** [comment]
Not an impact bug

**Comment by fawwaz1234** [comment]
try using vanilla launcher, and proof impact did that

**Comment by l1ving** [comment]
CNR
