### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by JPinNYC** [ImpactDevelopment/ImpactIssues#2954]
**Describe the bug**

**To Reproduce**
1. Go to impact installer 
2. Click on click on it

**Expected behavior**
i expected to see the installer to get the client 

**Screenshots**

 

```

```

```

```

</details> When i go to download the client it shows a pop up issue "can not bind shell folder to interface"

![unknown](https://user-images.githubusercontent.com/80540615/111033311-9aeaf580-83de-11eb-9dab-9f13dc489cd9.png)

 

- Impact Version: 

**Additional context**

**Comment by l1ving** [comment]
General troubleshooting should be done on the [Impact Discord](https://impactclient.net/discord)
