### ISSUE TITLE
Impact Capes not showing up

### ISSUE THREAD

**Issue by IMinedThat** [ImpactDevelopment/ImpactIssues#2955]
**Describe the bug**
The impact cape is not showing up after i enabled it. Its not in incognito mode, and i tried relogging.

**To Reproduce**
1. Go to Impact
2. Click on Render
3. Scroll down to Capes

**Expected behavior**
I am supposed to see my cape

**Screenshots**
Not really necessary, i just cant see my cape when i turn the mod on

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  All versions
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  None
- Operating System:  Macbook Pro Catalina

</details>

**Additional context**
None

**Comment by fawwaz1234** [comment]
go to ur dashboard and turn it on

**Comment by fawwaz1234** [comment]
wait sorry im wrong

**Comment by fawwaz1234** [comment]
try restarting ur game

**Comment by l1ving** [comment]
Make sure vanilla capes are enabled and you don't have other mods overriding it. 
General troubleshooting should be done on the [Impact Discord](https://impactclient.net/discord)
