### ISSUE TITLE
Fall Damage Delayer

### ISSUE THREAD

**Issue by Gorlix1337** [ImpactDevelopment/ImpactIssues#2956]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i get fall damage in front of a 3 block jump resulting me failing it.

**Describe the solution you'd like**
Delay the fall damage and use it as advantage.

**Describe alternatives you've considered**
Fall Damage Delayer
trigger when player is holding or pressing Space.
ignore trigger if delayer got timed out.
also probably there is a way to use fall damage as force to jump further and higher 0.5 blocks.

**Additional context**
Without fall damage delayer - https://i.imgur.com/92sqHkd.png
With fall damage delayer - https://i.imgur.com/lJcoVGm.png
Blue is the players path
Red is when player get fall damage

**Comment by l1ving** [comment]
Use blink

**Comment by Gorlix1337** [comment]
this meant to be automatic function... but okay...
