### ISSUE TITLE
Feature Request: AutoGapple

### ISSUE THREAD

**Issue by apinklover** [ImpactDevelopment/ImpactIssues#2960]
**Is your feature request related to a problem? Please describe.**
Feautre Request: Add AutoGapple or its equivalent

**Describe the solution you'd like**
If Enchanted Golden Apples are present in inventory, move them to the hotbar (slot is user-defined) and automatically eat when Health drops under a user-defined threshold. Then, switch back to the hotbar slot that was selected before AutoGapple event.

**Describe alternatives you've considered**
Going back to Sigma client (it has AutoGapple) but will not since it broke on my machine and is super sketchy.

**Additional context**
N/A

**Comment by l1ving** [comment]
enable auto eat
