### ISSUE TITLE
Auto disconnect/ping for when someone joins 

### ISSUE THREAD

**Issue by HEX101** [ImpactDevelopment/ImpactIssues#2966]
I just wanted to say something I play on a realm in which cheating is not really aloud but there is A LOT of admin abuse tping and spawning items in specifically and I have been using a bit of baritone to get stone for a build and I usually leave baritone on while I'm in online classes but I kinda don't want someone to get online and tp to me so it would be pretty cool if there was a feature that either pinged you if someone gets on or makes you leave

**Comment by l1ving** [comment]
AutoLog? Don't cheat on servers that don't allow it

**Comment by user670** [comment]
> AutoLog? Don't cheat on servers that don't allow it

AutoLog detects players that go **offline**, but he wants to detect when players go **online**.
