### ISSUE TITLE
Nuker update?

### ISSUE THREAD

**Issue by SnooW1e** [ImpactDevelopment/ImpactIssues#2967]
Just a suggestion for nuker, maybe allow a lower range? Like instead of a 4x4 being the lowest add a 3x3 or 2x2 the 4x4 if you click to fast on some servers it kicks you for to many packets. Thanks

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
