### ISSUE TITLE
Minecraft crashes when I open it

### ISSUE THREAD

**Issue by exterminatemusic** [ImpactDevelopment/ImpactIssues#2971]
**Describe the bug**
When I start Minecraft it crashes 

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 9.4 for 1.16.5
- Using Optifine? No
- Using LiteLoader? 
- Enabled mods: No
- Operating System: Windows 10 64bit

**Additional context**

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
