### ISSUE TITLE
1.16.5 impact bug

### ISSUE THREAD

**Issue by Zedman711** [ImpactDevelopment/ImpactIssues#2977]
I Donated, and I can't get 1.16.5 of the impact client because it says my password does not match even tho I copied and pasted the password, it says I have a premium account still don't have it; please help

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
