### ISSUE TITLE
Hello i have recently donated 5$ USD for 1.16.5 impact minecraft hacks and there is no option to hack on 1.16.5

### ISSUE THREAD

**Issue by LincolnO2802** [ImpactDevelopment/ImpactIssues#2978]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by l1ving** [comment]
Fill in the issue template
