### ISSUE TITLE
minecraft crash exit code 0

### ISSUE THREAD

**Issue by Vadm929** [ImpactDevelopment/ImpactIssues#2980]
minecraft crash exit code 0

Go to 'Minecraft Launcher'
Click on 'Play'
See error

 (1)](https://user-images.githubusercontent.com/63619824/111910351-b5217500-8a69-11eb-81bc-b96c141f797a.png)
1.16.5

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
