### ISSUE TITLE
minecraft crash exit code 0   please help me

### ISSUE THREAD

**Issue by Vadm929** [ImpactDevelopment/ImpactIssues#2981]
When I Click Install Its Says Succesfully Installed But When I Try To Start It, Its just give me error code 0.

 **1. Go to 'Impact Installer'
 2. Select Any Nightly Version With 1.16.5
 3.Click on 'Install'
 4.Start Minecraft And Start Impact Client
 5.See error Message 0**

**I have a donor account, but it doesn't work either**

**I updated Java but it didn't work**

**I reinstall everything but it didn't work**

Screenshots (https://user-images.githubusercontent.com/63619824/111918728-3dfed780-8a8f-11eb-8700-3ca22f72b63d.png)

_**Thanks for reading this.**_

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
