### ISSUE TITLE
getting detected easily

### ISSUE THREAD

**Issue by combat12** [ImpactDevelopment/ImpactIssues#2985]
**Describe the bug**
easy to detect all servers ban me in 5 seconds 

**To Reproduce**

**Expected behavior**

(not get detected so easily and in seconds of hiting someone)

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Idk what this means
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
none
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.15.2
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: hitbox and esp
- Operating System: windows 10 

</details>

**Additional context**

**Comment by l1ving** [comment]
ok
