### ISSUE TITLE
ESP Box bug

### ISSUE THREAD

**Issue by Skeptical101** [ImpactDevelopment/ImpactIssues#2986]
The ESP I use is Box and it's good. But then I realise that Box doesn't render crystals and only 2D and shader do. (Shader is buggy btw) Pls fix!

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
