### ISSUE TITLE
Question about lag on new verions like 1.16

### ISSUE THREAD

**Issue by Dinandpower** [ImpactDevelopment/ImpactIssues#2987]
When i am joining a world i mostly lag alot and i have the question is there a way of removing the lag

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
