### ISSUE TITLE
hi i was using baritone and midway through building something when the server i was on had to restart. i paused about 5 seconds before it happened. but when i came back in, when i typed #resume, nothing happened.

### ISSUE THREAD

**Issue by blaiiir** [ImpactDevelopment/ImpactIssues#2988]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by l1ving** [comment]
Nothing is supposed to happen. You didn't fill in the template either.

**Comment by blaiiir** [comment]
> Nothing is supposed to happen. You didn't fill in the template either.

so is there any way i can continue the build or do i have to start over

**Comment by l1ving** [comment]
the latter
