### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by Defaultic** [ImpactDevelopment/ImpactIssues#2992]
**Is your question request related to a problem? Please describe.**
 [my file is corrupted and ive redownloaded 3 times and i get stuck on logging in when i join servers]

**Describe what you are trying to achieve**
im trying to join 2b2t and i get stuck on logging in and i cant join

**Additional context**
Add any other context or screenshots about your question here.

**Comment by l1ving** [comment]
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/impactdevelopment/impactissues/issues/new?assignees=&labels=bug&template=bug.md)

**Comment by Defaultic** [comment]
that doesnt help i did the bug report and the discord is suspened i cant do anything with that info
