### ISSUE TITLE
unable to add optifine to 1.16.4

### ISSUE THREAD

**Issue by hamzawinixx** [ImpactDevelopment/ImpactIssues#2994]
**Describe the bug**
I am on latest nightly build, the installer shows the error box NULL when I try to include optifine

**To Reproduce**
1. Go to 'installer'
2. Click on 'install for official and press1.16.5'

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 

- Operating System: <!--  "Windows 10 64bit"

</details>

**Additional context**

**Comment by l1ving** [comment]
CNR / template
