### ISSUE TITLE
AutoGap

### ISSUE THREAD

**Issue by Retardcode** [ImpactDevelopment/ImpactIssues#2996]
Like a module that autogaps (golden apples) when your low HP. (PS: I saw another issue saying to implement this but the only reply was just AutoEat should be able to do this, and AutoEat cant do this)

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
