### ISSUE TITLE
It sais that an error occured while uploading files

### ISSUE THREAD

**Issue by IHaveAProblem1** [ImpactDevelopment/ImpactIssues#2997]
**Describe the bug**
https://launchermeta.mojang.com/mc/game/versions/1.15.2/1.15.2.jar : 404

**To Reproduce**
4. See an error

**Expected behavior**
To open the game and play

**Screenshots**
![image](https://user-images.githubusercontent.com/81366780/112475148-2a968980-8d79-11eb-8e56-f437a1dcf916.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: latest
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: none
- Operating System: windows 10

</details>

**Additional context**

**Comment by IHaveAProblem1** [comment]
i disabled my antivirus and i checked my internet

**Comment by l1ving** [comment]
pirated launchers aren't supported here
