### ISSUE TITLE
Auto disconnect within proximity to player/entity.

### ISSUE THREAD

**Issue by alphademon** [ImpactDevelopment/ImpactIssues#2999]
Not sure if this has been requested before (I couldn't find one), should be easy to add and helpful in certain situations. I would love to see an option on "auto disconnect" to trigger a disconnect when a player or specified entity is within a set amount of blocks.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
