### ISSUE TITLE
Please add support for Fabric

### ISSUE THREAD

**Issue by noahnao** [ImpactDevelopment/ImpactIssues#3000]
Add support for Fabric so that you can run it along with performance-improving mods like sodium. This would be so helpful.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
