### ISSUE TITLE
[BUG] Impact automatically places blocks and tools in hotbar.

### ISSUE THREAD

**Issue by Keramis** [ImpactDevelopment/ImpactIssues#3002]
**Describe the bug**
Impact automatically places a Pickaxe and Blocks in my hotbar, without me telling it to.

**To Reproduce**
1. Have any sort of pickaxe or blocks in your inventory.
2. It will automatically place them in your hotbar. I do not have any features enabled while this is happening.

**Expected behavior**
I expected impact to not do this.

**Screenshots**
https://youtu.be/fFJwQsGXLYI Video showing what happens.

- Impact Version: 1.16.5-Impact_nightly-20210308
- Using Optifine? No.
- Using LiteLoader? No.
- Enabled mods: Nothing, well, nothing that really mattered in the video. This also happens with no modules enabled, so it's not a module issue.
- Operating System: Windows 10 64bit

**Additional context**
Specs for my PC, if those really make a difference:
OS Name	Microsoft Windows 10 Home
System Type	x64-based PC
Processor	AMD Ryzen 5 3600 6-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB
Available Physical Memory	19.7 GB
Name	NVIDIA GeForce GTX 1050

**Comment by l1ving** [comment]
This isn't a bug
