### ISSUE TITLE
1.16.5 20210308 nightly build crashes before mojang logo.

### ISSUE THREAD

**Issue by DiamondsInLava** [ImpactDevelopment/ImpactIssues#3003]
**Describe the bug**

**To Reproduce**
1. Go to multimc
2. Click on lauch impact nightly 1.16.5
3. Crash log appears
4. https://pastebin.com/vhSRWaQP

**Expected behavior**
Open impact client sucefully

**Screenshots**
Crash log from multimc,, crashes too with minecraft client.
https://pastebin.com/vhSRWaQP

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>https://pastebin.com/vhSRWaQP</strong></summary>

```

```

</details>

<details> 
  <summary><strong>I was using multimc and normal mc client</strong></summary>
 

- Impact Version: 
- Using Optifine? <No>
- Using LiteLoader? <No>
- Enabled mods: <No>
- Operating System: <Windows 10 64-bits>

</details>

I have paid the 5$ and logged with my linked mc account,

**Comment by l1ving** [comment]
> java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at net.impactclient.0rz.<clinit>(0rz.java:16)

Lol how the fuck? Try reinstalling impact

**Comment by DiamondsInLava** [comment]
I reinstalled impact on a fresh .minecraft folder, still getting the same error, maybe its because the discord server is down?

new crash log on normal mc launcher: https://pastebin.com/S96wUvYv

**Comment by XuliGan4eg2006** [comment]
> I reinstalled impact on a fresh .minecraft folder, still getting the same error, maybe its because the discord server is down?
> 
> new crash log on normal mc launcher: https://pastebin.com/S96wUvYv

You started minecraft before pathing by impact?

**Comment by onayB09** [comment]
Im cant start nightly builds too. But they just closed my report without looking in the comments. I donated 5 dolars and this is what i get. if you dont fix this i will share this on youtube.

**Comment by DiamondsInLava** [comment]
> > I reinstalled impact on a fresh .minecraft folder, still getting the same error, maybe its because the discord server is down?
> > new crash log on normal mc launcher: https://pastebin.com/S96wUvYv
> 
> You started minecraft before pathing by impact?

Yes, I made sure to open normal 1.16.5 minecraft first. Normal minecraft opens with no issues

**Comment by onayB09** [comment]
> > > I reinstalled impact on a fresh .minecraft folder, still getting the same error, maybe its because the discord server is down?
> > > new crash log on normal mc launcher: https://pastebin.com/S96wUvYv
> > 
> > 
> > You started minecraft before pathing by impact?
> 
> Yes, I made sure to open normal 1.16.5 minecraft first. Normal minecraft opens with no issues

same here

**Comment by XuliGan4eg2006** [comment]
> Im cant start nightly builds too. But they just closed my report without looking in the comments. I donated 5 dolars and this is what i get. if you dont fix this i will share this on youtube.

Stop. Go to impact dashboard and paste ur nick a this graph and make sure that you pressed button "Link Minecraft"
![IMG_20210328_211056_578.jpg](https://user-images.githubusercontent.com/62839426/112762755-187f4a00-900a-11eb-8720-cc58caf82f2b.jpg)

**Comment by XuliGan4eg2006** [comment]
> Im cant start nightly builds too. But they just closed my report without looking in the comments. I donated 5 dolars and this is what i get. if you dont fix this i will share this on youtube.


And if all good, u will see that. And ur Minecraft will work

![IMG_20210328_211222_127.jpg](https://user-images.githubusercontent.com/62839426/112762785-4cf30600-900a-11eb-9eba-d25df4ba4cf0.jpg)

**Comment by onayB09** [comment]
> > Im cant start nightly builds too. But they just closed my report without looking in the comments. I donated 5 dolars and this is what i get. if you dont fix this i will share this on youtube.
> 
> Stop. Go to impact dashboard and paste ur nick a this graph and make sure that you pressed button "Link Minecraft"
> ![IMG_20210328_211056_578.jpg](https://user-images.githubusercontent.com/62839426/112762755-187f4a00-900a-11eb-8720-cc58caf82f2b.jpg)

omg people thinks we are stupid. we linked minecraft accounts already. fix your client and stop blaming us. i even linked discord.
![image](https://user-images.githubusercontent.com/53120690/112762849-a65b3500-900a-11eb-9c79-e61415f5a7ce.png)

**Comment by XuliGan4eg2006** [comment]
> > > Im cant start nightly builds too. But they just closed my report without looking in the comments. I donated 5 dolars and this is what i get. if you dont fix this i will share this on youtube.
> > 
> > Stop. Go to impact dashboard and paste ur nick a this graph and make sure that you pressed button "Link Minecraft"
> > ![IMG_20210328_211056_578.jpg](https://user-images.githubusercontent.com/62839426/112762755-187f4a00-900a-11eb-8720-cc58caf82f2b.jpg)
> 
> omg people thinks we are stupid. we linked minecraft accounts already. fix your client and stop blaming us. i even linked discord.
> ![image](https://user-images.githubusercontent.com/53120690/112762849-a65b3500-900a-11eb-9c79-e61415f5a7ce.png)
> 

Bruh, sorry. But I myself had such a problem (due to my inattention)

**Comment by onayB09** [comment]
> > > > Im cant start nightly builds too. But they just closed my report without looking in the comments. I donated 5 dolars and this is what i get. if you dont fix this i will share this on youtube.
> > > 
> > > 
> > > Stop. Go to impact dashboard and paste ur nick a this graph and make sure that you pressed button "Link Minecraft"
> > > ![IMG_20210328_211056_578.jpg](https://user-images.githubusercontent.com/62839426/112762755-187f4a00-900a-11eb-8720-cc58caf82f2b.jpg)
> > 
> > 
> > omg people thinks we are stupid. we linked minecraft accounts already. fix your client and stop blaming us. i even linked discord.
> > ![image](https://user-images.githubusercontent.com/53120690/112762849-a65b3500-900a-11eb-9c79-e61415f5a7ce.png)
> 
> Bruh, sorry. But I myself had such a problem (due to my inattention)

im sorry to im bit angry right now

**Comment by DiamondsInLava** [comment]
Just for the record, my account and discord are correctly linked.

BTW, if someone is working on this issue, just wanted to let you know I'm thankful for your attention.

**Comment by onayB09** [comment]
> Just for the record, my account and discord are correctly linked.
> 
> BTW, if someone is working on this issue, just wanted to let you know I'm thankful for your attention.

maybe because theres too many messages on this issue idk

**Comment by onayB09** [comment]
someone working on it?

**Comment by l1ving** [comment]
CNR

**Comment by l1ving** [comment]
I literally can't reproduce the issue

**Comment by DiamondsInLava** [comment]
I dont blame you, sorry for being mean, but i dont speak java at all neither i understand the issue, i just want to know maybe a probable cause, at least an idea.

**Comment by onayB09** [comment]
![image](https://user-images.githubusercontent.com/53120690/113488975-1580cf80-94ca-11eb-86a7-6fcee525142a.png)
Try this its worked for me if its your language is not english

**Comment by DiamondsInLava** [comment]
Getting the same error still

**Comment by rootinchase** [comment]
This is a JNA issue, try renaming the folder `C:/Users/React/Desktop/MultiMC/libraries` to something else. This folder contains all the libraries used by various mods, including JNA, and by moving it, MultiMC will retry downloading them.

There is a command line arg to use the system JNA, but I can't find it right now.

**Comment by DiamondsInLava** [comment]
Still crashes with code -1, but hey, thanks for looking at the problem and we are going somewhere since there is new code in the crash dump.
https://pastebin.com/tCnSThLV

**Comment by rootinchase** [comment]
Where is it trying to write the log file? Is it somewhere in C:/users/<your user>? I'm seeing several errors like this one:
`2021-04-13 20:05:50,719 main ERROR Cannot access RandomAccessFile java.io.FileNotFoundException: logs\latest.log (Acceso denegado) java.io.FileNotFoundException: logs\latest.log (Acceso denegado)`

Combine that with the fact that all libraries are in program files, leads me to believe that it's storing the instance in a location with limited access.

**Comment by DiamondsInLava** [comment]
Moved multimc folder to desktop and opened with administrator mode and it worked! Thanks a lot guys.
