### ISSUE TITLE
Discord isnt working on site

### ISSUE THREAD

**Issue by XuliGan4eg2006** [ImpactDevelopment/ImpactIssues#3006]
![image](https://user-images.githubusercontent.com/62839426/112754773-43f03d80-8fe6-11eb-86e0-ad5c78b03ebd.png)

It loads for a very long time and does not work. + if you click on "our discord" then this happens:

![image](https://user-images.githubusercontent.com/62839426/112754808-7e59da80-8fe6-11eb-8bab-3155bd63c6fa.png)

**Comment by l1ving** [comment]
That's a known issue, it already says so on the site

**Comment by XuliGan4eg2006** [comment]
> Это известная проблема, об этом уже написано на сайте
 
But can i connect to impact discord?

**Comment by l1ving** [comment]
No

**Comment by EmeraldSnorlax** [comment]
impact discord got terminated rofl
