### ISSUE TITLE
impact installed but doesn't exist

### ISSUE THREAD

**Issue by alreadytaked** [ImpactDevelopment/ImpactIssues#3008]
title says it all
To Reproduce
1: download installer
2: install
3: get lucky (or unlucky in my case)

Expected behavior
impact existing

details
game runs as if impact wasn't even installed
 

- Impact Version: 4.9.1 for 1.12.2
- Using Optifine? No
- Using LiteLoader?  No 
- Operating System:  OSX 1.12.6

**Comment by l1ving** [comment]
CNR
