### ISSUE TITLE
Forge curiosity

### ISSUE THREAD

**Issue by Rac25812** [ImpactDevelopment/ImpactIssues#3009]
I was just curious as to why you can't use impact 1.16.5 with forge. I'd like to help if that's even possible.

-Thanks

**Comment by l1ving** [comment]
Because it's not supported

**Comment by Rac25812** [comment]
is there a way to support it customly?

**Comment by l1ving** [comment]
No, because it's not supported

**Comment by Rac25812** [comment]
Well thanks
