### ISSUE TITLE
Using mods with Impact Client

### ISSUE THREAD

**Issue by BruhWhatEven** [ImpactDevelopment/ImpactIssues#3014]
**Is your question request related to a problem? Please describe.**
I play on a modded server. I've wanted to use Impact client on it for so long, but I can't figure out how to combine the nightly build with the mod I am using. I know some mods work, but how am I supposed to test it? I am on Minecraft 1.16.5, by the way. The specific mod is origins.

**Describe what you are trying to achieve**
I am trying to use the Impact Client with origins mod on a 1.16.5 server.

**Additional context**

**Comment by l1ving** [comment]
This is not possible.
