### ISSUE TITLE
Impact wont start up

### ISSUE THREAD

**Issue by YeetMasterUrMomGay** [ImpactDevelopment/ImpactIssues#3015]
Soooo I installed a impact client on my minecraft and when I click enter the game I get 
This XML file does not appear to have any style information associated with it. The document tree is shown below.
https://launchermeta.mojang.com/mc/game/versions/1.14.4/1.14.4.jar%20:%20404
I try 1.15.2 but its still the same  says like disabled anti-virus and i did still same
Uh yea plz help ty

**Comment by enescglyn** [comment]
delete .minecraft

**Comment by EmeraldSnorlax** [comment]
cracked launchers are not supported
