### ISSUE TITLE
Baritone mining problem

### ISSUE THREAD

**Issue by TheNameIsJulian** [ImpactDevelopment/ImpactIssues#3016]
**Describe the bug**
Whenever I use automine command with Baritone on 1.16.4 Impact it will continuously walk in one direction and won't go near targeted blocks. 

**To Reproduce**
1. type in the chat #mine (block of choice)
2. Watch Baritone not work

- Impact Version: 1.16.4
- Using Optifine?  No (there is no optifine out yet)
- Using LiteLoader?  No
- Enabled mods:  Nothing
- Operating System:  Windows 10 64bit

**Comment by l1ving** [comment]
CNR and wrong repo
