### ISSUE TITLE
Cannot Use Schematic (ISSUE)

### ISSUE THREAD

**Issue by Yeetmyo** [ImpactDevelopment/ImpactIssues#3017]
I cannot auto build with baritone with the schematics. I put in my files but it doesn't work. Please fix this!

![image](https://user-images.githubusercontent.com/80555439/113464670-20ebe080-9461-11eb-9477-785d4dddc8cc.png)
![image](https://user-images.githubusercontent.com/80555439/113464712-7627f200-9461-11eb-8b8b-7fe4d69bd1ba.png)

**Comment by l1ving** [comment]
There's nothing to fix.... you need to enter the name of a schematic you have downloaded.

**Comment by Yeetmyo** [comment]
I tried everything and it is not working
