### ISSUE TITLE
Hole Esp, Auto Hole And Auto High Way

### ISSUE THREAD

**Issue by AnnoyedBlue** [ImpactDevelopment/ImpactIssues#3020]
Hole Esp
Add Hole Esp Which Looks For Holes That Are Made Out Of Obsidian/Bedrock To Reduce Damage With Crystal Aura Like In Future Client.

Auto Hole
Auto Hole Is A Module Using Baritone To Automatically Make A Hole To Help Reduce Damage While Using Crystal Aura.

Auto Highway
Auto Highway Is A Module Using Baritone To Automatically Make A Highway To Ease Baritone Commands Instead Of #buildrepeat 213123213123,123123123123,21312312321 then #build Like On Kami Blue Client

Announcer
its stupid but it announces everything you do like mine ores / kill someone like on kami blue client

**Comment by graemeg** [comment]
You can build and use the custom Baritone version we are maintaining for Constantium's highway building. It can dig and pave in all 8 directions, mine echests for obsidian, find pickaxes and obsidian in shulkers, eat gapples before mining a block that leads to lava source blocks etc. More improvements to come.

https://github.com/mankool0/baritone/tree/highwayBuilding

Simply run: `./gradle build`
Then load the api-forge module which will override the one included in Impact.
