### ISSUE TITLE
Crashs after monjang logo before you click anything

### ISSUE THREAD

**Issue by Wizmtin** [ImpactDevelopment/ImpactIssues#3029]
**Describe the bug**
Crashs after monjang logo before get a can you click anything
**To Reproduce**
1. Go to 'Offical Launcher'
2. Click on 'Impact then play'
3. Scroll down to 'N/A'
4. I see the title srceen then it crashs

**Expected behavior**
It would stay open and waiting for an input.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/6277993/latest.log)

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[crash-2021-04-08_03.26.29-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/6277956/crash-2021-04-08_03.26.29-client.txt)

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  20210308 for 1.12.2
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods:  none
- Operating System:  Windows 10 64bit

</details>

**Additional context**

**Comment by l1ving** [comment]
Use a donator account
