### ISSUE TITLE
Selected villagers

### ISSUE THREAD

**Issue by EntityN4** [ImpactDevelopment/ImpactIssues#3031]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, having to max gear out for the whole squad it takes so long to get good villager trades
**Describe the solution you'd like**
An automated bot that, once the villager is trapped, breaks and replaces the lectern automatically until you get the selected enchant for the selected price (ex. #villager_trade_minecraft:protection_4_price_20) and it mines it until the villager gets that price or a lower one, then, if it has enough materials, it does 1 trade with the villager to lock it.

**Describe alternatives you've considered**
there isn't any alternative, u gotta mine a lectern and keep going

**Additional context**
It would also help to have a #villager_bringer so u say certain coords and it finds a way to bring the villager there

Obviously all this would be for the baritone. let me know

**Comment by EmeraldSnorlax** [comment]
![image](https://user-images.githubusercontent.com/43452521/114174875-cce17000-9928-11eb-8b4f-e9bddc6aead1.png)

---

![image](https://user-images.githubusercontent.com/43452521/114174894-d4087e00-9928-11eb-9ca5-52286957350f.png)

https://github.com/cabaletta/baritone/
