### ISSUE TITLE
when i play the 1.15.2 version its a demo

### ISSUE THREAD

**Issue by edgegamez** [ImpactDevelopment/ImpactIssues#3035]
title says it all!

**Comment by edgegamez** [comment]
and i have minecraft

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
