### ISSUE TITLE
game goes haywire 

### ISSUE THREAD

**Issue by thevc886613** [ImpactDevelopment/ImpactIssues#3037]
when i join a server my character goes haywire he starts to spin jump and moves. i turned off all the hacks and this still happens, i went to another server and the same thing keeps happening, i restarted my game several times and switched to a different version of minecraft. i went on minecraft without the hacks to my pc is fine but the client isnt, anyone know how to fix this problem?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
