### ISSUE TITLE
Impact 1.16.5 Crashes

### ISSUE THREAD

**Issue by DumpedFries** [ImpactDevelopment/ImpactIssues#3038]
When I try to open the game with the nightly builds for 1.16.5 the game crashes
Note: I am using a donor account, I opened the regular version of 1.16.5 before launching the builds for Impact 1.16.5, I have tried redownloading the builds.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
