### ISSUE TITLE
Add more totem settings and offhand crystal because impact strong for Impact + only

### ISSUE THREAD

**Issue by RealDanDamm1** [ImpactDevelopment/ImpactIssues#3039]
Implement Offhand Crystal and more autototem options!

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
