### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by Nhunor06** [ImpactDevelopment/ImpactIssues#3040]
when i try to install 1.16.5 with optifine it will display null

**Comment by TipoFake** [comment]
I have the same problem

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
