### ISSUE TITLE
Rubberbanding for seemingly no reason.

### ISSUE THREAD

**Issue by Aonarahcd** [ImpactDevelopment/ImpactIssues#3041]
Every couple of seconds I glitch back to a specific place and direction, it happens on single player worlds as well as servers. Similar to what happens with anticheat when using a speed hack, except it isn't anticheat.

Steps to reproduce the behaviour:
1. It isn't obvious what's causing this so i'm unsure. I don't think its reproducible, nothing was done just before it started happening.

Video:
https://youtu.be/jo4Zi6Orkdg

Expected behaviour:
Being able to move freely I guess?

Game didn't crash

Details:
- Impact Version: 4.9 for 1.12.1
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: I had many enabled when it first happened, but after reinstalling, it still happened with no mods enabled.
- Operating System: macOS High Sierra 10.13.6

Additional info:
Isn't affected by ping or tps.
Doesn't happen when running vanilla 1.12.2, only when running impact on its own.
I was running a couple other mods (cosmetic mods) with forge at the time but this still happens when impact is run on its own so it wasn't down to any other mod.
(not sure how helpful) but also:
Blocks can be placed but disappear right after while they still disappear from the hotbar.
Blocks can be broken but reappear right after and dont produce an item on the ground to pick up.
When reloading a world in vanilla 1.12.2 after placing/breaking blocks, all placed blocks are still in inventory and none remain broken.
Direction isnt changed when server rotation packets are disabled.
When using a bow or a pearl, the direction snaps back as you release (sooner than the regular 4-6 second lag thing) and the arrow/pearl is thrown to that direction, not the way you were aiming.
Chorus fruit and pearls work to move without lagging back.
You can move when on a mount although glitchy and the angle/looking direction still snaps to one spot.
While riding in freecam/third person, you can see the player glitching back to a couple of blocks away every 3-5 seconds.
Server uptime goes up in 3 to 7 seconds instead of 1, see video.
Move completely normally when using blink or freecam.

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)

**Comment by Aonarahcd** [comment]
Ill just use a different client.
