### ISSUE TITLE
Crashing on 1.12.2 only 1.12.2

### ISSUE THREAD

**Issue by WindfulBoi** [ImpactDevelopment/ImpactIssues#3045]
Basically I get Exit code: 0 when trying to launch i need help

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
