### ISSUE TITLE
Autofish doesn't work on hypixel skyblock

### ISSUE THREAD

**Issue by GodSaveTheDoge** [ImpactDevelopment/ImpactIssues#3047]
**Describe the bug**
It doesn't detect the fish, it just waits. I have already tried and neither of the modes work.

**To Reproduce**
1. Turn on autofish
2. Watch it do nothing

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.9.1
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Autofish
- Operating System: Ubuntu 20.04

</details>

**Comment by GodSaveTheDoge** [comment]
Note that it does work on vanilla, it's just hypixel skyblock

**Comment by GodSaveTheDoge** [comment]
also, idk if it's related but i can't see the fish particles you usually see...

**Comment by l1ving** [comment]
Then it does not work

**Comment by GodSaveTheDoge** [comment]
> Then it does not work

you have a point
