### ISSUE TITLE
Impact 1.16.5 OptiFine not working

### ISSUE THREAD

**Issue by TimyIsCool** [ImpactDevelopment/ImpactIssues#3048]
![image](https://user-images.githubusercontent.com/74112751/115116500-b1faa580-9f91-11eb-9232-7bb7120fb8fc.png)
Am I doing something wrong or what?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
