### ISSUE TITLE
Installer "Null" Issue 

### ISSUE THREAD

**Issue by FlekSSSer** [ImpactDevelopment/ImpactIssues#3049]
**Describe the bug**
Null issue when trying to install optifine with nightly impact build 1.16+ (1.16.4, 1.16.5)
It happens with any nightly impact 1.16+ version

**Expected behavior**
Should install nightly impact version with optifine

**Screenshots**
![image](https://user-images.githubusercontent.com/66696664/115121733-eafc3f80-9fbc-11eb-8184-b7df34cb1e98.png)
<details> 
  <summary><strong>Game output</strong></summary>
 

```
None.

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Launcher does not write any logs.

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 1.16.4, 1.16.5 nightly build 20210115
- Using Optifine? No 
- Using LiteLoader? No
- Enabled mods: No 
- Operating System:  Windows 10

</details>

**Additional context**
Null optifine issue

**Comment by l1ving** [comment]
There isn't an optifine version available for that impact version
