### ISSUE TITLE
Optifine Not working 1.16.5 or 1.16.4

### ISSUE THREAD

**Issue by TimyIsCool** [ImpactDevelopment/ImpactIssues#3051]
Optifine not working for 1.16.5 or 1.16.4 impact

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'ImpactNightlyInstaller-0.9.4'
2. Click on '
![image](https://user-images.githubusercontent.com/74112751/115140206-00f61880-a02e-11eb-83c6-33516ac932d3.png)
'
3. See error

Expected behaviour

Screenshots
![image](https://user-images.githubusercontent.com/74112751/115140243-3f8bd300-a02e-11eb-9518-ee821035ee7f.png)

- Impact Version:  Nightly-20210308"
- Using Optifine? This is the problem
- Using LiteLoader? No
- Enabled mods: No Idea
- Operating System: Window 10 64bit

**Comment by TimyIsCool** [comment]
> Optifine not working for 1.16.5 or 1.16.4 impact
> 
> **To Reproduce**
> Steps to reproduce the behaviour:
> 
> 1. Go to 'ImpactNightlyInstaller-0.9.4'
> 2. Click on '
>    ![image](https://user-images.githubusercontent.com/74112751/115140206-00f61880-a02e-11eb-83c6-33516ac932d3.png)
>    '
> 3. See error
> 
> Expected behaviour
> A clear and concise description of what you expected to happen.
> 
> Screenshots
> ![image](https://user-images.githubusercontent.com/74112751/115140243-3f8bd300-a02e-11eb-9518-ee821035ee7f.png)
> 
> * Impact Version:  Nightly-20210308"
> * Using Optifine? This is the problem
> * Using LiteLoader? No
> * Enabled mods: No Idea
> * Operating System: Window 10 64bit

On Include Optifine click yes

**Comment by l1ving** [comment]
Not supported on that version I suppose

**Comment by TimyIsCool** [comment]
> Not supported on that version I suppose

doubt it
