### ISSUE TITLE
no 1.16

### ISSUE THREAD

**Issue by TheSasquatchGod** [ImpactDevelopment/ImpactIssues#3052]
i donated a day or so ago and i wanted to use the 1.16 donator only pre release and im not able to use or download it at all. ive tried to uninstall impact but I still cant use it. i can see the i have the donator cape in game but i cant use 1.16. what else can i do?

**Comment by l1ving** [comment]
Link your account on the dashboard and use the donator installer

**Comment by TheSasquatchGod** [comment]
im not able to use my donator token
