### ISSUE TITLE
Support Blur emergancy

### ISSUE THREAD

**Issue by Sprink02** [ImpactDevelopment/ImpactIssues#3053]
I am putting my support here because I can't join the Discord

After I enabled blur the Gui became just a black screen. You can still interact with it but I cant see what I am doing. I just need a way to disable it or fix it. I already tried .gui blur disable. Could also be conflicting with Optifine.

Extra info
1.15.2 Minecraft
Impact 4.9.1 version w Optifine.
Playing Demo Version
Playing with Old laptop

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
