### ISSUE TITLE
2 security vendors flagged this file as malicious on VirusTotal - Can you help?

### ISSUE THREAD

**Issue by 00000n** [ImpactDevelopment/ImpactIssues#3054]
So I ran a scan because you know you never want a virus... And 2 security vendors flagged it as malicious, what do i do? Is it actually a virus?

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
