### ISSUE TITLE
2 security vendors flagged this file as malicious on VirusTotal

### ISSUE THREAD

**Issue by 00000n** [ImpactDevelopment/ImpactIssues#3055]
**Is your question request related to a problem? Please describe.**
So I ran a scan on the exe and it said "2 security vendors flagged this file as malicious on VirusTotal".

**Describe what you are trying to achieve**
I want to know if its actually a virus.

**Additional context**
![Screenshot 2021-04-18 at 5 59 45 PM](https://user-images.githubusercontent.com/81191047/115168500-fbb9bd80-a06f-11eb-9651-802b34ae3eec.png)

**Comment by l1ving** [comment]
no

**Comment by 00000n** [comment]
Can you explain why it says that?

**Comment by l1ving** [comment]
no

**Comment by l1ving** [comment]
it's literally the installer 

you can build your own jar from source if you don't trust it https://github.com/ImpactDevelopment/Installer
