### ISSUE TITLE
How to disable the blur gui without using the gui

### ISSUE THREAD

**Issue by Sprink02** [ImpactDevelopment/ImpactIssues#3056]
I do not believe my question is related to a problem

I am trying to fix my gui blur beacuse I enabled it and the Gui is now just a black screen. The items are still clickable but can't be seen

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
