### ISSUE TITLE
Blur Gui Fix?

### ISSUE THREAD

**Issue by Sprink02** [ImpactDevelopment/ImpactIssues#3058]
**Is your question request related to a problem? Please describe.**
My question is related to a problem. It is that I have accedently enabled the blur gui option. It has made the hack menu gui all black/grey. I can't find the Module to disable it.

**Describe what you are trying to achieve**
I am trying to fix my problem

**Additional context**
I am running an old laptop
windows 10
Impact 4.9.1 with Optifine
Minecraft 1.15.2
Demo World Minecraft. (Waiting for enough to buy full)
THX :)

**Comment by l1ving** [comment]
just delete the config file

**Comment by l1ving** [comment]
or remove Optifine
