### ISSUE TITLE
token

### ISSUE THREAD

**Issue by TheSasquatchGod** [ImpactDevelopment/ImpactIssues#3059]
ive been tryting to download the donator client for a few days and i cant seem to get my token to work. it put to token code in and it doesnt say invalid code, or anything. it wont let me use it

**Comment by l1ving** [comment]
log into your account on the dashboard

**Comment by TheSasquatchGod** [comment]
i have. i tried using my token but it wont let me

**Comment by l1ving** [comment]
what the fuck is a token
