### ISSUE TITLE
Add anchor pvp?

### ISSUE THREAD

**Issue by FloppyDisk2020** [ImpactDevelopment/ImpactIssues#3060]
Can we get Anchor PvP in the 1.16 builds? 
Most clients will have it in the final 1.16 release from what I know.

_Sorry if this is already being worked on!_

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Bug&template=bug_report.md)
- [**Suggestion**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md)
- [**Question**](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Question&template=question-or-support.md)
