### ISSUE TITLE
Unable to import installed Impact client into MultiMC instances on Raspberry Pi

### ISSUE THREAD

**Issue by skyper-cz** [ImpactDevelopment/ImpactIssues#3061]
**Describe the bug**
Operating System

No response
Description of bug

For experimenting pupose I installed MultiMC for ARM64 and make instance for 1.12.2. Then I downloaded the impact client and install him. After installation I tried to import the instance, but I could not find the instance or how to do it.

Hardware: Raspberry pi model 4B 4GB
Software: Raspberry pi OS (beta) 64-bit
Steps to reproduce

Try to do it by yourself
Suspected cause

Software limir
or
Missing info how to do it

**Comment by l1ving** [comment]
no

**Comment by skyper-cz** [comment]
BTW solved
