### ISSUE TITLE
"Null" Error when using nightly installer.

### ISSUE THREAD

**Issue by aaashleyyyy** [ImpactDevelopment/ImpactIssues#3069]
**Describe the bug*
Sorry to use the Github, but the discord is gone so here we are. Whenever I use the Impact Nightly 
![oweb1MPK](https://user-images.githubusercontent.com/83358470/116427160-c5b7ce80-a811-11eb-9d50-fd9930c67b83.gif)
Installer, I get a "null" error every time I press an option, and most importantly it doesn't install anything. Yes, I have reinstalled the launcher.
**To Reproduce**
I have no way of reproducing this as it seems I am the only one with this problem. But there is a gif I will add to show you what happens.

**Expected behavior**
I expected It to, obviously, install Impact for 1.16, but it just doesn't do it.

**Screenshots**
A gif of what happens is put below.

- Impact Version: <Any nightly version>
- Using Optifine? <Both produce the error>
- Using LiteLoader? <No>
- Enabled mods: 
- Operating System: <Windows 10 Home, 64 BIT>

**Comment by Flurrrr** [comment]
This only happens with optifine as it is not available for 1.16.5 yet, so change it to no and try to install again
