### ISSUE TITLE
Deleting

### ISSUE THREAD

**Issue by OlegTerV** [ImpactDevelopment/ImpactIssues#3071]
How do I uninstall this program on my computer?

**Comment by OlegTerV** [comment]
On windows

**Comment by LeafHacker** [comment]
Depends how thorough you want to be.

- Firstly you can delete any Minecraft Launcher instances you have. You can do this from within the Minecraft Launcher.
- Additionally, you can delete Impact's config folder. This is located in the game's run directory (`%appdata%\.minecraft` by default) and is named `Impact`.
- You can also delete versions and libraries.
  - Versions are folders inside `%appdata%\.minecraft\versions`, delete any folders with `Impact` in their name.
  - Libraries are the stuff that actually make the game run. They are downloaded automatically by thee launcher or installed by some installers, such as OptiFine and Forge's respective installers. It's usually safe to delete the entire contents of `%appdata%\.minecraft\libraries`, but if you don't want to you'll need to find the libraries used by impact and delete those. Most Impact related stuff will be in `%appdata%\.minecraft\libraries\com\github`, so deleting that folder is probably the next best option.

**Comment by OlegTerV** [comment]
Thank you
