### ISSUE TITLE
While Baritone mining, fill lava pockets in the Nether

### ISSUE THREAD

**Issue by graemeg** [ImpactDevelopment/ImpactIssues#3073]
**Is your feature request related to a problem? Please describe.**
I'm using Impact+Baritone to build a diagonal Nether highway. It simply stops when it found a lava pocket and then stands there while lava flows onto your feet. Without AutoLog (during a AFK session) you will be dead.

**Describe the solution you'd like**
Could it be improved to auto-fill such single lava pockets, or step back to avoid the lava flow touching you.

**Describe alternatives you've considered**
Some other mod-clients like KAMI Blue can already do this, but I still prefer Impact, so don't want to switch.

**Comment by Pechu317** [comment]
this seems like something that you should take up with the baritone devs and not impact, so go here: https://github.com/cabaletta/baritone

**Comment by graemeg** [comment]
Thank you for the suggestion. I found a related feature request in the Baritone project, and added my comments there.

If others want to follow this, I reported it here: https://github.com/cabaletta/baritone/issues/1154
