### ISSUE TITLE
Player using TLauncher cannot move while using Impact

### ISSUE THREAD

**Issue by Crandie** [ImpactDevelopment/ImpactIssues#3098]
**Describe the bug**
I was playing Minecraft via TLauncher, testing the hack client on a singleplayer creative world, and I have always been rubberbanding while I was using it. I try disabling hacks, especially the ones that affect the player's movement speed but nothing has worked!

**To Reproduce**
1. Download Impact on Forge
2. Boot TLauncher, Select "ForgeOptifine 1.12.2" and click the "Enter The Game" button
3. Click "Singleplayer", click on any world.

**Expected behavior**
Player will start rubberbanding every second upon entering the world.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 0.9.4 for 1.12.2
- Using Optifine?: Yes
- Using LiteLoader?: No
- Enabled mods: Auto Totem, Bow Aimbot, Safe Walk, Anti Blind, Anti Hunger, Auto Eat, Search, ESP Box, BoatFly, Signs
- Operating System: Windows 10 64bit

</details>

**Comment by EmeraldSnorlax** [comment]
TLauncher is not supported.
