### ISSUE TITLE
Hotbar bug (1.16) Premium Edition

### ISSUE THREAD

**Issue by Frankiecat** [ImpactDevelopment/ImpactIssues#3109]
When I pick up dirt/netherrack it goes to my 9th hotbar slot automatically. It will switch out any other item to put the 
dirt/netherrack there. (My sword is in my 1st hotbar slot, pickaxe in 2nd slot) when I press 2 in my inventory to switch my pickaxe out for a different pickaxe it will automatically put my sword in my inventory and then the pickaxe im trying to switch out in my 1st slot and it will do this quite a bit. I will have to leave the game multiple times or drop it to solve the problem. This problem doesnt happen with any other profiles of minecraft that I have, and when I'm using impact the bug happens regardless of what modules I have turned on.

**Comment by SoNothingMC** [comment]
It looks like Baritone is interfering with your hotbar. 

To fix this, turn the `allowInventory` setting off.

**Comment by Frankiecat** [comment]
> It looks like Baritone is interfering with your hotbar.
> 
> To fix this, turn the `allowInventory` setting off.

Bruh I never realized that could have been the issue. Thanks!
