### ISSUE TITLE
Can't plant wart

### ISSUE THREAD

**Issue by enzipenzo** [ImpactDevelopment/ImpactIssues#3112]
**Is your question request related to a problem? Please describe.**
I'm trying to plant wart on soul sand using baritone, and it doesn't work. It says that it'll plant and shows green boxes wherever I go, but they don't do anything. I have enough wart, and I've tried selecting the same level as the soul sand, and higher than it

**Describe what you are trying to achieve**
I want baritone to start planting wart wherever I select

**Additional context**
Add any other context or screenshots about your question here.

**Comment by SoNothingMC** [comment]
You are asking the question in the wrong repository.

Please (search and) reopen the issue in the [Baritone repository](/cabaletta/baritone/issues).
