### ISSUE TITLE
GDPR required privacy policy missing

### ISSUE THREAD

**Issue by D3V1LC0D3R** [ImpactDevelopment/ImpactIssues#3118]
**Describe the bug**
The GDPR requires all websites to have a privacy policy (for the website and the client) and requires explicit opt-**IN** for analytics (like googletagmanager on your site)
**To Reproduce**
1. Go to your website

**Expected behavior**
See a privacy policy (who recieves/gives what data, how is its stored, ...) and a banner with an OPT-IN and a clear coice between analytics and no analytics

**Comment by pepsilord420** [comment]
![20210519_230952](https://user-images.githubusercontent.com/63393222/119193545-c5e16d80-ba4f-11eb-84d5-d79032cd402d.jpg)

**Comment by Callihan-ops** [comment]
At the bottom of the Impact website there is a small mention of GDPR, but I do not believe Impact is GDPR compliant at the moment. However given the privacy rights mentioned on gdpr.eu, I am certain that Impact would comply with any request if you contacted a developer or admin directly through discord.

**Comment by D3V1LC0D3R** [comment]
>  I am certain that Impact would comply with any request if you contacted a developer or admin directly through discord.

i just wanted to know what additional data Impact shares/uploads (that is not in the vanilla client behaviour)

**Comment by D3V1LC0D3R** [comment]
the analytics on the website have been removed and anything else is minor (as far as i can tell)
