### ISSUE TITLE
Premium features

### ISSUE THREAD

**Issue by Josephblachly** [ImpactDevelopment/ImpactIssues#3136]
I paid 5$ so I could play on 1.16.5 but in the launcher theres no option for 1.16.5

**Comment by Callihan-ops** [comment]
Hi! You have to login in on the impactclient.net website. There should be a 4 links once you login, click on the third or fourth. [What it should look like](https://ibb.co/XVSWCtq)

**Comment by Josephblachly** [comment]
Thank you!
