### ISSUE TITLE
Make autoeat cancel on left click

### ISSUE THREAD

**Issue by leonhma** [ImpactDevelopment/ImpactIssues#3158]
**Is your feature request related to a problem? Please describe.**
yeah sure... monsters attack me and in the worst possible moment autoeat kicks in...

**Describe the solution you'd like**
make autoeat cancel on leftclick

**Describe alternatives you've considered**
dying (im mc)

**Additional context**

**Comment by AxenKing** [comment]
Set it on a keybind that you can cancel it quickly
