### ISSUE TITLE
What is the criticals function?

### ISSUE THREAD

**Issue by Saidaloimpacter** [ImpactDevelopment/ImpactIssues#3176]
What is the criticals function on impact? What will this function do?

Can you explain please?

Can you also tell me how to configure it so that it does not kick on the nexusgrief server?

Criticals

**Comment by Saidaloimpacter** [comment]
Please say me about this function

**Comment by berrely** [comment]
Google exists. [Minecraft wiki](https://minecraft.fandom.com/wiki/Damage#Critical_hit)
