### ISSUE TITLE
GUI doesn't show anything (I'm on 1.12.2)

### ISSUE THREAD

**Issue by IrregularFalcon** [ImpactDevelopment/ImpactIssues#3191]
The GUI does not show anything, pls help me, do I have to reinstall the client???

![Screenshot (25)](https://user-images.githubusercontent.com/86844370/124296546-6308e900-db5a-11eb-810a-cfdcb08e3453.png)

pls help me

**Comment by cheeselma** [comment]
try to reinstall somehow
like try to delete that version and install it again
