### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by KrakenMC4** [ImpactDevelopment/ImpactIssues#3204]
whenever i try to launch impact i get the error on tlauncher

https://launchermeta.mojang.com/mc/game/versions/1.16.5/1.16.5.jar -> C:\Users\WORK\AppData\Roaming\.minecraft\libraries\v1\versions\1.16.5\1.16.5.jar : 404

i can open vanilla 1.16.5 without any error can u help me????????

**Comment by AxenKing** [comment]
It doesn't work for tlauncher you idiot

**Comment by Doogie13** [comment]
Please add a brief but descriptive title

**Comment by CesiumCs** [comment]
we should have a bot auto close issues that mention tlauncher
