### ISSUE TITLE
Is it possible to run Impact client together with Labymod?

### ISSUE THREAD

**Issue by Lampstern** [ImpactDevelopment/ImpactIssues#3205]
Normally fps clients like Labymod doesn't like when you run them together with hacked clients, but I know it is possible to run together with Xray, so there may also be a way to do this together with Impact.

**Comment by AxenKing** [comment]
Just try it out yourself

**Comment by REALERvolker1** [comment]
yes, it works for me.

**Comment by Lampstern** [comment]
> yes, it works for me.

In what version? It doesn't work for me.

**Comment by CesiumCs** [comment]
like AxenKing says, instead of asking if something is possible, try it yourself and answer your own question.
