### ISSUE TITLE
I need help installing impact client 1.16.5

### ISSUE THREAD

**Issue by elrusit0** [ImpactDevelopment/ImpactIssues#3206]
**Is your question request related to a problem? Please describe.**

when installing the impact it goes well but when starting it in the tlauncher I get the error of "https://launchermeta.mojang.com/mc/game/versions/1.16.5/1.16.5.jar -> C: \ Users \ palac \ AppData \ Roaming \ .minecraft \ libraries \ v1 \ versions \ 1.16.5 \ 1.16.5.jar: 404 "

**Describe what you are trying to achieve**

I need someone to pass me the libraries / v1 / versions / 1.16.5 folder

**Additional context**
Please someone help me or pass me the folder, thank you very much

**Comment by faded-ninja** [comment]
I Am Getting The Same Error As Well , Can Anyone Please Help Us Out

**Comment by roko1112** [comment]
i figured it out,
so when you have the installer there is an option to install with optifine if its on than it wont work i dont know why

**Comment by CesiumCs** [comment]
> when starting it in the tlauncher

buy the game
