### ISSUE TITLE
[BUG] MACROS STILL WORKS AFTER DELETING

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [ImpactDevelopment/ImpactIssues#3277]
**Describe the bug**
Macro still works even if i deleted it in macro manager

**To Reproduce**
1. Add some macro (i added macro to R key saying "test")
2. Go to game and use the macro
3. Go to macro manager and delete the macro
4. Save and go back to the game. Then press deleted macro key

**Expected behavior**
When macro is deleted it shouldn't work anymore right?

**Screenshots**
i have none

<details> 
  <summary><strong> Details</strong></summary>
 

```
Impact 4.9.1 for Minecraft 1.12.2 (extracted as forge mod)
Mods used:
Optifine HD U G6 Pre1
liteloader latest 1.12.2 (with no litemods loaded)
BetterHUD mod (latest 1.12.2) https://www.curseforge.com/minecraft/mc-mods/better-hud

that's all 0.0
```

</details>

<details> 
  <summary><strong>Additional Impact 4.9.1 - 1.12.2</strong></summary>
 

- Impact Version:  **4.9.1 for 1.12.2 (as a forge mod)**
- Using Optifine?  **Yes**
- Using LiteLoader?  **Yes**
- Enabled mods:  **None**
- Operating System:  **Win10 64bit intel Core i5**

</details>

**Additional context**
To actually **delete** the macro binds i had to delete Full Impact Folder (deleting macros.json didn't work)

**Comment by CesiumCs** [comment]
you have to restart the game for the deletion to actually apply. devs are aware of this and might fix it in the next three or four years
