### ISSUE TITLE
My game crashes

### ISSUE THREAD

**Issue by arandompersonn** [ImpactDevelopment/ImpactIssues#3284]
It just crashes when i try to turn on the 1 16 client

 

- Impact Version: 4.9.1
- Using Optifine? Both
- Using LiteLoader? No (i think)
- Enabled mods: none
- Operating System: Windows 10

**Comment by CesiumCs** [comment]
If you're still having this problem, could you open a new issue with more detailed information? We can't really tell much from this other than "someones game somewhere is crashing on this version that other people dont have trouble with"
