### ISSUE TITLE
Baritone Select Blocks To Mine

### ISSUE THREAD

**Issue by eddy1502** [ImpactDevelopment/ImpactIssues#3285]
How would I select certain blocks for the mine over and over? I want to use this to mine in hypixel skyblock, but the regular mine always leaves the area to find other blocks. Thanks for the help!

**Comment by Spyralonn** [comment]
i just wanna say, using a hacked client on hypixel is the DUMBEST IDEA i can think of. getting banned on hypixel wouldn't be fun..

**Comment by CesiumCs** [comment]
baritone has a [usage guide](https://github.com/cabaletta/baritone/blob/master/USAGE.md) and please dont cheat
