### ISSUE TITLE
client dropdown menu size error

### ISSUE THREAD

**Issue by LordoCreations** [ImpactDevelopment/ImpactIssues#3287]
**Describe the bug**

When I open Impact, the dropdown hack bars are made so that the bottom most hacks are out of the container, so I can't activate or open them. (Using on TLauncher)

**Expected behavior**
I want to be able to activate the bottom-most hacks

<details> 
  <summary><strong>Game output</strong></summary>
 

- Impact Version: Newest for 1.16.5
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 x64

</details>

**Comment by CesiumCs** [comment]
you can either change the clickgui scale, or just scroll down as the list of mods should let you
![image](https://user-images.githubusercontent.com/24397680/145883844-2b44e6f1-3eb3-450e-a9f2-0e5449bd38e8.png)
![image](https://user-images.githubusercontent.com/24397680/145883996-f8ece605-6c5d-418b-b2b1-f48df9692634.png)
in addition, buy the game you greasy pirate
