### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Slavko-P** [ImpactDevelopment/ImpactIssues#3291]
What's this?
![GoogleAnal](https://user-images.githubusercontent.com/33180175/135765372-0fb4e0db-f3a4-46d1-aaff-718b9eabb931.png)

**Comment by CesiumCs** [comment]
[that would be the analytics reporter](https://github.com/ImpactDevelopment/Installer/blob/master/src/main/java/io/github/ImpactDevelopment/installer/utils/Tracky.java)
