### ISSUE TITLE
Commands often don't work

### ISSUE THREAD

**Issue by Dashw445** [ImpactDevelopment/ImpactIssues#3294]
Most of the time it works fine when I am in 1.12 but when I'm in 1.16 then commands stop working for Baritone and the server commands

**Comment by CesiumCs** [comment]
If you're still having this problem, could you open a new issue including more details? We have [a few templates](https://github.com/ImpactDevelopment/ImpactIssues/issues/new/choose) that should cover everything we'd need to know.
