### ISSUE TITLE
error with impact installer

### ISSUE THREAD

**Issue by wazzyunknown** [ImpactDevelopment/ImpactIssues#3310]
its says vanilla minecraft not detected at c:/user/appdata/roaming/.minecraft have you opened the launcher before 

i have opened launcher thats as much info as i can give

**Comment by TheLordGoose8008** [comment]
Yeah the same thing is happening with me

**Comment by tjallo** [comment]
Having the same problem

**Comment by MMHKGamerpro12** [comment]
i can't even install impact it just crashing

**Comment by SplatTab** [comment]
run the version ur installing

**Comment by CesiumCs** [comment]
KillerGoldFisch's workaround at #3333 should work until the Installer is fixed to work with the Windows Store version.
