### ISSUE TITLE
Installer does not work on MS store Minecraft installation

### ISSUE THREAD

**Issue by satzmann666** [ImpactDevelopment/ImpactIssues#3316]
**Describe the bug**
Installing Impact using ImpactInstaller-0.9.5 on fresh Minecraft installation from MS store fails with message "Vanilla Minecraft not detected at {PATH}, have you opened the Minecraft launcher before?"

**To Reproduce**
1. Attempt to install Impact on fresh installation of Minecraft from MS store

**Expected behavior**
Installation proceeds as usual

**Workaround**
Create additional _launcher_profiles.json_ file in minecraft installation folder

**Additional context**
On this line
https://github.com/ImpactDevelopment/Installer/blob/acda0df9f296c59d1959380a1fc4d7f44e3ee323/src/main/java/io/github/ImpactDevelopment/installer/target/targets/VanillaProfiles.java#L133
the script checks for file _launcher_profiles.json_ to validate given path is minecraft installation, but this file has been renamed to _launcher_profiles_microsoft_store.json_ in MS store installation.

**Comment by RaptorWasTaken** [comment]
Impact will only run on java edition, which is downloaded from the official site. It does not work on bedrock.

**Comment by zeus0001** [comment]
hello i am facing the same issue but on java edition

**Comment by Shigetorum635** [comment]
> hello i am facing the same issue but on java edition

So its not installing on minecraft java edition which you downlaoded from the Minecraft Website?

**Comment by Shigetorum635** [comment]
> **Describe the bug** Installing Impact using ImpactInstaller-0.9.5 on fresh Minecraft installation from MS store fails with message "Vanilla Minecraft not detected at {PATH}, have you opened the Minecraft launcher before?"
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Attempt to install Impact on fresh installation of Minecraft from MS store
> 
> **Expected behavior** Installation proceeds as usual
> 
> **Workaround** Create additional _launcher_profiles.json_ file in minecraft installation folder
> 
> **Additional context** On this line https://github.com/ImpactDevelopment/Installer/blob/acda0df9f296c59d1959380a1fc4d7f44e3ee323/src/main/java/io/github/ImpactDevelopment/installer/target/targets/VanillaProfiles.java#L133 the script checks for file _launcher_profiles.json_ to validate given path is minecraft installation, but this file has been renamed to _launcher_profiles_microsoft_store.json_ in MS store installation.

@satzmann666 Close the issue when possible.
