### ISSUE TITLE
Hello Impact team! I can't install the Impact to official minecraft 

### ISSUE THREAD

**Issue by Zalan2006** [ImpactDevelopment/ImpactIssues#3325]
Hello Impact team! I can't install the Impact to official minecraft.
![image](https://user-images.githubusercontent.com/69893196/142065323-99f092d2-0b81-4b04-9aeb-4ee2a03eb3aa.png)

**Comment by narozmiromme** [comment]
I am having this exact same issue.

**Comment by fel1x0u** [comment]
Try opening the minecraft launcher first, then run the program.

**Comment by KillerGoldFisch** [comment]
Check out my Workaround: https://github.com/ImpactDevelopment/ImpactIssues/issues/3333
