### ISSUE TITLE
FPS Wont go higher than 30

### ISSUE THREAD

**Issue by nevvorlds** [ImpactDevelopment/ImpactIssues#3327]
when using impact my fps wont go higher than 30 and I have the limiter set to 120, but when not using impact i get 100-120 fps

**Comment by yum13241** [comment]
Try setting the limiter to either VSync, or unlimited.

**Comment by CesiumCs** [comment]
If you're still having this problem, could you open a new issue using our bug report template? it helps us get the info we need to be able to figure out how this is happening and properly help
