### ISSUE TITLE
My X-ray doesn't work on 1.16.5 with no optifine, It doesn't even work in a regular world.

### ISSUE THREAD

**Issue by ghost** [ImpactDevelopment/ImpactIssues#3328]
![2021-11-19_21 50 30](https://user-images.githubusercontent.com/89149375/142713619-ab6de339-fc9a-4267-abbd-eeb7ef0916be.png)
![2021-11-19_21 50 24](https://user-images.githubusercontent.com/89149375/142713620-d0e5fb44-4f4e-4e39-81b6-c3424e092edb.png)
 Impact X-Ray doesn't work even in a regular world. My impact doesn't have optifine for 1.16.5 PLease help me

**Comment by CesiumCs** [comment]
i know this is a deleted account but for anyone who stumbles across this issue, make sure the blocks you want to see are enabled in the menu from Pause>Impact>Xray
