### ISSUE TITLE
Impact will appear in my "versions" folder but not in my actual minecraft launcher

### ISSUE THREAD

**Issue by whythoughbruhcomeon** [ImpactDevelopment/ImpactIssues#3331]
idk what's going on bro. ask questions in the comments ig

**Comment by jayjar291** [comment]
Works in the legacy launcher but not the new Windows store version launcher

**Comment by SkyfallWasTaken** [comment]
- Go to .minecraft
- rename launcher_profiles.json to launcher_profiles_microsoft_store.json

**Comment by KillerGoldFisch** [comment]
Check out my Workaround: https://github.com/ImpactDevelopment/ImpactIssues/issues/3333
