### ISSUE TITLE
can I use this client with mods? 

### ISSUE THREAD

**Issue by oil01** [ImpactDevelopment/ImpactIssues#3332]
I want this client  with pixelmon mod how can I do this

**Comment by yum13241** [comment]
Use Forge. Forge Impact is only available for 1.12.2, and Impact doesn't even exist for 1.7.10.

**Comment by ItsPancho8** [comment]
Yes you can in 1.12.2, I actually installed a few mods and it works!

**Comment by yum13241** [comment]
IK. But as it seems OG pixelmon is 1.7.10 only.

**Comment by CesiumCs** [comment]
seems like there's some kind of Pixelmon for 1.12.2. Install impact as a forge mod using the Installer and cross your fingers, its a hit or miss kinda thing

**Comment by yum13241** [comment]
For me it never worked.
