### ISSUE TITLE
MultiMC, Impact, Forge, and 1.16.5 - not working together

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [ImpactDevelopment/ImpactIssues#3335]
# Describe what you are trying to achieve
I'm using the MultiMC launcher, and i'm trying to get Impact and Forge to work together. They're not.

# Describe the problem
I installed impact using `ImpactInstaller-0.9.5.jar`, configuring it like this: 
![image](https://user-images.githubusercontent.com/14184826/144756169-b95b26a3-8b27-455c-a0d9-61ffe562205a.png)
which worked fine; the instance appeared in multimc, launced, and ran.

I then selected "install forge" in multimc, selecting the latest version, 36.2.19. It now looks like this:
![image](https://user-images.githubusercontent.com/14184826/144756305-66537c0a-2f5f-44ed-bbbc-8564d535b89b.png)

on launch, the minecraft window opens, but the game crashes after about a second with this log: https://pastebin.com/9iuWj4WM

so I tried configuring the instance like this:
![image](https://user-images.githubusercontent.com/14184826/144756397-88342b52-ad6e-45f2-8087-fa49a0a04f3e.png)
the game launches, but mods don't seem to work. I installed Inventory Tweaks Renewed, launched the game, created a new world, and looked around a bit; here's the log: https://pastebin.com/kKdvUMBH

# Additional context
some system info: 
![image](https://user-images.githubusercontent.com/14184826/144756081-64f3a85b-540d-4879-ad78-cc67411cd6c7.png)

**Comment by Ashley123477** [comment]
I believe the forge version is only for 1.12

**Comment by CesiumCs** [comment]
yes, impact is only working on forge on 1.12.2

**Comment by SIGSTACKFAULT** [comment]
@CesiumCs this isn't the forge mod version of Impact, this is the normal version.
