### ISSUE TITLE
How to off anti virus java? 

### ISSUE THREAD

**Issue by Dream8739** [ImpactDevelopment/ImpactIssues#3411]
**Is your question request related to a problem? Please describe.**

**Describe what you are trying to achieve**

**Additional context**
Add any other context or screenshots about your question here.
[](url)

**Comment by Dream8739** [comment]
![image](https://user-images.githubusercontent.com/106386704/170701366-715ba142-b386-4d12-a812-2d211e98c4d1.png)

**Comment by CesiumCs** [comment]
and also we dont support tlauncher at all
