### ISSUE TITLE
Is there any way to disable the chat window command starting with ' . ' ?

### ISSUE THREAD

**Issue by witherdragon** [ImpactDevelopment/ImpactIssues#3431]
The verification plug-in of the server needs to log in and click the box in the chat window to verify before playing. After clicking, it will be displayed '[impact]Unknown command!Use .help to view a list of commands'
Is there any way to disable the chat window command starting with ' . ' ?

**Comment by CesiumCs** [comment]
i thought i responded to this earlier oops (or maybe it was just a similar issue)
you can change your prefix using `.prefix $` or whatever you prefer it to be to make sure messages starting with the dot still go through, you just have to use the new prefix for impact commands like `$help`
