### ISSUE TITLE
Hi, I am trying to implement OpenAI's VPT agent into MC 1.12.2

### ISSUE THREAD

**Issue by Coriana** [ImpactDevelopment/ImpactIssues#3436]
As you might be aware, OpenAI recently released some models that were trained on 8 years of gameplay footage, (repeatedly, 26 times over like in clockwork orange.)
It uses only frames from Minecraft to guesstimate what keys it wants to press

**Describe the solution you'd like**
I would like to implement a way to load and let the agent take control of the minecraft client, while yes its more likely to run into lava than eat a loaf of bread, I am looking to the future when they aren't so... braindead. 

I also am trying to do a study on long term effects of unrestrained AI onto a world, and would love to have an easy way to have multiple agents running and slowly terraforming the world to their whims and see what happens over weeks/months of an AI anarchy server.

**Describe alternatives you've considered**
I currently have used a screenrecorder and macro program to take pictures, feed it in, and then simulate a keyboard/mouse.

I also have an ESP32 virtual keyboard and mouse (in a github repo) that i have interfacing with a python script that reads a HDMI output from raspberry pi running minecraft, but pis are... underpowered and unable to connect to multiplayer server at this time, I keep hitting null pointer errors somehow, but am running a very stripped down version so...

**Additional context**
Github repos:
https://github.com/openai/Video-Pre-Training
https://github.com/Coriana/ESP32-Virtual-kb-mouse
https://github.com/neverix/plai-py
Gameplay of the AI:
https://www.youtube.com/watch?v=MpfbCFDXVy0

**Comment by CesiumCs** [comment]
This would be more of a task to try to rig [Baritone](https://github.com/cabaletta/baritone) up to. Though if you don't have the Java skills to do it yourself, I don't know who could help you.
