### ISSUE TITLE
.mcpack please

### ISSUE THREAD

**Issue by sub-1** [ImpactDevelopment/ImpactIssues#3443]
The only computer, currently that I have is a school Chromebook and I can add mods on minecraft education edition if its a .mcpack file. So to get to my point please make a version that can be a .mcpack file. If not  please recommend another pathfinder client or outher type of client that is a .mcpack.

thanks

**Comment by CesiumCs** [comment]
Porting this Java mod to the Bedrock-based Education Edition would be rewriting the mod for an entirely different game in a different language, and isn't possible. I can't recommend any other Bedrock mods as I don't play Bedrock nor know any of its mods.
