### ISSUE TITLE
Supper lag spikes if im not in the F3 Menu

### ISSUE THREAD

**Issue by LunarFR** [ImpactDevelopment/ImpactIssues#3449]
Hello, i get about 5 fps when I'm not in the F3 menu when I open it I get around 120.

**Comment by SlowingDisc** [comment]
you know how to fix?

**Comment by SlowingDisc** [comment]
@LunarFR

**Comment by CesiumCs** [comment]
I'm condensing this duplicate issue with the oldest report of it to keep it all in one spot. #3441

**Comment by SiGMA051** [comment]
same thing happening to me regardless the minecraft version

**Comment by CesiumCs** [comment]
Could you go to the issue I mentioned (#3441) and comment graphics driver version, and os type and version? I'm trying to reproduce this bug on my end but haven't had any luck so far
