### ISSUE TITLE
The brightness auto changes when in-game

### ISSUE THREAD

**Issue by leduyquang753** [ImpactDevelopment/ImpactIssues#503]
### What happens?

I have been playing around with Impact for some days and there has been a problem. That is the brightness automatically changes depending on the lighting of the area I am standing on. When I am at 0 lighting area, the screen becomes compltely black and I can't see anything.

### When does this happen?

This always happens when I am in-game.

- Impact Version: 4.1 for 1.12.2
- Using Optifine: No 
- Enabled mods: ESP, Nametags, **Lighting**, Velocity, NoFall, NoPush, Middle-Click friend
- Operating System: Windows 10 64bit

**Comment by InstantReflex** [comment]
> Lighting

That's a brightness mod, you know that right?

**Comment by InstantReflex** [comment]
If it's not too much trouble, reinstall Impact. No one I know is having this problem, and if it was a bug it should have been mentioned before. It's is most likely because of something on your side. I am in no way an expert, but go ahead and try. If the problem persists, keep this post up.

**Comment by leduyquang753** [comment]
I have reinstalled it twice. :(

**Comment by ZeroMemes** [comment]
What are your settings for the "Light" mod?

**Comment by MightyKnight** [comment]
No answer, was likely wrong configuration of Light mod. Closing.
