### ISSUE TITLE
Lowhop glitches

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactIssues#520]
### What happens?
1. LowHop is not affected by Timer unlike other modules such as normal B-hop or flight.
2. Using Lowhop on slabs make your vertical movement much slower.
### Additional Client Info
- Impact Version: 4.1 for 1.12.2
- Enabled mods: Speed (lowhop) and timer (timer for first issue).

**Comment by MightyKnight** [comment]
**Just tested: LowHop is affected by Timer as of Impact version 4.2.**
As this is fixed, I'm closing the issue.

Please create a seperate issue for **2** (lowhop on slabs) if it is important.
