### ISSUE TITLE
Killaura target teammate broken

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactIssues#527]
### What happens?

Target teammate whether on or off will attack people in my team like in cake wars for example. Killaura will swing and try to hit them regardless if its enabled or not.

Server it happened on was Mineplex. I tried in both Cake Wars and Minestrike. 

### Additional Client Info
- Impact Version: 4.2
- Using Optifine? No
- Enabled mods: https://gyazo.com/6ebfc78538cc414366ea6cd4e4d514dc
- Operating System: Windows 10 64 bit

**Comment by ZeroMemes** [comment]
What server? Some servers have teams setup to where the check that is in place will not work.

**Comment by Pabsb** [comment]
@ZeroMemes Added inside saying Mineplex Cakewars. I used killaura Single, 12 aps, 0.53 randomized aps, 3.8 range, players, invisibles, (tried with both Target team on and off) Target Team and it still hits my team mates regardless and still gets me gwen banned wave with antibot on with all options on and only mineplex on.

**Comment by dominikaaaa** [comment]
I can't reproduce this issue
