### ISSUE TITLE
Minestrike mode bugs

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactIssues#530]
### What happens?
With 4.1 aimlock targeting mode didn't miss as much nor did it take as long to lock onto a player. Lock on now is a few milliseconds longer and also few milliseconds longer to shoot. While blink is on set to All and you scope with an AWP and move to where you want to, it doesn't actually scope until a few seconds after you toggle off blink. It also doesn't show your scoped. You have to use blink packet for it to work better and show you are scoped but still some noticeable delay. 

### Game output?

```

```

### Crash report?

```

```

### Additional Client Info
- Impact Version: 4.2
- Using Optifine? No
- Enabled mods: https://gyazo.com/6ebfc78538cc414366ea6cd4e4d514dc
- Operating System: Windows 10 64bit

**Comment by 0-x-2-2** [comment]
Blink mode all stops all packets from being sent to the server when its on there for you can't scope because it sends a packet

**Comment by zPeanut** [comment]
can you reproduce it? if yes, ill keep this labeled as a bug. if not then this will be closed thx

**Comment by ZeroMemes** [comment]
Outdated
