### ISSUE TITLE
HitBox + Esp

### ISSUE THREAD

**Issue by 9ineOff** [ImpactDevelopment/ImpactIssues#594]
# What happens?
It would be really nice to see the expanded hitbox in ESP for reference...
P.S. Hitbox works...
- Impact Version: 4.2 for 1.12.2
<p align="center">
  <img src="https://image.prntscr.com/image/S_ra0Ai8QtKHff-H_JLMqg.png"
</p>

**Comment by ZeroMemes** [comment]
I believe the issue is requesting for the Hitbox mod's effect on entity hitboxes to be visible when you have the debug bounding boxes enabled.

**Comment by 9ineOff** [comment]
Well the bold box around the subject aka pig is the effect of esp, I in visioned that when the mod called HitBox was enable if ESP was enabled aswell during that time the box that surrounds subject should be expanded accordingly. However it is true that entity hitboxes were also toggled on through debug menu when this picture was taken.

**Comment by ZeroMemes** [comment]
Okay I added an option to HitBox that will increase the size of debug bounding boxes based on your settings if it is enabled. First image is without, second is with (0.1 increase).

![](https://i.imgur.com/EflAwUy.png) ![](https://i.imgur.com/9Fre5aT.png)

**Comment by LeafHacker** [comment]
@ZeroMemes does it make more sense to increase the size of our stuff instead of the dbb? The entire point of dbb is to provide an accurate view of the entity's bounding box.

**Comment by MastaNub** [comment]
It increases hitbox size, not bounding box. Don't change it. Add separate option for expanding bounding boxes in misc maybe?

**Comment by TheGamingTitan11** [comment]
I agree, the point of a hitbox is to guide players where to hit.This isn't even technically cheating because you can do this is Vanilla Minecraft without Hacked Clients too.Making the hitbox bigger will confuse the player into hitting into a place that does nothing to the entity

**Comment by ZeroMemes** [comment]
Issue was properly addressed, should've been closed.
