### ISSUE TITLE
ElytraPlus hurting you occasionally

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactIssues#619]
### What happens?
When flying with ElytraPlus enabled, the player sometimes takes damage and stops mid flight.

### Exact steps to reproduce?

- Launch Impact 4.2 and get in a world/server
- Equip and elytra and attempt to use it with ElytraPlus enabled
- Fly around long and enough and you will notice that sometimes you take damage and stop in the middle of flying.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: Impact 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Riding, NoFall, Criticals.
- Operating System: Windows 10 64bit

</details>

**Comment by LeafHacker** [comment]
Can you reproduce this with NoFall disabled (better yet, everything disabled except for ElytraPlus)?

This is likely a _feature_ of the server's anticheat, not a bug in Impact, which server are you experiencing this on?

**Comment by VitorISs** [comment]
same thing happened to me with flight... i was on a vanilla server and with flight (anti kick on, mode criative), nofall and criticals on

and i consistently took damage once every 4 seconds.. and sometimes i even got teleported to the ground.

**Comment by 0-x-2-2** [comment]
@VitorISs sounds to be caused by antikick

**Comment by dominikaaaa** [comment]
Closed as stale
