### ISSUE TITLE
Duping Utility Meme

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactIssues#620]
Duping is pretty useful on mulitplayer servers, I've seen some 1.12.2 servers today that still have the old disconnect dupe (the one where you dropped your items and disconnected at the same time). I know you guys don't like to talk about Future that much but it has a way to dupe. I think a duping hack would be very beneficial.

**Comment by LordQuadrato** [comment]
Do you mean [MC-63](https://bugs.mojang.com/browse/MC-63) by the old disconnect dupe? It works only in singleplayer

**Comment by LeafHacker** [comment]
No he is talking about a few spigot/paper spigot issues such as PaperMC/Paper#492 from ~nov 16

**Comment by dominikaaaa** [comment]
Closing this as won't fix, because lets be real here, who is running 4 year old paper
