### ISSUE TITLE
Freecam / Horse bug

### ISSUE THREAD

**Issue by ShadyTheDragon** [ImpactDevelopment/ImpactIssues#739]
When entering freecam on a horse, after using shift to move down, it bugs out the horse making it so your player, even after leaving free cam mode still seems to be "in" freecam mode. 
I made a 2min long video to show this. Im using 4.3 1.12.2
https://www.youtube.com/watch?v=1_duDlLHzyE

### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Comment by zPeanut** [comment]
use layout next time

dont really get whats the problem here, could be me being dumb

**Comment by ZeroMemes** [comment]
Freecam doesn't work properly on 4.3. Can you confirm if this is reproducible on 4.4? @ShadyTheDragon

**Comment by LeafHacker** [comment]
Cant find the original issue, but I could've sworn this was already reported and fixed in 4.3~4.4?

**Comment by ShadyTheDragon** [comment]
As shown in that video, it is present in 4.3, and caused when using shift
in free cam to desend while riding a horse, I have not tested on 4.4 yet to
see if it is still a issue.

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
