### ISSUE TITLE
Impact Keeps Unloading Resourcepacks

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#758]
If you turn on a resourcepack, then restart ur game impact turns off the resourcepack/s
Resourcepack name: §f§lInFinite 16x §8§l1.12.2
**pack.mcmeta:**
```
{
 "pack": {
   "pack_format": 2,
   "description": "  Clean 16x Default Pack              -By FinsGraphics"
 }
}
```
Most likely due to that new server resourcepack thing which I havent yet even turned on

**Comment by MightyKnight** [comment]
I cannot reproduce with my own resourcepack, can you please try it with another one? It may be an issue with the pack itself.

**Comment by ThatGrzegorzB** [comment]
> I cannot reproduce with my own resourcepack, can you please try it with another one? It may be an issue with the pack itself.

i think its because of its name

**Comment by MightyKnight** [comment]
Does it also happen in Vanilla Minecraft?

**Comment by ThatGrzegorzB** [comment]
> Does it also happen in Vanilla Minecraft?

nope

**Comment by ThatGrzegorzB** [comment]
this didint happen in 4.3, im still using the same dir i used in 4.3
