### ISSUE TITLE
ClickGUI crash on main menu

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#761]
Sometimes the click GUI in the main menu crashes. Cant replicate, was messing around with baritone settings.

**Comment by 0-x-2-2** [comment]
Can you send a crash report?

**Comment by ThatGrzegorzB** [comment]
> Can you send a crash report?

sorry not really, my mc is set up in a funny way

**Comment by LeafHacker** [comment]
If you open Impact and go to the `Impact` Menu -> `Impact Files` -> go [up](https://user-images.githubusercontent.com/23565638/47262298-d8cce380-d4dc-11e8-96aa-a0ca42e6fb87.png) a directory  -> open `crash-reports` -> [drag and drop](https://cloud.githubusercontent.com/assets/596/10057441/2c0e7a6c-61f5-11e5-8126-9317749bf9fb.gif) the relevant crash report file into a comment on this issue.

**Comment by S-B99** [comment]
bruh moment
