### ISSUE TITLE
No way to disable custom main-menu

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#767]
![image](https://user-images.githubusercontent.com/6506529/47177055-9dcd8300-d317-11e8-80dc-b2c584aa871b.png)
There is still no way to turn these off...

**Comment by 0-x-2-2** [comment]
I believe this is intended.

**Comment by SigmaRS** [comment]
Main menu would look cleaner...

**Comment by LeafHacker** [comment]
It was intended that the basic impact info would always remain on the main regardless of other settings. (The font does change though, that's cool right?)

I don't see a reason to oppose adding a separate toggle for it though.

**Comment by ZeroMemes** [comment]
This is available now as a *Premium* option.
