### ISSUE TITLE
AntiAFK continues to walk when disabled via GUI, until GUI is closed.

### ISSUE THREAD

**Issue by SylveonBottle** [ImpactDevelopment/ImpactIssues#815]
### What happens?

Enabling AntiAFK with the Walk option causes you to walk forwards automatically, but disabling it via the GUI causes you to continue walking until you close it.
### Exact steps to reproduce?

1. Open GUI
2. Enable AntiAFK
3. Disable AntiAFK

You'll now be walking constantly.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.4 for 1.12.2
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods:  AntiAFK
- Operating System:  Windows 10 64bit

</details>

**Comment by MightyKnight** [comment]
Seems fixed, can't reproduce for versions 4.7 and up.
