### ISSUE TITLE
Ban book protection

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactIssues#878]
Preface: this is crazy.

Any open inventory slots would be filled with dirt / cobblestone, at all times. But, they would render as all empty slots except one. If you move around items, everything works as it was except there are a few more clicks behind the scenes to collect the dirt back into one slot, do whatever you're doing, then spread them out over all the other slots with a drag.

LOL

**Comment by EvilSourcerer** [comment]
way too complex. all you need to do is modify autoeject to automatically eject shulkers which contains large amounts of books. querying this data may be difficult, but so much easier than this dirt idea.

**Comment by leijurv** [comment]
Yeah I know it's crazy but it's the only way to be safe guaranteed... since it randomly kicks people all the time

**Comment by 0-x-2-2** [comment]
PaperMC/Paper/ver/1.12.2@cedf38aac061173a5f055f7c2acf089627c440c1

**Comment by SylveonBottle** [comment]
Could someone explain what "ban book" is and what moving lots of dirt has to do with it?

**Comment by ZeroMemes** [comment]
A ban book is a book that contains an insane amount of NBT data, and I believe will prevent connecting to the server with it in your inventory because sending that much data will cause a timeout to occur. The point of the dirt is to fill your empty inventory slots with something so that you don't pick one up.

**Comment by SylveonBottle** [comment]
I'm pretty sure I've seen mods in minecraft that can disable picking up certain items. Could this not be added, and just let the user set it to books?

**Comment by ThatGrzegorzB** [comment]
those kind of mods are server sided

**Comment by EvilSourcerer** [comment]
just autoeject the ban books

**Comment by SylveonBottle** [comment]
> just autoeject the ban books
Is it possible to detect a ban book in your inventory without having connection issues? Suppose this could be added as a sub-option for AutoEject.

**Comment by EvilSourcerer** [comment]
another alternative is to check all dropped shulkers for ban books and log if it detects one.

**Comment by Perry1900** [comment]
At first, I thought it's possible with autoeject's code but someone told me that it kicks you before even sending the client the packet that tells it what is new in the inventory because the kick is now server sided.

**Comment by S-B99** [comment]
Ban books are patched so this can be closed?

**Comment by Perry1900** [comment]
I guess

**Comment by S-B99** [comment]
I didn't ask you, I asked the issue author???
