### ISSUE TITLE
Shaders mod doesn't work with Impact

### ISSUE THREAD

**Issue by jehmeme** [ImpactDevelopment/ImpactIssues#879]
I installed Optifine with Impact 4.4 and i'm trying to use Shaders but they don't seem to work. When I enable any shaders and try to load into any single/multi player world, it will just show the Minecraft dirt background. 

If its any help, I followed this video when installing Optifine with Impact: https://www.youtube.com/watch?v=o1LHq6L0ibk

### What happens?
The client shows the Minecraft dirt background. I am able to open the main menu but i can't see if it's open or not, it'll just allow me to move my cursor around.

### Exact steps to reproduce?

- Install Optifine with Impact 4.4 (I'm using Optifine_HD_U_E1)
- Download any shaders mod (or use (internal))
- Enable the shader
- Load into a single/multi player world

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.4 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Most of them (can't be bothered writing them out, i will if you need them)
- Operating System: Windows 10 64bit

</details>

**Comment by leijurv** [comment]
works for me

**Comment by Selron** [comment]
I have the exact same problem. 
It is only when I start the Impact client (4.6) that shaders cause a dirt screen. I tested the internal shaders and acid shaders. 
When I only start Optifine the shaders work.

**Comment by Milo5h** [comment]
I think that I may have just stumbled upon a solution,
if you have the "Light" hack enabled, this is what makes the game not load, so either turn off the shaders or the light hack before going into game and it should be fixed, atleast that's what worked for me!

**Comment by realflow100** [comment]
Huh. I had optifine this whole time and didn't realize it was working because I had light option turned off already.
but cubic chunks mod has problems and incompatibilities with baritone even without impact when i tried it. so I had to ditch the cubic chunks mod. it would cause crashing and the inability to goto blocks and mine anything and legit mine is not turned on. it works with the same settings correctly without any cubic chunk stuff installed.

**Comment by dominikaaaa** [comment]
Closed as won't fix, Impact forge isn't officially supported. If you have compatibility issues you have to remove the incompatible mods.
