### ISSUE TITLE
Impact 4.4 Outer Skin Layer Not Rendering

### ISSUE THREAD

**Issue by fdigl** [ImpactDevelopment/ImpactIssues#889]
### What happens?
The outer layers of a skin don't render in Impact 4.4, I'm unsure if the use of OptiFine is affecting this.

### Exact steps to reproduce?
It happens every time for me, just normal installation, adding in OptiFine to the json, and launching and playing in multiplayer. Fast Renderer on or off doesn't change this. Skin options says everything is 

  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Win10 Pro x64 1703

</details>

**Comment by LeafHacker** [comment]
@MightyKnight I assume you couldn't reproduce without optifine? Would be good to confirm this is an upstream bug and not an Impact one - or at least that it only affects Impact+Optifine setups.

@fdigl can you try reproducing on an OptiFine only install (preferably the same build as you used with Impact) and also an Impact install without OptiFine?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
