### ISSUE TITLE
TabGUI

### ISSUE THREAD

**Issue by 80486sx** [ImpactDevelopment/ImpactIssues#89]
3.0 had it and it would be very useful

**Comment by zPeanut** [comment]
why would you use the tabgui when you have the clickgui where you can toggle all settings better and manually. i think that the removal of the tabgui was a good thing.

**Comment by LeafHacker** [comment]
ClientAPI has a tabgui interface written by Nerxit iirc. @ZeroMemes is probably in the process of converting over to it?

**Comment by kekkekek** [comment]
Tab GUI is quicker and easier if you are running from someone you can easily switch to a different speed mode and get away

**Comment by kekkekek** [comment]
Tab GUI is quicker and easier if you are running from someone you can easily switch to a different speed mode and get away

**Comment by kekkekek** [comment]
Oops you can delete the duplicate and this one

**Comment by SuperOP535** [comment]
tabgui got removed from clientapi 🤔

**Comment by ZeroMemes** [comment]
It pains me to do this, but I would really like to write a UI system that will be able to simultaneously support the Tab GUI and Click GUI, and there isn't time for that before I want 4.4 to be released.

**Comment by ZeroMemes** [comment]
Added in 4.9
