### ISSUE TITLE
No sound when you get hit.

### ISSUE THREAD

**Issue by Fuiza** [ImpactDevelopment/ImpactIssues#901]
### What happens?
Everytime i get hit (it doesnt matter if its a mob or a player) the hit sound doesnt play, i cant hear it (i even installed a resource pack with the old hit sound (lol) just to see if it was my minecraft), later i tested a vanilla 1.12.2 to test, and the hit sound plays. by the way, it doesnt matter what mods you have on, it just doesnt work, also, i tried this with, and without optifine.

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.4 for 1.12.2
- Using Optifine? *See up*
- Using LiteLoader? No
- Enabled mods: *See up*
- Operating System: Windows 10 64 bits

</details>

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
