### ISSUE TITLE
killaura randomly stopped working one day

### ISSUE THREAD

**Issue by iqAnm** [ImpactDevelopment/ImpactIssues#931]
### Exact steps to reproduce?

- Step one turn on killaura
- Another step join a match
  - Note about "Another step"
- A third step try to use it
- etc. it fails

<details> 
  <so i have no idea how to fix this and it randomly worked once but never agin after>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: <--impact 4.4 for minecraft 1.12.2-->
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details> so one day killaura randomly stopped working and it hasnt worked at all since then

**Comment by SigmaRS** [comment]
+1 I noticed that if you enable "teammates" it works(but with all players). This is probably some anti-cheat measure(AAC?)

**Comment by sCrONcHerz** [comment]
**Same issue here, dude.**
EXCEPT. This only seems to happen on AAC, as well as it does that w/ basically each aim hack.
SmoothAim,
KillAura,
Aimbot,
etc. You get the gist.
It rarely happens on servers without AAC I've noticed, so yea, eventually, it comes down to see that, in fact, AAC has adapted to our measures of aiming w/ hacks.

**Comment by sCrONcHerz** [comment]
By the way, the comment I said up here goes to SigmaRS.

**Comment by ZeroMemes** [comment]
After the latest hotfix in 4.5, this issue should be fixed if it is related to the teammate check, can this be confirmed?

**Comment by dominikaaaa** [comment]
Closed as stale. Reopen if you can still reproduce this.
