### ISSUE TITLE
.locate doesn't work

### ISSUE THREAD

**Issue by Highghlife** [ImpactDevelopment/ImpactIssues#94]
always says unable to locate structure with "Village"

**Comment by LeafHacker** [comment]
To help reproducing this bug, can you let us know what the exact command(s) you entered were?

**Comment by Highghlife** [comment]
i tried it in singleplayer with and without putting the seed.
 In a singleplayer world i typed .locate Village with the result "Unable to locate structure with type "Village"
As well as i typed .locate Village -5695362996349995095 which was the seed of the singleplayer world with the result of  "Invalid syntax provided! Use "help locate for syntax definitions"

In a vanilla multiplayer world i do .locate Village (seed of the world) and it comes up with unable to locate structure with type "Village"

I dont know if im just doing this command wrong but i cant seem to get it to work?

**Comment by LeafHacker** [comment]
`/locate Village` works fine, so I imagine `.locate` should function the same way... @ZeroMemes?

**Comment by Highghlife** [comment]
yeah i tested /locate and it worked fine, but switching over to .locate doesn't seem to work

**Comment by w-o-a-h** [comment]
.locate prob only works in singleplayer

**Comment by ZeroMemes** [comment]
Bumping to 4.2, Still unable to find a solution to this issue.

**Comment by ZeroMemes** [comment]
Haven't been looking for a solution, going to bump this to 4.3 to focus on the issues that can be done without further investigation.

**Comment by dominikaaaa** [comment]
This shouldn't even be able to work
