### ISSUE TITLE
Horse AutoWalk

### ISSUE THREAD

**Issue by OWBeeVa** [ImpactDevelopment/ImpactIssues#976]
### What is your suggestion?
Autowalk support for horses/donkeys 
### Why is it useful?
You can autowalk farther distances must quicker and also would just be cool :D

**Comment by SuperOP535** [comment]
iirc leijurv said this would be complicated because of different entity height

**Comment by 0-x-2-2** [comment]
its not just height it is also width

**Comment by SuperOP535** [comment]
ok smart guy

**Comment by dominikaaaa** [comment]
This is a [Baritone](https://github.com/cabaletta/baritone) issue. 

See https://github.com/cabaletta/baritone/issues/616 and https://github.com/cabaletta/baritone/issues/223
