### ISSUE TITLE
Minestrike ignore smoke broken

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactIssues#985]
### What happens?

When ignore smoke is enabled a player will only target some on on the outer right, front, and left sides edges of the smoke but if someone is in it or behind it and not near an edge no targeting will happen
### Exact steps to reproduce?
Kinda plain and simple
Test all the areas of smoke to see which parts are targeted and which aren't

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.5 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: N/A
- Operating System: Windows 10 64bit

</details>

**Comment by lemonsucks** [comment]
![acacia_boat](https://user-images.githubusercontent.com/25157685/54648028-2002d480-4a7b-11e9-8867-ecd49cabe1fd.png)

**Comment by 0-x-2-2** [comment]
thank you lemon very cool

**Comment by dominikaaaa** [comment]
#1701
